partitioned-table.md

Added a warning that Range COLUMNS and Range INTERVAL are experimental features.

sql: add a warning that Range INTERVAL is experimental

---

tune-operating-system.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10967

tune-operating-system.md: add more links and fix format

---

sql-statements/sql-statement-explain.md

Change an SQL example in the EXPLAIN doc from `desc format` to `explain format`
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9616

sql-statements: change an example in EXPLAIN page from desc to explain

---

tidb-cloud/tidb-cloud-roadmap.md

cloud: update roadmap

---

develop/dev-guide-choose-driver-or-orm.md

Update the description of jdbc based on the discussion in [this thread](https://github.com/pingcap/docs/pull/10249#discussion_r979613479).

develop: update description of jdbc

---

dm/dm-manage-source.md
dm/dmctl-introduction.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11441

Remove the operate-source update command

---

basic-features.md
experimental-features.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11423

update experimental features and basic features for 6.3

---

br/pitr-known-issues.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11450

log-backup: add known issue: azure or gcs first truncate

---

tidb-cloud/tidb-cloud-glossary.md

cloud: refine a glossary term

---

production-deployment-using-tiup.md
scale-tidb-using-tiup.md
tiup/tiup-cluster.md
tiup/tiup-component-cluster-deploy.md
tiup/tiup-component-management.md
tiup/tiup-mirror.md
tiup/tiup-playground.md
upgrade-tidb-using-tiup.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11456

v6.3: bump version for tiup

---

_index.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11466

v6.3: bump version for learning path

---

backup-and-restore-use-cases-for-maintain.md
br/backup-and-restore-use-cases.md
dm/quick-start-create-task.md
migrate-from-tidb-to-mysql.md
pd-control.md
quick-start-with-tidb.md
replicate-data-to-kafka.md
ticdc/integrate-confluent-using-ticdc.md
ticdc/manage-ticdc.md
tidb-binlog/get-started-with-tidb-binlog.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11465

v6.3: bump version for tools

---

cached-tables.md
dashboard/dashboard-ops-deploy.md
dashboard/dashboard-ops-reverse-proxy.md
dashboard/dashboard-ops-security.md
optimizer-hints.md
tiflash/use-tiflash-mpp-mode.md

The copyable snippet in code block will be removed during processing markdown pages and `> {{copyable xxx}}` will be modified to `> >`. 
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11476

Remove copyable in code block

---

statistics.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11454

add some point desc

---

backup-and-restore-use-cases-for-maintain.md

trigger update

---

system-variables.md

Update the link for the PHP docs

system-variables: Update link to PHP docs

---

tidb-cloud/tidb-cloud-roadmap.md

cloud: update roadmap description 

---

functions-and-operators/string-functions.md

Fix typo by replacing `deos` with `does`. Follow up #10483

Fix typo by replacing `deos` with `does`

---

_index.md

Added reference in TiDB learning path for v6.3
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/11493

learning path: add reference in TiDB learning path for v6.3

---

_index.md

Added reference in TiDB learning path for v6.1
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/11494

learning path: add reference in TiDB learning path for v6.1

---

tidb-cloud/_index.md

Add reference in TiDB Cloud learning path

learning path: add reference in TiDB Cloud learning path

---

tidb-cloud/pause-or-resume-tidb-cluster.md
tidb-cloud/scale-tidb-cluster.md

TiDB Cloud API is in public beta and available to all users.

Cloud API: remove the description of private beta

---

tidb-cloud/_index.md
tidb-cloud/import-csv-files.md
tidb-cloud/migrate-sql-shards.md

- Replaced a link in Learning Path 
- Refined a description about csv config.

tidb cloud:updated learning path and a description about csv config

---

releases/release-notes.md

Add release date for each release according to [TiDB Release Timeline](https://docs.pingcap.com/tidb/dev/release-timeline).

Release notes: add release date

---

tidb-cloud/limitations-and-quotas.md

Adjust the default TiDB Cloud cluster quota as requested by @easonn7 

cloud: modify the cluster quota

---

TOC-tidb-cloud.md
sql-physical-optimization.md

Fix customcontent label

---

ecosystem-tool-user-guide.md
sql-statements/sql-statement-recover-table.md

Updated ecosystem-tool-user-guide as chinese version.
Translated from this PR https://github.com/pingcap/docs-cn/pull/7117 but based on the latest version online.
Restore this accidentally deleted PR https://github.com/pingcap/docs/pull/10540 …

tools: updated ecosystem-tool-user-guide as chinese version

---

tidb-cloud/set-up-private-endpoint-connections.md

cloud: add private endpoint security group configuration

---

faq/manage-cluster-faq.md

Close https://github.com/pingcap/docs/issues/6540
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11539

faq: correct description about TiDB versions

---

system-variables.md

Add missing description for `tidb_auth_signing_cert` and `tidb_auth_signing_key`.

system variables: add docs for `signing_cert` and `signing_key`

---

config-templates/complex-tiflash.yaml
schedule-replicas-by-topology-labels.md
tiflash/create-tiflash-replicas.md
tiflash/tiflash-configuration.md
tiup/tiup-cluster.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10355

add tiflash label settings example

---

system-variables.md
tidb-configuration-file.md

- Feedback from AskTUG
- Improve the description of `force-priority` to make the value options more clear
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10996

sysvar, config: improve force-priority

---

tiflash/use-tiflash-mpp-mode.md

Align the value with [Chinese](https://docs.pingcap.com/zh/tidb/stable/use-tiflash-mpp-mode#%E6%8E%A7%E5%88%B6%E6%98%AF%E5%90%A6%E9%80%89%E6%8B%A9-mpp-%E6%A8%A1%E5%BC%8F)

tiflash: fix config value of tidb_allow_mpp

---

br/point-in-time-recovery.md

add missing sections for pitr. 
ref: https://github.com/pingcap/docs-cn/pull/9532/files#diff-5b3d37216709d97ccf3389b54beb87ae94ab898b97090fc23ee6546c19b27fb1R95

br: add missing sections for pitr

---

tiup/tiup-component-dm-import.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/11506

tiup: add a notice to tiup dm import

---

sql-statements/sql-statement-explain.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11185

revise explain format by list

---

releases/release-6.3.0.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11575

 add adding index acceleration to key feature

---

tidb-cloud/tidb-cloud-billing.md

Add **Summary by service** and **Usage details**.

cloud: update billing details page

---

tidb-cloud/release-notes-2022.md

cloud: add release notes for 20221011

---

TOC.md
tidb-troubleshooting-map.md
troubleshoot-tidb-oom.md

Add TiDB OOM troubleshooting tips.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/11262

troubleshooting: add TiDB OOM troubleshooting tips

---

cached-tables.md
certificate-authentication.md
configure-load-base-split.md
dynamic-config.md
sql-statements/sql-statement-recover-table.md
sql-statements/sql-statement-show-engines.md
sql-statements/sql-statement-show-profiles.md

Add an example for the adjustment of byte-threshold and region-cpu-overload-threshold-ratio of the Load Base Split.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11598

Add an example for byte-threshold and region-cpu-overload-threshold-ratio adjustment

---

tidb-cloud/connect-to-tidb-cluster.md

cloud: add a note for standard connection

cloud: add a note for standard connection

---

comment-syntax.md
sql-prepared-plan-cache.md
sql-statements/sql-statement-create-index.md
system-variables.md
tidb-lightning/tidb-lightning-backends.md
tiflash/tiflash-configuration.md
tiflash/use-tiflash.md
tikv-control.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11631

Fix admonitions syntax in release-5.4

---

hardware-and-software-requirements.md

Add RHE Linux 8 stream and AWS linux to software requirement doc
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11459

Add RHE Linux 8 stream and AWS linux to software requirement doc

---

dm/dm-manage-schema.md
migrate-with-more-columns-downstream.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/9107

dm: improve binlog schema description

---

tidb-cloud/migrate-data-into-tidb.md

lightning has deprecated the term of "backend" and uses "import mode". 

cloud: remove description about lightning backend

---

performance-tuning-methods.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11649

fix typos in performance tuning methods

---

tidb-cloud/terraform-use-cluster-resource.md

fix terraform doc error

---

tidb-cloud/tidb-cloud-quickstart.md

- Fix several issues found in tests
- remove dedicated tier
- simplify description
- Adjust the steps to align with new email

cloud: update quickstart according to tests

---

develop/dev-guide-third-party-tools-compatibility.md
grafana-tidb-dashboard.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11673

Fix the docs-merge pipeline failure issue

---

ticdc/ticdc-faq.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11240

ticdc: add three ticdc faqs

---

tidb-cloud/tidb-cloud-billing.md

cloud: add the contract tab to billings

---

tidb-cloud/size-your-cluster.md

Update doc for [DM-6179](https://jira.tidbcloud.com/browse/DM-6179).

cloud: update tikv/tiflash node storage

---

tidb-cloud/release-notes-2022.md

cloud: add release notes for 20221018

---

sql-statements/sql-statement-flashback-table.md
system-variables.md

sysvar: fix typos

---

tidb-binlog/tidb-binlog-configuration-file.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11674

drainer: add read-timeout configuration explanation

---

tidb-cloud/release-notes-2022.md

cloud: add 20221019 release notes

---

partitioned-table.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11280

Fix typos in partitioned-table.md

---

tiup/tiup-cluster.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10437

Add backup and restore content for tiup-cluster.md

---

sync-diff-inspector/upstream-downstream-diff.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11218

Add TiCDC TSO acquisition in sync-diff-inspector doc

---

sql-mode.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11706

sql-mode: fix wrong description

---

TOC-tidb-cloud.md
mysql-compatibility.md
tidb-cloud/_index.md
tidb-cloud/monitor-datadog-integration.md
tidb-cloud/monitor-prometheus-and-grafana-integration.md
tidb-cloud/monitor-tidb-cluster.md
tidb-cloud/terraform-tidbcloud-provider-overview.md
tidb-cloud/third-party-integrations.md
tidb-cloud/third-party-monitoring-integrations.md
tidb-cloud/tidb-cloud-poc.md

cloud: added integrations

---

system-variables.md

planner: add docs for some variables

---

placement-rules-in-sql.md

remove tiflash and placement in sql incompatible description

---

system-variables.md

sysvar: add a description for a sysvar

sysvar: add a description for a sysvar

---

system-variables.md

add document for the block_encryption_mode function

---

develop/dev-guide-sample-application-golang.md
develop/dev-guide-sample-application-java.md
develop/dev-guide-sample-application-spring-boot.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11738, https://github.com/pingcap/docs-cn/pull/10072

Modify the recommended way as the first tab

---

system-variables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11729

sysvar: add a sysvar

---

online-unsafe-recovery.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11711

Fix tiup scale-in commands after online unsafe recovery

---

best-practices/java-app-best-practices.md
develop/dev-guide-connection-parameters.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11406

[Update] use link to replace fixed props

---

three-data-centers-in-two-cities-deployment.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11761

remove the info about configuring tolerant-size-ratio

---

tidb-cloud/release-notes-2022.md

cloud: add release notes for 20221025

---

dm/dm-command-line-flags.md
dm/dm-daily-check.md
dm/dm-error-handling.md
dm/dm-generate-self-signed-certificates.md
dm/dm-handle-alerts.md
dm/dm-handle-performance-issues.md
dm/dm-hardware-and-software-requirements.md
dm/dm-key-features.md
dm/dm-manage-schema.md
dm/dm-manage-source.md
dm/dm-overview.md
dm/dm-query-status.md
dm/dm-source-configuration-file.md
dm/handle-failed-ddl-statements.md
dm/quick-start-create-source.md
dm/table-selector.md

dm: update headings and minor errors

---

experimental-features.md
pd-control.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11566

pd: add rank-formula-version config for hot scheduler

---

releases/release-6.3.0.md

Add a note about HAProxy
- https://github.com/pingcap/tidb/pull/27768

v6.3 release notes: Add HAProxy note

---

tidb-configuration-file.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11791

fix the default value of slow-threshold

---

tidb-cloud/import-csv-files.md
tidb-cloud/import-parquet-files.md
tidb-cloud/import-sample-data.md
tidb-cloud/migrate-from-amazon-s3-or-gcs.md
tidb-cloud/migrate-from-aurora-bulk-import.md
tidb-cloud/migrate-sql-shards.md
tidb-cloud/tidb-cloud-quickstart.md

cloud: change Role-ARN to Role ARN

---

experimental-features.md
tidb-configuration-file.md

Cherry-pick https://github.com/pingcap/docs/pull/11056

add description for enable-table-lock

---

tidb-cloud/create-tidb-cluster.md

Signed-off-by: Xiaoguang Sun <sunxiaoguang@gmail.com>

Fix create time for serverless

---

tidb-cloud/create-tidb-cluster.md

remove unncessary steps in create serverless clusters

---

develop/dev-guide-build-cluster-in-cloud.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11826

[Update] remove cloud picture link in the doc

---

tidb-cloud/integrate-tidbcloud-with-airbyte.md

Update integrate-tidbcloud-with-airbyte.md

cloud: Update integrate-tidbcloud-with-airbyte.md

---

tidb-cloud/tidb-cloud-quickstart.md

cloud: update the step number for querying data

---

dm/dm-faq.md
tidb-lightning/troubleshoot-tidb-lightning.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11718

add workaround for charset error when migrate data

---

basic-features.md
dashboard/dashboard-diagnostics-access.md
experimental-features.md
information-schema/information-schema-sql-diagnostics.md

Signed-off-by: mornyx <mornyx.z@gmail.com>

dashboard: remove warnings on diagnostics page

---

ticdc/manage-ticdc.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11783

Support kafka 3

---

experimental-features.md
pd-configuration-file.md
tikv-configuration-file.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11579

tikv: modify TiKV & PD config docs for TiKV API v2

---

information-schema/information-schema-processlist.md

This pull request updates the processlist column information.
- Add `DIGEST` via https://github.com/pingcap/tidb/pull/19622
- Add `DISK` via https://github.com/pingcap/tidb/pull/22417
- Update `INFO` data type from `binary(512)` to `longtext` via https://github.com/pingcap/tidb/pull/19648
Fix #11038
- Other …

Update the processlist column information

---

develop/dev-guide-build-cluster-in-cloud.md
tidb-cloud/backup-and-restore.md
tidb-cloud/built-in-monitoring.md
tidb-cloud/changefeed-sink-to-apache-kafka.md
tidb-cloud/connect-to-tidb-cluster.md
tidb-cloud/delete-tidb-cluster.md
tidb-cloud/monitor-built-in-alerting.md
tidb-cloud/monitor-datadog-integration.md
tidb-cloud/monitor-prometheus-and-grafana-integration.md
tidb-cloud/monitor-tidb-cluster.md
tidb-cloud/pause-or-resume-tidb-cluster.md
tidb-cloud/release-notes-2021.md
tidb-cloud/release-notes-2022.md
tidb-cloud/scale-tidb-cluster.md
tidb-cloud/select-cluster-tier.md
tidb-cloud/size-your-cluster.md
tidb-cloud/third-party-monitoring-integrations.md
tidb-cloud/tidb-cloud-billing.md
tidb-cloud/tidb-cloud-poc.md
tidb-cloud/tidb-cloud-quickstart.md

cloud: add beta to serverless tier

---

dm/dm-precheck.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11710

dm: update precheck

---

TOC-tidb-cloud.md
tidb-cloud/naming-conventions-for-data-import.md

Add a new article about naming conventions for data import

cloud: add a new article about naming conventions for data import

---

dm/dm-key-features.md
migrate-small-mysql-shards-to-tidb.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11536

dm: add extend columns routes usage

---

br/br-log-command-line.md
br/pitr-known-issues.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11832

pitr: support restart log-backup task and remove several know issues

---

hardware-and-software-requirements.md

Fix OS info
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11854
- Other reference link(s): https://github.com/pingcap/docs/pull/10595

Update OS info

---

dm/dm-query-status.md
dm/handle-failed-ddl-statements.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11755

dm: add some query status

---

tidb-cloud/select-cluster-tier.md

Update select-cluster-tier.md.

cloud: Add TLS constrict in select-cluster-tier.md

---

dm/deploy-a-dm-cluster-using-tiup.md

dm: update cluster name

---

ticdc/manage-ticdc.md
ticdc/ticdc-faq.md
ticdc/ticdc-overview.md
ticdc/troubleshoot-ticdc.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6553

ticdc: fix typos

---

functions-and-operators/json-functions.md

Signed-off-by: YangKeao <yangkeao@chunibyo.icu>
Add a new function `json_storage_free`.
- Other reference link(s): https://github.com/pingcap/tidb/issues/38517

json: add document for json_storage_free

---

data-type-json.md

Signed-off-by: YangKeao <yangkeao@chunibyo.icu>
Remove the json path restrictions, as the TiDB doesn't have this restriction after 6.4.

remove json path restrictions

---

hardware-and-software-requirements.md
tiup/tiup-cluster-topology-reference.md

- Other reference link(s): https://github.com/pingcap/docs-cn/pull/8889

fix ngm port

---

sql-statements/sql-statement-drop-index.md
tidb-configuration-file.md

- [update open-tracing tidb-configuration description by tangenta · Pull Request #10971 · pingcap/docs-cn](https://github.com/pingcap/docs-cn/pull/10971)
- [update the doc of `drop index` by djshow832 · Pull Request #10453 · pingcap/docs-cn](https://github.com/pingcap/docs-cn/pull/10453)
- [update open-tracing …

align 2 PR from docs-cn (2)

---

TOC.md
pd-configuration-file.md
releases/release-5.1.0.md
sql-statements/sql-statement-rename-user.md

- [correct placement rules config by TomShawn · Pull Request #11345 · pingcap/docs-cn](https://github.com/pingcap/docs-cn/pull/11345)
- [add the doc for `rename user` by djshow832 · Pull Request #10383 · pingcap/docs-cn](https://github.com/pingcap/docs-cn/pull/10383) …

align 2 PR from docs-cn

---

system-variables.md
tidb-configuration-file.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11853

add chunk alloc system variable

---

TOC.md
functions-and-operators/miscellaneous-functions.md
information-schema/information-schema-tidb-indexes.md
sql-statements/sql-statement-alter-table.md
sql-statements/sql-statement-create-database.md
sql-statements/sql-statement-create-table.md
sql-statements/sql-statement-show-create-database.md

- [placement: add some additional syntax tree by xhebox · Pull Request #10863 · pingcap/docs-cn](https://github.com/pingcap/docs-cn/pull/10863)
- [doc: update information_schema tidb_index by xiongjiwei · Pull Request #10626 · pingcap/docs-cn](https://github.com/pingcap/docs-cn/pull/10626)
- [doc: show create schema by xiongjiwei · Pull Request #10584 · pingcap/docs-cn](https://github.com/pingcap/docs-cn/pull/10584)
- [Remove locking function from the list of unsupported functions by TomShawn · Pull Request #10397 · pingcap/docs-cn](https://github.com/pingcap/docs-cn/pull/10397)
By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or …

align 4 PR from docs-cn

---

system-variables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11877

Change compatibility description for add index acceleration&PiTR

---

sql-statements/sql-statement-alter-table-compact.md
sql-statements/sql-statement-alter-table.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11641

update sql-statement-alter-table-compact.md 

---

system-variables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11855

Add tidb_auto_analyze_partition_batch_size variable

---

best-practices/three-nodes-hybrid-deployment.md
clinic/clinic-data-instruction-for-tiup.md
dashboard/dashboard-ops-deploy.md
enable-tls-between-components.md
pd-control.md
scale-tidb-using-tiup.md
three-data-centers-in-two-cities-deployment.md
ticdc/manage-ticdc.md
tidb-control.md
tiflash/tiflash-configuration.md
tikv-control.md
tiup/tiup-cluster.md
troubleshoot-lock-conflicts.md
troubleshoot-write-conflicts.md

The command tiup ctl does not work if a version of ctl is not specified. Therefore, I add <cluster-version>.
Close https://github.com/pingcap/docs/issues/9941

add version to tiup ctl to make the command work

---

dashboard/dashboard-ops-deploy.md
migrate-from-tidb-to-mysql.md
replicate-data-to-kafka.md
ticdc/integrate-confluent-using-ticdc.md

- Other reference link(s): https://github.com/pingcap/docs-cn/pull/11914

add version to tiup ctl (2)

---

tidb-cloud/integrate-tidbcloud-with-vercel.md

treat Serverless Tier & Dedicated Tier traffic filter rule different

---

releases/release-6.1.0.md
releases/release-6.1.1.md
releases/release-6.1.2.md
releases/release-6.2.0.md
releases/release-6.3.0.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11867, https://github.com/pingcap/docs-cn/pull/11922

release note: add the TiDB downloading info 

---

TOC.md
_index.md

toc: remove recommended from tiup deployment

---

tispark-overview.md

Close https://github.com/pingcap/docs/issues/11202
The preview documentation is:
The preview PDF is:
- Other reference link(s): https://github.com/pingcap/docs/pull/10492

Fix the PDF build failure caused by a special character

---

system-variables.md

Add global scope for `tidb_opt_agg_push_down`, helping to tune AP SQL.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11876

system variables: add global scope for `tidb_opt_agg_push_down`

---

dynamic-config.md
tikv-configuration-file.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11831

docs: add config "raftstore.appy-yield-msg-size"

---

dm/task-configuration-file-full.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11936

dm: update full doc about extend routes

---

ticdc/manage-ticdc.md

ticdc: fix a typo

---

system-variables.md

add system variable tidb_opt_prefix_index_single_scan
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11713

add system variable tidb_opt_prefix_index_single_scan

---

tidb-cloud/release-notes-2022.md

cloud: update release notes for 1108

cloud: update release notes for 20221108

---

experimental-features.md
statistics.md
system-variables.md

as title
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/11864

optimizer: enable tidb_stats_load_sync_wait by default

---

TOC.md
configure-placement-rules.md
dynamic-config.md
garbage-collection-configuration.md
pd-configuration-file.md
pessimistic-transaction.md
releases/release-5.1.1.md
releases/release-6.1.0.md
releases/release-6.2.0.md
storage-engine/titan-configuration.md
tikv-control.md
tune-tikv-memory-performance.md

*: replace the wording "modify configuration online""

*: replace the wording "modify configuration online""

---

alert-rules.md

Add documentation for `PD_cluster_unhealthy_tikv_nums`
- https://github.com/tikv/pd/pull/5612

metrics: Add the `PD_cluster_unhealthy_tikv_nums` alert

---

TOC.md
sql-statements/sql-statement-flashback-database.md

as title
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/11915

sql: add doc for flashback database

---

.github/pull_request_template.md

pull_request_template: add v6.5

---

clustered-indexes.md
system-variables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11938

clustered-indexes.md: change the system variable default value to ON

---

non-transactional-dml.md

transaction: add a link
- Other reference link(s): https://github.com/pingcap/docs/issues/11217

transaction: add a link

---

system-variables.md

Change tiflash_fine_grained_shuffle_batch_size description
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11953

Change tiflash_fine_grained_shuffle_batch_size description

---

scale-tidb-using-tiup.md
troubleshoot-lock-conflicts.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11954 https://github.com/pingcap/docs-cn/pull/11961

scale tiflash: add a SQL to check tiflash table replica

---

clustered-indexes.md
information-schema/information-schema-tables.md

clustered index: add error information about dropping primary key

clustered index: add error information about dropping primary key

---

system-variables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11239

add system variable tidb_opt_range_max_size

---

system-variables.md

sysvar: add 2 gogc variables in 6.4 doc
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11863 https://github.com/pingcap/docs-cn/pull/11944

sysvar: add variables in 6.4 doc

---

mysql-compatibility.md

Use an unordered list at the beginning of MySQL Compatibility.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11982

Refine the style of MySQL Compatibility

---

develop/dev-guide-third-party-tools-compatibility.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/11654

add sequelize to 3rd party tools incompatibility

---

config-templates/complex-cdc.yaml
config-templates/complex-mini.yaml
config-templates/complex-tidb-binlog.yaml
config-templates/complex-tiflash.yaml
config-templates/complex-tispark.yaml
pd-configuration-file.md
tidb-configuration-file.md
tikv-configuration-file.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11997

Add aliases for configuration files

---

system-variables.md

sysvar: delete two sysvar that has been removed from code
tidb_auth_signing_cert
tidb_auth_signing_key
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11998

sysvar: delete two sysvar that has been removed from code

---

explain-overview.md

explain-overview: add a description to include tiflash mpp cases

explain-overview: update a description to consider tiflash mpp cases

---

tidb-cloud/release-notes-2022.md

cloud: update release notes for 20221115

cloud: update release notes for 20221115

---

tidb-cloud/tidb-cloud-roadmap.md

cloud: fix typo in roadmap

---

tidb-cloud/release-notes-2022.md

cloud: fix indentation for release note

cloud: fix indentation for release note

---

system-variables.md

sysvar: update tidb_guarantee_linearizability information
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12000

sysvar: update tidb_guarantee_linearizability information

---

dm/dm-manage-schema.md

- [x ] v6.1 (TiDB 6.1 versions)

dm: fix capitalization in heading

---

tidb-cloud/tidb-cloud-roadmap.md

cloud: update roadmap table layout

---

br/br-deployment.md
hardware-and-software-requirements.md

Update os supports for dmr versions
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11996

Update os supports for dmr versions

---

_index.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12011

v6.4: update _index.md

---

production-deployment-using-tiup.md
scale-tidb-using-tiup.md
tiup/tiup-cluster.md
tiup/tiup-component-cluster-deploy.md
tiup/tiup-component-management.md
tiup/tiup-mirror.md
tiup/tiup-playground.md
upgrade-tidb-using-tiup.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12006

tiup: bump version to 6.4

---

backup-and-restore-use-cases-for-maintain.md
br/backup-and-restore-use-cases.md
dm/quick-start-create-task.md
pd-control.md
quick-start-with-tidb.md
ticdc/manage-ticdc.md
tidb-binlog/get-started-with-tidb-binlog.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12015

v6.4: bump version for tools

---

basic-features.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11948

update the basic feature tables for v6.4 

---

br/pitr-known-issues.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11836

pitr: uncommenting the annotation in the known-issues: pitr truncate

---

releases/release-6.2.0.md
releases/release-6.4.0.md

Remove the 'v' from release notes title to keep it consistent with other release notes.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12038

Remove "v" from release notes titles

---

tikv-configuration-file.md

Signed-off-by: Ping Yu <yuping@pingcap.com>
Fix link of RawKV CDC. See [rendered](https://github.com/pingyu/docs/blob/fix-rawkv-cdc-link/tikv-configuration-file.md#api-version-new-in-v610).

tikv: Fix RawKV CDC link

---

releases/release-6.1.0.md
releases/release-6.1.1.md
releases/release-6.1.2.md
releases/release-6.2.0.md
releases/release-6.3.0.md
releases/release-6.4.0.md

release notes: update TiDB download links

---

tiup/tiup-overview.md
tiup/tiup-reference.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12048

remove arg -B in tiup

---

statistics.md

Refine word in statistics

---

tidb-cloud/terraform-get-tidbcloud-provider.md
tidb-cloud/terraform-tidbcloud-provider-overview.md
tidb-cloud/terraform-use-backup-resource.md
tidb-cloud/terraform-use-cluster-resource.md
tidb-cloud/terraform-use-restore-resource.md

Update terraform doc according to the new terraform version https://github.com/tidbcloud/terraform-provider-tidbcloud/releases/tag/v0.1.0
1. datasource has been renamed
2. some ids are changed from `just for test` to a random number. So I just delete them in the doc.

update according to terraform 0.1.0

---

tidb-cloud/monitor-tidb-cluster.md

cloud: update cloud node status

cloud: update cloud node status

---

tiflash/create-tiflash-replicas.md

Signed-off-by: Wish <breezewish@outlook.com>
Add some instructions about how to sync TiFlash replica faster.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11653
- Other reference link(s): https://github.com/pingcap/docs/pull/11398

[release-6.1] tiflash: Add instructions to improve replica sync performance

---

tiflash/use-tiflash.md

Signed-off-by: Wish <breezewish@outlook.com>
Cherry pick from https://github.com/pingcap/docs/pull/11401

[release-5.4] tiflash: Add instructions to improve replica sync performance

---

tidb-cloud/migrate-from-mysql-using-data-migration.md
tidb-cloud/release-notes-2022.md

cloud: delete singapore region

---

TOC-tidb-cloud.md
tidb-cloud/select-cluster-tier.md
tidb-cloud/serverless-tier-faqs.md
tidb-cloud/serverless-tier-limitations.md
tidb-cloud/tidb-cloud-faq.md

Serverless FAQ and limitations

---

faq/sql-faq.md
mysql-compatibility.md

*: address github issues
closes https://github.com/pingcap/docs/issues/6533 
closes https://github.com/pingcap/docs/issues/6534 
closes https://github.com/pingcap/docs/issues/7979
- Other reference link(s): https://github.com/pingcap/docs/issues/6533 https://github.com/pingcap/docs/issues/6534 …

*: address github issues

---

tidb-cloud/config-s3-and-gcs-access.md

Deleted an outdated screenshot.

cloud: delete a screenshot

---

tidb-cloud/migrate-from-mysql-using-data-migration.md
tidb-cloud/release-notes-2022.md

Add the Singapore region Singapore (ap-southeast-1)

cloud: add singapore region

---

tidb-cloud/tidb-cloud-roadmap.md

cloud: update roadmap for release 1122

---

tiup/tiup-cluster-topology-reference.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12099

tiup: remove restriction for enable_tls

---

metadata-lock.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12123

Add one more DDL supported by metadata lock

---

benchmark/benchmark-tidb-using-tpcc.md
tiup/tiup-bench.md

Signed-off-by: zyguan <zhongyangguan@gmail.com>
Keeping tiup-bench docs up-to-date. see https://github.com/pingcap/docs-cn/pull/11838 .
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11838

tiup: update docs of tiup-bench

---

TOC-tidb-cloud.md
tidb-cloud/migrate-from-mysql-using-data-migration.md

Updated a limitation description and TOC

cloud: updated a limitation description and TOC

---

dm/dm-open-api.md
non-transactional-dml.md
tidb-configuration-file.md

Fix admonition style

---

releases/release-6.4.0.md

add ticdc split transaction release note
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12146/files
https://github.com/pingcap/tiflow/issues/7505

add ticdc split transaction release note

---

TOC-tidb-cloud.md
tidb-cloud/create-tidb-cluster.md
tidb-cloud/tidb-cloud-billing.md

cloud: Support billing from cloud provider

---

tidb-cloud/release-notes-2022.md
tidb-cloud/tidb-cloud-roadmap.md

cloud: update release notes for 1129

cloud: update release notes for 1129

---

_docHome.md
_index.md
faq/deploy-and-maintain-faq.md
faq/tidb-faq.md
hardware-and-software-requirements.md
multi-data-centers-in-one-city-deployment.md
overview.md

Changed the term "NewSQL" to "distributed SQL"

*: change NewSQL to distributed SQL

---

br/use-br-command-line-tool.md

Translate [use-br-command-line-tool.md](https://docs.pingcap.com/zh/tidb/dev/use-br-command-line-tool).
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11316

br refactor: translate br Command-line Manual

---

download-ecosystem-tools.md
pd-control.md
pd-recover.md
production-deployment-using-tiup.md
quick-start-with-tidb.md
scale-tidb-using-tiup.md
sync-diff-inspector/sync-diff-inspector-overview.md
ticdc/manage-ticdc.md
tiup/tiup-cluster.md
tiup/tiup-component-cluster-deploy.md
tiup/tiup-component-management.md
tiup/tiup-mirror.md
tiup/tiup-playground.md
upgrade-tidb-using-tiup.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12152

bump version for v5.3.4

---

_docHome.md
_index.md
faq/deploy-and-maintain-faq.md
faq/tidb-faq.md
hardware-and-software-requirements.md
multi-data-centers-in-one-city-deployment.md
overview.md

A complement to https://github.com/pingcap/docs/pull/11463.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12161
- Other reference link(s): #11463

*: add annotations for l10n

---

releases/release-6.3.0.md

Fix incorrect description of a ticdc improvement in 6.3 RN

---

statistics.md

planner: update docs for auto analyze
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10647

planner: update docs for auto analyze

---

identify-slow-queries.md

Changed [tidb_enable_slow_log](https://docs.pingcap.com/zh/tidb/v6.4/system-variables#tidb_enable_slow_log) to [tidb_slow_log_threshold](https://github.com/system-variables.md#tidb_slow_log_threshold)
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/12176

slow log: fix an error in slow log

---

configure-memory-usage.md
system-variables.md

sysvar: add a note to disable tidb_enable_rate_limit_action
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12121

sysvar: add a note to disable tidb_enable_rate_limit_action

---

experimental-features.md
tidb-lightning/tidb-lightning-configuration.md
tidb-lightning/tidb-lightning-physical-import-mode-usage.md

The disk quota feature goes GA.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/12090, https://github.com/pingcap/docs-cn/pull/12162

lightning: disk quota GA

---

dumpling-overview.md
tidb-lightning/tidb-lightning-data-source.md
tidb-lightning/troubleshoot-tidb-lightning.md

Added content about compressed files
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/12083

dumpling, lightning: add document for compressed files support

---

auto-increment.md
experimental-features.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11960

AUTO_INCREMENT: MySQL compatibility mode GA

---

develop/dev-guide-proxysql-integration.md

Update option name for cloud serverless integration 

---

TOC.md

To align with [docs-cn TOC](https://github.com/pingcap/docs-cn/blob/master/TOC.md)

add br checkpoint to TOC

---

br/rawkv-backup-and-restore.md
experimental-features.md
releases/release-6.2.0.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12189

rawkv: rawkv: change the deprecation statement back to experiment statement

---

sync-diff-inspector/sync-diff-inspector-overview.md
ticdc/manage-ticdc.md

sync-diff: update passwd description
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12076 https://github.com/pingcap/docs-cn/pull/12101

sync-diff: update passwd description

---

tikv-control.md

Exchange the position of bad-ssts nad --data-dir, or it will report `error: Found argument '--data-dir' which wasn't expected, or isn't valid in this context`
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12064

Correct the order of bad-ssts and --data-dir

---

tiflash/tiflash-supported-pushdown-calculations.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12047

tiflash: support pushing down json extract

---

hardware-and-software-requirements.md

add newer go version to environment requirements

---

releases/release-6.1.3.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12231

add a ticdc bug fix to 6.1.3 RN

---

tikv-configuration-file.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9871

tikv: change cdc.min-ts-interval from 1s to 200ms

---

non-transactional-dml.md
sql-statements/sql-statement-batch.md

Starting from TiDB v6.5.0, the `BATCH` syntax supports `UPDATE`, `INSERT`, and `REPLACE`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12079

add content about nt-dml for insert and update

---

tidb-cloud/release-notes-2022.md
tidb-cloud/tidb-cloud-support.md

cloud: add release notes for 1206

---

dashboard/dashboard-access.md
dashboard/dashboard-intro.md
dashboard/dashboard-ops-deploy.md
dashboard/dashboard-ops-security.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11980

dashboard: deploy tidb dashboard as a separate pod

---

system-variables.md
ticdc/manage-ticdc.md

cdc: fix a typo

---

TOC.md
functions-and-operators/encryption-and-compression-functions.md
mysql-schema.md
password-management.md
security-compatibility-with-mysql.md
sql-statements/sql-statement-alter-user.md
sql-statements/sql-statement-create-user.md
system-variables.md
tidb-configuration-file.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/12103

security: add doc for password management

---

tidb-cloud/secure-connections-to-serverless-tier-clusters.md

Add windows ca root in secure-connections-to-serverless-tier-clusters.md.

cloud: add windows ca path

---

develop/dev-guide-tidb-crud-sql.md
tidb-cloud/tidb-cloud-quickstart.md

cloud: add doc for sql editor

---

tidb-cloud/connect-to-tidb-cluster.md

SQL shell will be removed from serverless.

cloud: remove sql shell for serverless

---

br/backup-and-restore-overview.md
br/backup-and-restore-storages.md
br/backup-and-restore-use-cases.md
br/br-pitr-guide.md
br/br-pitr-manual.md
br/br-snapshot-guide.md
br/br-use-overview.md
faq/backup-and-restore-faq.md

- Other reference link(s): https://github.com/pingcap/docs/pull/11510

add aliases for br v6.4 versions

---

br/backup-and-restore-use-cases.md
check-before-deployment.md
dm/quick-start-create-task.md
download-ecosystem-tools.md
pd-control.md
production-deployment-using-tiup.md
quick-start-with-tidb.md
scale-tidb-using-tiup.md
ticdc/manage-ticdc.md
tidb-binlog/get-started-with-tidb-binlog.md
tidb-cloud/export-data-from-tidb-cloud.md
tiflash/create-tiflash-replicas.md
tiup/tiup-cluster.md
tiup/tiup-component-cluster-deploy.md
tiup/tiup-component-management.md
tiup/tiup-mirror.md
tiup/tiup-playground.md
upgrade-tidb-using-tiup.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12272

bump version for 6.1.3

---

TOC-tidb-cloud.md
system-variables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12271

docs: add tidb_enable_amend_pessimistic_txn depreciation

---

tidb-cloud/connect-to-tidb-cluster.md
tidb-cloud/secure-connections-to-serverless-tier-clusters.md
tidb-cloud/select-cluster-tier.md

cloud: improve connect exp

---

tidb-cloud/integrate-tidbcloud-with-vercel.md

refresh steps for vercel connection after add prisma

---

releases/release-6.1.3.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12288

add a ticdc compatibility change to 6.1.3 RN

---

tidb-cloud/release-notes-2022.md
tidb-cloud/tidb-cloud-roadmap.md

cloud: add release notes for 1213

---

faq/sql-faq.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/12298

faq: fix an outdated description

---

system-variables.md

sysvar: correct a default value
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11972

sysvar: correct a default value

---

tidb-cloud/migrate-from-mysql-using-data-migration.md

Added troubleshooting tips for Data Migration on TiDB Cloud.

cloud dm: add troubleshooting tips

---

tidb-cloud/serverless-tier-limitations.md

Signed-off-by: Xiaoguang Sun <sunxiaoguang@gmail.com>

Add one more limitation to serverless tier to document

---

scripts/get-duplicated-notes.py

chore: refine get duplicated notes

chore: refine get duplicated notes

---

tidb-cloud/serverless-tier-faqs.md
tidb-cloud/serverless-tier-limitations.md

Serverless limitation transaction limit on FAQ page

---

tikv-configuration-file.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12279

add config import.memory-use-ratio

---

tidb-cloud/release-notes-2022.md

cloud: add release notes for 1220

---

ticdc/ticdc-faq.md
ticdc/ticdc-open-protocol.md
ticdc/ticdc-overview.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12120

add ticdc best pratice and FAQ

---

tidb-cloud/csv-config-for-import-data.md

Fix the issue that [docs-merge-pipeline/2948](https://ci.pingcap.net/job/docs-merge-pipeline/2948/) fails to build due to the lack of escaping for the backslash character (\).

Fix the format of default value to prevent PDF generation errors

---

pd-control.md

Delete  region-add and region-remove from doc

Delete 2 pd parameters that have been deleted in code

---

pd-control.md
pd-recover.md
tidb-control.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12280
- Other reference link(s): https://github.com/pingcap/tidb/pull/37487

update go version to v1.19

---

tiup/tiup-mirror.md
tiup/tiup-overview.md
tiup/tiup-reference.md

Delete a deprecated tiup command-line arg

Delete a deprecated tiup command-line arg

---

ticdc/integrate-confluent-using-ticdc.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11839

ticdc: replica changelog to snowflake, add a part about ETL in snowflake

---

tiflash/tiflash-configuration.md

Delete deprecated tiflash configs

Delete deprecated tiflash configs

---

benchmark/benchmark-sysbench-v4-vs-v3.md
benchmark/benchmark-sysbench-v5-vs-v4.md
benchmark/v4.0-performance-benchmarking-with-tpcc.md
benchmark/v5.0-performance-benchmarking-with-tpcc.md
upgrade-tidb-using-tiup.md

Delete 3 tidb configs that have been deleted in code

Delete 3 tidb configs that have been deleted in code

---

cached-tables.md
mysql-schema.md

cached-tables: add description about mysql.table_cache_meta table
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10310

cached-tables: add description about mysql.table_cache_meta table

---

tidb-cloud/secure-connections-to-serverless-tier-clusters.md
tidb-cloud/tidb-cloud-faq.md

Updated Security faq of TIDB Cloud FAQ

---

releases/release-6.1.3.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12359
- Other reference link(s): https://github.com/pingcap/docs/pull/11658

add the reason for changing the default value

---

tidb-cloud/select-cluster-tier.md
tidb-cloud/serverless-tier-faqs.md
tidb-cloud/serverless-tier-limitations.md

allowed to create five Serverless clusters per account

---

develop/dev-guide-use-follower-read.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12284

tidb: update follower read guide

---

join-reorder.md
system-variables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12340

system_vars: re-set default value to ON for outer join reorder

---

ticdc/ticdc-sink-to-kafka.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12419

add a title for best practices for better findability

---

garbage-collection-configuration.md

cloud: customize content about GC configuration for cloud

---

best-practices/java-app-best-practices.md
develop/dev-guide-connection-parameters.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12332

update metric: CPS by instance

---

TOC-tidb-cloud.md
tidb-cloud/changefeed-overview.md
tidb-cloud/changefeed-sink-to-apache-kafka.md
tidb-cloud/changefeed-sink-to-mysql.md
tidb-cloud/pause-or-resume-tidb-cluster.md

add doc for multiple changefeeds and edit changefeed

add doc for multiple changefeeds and edit changefeed for tidb cloud

---

tidb-cloud/release-notes-2022.md

cloud: add release notes for 20221227

---

tidb-cloud/release-notes-2022.md

cloud: roll back default TiDB version of serverless tier clusters

---

basic-features.md
statistics.md

dev-v6.2: remove stats feedback
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12165

dev-v6.2: remove stats feedback

---

statistics.md
tidb-configuration-file.md

v6.1-v5.4: emphasize deprecation for stats feedback
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12166

v6.1-v5.4: emphasize deprecation for stats feedback

---

statistics.md
tidb-configuration-file.md

v5.3-v5.0: emphasize experimental for stats feedback
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12167

v5.3-v5.0: emphasize experimental for stats feedback

---

TOC.md
tiup/tiup-component-cluster-meta-backup.md
tiup/tiup-component-cluster-meta-restore.md
tiup/tiup-component-cluster-start.md
tiup/tiup-component-cluster.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12144

add cluster commands

---

system-variables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12446

change tidb_enable_gc_aware_memory_track default value to off

---

functions-and-operators/encryption-and-compression-functions.md

Close https://github.com/pingcap/docs/issues/11745
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12339

Remove functions related to MySQL Enterprise

---

functions-and-operators/encryption-and-compression-functions.md

format: use the standard ASCII vertical bar in table

---

_index.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12450

index page: bump up to v6.5

---

ticdc/ticdc-bidirectional-replication.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/12483

ticdc: fix cdc wording in bidirectional replication

---

br/backup-and-restore-use-cases.md
dm/quick-start-create-task.md
pd-control.md
quick-start-with-tidb.md
ticdc/deploy-ticdc.md
tidb-binlog/get-started-with-tidb-binlog.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12443

 v6.5: bump version for tools

---

production-deployment-using-tiup.md
scale-tidb-using-tiup.md
tiup/tiup-cluster.md
tiup/tiup-component-cluster-deploy.md
tiup/tiup-component-management.md
tiup/tiup-mirror.md
tiup/tiup-playground.md
upgrade-tidb-using-tiup.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12442

TiUP: bump version to 6.5

---

metadata-lock.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12414

refine the document of metadata lock

---

hardware-and-software-requirements.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12505

Update OS info for v6.5

---

ticdc/ticdc-manage-changefeed.md

`http://docs.pingcap.com/tidb/stable/manage-ticdc` is 404.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12512

add aliases for manage-ticdc

---

user-account-management.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12337

update description in user account management

---

releases/release-5.1.5.md

modify release notes 5.1.5

---

TOC.md

Add index merge to TOC

---

br/br-snapshot-guide.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12537

add aliases for br snapshot guide

---

br/backup-and-restore-overview.md
br/backup-and-restore-storages.md
br/backup-and-restore-use-cases.md
br/br-pitr-guide.md
br/br-pitr-manual.md
faq/backup-and-restore-faq.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12557

add aliases for br docs in 6.5 branch

---

tidb-cloud/secure-connections-to-serverless-tier-clusters.md

add reasons why TLS 1.0 and TLS 1.1 not support

---

tidb-cloud/integrate-tidbcloud-with-netlify.md

Change TiDB Cloud Starter Template URL in integrate-tidbcloud-with-netlify.md

cloud: update integrate-tidbcloud-with-netlify.md

---

TOC-tidb-cloud.md
tidb-cloud/_index.md
tidb-cloud/release-notes-2022.md
tidb-cloud/release-notes.md
tidb-cloud/serverless-tier-faqs.md
tidb-cloud/tidb-cloud-faq.md
tidb-cloud/tidb-cloud-release-notes.md

cloud: add release note 20230104

---

tidb-cloud/monitor-prometheus-and-grafana-integration.md

cloud: Fix dashboard json link

---

tidb-cloud/tidb-cloud-release-notes.md

Signed-off-by: Xiaoguang Sun <sunxiaoguang@gmail.com>

Upgrade Serverless Tier TiDB to 6.4

---

subquery-optimization.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12562

fix a typo in subquery optimization

---

tidb-configuration-file.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12572
- Other reference link(s): https://github.com/pingcap/tidb/blob/master/config/config.toml.example#L32

tidb configuration file: adjust the position of temp-dir

---

sql-statements/sql-statement-alter-user.md
sql-statements/sql-statement-create-user.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12574, https://github.com/pingcap/docs-cn/pull/12579

sql: fix ebnf diagram

---

tidb-cloud/csv-config-for-import-data.md
tidb-cloud/tidb-cloud-billing-dm.md

Deleted the description about internet fees

cloud dm: update description about internet fees

---

tiflash/tune-tiflash-performance.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12513

TiFlash: add a section of data compaction

---

system-variables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12386

Update the variable max_prepared_stmt_count

---

dashboard/dashboard-cluster-info.md
tiup/tiup-command-status.md
tiup/tiup-component-cluster-display.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12612

More verbose status

---

ticdc/ticdc-sink-to-mysql.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12606

fix cdc consistent config

---

sql-statements/sql-statement-split-region.md

split statement: add a description
- This PR is translated from:  https://github.com/pingcap/docs-cn/pull/11760

split statement: add a description

---

mysql-compatibility.md

Added descriptions for each default value.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/12613

mysql-compatibility: refined descriptions about lower_case_table_names

---

br/backup-and-restore-overview.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12471

Update br compatibility

---

tidb-cloud/tidb-cloud-release-notes.md

cloud: add release note for 20230110

---

TOC.md
dashboard/dashboard-cluster-info.md
tiup/tiup-command-status.md
tiup/tiup-component-cluster-audit-cleanup.md
tiup/tiup-component-cluster-display.md
tiup/tiup-component-dm-audit.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12131, https://github.com/pingcap/docs-cn/pull/12122

tiup: update cluster display and add audit cleanup.md

---

TOC.md
develop/dev-guide-outdated-for-django.md
develop/dev-guide-outdated-for-python-mysql-connector.md
develop/dev-guide-outdated-for-sqlalchemy.md

develop: archived -> legacy

---

sql-plan-replayer.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11110

revise plan replayer load

---

time-to-live.md

ttl: improve seo

---

placement-rules-in-sql.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9279

Update usage scenarios for placement-rules-in-sql.md

---

placement-rules-in-sql.md
sql-statements/sql-statement-recover-table.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9319

update a ddl command

---

tiflash/tiflash-results-materialization.md
tiflash/tiflash-supported-pushdown-calculations.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12625

add examples in tiflash docs

---

tiflash/tune-tiflash-performance.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12637, https://github.com/pingcap/docs-cn/pull/12664

add tiflash execution tuning materials

---

ticdc/integrate-confluent-using-ticdc.md

fix wrong jdbc sqlite url in ticdc confluent integration doc 
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/8608

ticdc:fix wrong jdbc sqlite url in ticdc confluent integration doc

---

sql-statements/sql-statement-drop-stats.md

Signed-off-by: YangKeao <yangkeao@chunibyo.icu>
I synchronize the syntax tree of drop stats with the newest one. It has two changes:
1. Allow drop the stats of multiple tables at the same time.
The `DROP STATS ... PARTITION ...` and `DROP STATS ... GLOBAL` syntax are deprecated, so I didn't update them to documents. …

Synchronise the syntax tree with drop stats

---

tidb-cloud/migrate-sql-shards.md

Changed the actual version to a variable.

dm: changed version to variable

---

releases/release-6.3.0.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12087

release note v6.3.0: reduce the impact of big queries

---

TOC.md
information-schema/information-schema-tiflash-segments.md
information-schema/information-schema-tiflash-tables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12629

add desc for tiflash system tables

---

backup-and-restore-using-dumpling-lightning.md
dumpling-overview.md
migrate-large-mysql-shards-to-tidb.md
migrate-large-mysql-to-tidb.md
read-historical-data.md
tidb-cloud/migrate-sql-shards.md

Refined the structure and polished some descriptions.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/7143

dumpling: refined as per cn doc

---

tidb-cloud/csv-config-for-import-data.md
tidb-cloud/import-csv-files.md
tidb-cloud/migrate-sql-shards.md

Deleted not-null and null in csv config.

cloud dm: deleted not-null and null in csv config

---

ticdc/manage-ticdc.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12466

Add compression to TiCDC Kafka sink config 5.0-6.4

---

develop/dev-guide-build-cluster-in-cloud.md
tidb-cloud/tidb-cloud-quickstart.md

cloud: update quick start for Serverless Tier cluster creation

---

tidb-cloud/tidb-cloud-release-notes.md

cloud: add release note for 20230117

---

dumpling-overview.md

dumpling: fix a tag error

---

tidb-lightning/tidb-lightning-error-resolution.md

Change "fourty" to "forty".
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11407

lightning: fix a typo

---

hardware-and-software-requirements.md
upgrade-tidb-using-tiup.md

Add the description that to deploy or upgrade TiFlash under the Linux AMD64 architecture, the CPU must support AVX2 instruction sets
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/12692, https://github.com/pingcap/docs-cn/pull/11501

add notice of tiflash avx2

---

TOC.md

According to the user visit data of the official documentation website in 2022, tiflash, configuration files, and system variables are obviously more frequently searched than other pages. It is assumed that this is because these contents are not in an easy-catch position in the navigation tree. Therefore, this PR moves the storage engine part out, and moves system variables, CLI, and configuration files upward, hoping that users can more easily catch these pages.
For details, see [tips for choosing the …

adjust the order of titles under Reference in TOC

---

tikv-configuration-file.md

The head style for the configuration item "in-memory" is not correct.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12695

tikv: fix anchor link

---

tidb-lightning/tidb-lightning-error-resolution.md

create_table -> create_time
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/10520

fix a typo of create_time

---

tidb-cloud/create-tidb-cluster.md
tidb-cloud/manage-user-access.md
tidb-cloud/tidb-cloud-password-authentication.md
tidb-cloud/tidb-cloud-quickstart.md
tidb-cloud/tidb-cloud-release-notes.md
tidb-cloud/tidb-cloud-sso-authentication.md

This PR is to add the Microsoft SSO steps for the TiDB Cloud console.

cloud: support Microsoft SSO

---

develop/dev-guide-choose-driver-or-orm.md

Translate from https://github.com/pingcap/docs-cn/pull/12748
- Maintaining two copies of the same content might bring additional costs. When there are changes needed in the MySQL Compatibility doc, it would be easy to forget to update the same information in `dev-guide-choose-driver-or-orm.md`.
- Remove detailed description of MySQL compatibility from `dev-guide-choose-driver-or-orm.md` and use the link instead.
For details, see [tips for choosing the …

develop: remove details of mysql compatibility

---

enable-tls-between-components.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12295

Update enable-tls-between-components and add TLS rotation description

---

tiup/tiup-bench.md

Add a section describing how to test TiKV using YCSB. This PR is only effective in branches 6.2 and 6.3 because later versions have been updated in v6.4. This PR is to align with the Chinese in v6.2 and v6.3.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8735

add a tutorial of ycsb bench in TiUP

---

backup-and-restore-using-dumpling-lightning.md

The file export-or-backup-using-dumpling has been removed but no aliases is added for it. This PR adds its aliases to backup-and-restore-using-dumpling-lightning to avoid a 404 page.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9837

br: add aliases to export backup using dumpling

---

telemetry.md

TiSpark has telemetry in master branch and will have release the telemetry function in the next version. So we should add TiSpark telemetry instructions in telemtry.md.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9659

[Update] Add TiSpark telemetry

---

statistics.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8151

statistics.md: update the content of analyze version2 OOM handling

---

mysql-schema.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8626

mysql-schema.md: update system tables

---

sql-plan-replayer.md

Fix typo: `REPLAER` → `REPLAYER`

sql-plan-replayer.md: fix typo

---

subquery-optimization.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/9438

fix typo in subquery optimization

---

migrate-aurora-to-tidb.md

fix some configuration comments in migrate to aurora.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/10885

migrate: update config comments in migrate to aurora

---

tidb-lightning/tidb-lightning-error-resolution.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/10428

dm: fix duplicate content

---

tidb-lightning/tidb-lightning-configuration.md

improve wording for the description of config `on-duplicate`.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/12804

lightning: improve wording for the description of config on-duplicate

---

TOC.md
dm/dm-ddl-compatible.md

add doc for dm's ddl compatibility.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/9191 https://github.com/pingcap/docs-cn/pull/11584

dm: add doc for dm's ddl compatibility

---

tikv-configuration-file.md

The text is optimized from [annotations](https://github.com/tikv/tikv/blob/b6cad4e9d989840a9b69465df2706c985ba8b00b/etc/config-template.toml#L689)
Because this is an enhancement type change, simply cherry-picking to v6.1 and v6.5 should suffice.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/10291 …

tikv: add more description for config max-bytes-for-level-base

---

upgrade-tidb-using-tiup.md

Fix a typo in upgrade-tidb-using-tiup.md.
The version number in the description part was not updated. This PR updates the incorrect v6.0 to v6.1.

Fix a typo in upgrade-tidb-using-tiup.md

---

tiflash/tiflash-configuration.md

Polish the format of dt_compression_level for better readability.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11425

tiflash: polish the format of dt_compression_level

---

tidb-binlog/tidb-binlog-faq.md

According to the following information, Pump also needs the Create View privilege to replicate data:
```sql
mysql> show grants for repl;
+----------------------------------------------------------------------------------------+
| Grants for repl@% |
+----------------------------------------------------------------------------------------+
| GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER,EXECUTE,INDEX ON . TO 'repl'@'%' |
+----------------------------------------------------------------------------------------+
mysql> CREATE TABLE t1 (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, c1 INT NOT NULL);
Query OK, 0 rows affected (0.10 sec)
mysql> INSERT INTO t1 (c1) VALUES (1),(2),(3),(4),(5);
Query OK, 5 rows affected (0.02 sec)
Records: 5 Duplicates: 0 Warnings: 0 …
```

binlog: add Create View to privileges required by Pump

---

tidb-cloud/tidb-cloud-auditing.md

This PR adds a note for requesting database audit logging because this feature is not visible by default.
- Other reference link(s): Fix https://github.com/pingcap/docs/issues/12230

cloud: add a note for requesting database audit logging

---

tidb-cloud/migrate-from-mysql-using-data-migration.md

Movded the details tag out of the itemlist.

cloud dm: fix details format issue

---

tiup/tiup-component-cluster-check.md

[TiUP v1.9.0](https://github.com/pingcap/tiup/releases/tag/v1.9.0) supports checking the yaml file before scale out. This feature is very useful and should be documented.
close #12234

[TiUP] add support check the yaml file before scale out

---

sql-plan-management.md

Fix plan binding status

---

releases/release-6.0.0-dmr.md
releases/release-6.2.0.md

This PR adds a note to v6.0 and v6.2 release notes to let users know their doc locations.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12808

v6.0 and v6.2: add a note for docs archiving

---

develop/dev-guide-create-table.md
tiflash/tiflash-overview.md

Avoid mentioning TiSpark in the TiDB Cloud docs as TiSpark is not available for TiDB Cloud.

Avoid TiSpark in TiDB Cloud docs

---

br/use-br-command-line-tool.md

add experimental warning for incremental backup & restore earlier than 5.4
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/10312

br: add experimental warning for br incremental backup

---

enable-tls-between-components.md

DC supports certificate reloading but it is not missing in the current description.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12914

security: add TiCDC for certificate reloading descriptions

---

tidb-cloud/_index.md

Update Cloud learning path for integration docs.

cloud: update learning path for integration docs

---

pd-configuration-file.md

Signed-off-by: Sen Han <00hnes@gmail.com>
Keep the layer of flow-round-by-digit consistent with [config.go](https://github.com/tikv/pd/blob/40b6daffec969295544ab082891a01d67ade09f1/server/config/config.go#L1201).
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12644

fix flow-round-by-digit in pd cfg docs

---

.github/workflows/media.yml
scripts/upload.py

Stop uploading media to aws.
all active versions
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/12896

chore: stop uploading media and pdf to aws

---

dynamic-config.md

Signed-off-by: Lucasliang <nkcs_lykx@hotmail.com>
Add docs on the dynamic modification supports to `raftstore.store-io-pool-size`.
Ref: https://github.com/tikv/tikv/issues/13964
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12765

tikv: support dynamic modifications on `raftstore.store-io-pool-size`

---

br/backup-and-restore-overview.md
br/backup-and-restore-storages.md
br/br-pitr-guide.md
br/br-snapshot-guide.md

According to some users feedback. the document of br is not easy to understand. this PR try to make it more clear.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12801, https://github.com/pingcap/docs-cn/pull/12927

backup: refactor some docs for easier understanding

---

develop/dev-guide-overview.md

Update the link of PingCAP Education from https://freeclasses.edu.pingcap.com to https://eng.edu.pingcap.com

PingCAP Education Update Sub-domain

---

br/backup-and-restore-use-cases.md
check-before-deployment.md
dm/quick-start-create-task.md
download-ecosystem-tools.md
pd-control.md
production-deployment-using-tiup.md
quick-start-with-tidb.md
scale-tidb-using-tiup.md
ticdc/manage-ticdc.md
tiflash/create-tiflash-replicas.md
tiup/tiup-cluster.md
tiup/tiup-component-cluster-deploy.md
tiup/tiup-component-management.md
tiup/tiup-mirror.md
tiup/tiup-playground.md
upgrade-tidb-using-tiup.md

Updated docs related to 6.1.3 to 6.1.4
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12924

add bump 6.1.4

---

upgrade-tidb-using-tiup.md

Move compatibility changes to a more noticeable position in upgrade guide

deploy: move compatibility changes to a more noticeable position in upgrade guide

---

ticdc/ticdc-sink-to-mysql.md

ticdc supports using gcs/azure as external storage in redo log.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12653

fix cdc redo log storage configuration

---

overview.md
tidb-cloud/tidb-cloud-intro.md

enable youtube video tracking in ga4

*: enable video tracking in ga4

---

overview.md
tidb-cloud/tidb-cloud-intro.md

*: fix youtube video tag

---

ticdc/ticdc-changefeed-config.md
ticdc/ticdc-sink-to-kafka.md

Translate from https://github.com/pingcap/docs-cn/pull/12693
TiCDC v6.6: add doc about scale out feature for Kafka changefeed.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12693

ticdc: add scale out for kafka changefeed

---

dm/dm-precheck.md
dm/monitor-a-dm-cluster.md
dm/task-configuration-file-full.md

update DM config to integrate with lightning.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12296

dm: update DM config to integrate with lightning

---

develop/dev-guide-use-follower-read.md
follower-read.md
system-variables.md

Signed-off-by: Lucasliang <nkcs_lykx@hotmail.com>
Add a new mode `prefer-leader` for the system variable `replica_read_mode`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12865

[TiDB] Add a new mode `prefer-leader` for `replica_read_mode`.

---

system-variables.md
troubleshoot-lock-conflicts.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12093

Add document for enanced pessimistic lock model

---

choose-index.md
functions-and-operators/json-functions.md
sql-statements/sql-statement-create-index.md

Add documentation for multi-valued index for v6.6 release.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12634

*: add doc for multi-valued index

---

system-variables.md

sysvar: stabilize `tidb_store_batch_size`
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12676

sysvar: stabilize `tidb_store_batch_size`

---

sql-plan-management.md
sql-statements/sql-statement-create-binding.md
sql-statements/sql-statement-drop-binding.md

Add document for the GA of SQL binding from history in v6.6.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12736

planner: binding from history GA user doc

---

sql-prepared-plan-cache.md

Update document to add plan cache diagnostics and some examples for v6.6
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12739

planner: update docs related to plan cache

---

basic-features.md
releases/release-6.2.0.md
system-variables.md

Signed-off-by: wjhuang2016 <huangwenjun1997@gmail.com>
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12680

remove tidb_enable_concurrent_ddl

---

as-of-timestamp.md
develop/dev-guide-use-stale-read.md
stale-read.md
tidb-external-ts.md

Update stale_read doc since TiFlash supports stale read.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12688

Update stale_read doc for the support of TiFlash

---

dumpling-overview.md
tidb-lightning/tidb-lightning-overview.md
tidb-troubleshooting-map.md

closes https://github.com/pingcap/docs/issues/11571

*: update oudated repo links

---

dm/dm-handle-alerts.md

Enhance description about error triggering condition
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/12301

dm: enhance description about error triggering condition

---

tidb-cloud/changefeed-replication.md
tidb-cloud/migrate-from-mysql-using-data-migration.md
tidb-cloud/tidb-cloud-dm-precheck-and-troubleshooting.md

Add a new section about the "cloud_cdc_admin" account to explain why this account is necessary.

cloud changefeed: add a new section about "cloud_cdc_admin"

---

dumpling-overview.md

closes https://github.com/pingcap/docs/issues/10526

dumpling: clarify some nuances about gc life time

---

sql-statements/sql-statement-flashback-to-timestamp.md

Add support for ddl statements in `flashback cluster`.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/12811

sql-statements: flashback cluster support through ddl history

---

tikv-configuration-file.md

Add a configuration item `raftstore.report-min-resolved-ts-interval` in TiKV configuration file.
`raftstore.report-min-resolved-ts-interval` is introduced in https://github.com/tikv/tikv/pull/12157 (on Mar 17, 2022) and the item applies to TiDB v6.1 and later versions. …

tikv: add raftstore.report-min-resolved-ts-interval

---

tidb-cloud/changefeed-replication.md

Deleted the description about the `cloud_cdc_admin` account.

cloud changefeed: delete description about `cloud_cdc_admin`

---

TOC-tidb-cloud.md
sql-plan-replayer.md
system-variables.md

add plan replayer capture.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/12318

sql: add plan replayer capture

---

tidb-lightning/tidb-lightning-configuration.md

This change guides users how to set compression for KV pairs sent to TiKV.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12948

lightning: support compression when sending kv pairs to tikv

---

best-practices/three-nodes-hybrid-deployment.md
clinic/clinic-data-instruction-for-tiup.md
dashboard/dashboard-ops-deploy.md
enable-tls-between-components.md
migrate-from-tidb-to-mysql.md
pd-control.md
replicate-data-to-kafka.md
scale-tidb-using-tiup.md
three-data-centers-in-two-cities-deployment.md
ticdc/deploy-ticdc.md
ticdc/integrate-confluent-using-ticdc.md
ticdc/ticdc-changefeed-overview.md
tidb-control.md
tiflash/create-tiflash-replicas.md
tiflash/tiflash-configuration.md
tikv-control.md
tiup/tiup-cluster.md
troubleshoot-lock-conflicts.md
troubleshoot-write-conflicts.md

- It's not clear whether the `<cluster-version>` placeholder contains `v` or not.
- To make it more accurate, this PR replaces `tiup ctl:<cluster-version>` with `tiup ctl:v<CLUSTER_VERSION>`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12998

update tiup ctl:<version> to tiup clt:v<version>

---

grafana-tidb-dashboard.md

Close https://github.com/pingcap/docs-cn/issues/12312.
This PR lists these key metrics using H3 instead of list.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13010

TiDB Monitoring Metrics: update key metrics from list to headings

---

information-schema/information-schema-slow-query.md
statement-summary-tables.md
tidb-cloud/serverless-tier-limitations.md
tidb-cloud/tune-performance.md

Update information-schema slow query & Statement.md

---

tidb-cloud/scale-tidb-cluster.md

cloud: tikv/tiflash scale in

---

tidb-cloud/built-in-monitoring.md
tidb-cloud/serverless-tier-limitations.md

cloud: support built-in monitoring for serverless tiers

---

tidb-cloud/tidb-cloud-release-notes.md

cloud: add release notes for 0214

---

placement-rules-in-sql.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12682

placementinsql: add the survival preferences docs

---

glossary.md

fix the heading level of raft engine

glossary: fix the heading level of raft engine

---

sql-statements/sql-statement-create-table.md

Close https://github.com/pingcap/docs/issues/11630
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13018

sql: fix the number of supported columns in a single table

---

keywords.md

Close https://github.com/pingcap/docs/issues/7982
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13028

sql: add a special keywords section

---

statistics.md
system-variables.md

This PR describes the default value difference between OP and Cloud for the tidb_analyze_version variable to avoid any misuse.

tidb_analyze_version: describe default value difference between OP and Cloud

---

tidb-cloud/tidb-cloud-glossary.md

Cloud: Modify the heading level of **Credit** from H2 to H3

fix the heading level of Credit

---

sql-statements/sql-statement-explain.md

`EXPLAIN FOR CONNECTION` is used to get the execution plan of the currently executed SQL query or the last executed SQL query in a connection.
Fix the compatibility to make it consistent with https://github.com/pingcap/tidb/pull/10030
```
Differences with MySQL EXPLAIN FOR
If one connection is sleeping, query for query plan for that connection will get nothing in MySQL. However, in this PR, query play for last query will be returned.
Side effect of 1., EXPLAIN FOR CONNECTION <id of this connection> will get error in MySQL, but will get query plan of last query in this PR.
If one without ProcessPriv queries plan for another user's connection, MySQL won't return error if that connection does not running any queries, however, in this PR, an error will always returns, even if that connection …
```

explain for connection: fix the compatibility with MySQL

---

TOC.md
tidb-lightning/tidb-lightning-log-message-explanation.md

Added doc to explain lightning log message, since it binds with specific tidb version. so we add it as part of 5.4 release currently
- This PR is translated from: NA

Add lightning log message explanation doc

---

tikv-configuration-file.md

This PR changes the default values of rocksdb.defaultcf.block-size and rocksdb.writecf.block-size to 16KB

update default value

---

clinic/clinic-data-instruction-for-tiup.md
clinic/clinic-introduction.md
clinic/clinic-user-guide-for-tiup.md
clinic/quick-start-with-clinic.md

Diag is open source. This PR adds the repo link for Diag.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13049

clinic: add Diag repo link

---

br/backup-and-restore-overview.md
br/backup-and-restore-storages.md
br/br-incremental-guide.md
br/br-pitr-manual.md
br/br-snapshot-guide.md
br/use-br-command-line-tool.md
dumpling-overview.md
migrate-aurora-to-tidb.md
migrate-large-mysql-shards-to-tidb.md
migrate-large-mysql-to-tidb.md
sql-statements/sql-statement-backup.md
sql-statements/sql-statement-restore.md
ticdc/ticdc-sink-to-cloud-storage.md
tidb-lightning/tidb-lightning-command-line-full.md
tidb-lightning/tidb-lightning-configuration.md
tidb-lightning/tidb-lightning-data-source.md
tidb-lightning/tidb-lightning-distributed-import.md
tidb-lightning/tidb-lightning-logical-import-mode-usage.md
tidb-lightning/tidb-lightning-overview.md
tidb-lightning/tidb-lightning-physical-import-mode-usage.md

add session-token to external storage url
Now we use the iam user with its access key id and secret access key to access s3. But the best practice from aws is using the iam role with its access ket id, secret access key and session token to access s3. Because the session token is time-limited. …

lightning/br/dumpling: add session-token to external storage url

---

system-variables.md

Correct links for tidb_enable_paging

system-variables: Correct links for tidb_enable_paging

---

_index.md

update _index.md for v6.6

---

dashboard/dashboard-intro.md
pd-configuration-file.md
production-deployment-using-tiup.md
quick-start-with-tidb.md
system-variables.md
telemetry.md
tidb-configuration-file.md
tispark-overview.md
tiup/tiup-command-telemetry.md
tiup/tiup-overview.md
upgrade-tidb-using-tiup.md

*: disable telemetry by default
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13009

*: disable telemetry by default

---

production-deployment-using-tiup.md
scale-tidb-using-tiup.md
ticdc/deploy-ticdc.md
tiup/tiup-cluster.md
tiup/tiup-component-cluster-deploy.md
tiup/tiup-component-management.md
tiup/tiup-mirror.md
tiup/tiup-playground.md
upgrade-tidb-using-tiup.md

bump version 6.6 tiup
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12973

bump version 6.6 tiup

---

develop/dev-guide-overview.md

The following list with `CustomContent` is rendered as two unordered lists in documentation website:
```markdown
- [Quick Start](/develop/dev-guide-build-cluster-in-cloud.md)
- [Choose Driver or ORM](/develop/dev-guide-choose-driver-or-orm.md)
<CustomContent platform="tidb">
- [Connect to TiDB](/develop/dev-guide-connect-to-tidb.md)
</CustomContent>
- [Database Schema Design](/develop/dev-guide-schema-design-overview.md)
- [Write Data](/develop/dev-guide-insert-data.md)
- [Read Data](/develop/dev-guide-get-data-from-single-table.md)
- [Transaction](/develop/dev-guide-transaction-overview.md)
- [Optimize](/develop/dev-guide-optimize-sql-overview.md)
- [Example Applications](/develop/dev-guide-sample-application-spring-boot.md)
```
In TiDB documentation, the content is:
```markdown
- [Quick …
```

dev guide: fix a render issue

---

tiup/tiup-component-dm-patch.md

Add example about how to apply hotfix to dm cluster.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8143, https://github.com/pingcap/docs-cn/pull/12858

Add example about how to apply hotfix to dm cluster

---

deploy-monitoring-services.md

trigger jenkins for pdf update

trigger jenkins for pdf update

---

develop/dev-guide-schema-design-overview.md

- Expression indexes is GA in TiDB 6.5 and the description `[Expression indexes](/sql-statements/sql-statement-create-index.md#expression-index) (Experimental)` is outdated.
- Maintaining two copies of the same content might bring additional costs. When there are changes needed in the TiDB Features doc and TiDB Limitations doc, it would be easy to forget to update the same information in `develop/dev-guide-schema-design-overview.md`.
- Remove details of specialized indexes and object limitations from `develop/dev-guide-schema-design-overview.md` and use the link instead.
By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a …

develop: use cross-references link instead of detailed tables

---

TOC.md
releases/release-notes.md
releases/release-timeline.md

v6.6: add dmr to toc
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13112

v6.6: add dmr to toc

---

tidb-cloud/tidb-cloud-dm-precheck-and-troubleshooting.md

cloud: fix a tiny error

---

tidb-cloud/manage-user-access.md
tidb-cloud/tidb-cloud-console-auditing.md

TiDB Cloud has improved the Console audit log function. Function docs are now updated.

Update console audit log feature documentation

---

tidb-cloud/tidb-cloud-console-auditing.md

Changes reason: There is another similar note before the event type table. 

cloud: remove a note about event type

---

.github/pull_request_template.md
scripts/pr_reminder_basedon_assignee.py

chore: update pr bot for v7.0

---

system-variables.md
tidb-configuration-file.md

Close https://github.com/pingcap/docs-cn/pull/12981
Translate form https://github.com/pingcap/docs-cn/pull/12979
> controls whether the corresponding TiDB server can run DDL statements or not.
The description of `tidb_enable_ddl` is inaccurate. This PR changes the description of tidb_enable_ddl to `controls whether the corresponding TiDB instance can become a DDL owner or not`. …

tidb_enable_ddl: modify the description from "run DDLs" to "become DDL owner"

---

tiup/tiup-playground.md

Describe how to specify tag in tiup playground.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12740

tiup: specify a tag when using playground

---

dr-multi-replica.md

Fix the toml format in dr-multi-replica.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13166

fix format in dr-multi-replica

---

config-templates/complex-mini.yaml
config-templates/simple-mini.yaml
minimal-deployment-topology.md

A presales colleague mentioned that our docs does not clearly specify the minimal storage requirement for pd and tidb, which makes readers confused.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13160, https://github.com/pingcap/docs-cn/pull/12953

add minimal storage for pd and tidb

---

alert-rules.md

Keep the rule consistent with https://github.com/pingcap/tidb/blob/435dc5849f5d2f32bf52bc835df9bb585809ae79/infoschema/metric_table_def.go#L1368-L1372
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13175

alert rule: fix the rule of TiKV_scheduler_command_duration_seconds

---

best-practices/three-dc-local-read.md

After https://github.com/pingcap/tidb/pull/28033/files merged, need to set tidb_replica_read as closest-replicas for local read.
When using the Stale Read feature to read local data under three DCs deployment, you need to set `tidb_replica_read = closest-replicas`. …

three dc: set tidb_replica_read to closest-replicas

---

TOC-tidb-cloud.md
tidb-cloud/terraform-get-tidbcloud-provider.md
tidb-cloud/terraform-tidbcloud-provider-overview.md
tidb-cloud/terraform-use-backup-resource.md
tidb-cloud/terraform-use-cluster-resource.md
tidb-cloud/terraform-use-import-resource.md
tidb-cloud/terraform-use-restore-resource.md

1. Add terraform import resource
2. optimize other terraform docs

Add terraform import resource

---

TOC-tidb-cloud.md
tidb-cloud/terraform-use-import-resource.md

This PR fixes the wrong reference of the Terraform import doc.

cloud: update Terraform TOC

---

releases/release-6.6.0.md
tikv-configuration-file.md
tune-tikv-memory-performance.md

Deprecate raftdb.enable-statistics
https://github.com/tikv/tikv/pull/13942
- Other reference link(s): https://github.com/pingcap/docs/pull/11626

tikv: deprecate enable-statistics

---

auto-random.md

https://github.com/pingcap/tidb/pull/38617 supports defining `AUTO_RANDOM` on the first column in a composite clustered primary key.
- Other reference link(s): https://github.com/pingcap/tidb/pull/38617

auto-random: support composite clustered primary key

---

releases/release-6.5.0.md
ticdc/ticdc-overview.md

- Add bidirectional replication in cdc overview
- Fix 6.5.0 release notes
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12654

ticdc: fix overview and 6.5 release notes

---

br/backup-and-restore-use-cases.md
check-before-deployment.md
dm/quick-start-create-task.md
download-ecosystem-tools.md
pd-control.md
production-deployment-using-tiup.md
quick-start-with-tidb.md
scale-tidb-using-tiup.md
ticdc/manage-ticdc.md
tidb-binlog/get-started-with-tidb-binlog.md
tiflash/create-tiflash-replicas.md
tiup/tiup-cluster.md
tiup/tiup-component-cluster-deploy.md
tiup/tiup-component-management.md
tiup/tiup-mirror.md
tiup/tiup-playground.md
upgrade-tidb-using-tiup.md

This PR updated the example TiDB version in docs from v6.1.4 to v6.1.5.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13192

v6.1: bump version for v6.1.5

---

tidb-cloud/changefeed-sink-to-apache-kafka.md
tidb-cloud/changefeed-sink-to-mysql.md
tidb-cloud/config-s3-and-gcs-access.md

Refine steps for creating access keys.

cloud: refine steps for creating access keys

---

releases/release-6.1.5.md

Update release-6.1.5.md to add a link for telemetry

---

tidb-cloud/api-overview.md

cloud: add imports to api resources

---

tidb-cloud/serverless-tier-limitations.md
tidb-cloud/tune-performance.md

cloud: add slow query page to serverless

---

tidb-cloud/tidb-cloud-release-notes.md
tidb-cloud/tidb-cloud-roadmap.md

- add release notes for release 20230228.
- update roadmap accordingly.

cloud: add release notes; update roadmap

---

functions-and-operators/expressions-pushed-down.md
functions-and-operators/window-functions.md
tiflash/tiflash-supported-pushdown-calculations.md

- Specify MAX() isn't supported as window function.
- Extend the examples with both a MAX() and a ROW_NUMBER() example.
- Add a link to the window_functions page and add links to other direction as well.
- Add a link to the TiKV pushdown information page.
- Update existing examples to more clearly indicate how you can see what is pushed down, e.g. by highlighting the right row/column from the explain plan. …

TiFlash: Revise the pushdown information

---

config-templates/complex-cdc.yaml

Close https://github.com/pingcap/docs/issues/5962
Add cdc configs to the `server_configs` part so that users know they can configure cdc para in this part as well, besides `cdc_servers`.

config: add cdc configs to server_configs

---

tidb-cloud/changefeed-sink-to-apache-kafka.md
tidb-cloud/changefeed-sink-to-mysql.md

Clarified that you need to create a table in MySQL only if you decide not to load full data.

changefeed: updated prerequisites for sink to mysql

---

dynamic-config.md

fix a dynamic config

---

system-variables.md

This PR fixes the issue that some variable names have a gray background and some do not. 

unify the format of system variable titles

---

system-variables.md

This PR fixes the issue that some variable names have a gray background and some do not.

v6.5: unify the format of system variable titles

---

ticdc/ticdc-alert-rules.md

The rule of cdc_resolvedts_high_delay is `(time() - ticdc_processor_resolved_ts / 1000) > 300` and the threshold should be **5 minutes** instead of **10 minutes**
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13234

ticdc: fix the description of cdc_resolvedts_high_delay

---

system-variables.md

Fix `validate_password`.check_user_name to `validate_password.check_user_name`

Fix variable title format error

---

system-variables.md

When we search for a system name with `` included in the variable name title, the first link in the result for system variables does not redirect correctly. This PR fixes the issue by removing the ``.

system-variables: remove `` from variable section titles to fix the search link issues

---

system-variables.md

When we search for a system name with `` included in the variable name title, the first link in the result for system variables does not redirect correctly. This PR fixes the issue by removing the ``.

v6.5: remove `` from variable section titles to fix the search link issues 

---

tikv-configuration-file.md

- Add right-derive-when-split (introduced in v3.0)
- Add more description for `compaction-pri` https://github.com/pingcap/docs/pull/7376/files#r854214472 (v5.4 and later versions)

tikv config: align with Chinese

---

ticdc/ticdc-sink-to-mysql.md

Add note about `/path` for the MySQL Sink of TiCDC

ticdc-sink-to-mysql: add note about path

---

grafana-tidb-dashboard.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13272

grafana-tidb-dashboard: update DDL related metrics

---

privilege-management.md

Add description about the `SUPER` privilege
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13275

Add description about `SUPER` privilege

---

user-account-management.md

update the Forgot root password
Close https://github.com/pingcap/docs-cn/issues/5959
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11507

update the Forgot root password

---

sql-statements/sql-statement-update.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13304

sql: update incorrect mysql compatibility info

---

syncer-overview.md

syncer: add a missing alias

---

partition-pruning.md
partitioned-table.md

- Uppercase function names
- Add `()` to indicate it is a function
- Add link to docs

partitioning: change formatting

---

tidb-cloud/tidb-cloud-release-notes.md

cloud: add release notes

---

tidb-cloud/backup-and-restore.md

- Support turning off auto backup on console. 
- Rearrange the description of backup settings in a different order to match the UI.

cloud: support disabling auto backup

---

tidb-resource-control.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13333

resource_control: fix rfc link

---

as-of-timestamp.md
stale-read.md
tidb-read-staleness.md
tikv-configuration-file.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13073

Add stale read tikv configuration documentation

---

TOC.md
basic-features.md
sql-statements/sql-statement-lock-tables-and-unlock-tables.md
tidb-configuration-file.md

Close https://github.com/pingcap/docs/issues/8632
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13301

sql-statements: add doc of lock tables and unlock tables

---

tikv-configuration-file.md

The value range of max-thread-count is modified in https://github.com/tikv/tikv/pull/13766 (TiDB v6.5.1 and later versions)
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13340

tikv: update value range of max-thread-count

---

develop/dev-guide-sample-application-spring-boot.md

Update the version of JPA to the latest stable version
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13362

[Update] new version of JPA adaption

---

troubleshoot-lock-conflicts.md

as title
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/13386

tidb-ctl: fix decoder command

---

dashboard/continuous-profiling.md

Fix version description regarding the Continuous Profiling's switch.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13399

conprof: fix version desc

---

dumpling-overview.md
releases/release-5.0.0.md

Various formatting fixes

---

pd-control.md

Close #10690 
`service-gc-safepoint` is introduced in https://github.com/tikv/pd/pull/2797
```
~$ tiup ctl:v6.5.0 pd service-gc-safepoint
Starting component `ctl`: /home/.tiup/components/ctl/v6.5.0/ctl pd service-gc-safepoint
{
"service_gc_safe_points": [
{
"service_id": "gc_worker",
"expired_at": 9223372036854775807,
"safe_point": 439923410637160448
}
],
"gc_safe_point": 0
}
```
For details, see [tips for choosing the affected versions (in Chinese)](https://github.com/pingcap/docs-cn/blob/master/CONTRI …

pd control: add service-gc-safepoint command

---

dumpling-overview.md

The previous description about privileges required for exporting data from Dumpling is not clear. This PR aims to detail the requirements in a more clear way.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10884

update description about dumpling privileges

---

br/br-snapshot-manual.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13393

br: add a note about GC

---

br/backup-and-restore-use-cases.md

Remove a check item for backup using br
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13395

br: remove an inaccurate prerequisite

---

templates/copyright.tex

Update the date in copyright from 2019 to 2023
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13425

update the copyright date to 2023

---

migration-tools.md
tidb-cloud/backup-and-restore.md

Fixed typo which misspelt as 'custer' where 'cluster' should be used.

fix typo mis-spelled as 'custer'

---

clustered-indexes.md
shard-row-id-bits.md
troubleshoot-hot-spot-issues.md

1. The change in default value for [`tidb_enable_clustered_index`](https://docs.pingcap.com/tidb/stable/system-variables#tidb_enable_clustered_index-new-in-v50) wasn't propagated to all docs as now non-integer PK's will also use a clustered index by default
2. A table without a primary key is not a good example.
3. Add links between related docs
For details, see [tips for choosing the affected versions](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md#guideline-for-choosing-the-affected-versi …

Update docs of `SHARD_ROW_ID_BITS`

---

functions-and-operators/operators.md
functions-and-operators/string-functions.md

One page already listed `SOUNDS LIKE` as unsupported, while it was listed as supported on another page.
MySQL 8.0.32:
```
sql> SELECT "FOO" SOUNDS LIKE "FOO";
+-------------------------+
| "FOO" SOUNDS LIKE "FOO" |
+-------------------------+
|                       1 |
+-------------------------+
1 row in set (0.0009 sec)
sql> SELECT SOUNDEX("FOO");
+----------------+
| SOUNDEX("FOO") |
+----------------+
| F000           |
+----------------+
1 row in set (0.0005 sec)
sql> SELECT VERSION();
+-----------+
| VERSION() |
+-----------+
| 8.0.32    |
+-----------+
1 row in set (0.0003 sec)
```
TiDB:
```
sql> SELECT "FOO" SOUNDS LIKE "FOO";
ERROR: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column …
```

functions-and-operators: Correct support for `SOUNDS LIKE`

---

faq/backup-and-restore-faq.md
system-variables.md

as title
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/13309

pitr: compatibility between pitr and accelerated indexing

---

system-variables.md

as title
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/13458

ddl: update fast ddl compatibility description

---

templates/copyright.tex

Fix the typo in copyright.tex from "Reversed" to "Reserved".

fix the typo in copyright.tex

---

TOC-tidb-cloud.md
tidb-cloud/limitations-and-quotas.md

- adjust toc to align the limits of dedicated and serverless
- modify the title of `tidb-cloud/limitations-and-quotas.md`

cloud: adjust toc to align the limits of dedicated and serverless

---

sql-statements/sql-statement-alter-table.md

- The old example didn't have a table name, causing it to always return errors in both TiDB and MySQL.
- The old example didn't work in MySQL.

sql-statement-alter-table: Beter example for schema dependency

---

releases/release-6.6.0.md
tidb-lightning/tidb-lightning-configuration.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13449

lightning: set compress-kv-pairs as experimental 

---

tiflash/tiflash-configuration.md

Add three tiflash configurations.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13342

add TiFlash spill doc

---

dynamic-config.md
tiflash/create-tiflash-replicas.md
tikv-configuration-file.md

rename tikv config `server.snap-max-write-bytes-per-sec` to `server.snap-io-max-bytes-per-sec`.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/13336
- Other reference link(s):https://github.com/tikv/tikv/pull/14275

*: rename tikv config server.snap-max-write-bytes-per-sec

---

tidb-cloud/release-notes-2022.md
tidb-cloud/scale-tidb-cluster.md
tidb-cloud/tidb-cloud-dm-precheck-and-troubleshooting.md
tidb-cloud/tidb-cloud-release-notes.md

TiDB Cloud supports decreasing the size of TiDB, TiKV, and TiFlash nodes to scale in a Dedicated Tier.

tidb cloud: support decreasing the node size to scale in a Dedicated Tier

---

tidb-cloud/migrate-from-mysql-using-data-migration.md

Data migration : suports GCP Tokyo region

cloud: suport GCP Tokyo region for data migration

---

tidb-resource-control.md

- This PR is translated from: pingcap/docs-cn#13501

resource_control: fix resource group rfc link

---

system-variables.md

Add a note to the `tidb_rc_read_check_ts` system variable.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/13405

*: add a note to the `tidb_rc_read_check_ts` system variable

---

tidb-lightning/tidb-lightning-configuration.md
tidb-lightning/tidb-lightning-logical-import-mode-usage.md
tidb-lightning/tidb-lightning-physical-import-mode.md

Add add-index-by-sql.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/13391

lightning: add add-index-by-sql

---

ticdc/ticdc-csv.md
ticdc/ticdc-sink-to-cloud-storage.md

Added description about index.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/13448

ticdc: add index design for cdc storage sink

---

ticdc/ticdc-changefeed-config.md
ticdc/ticdc-sink-to-kafka.md

Update changefeed scheduler configs.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/13341

ticdc: update changefeed scheduler configs

---

tidb-cloud/migrate-from-mysql-using-data-migration.md

cloud: remove mumbai from DM support

---

develop/dev-guide-third-party-support.md
develop/dev-guide-third-party-tools-compatibility.md

Add a link to describe third-party tools.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13463

Explain the third party means

---

tidb-cloud/changefeed-sink-to-apache-kafka.md
tidb-cloud/changefeed-sink-to-mysql.md

Updated the number of changefeeds from 10 to 5.

cloud changefeed: updated the number of changefeeds from 10 to 5

---

TOC-tidb-cloud.md
TOC.md
system-variables.md
tiflash/tiflash-late-materialization.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13359

TiFlash late materialization

---

releases/release-6.5.1.md

For v6.5.1, the batch update support for TiCDC is not provided.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13511

release-6.5.1: remove batch update support description for TiCDC

---

system-variables.md

Add links to other resources related to `max_execution_time`.

system-variables: Link various resources related to MAX_EXECUTION_TIME

---

tidb-cloud/monitor-built-in-alerting.md

cloud: Update monitor-built-in-alerting.md

---

TOC-tidb-cloud.md
TOC.md
blocklist-control-plan.md
derive-topn-from-window.md
system-variables.md

In v7.0.0, TiDB supports deriving TopN or Limit from window functions.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13445

add docs for derive topn from window

---

tidb-resource-control.md

resource control: fix a link

---

tiflash/tiflash-spill-disk.md

tiflash-spill-disk: make SQL code stacked

---

tidb-lightning/tidb-lightning-configuration.md
tidb-lightning/tidb-lightning-logical-import-mode-usage.md
tidb-lightning/tidb-lightning-physical-import-mode-usage.md
tidb-lightning/tidb-lightning-physical-import-mode.md

as tittle
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/13515
- Other reference link(s):https://github.com/pingcap/docs/pull/12948

lightning: update the default value of add-index-by-sql to false

---

system-variables.md

Add the doc for tidb_load_based_replica_read_threshold.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13382

system variable: add tidb_load_based_replica_read_threshold

---

information-schema/information-schema-resource-groups.md
sql-statements/sql-statement-create-resource-group.md
sql-statements/sql-statement-set-resource-group.md
tidb-resource-control.md

as tittle
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/13533

resource_groups: add description about default resource group

---

system-variables.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/13537

update tidb_dml_batch_size for load data

---

sql-plan-replayer.md
system-variables.md

Add a feature and its sysvar.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13332, https://github.com/pingcap/docs-cn/pull/13525

add sysvar tidb_enable_plan_replayer_continuous_capture

---

tidb-cloud/_index.md
tidb-cloud/scale-tidb-cluster.md
tidb-cloud/select-cluster-tier.md
tidb-cloud/tidb-cloud-quickstart.md
tidb-cloud/tidb-cloud-release-notes.md

- "https://docs.pingcap.com/tidbcloud/beta" is redirected to "https://docs.pingcap.com/tidbcloud" (302).
- "https://docs.pingcap.com/tidbcloud/public-preview" is redirected to "https://docs.pingcap.com/tidbcloud" (302).
The metadata in `_index,md` should be modified to `['/tidbcloud/privacy-policy', '/tidbcloud/terms-of-service', '/tidbcloud/service-level-agreement']`. Then, "https://docs.pingcap.com/tidbcloud/beta/privacy-policy" -> "https://docs.pingcap.com/tidbcloud/privacy-policy" -> "https://docs.pingcap.com/tidbcloud/_index".
By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED …

cloud: update the aliases in _index.md

---

tidb-cloud/migrate-from-mysql-using-data-migration.md

cloud: support two new GCP regions for data migration

---

TOC-tidb-cloud.md
tidb-cloud/changefeed-overview.md
tidb-cloud/changefeed-sink-to-tidb-cloud.md

cloud: Sink to TiDB Cloud

---

tidb-cloud/tidb-cloud-encrypt-cmek.md

TiDB Cloud provides customer-managed encryption key (CMEK) capabilities for static data.

TiDB Cloud supports CMEK encryption

---

system-variables.md
tidb-resource-control.md

as tittle
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/13541

resource control: change resource control to experimental

---

_index.md
dashboard/dashboard-user.md
develop/dev-guide-third-party-support.md
dm/task-configuration-file-full.md
migrate-large-mysql-shards-to-tidb.md
migrate-small-mysql-shards-to-tidb.md
ticdc/ticdc-changefeed-config.md
tidb-lightning/tidb-lightning-configuration.md
tiflash/tiflash-configuration.md

*: update absolute links in learning path and others

---

tidb-cloud/tidb-cloud-billing-ticdc-rcu.md

cloud: update RCU description

---

README.md

update readme
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/13547

update readme for 7.0

---

ticdc/ticdc-avro-protocol.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13462

cdc add description about avro float incompatible change

---

tidb-cloud/_index.md

Add some documents into TiDB Cloud learning path:
- Add BR, Changefeed, and CLI into the "Use" section.
- Update the "Use" section to "Maintain".

cloud learning path: add back up and restore

---

sql-statements/sql-statement-load-data.md
sql-statements/sql-statement-operate-load-data-job.md
sql-statements/sql-statement-show-load-data.md

as tittle
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/13552

lightning: add note about experimental feature for sql-statement-load-data

---

production-deployment-using-tiup.md
scale-tidb-using-tiup.md
tiup/tiup-cluster.md
tiup/tiup-component-cluster-deploy.md
tiup/tiup-component-management.md
tiup/tiup-mirror.md
tiup/tiup-playground.md
upgrade-tidb-using-tiup.md

as title
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/13538

bump version to 7.0

---

LICENSE
README.md

Update the `LICENSE` to [CC BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/)
- This PR is translated from: N/A

Update the LICENSE

---

br/backup-and-restore-use-cases.md
dm/quick-start-create-task.md
pd-control.md
quick-start-with-tidb.md
ticdc/deploy-ticdc.md
tidb-binlog/get-started-with-tidb-binlog.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/13543

bump version for tool in v7.0

---

basic-features.md

as title
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/13503

*: update basic features for 7.0

---

information-schema/information-schema-user-privileges.md

cloud: update the user privileges output for the root user

---

tidb-cloud/naming-conventions-for-data-import.md

improve import's file naming
- Other reference link(s): close https://github.com/pingcap/docs/issues/13030

import: improve file naming

---

best-practices/java-app-best-practices.md
develop/dev-guide-connection-parameters.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13551

[Update] tomcat-jdbc version update

---

migration-tools.md

Translate from https://github.com/pingcap/docs-cn/pull/13568

migration tools: remove duplicate upstream

---

partitioned-table.md

as title
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/13420

partitioned-table: fix a command

---

time-to-live.md

Translate from https://github.com/pingcap/docs-cn/pull/13576
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13576

TTL: fix SQL statement

---

.github/pull_request_template.md

chore: update pr template for v7.1

chore: update pr template for v7.1

---

upgrade-tidb-using-tiup.md

as title
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13585

bump version for upgrade guide

---

tidb-cloud/tidb-cloud-import-local-files.md

- Added description for multiple and fewer columns, during local file import.
- Listed the options of the CSV configuration.

import: adjust for new local import

---

tidb-lightning/tidb-lightning-configuration.md

as tittle
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/13586

lightning: update descriptions of some parameters

---

basic-features.md

basic features: update user-level lock

basic features: update user-level lock

---

sql-statements/sql-statement-drop-table.md
statement-summary-tables.md

Fix https://github.com/pingcap/docs-cn/issues/11327
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11330, https://github.com/pingcap/docs-cn/pull/12845

fix statement summary table descriptions and add warning message of drop table

---

benchmark/benchmark-tidb-using-ch.md
releases/release-6.4.0.md
system-variables.md
tidb-configuration-file.md

The changes in this PR are the English version of the following PRs:
- https://github.com/pingcap/docs-cn/pull/12181
- https://github.com/pingcap/docs-cn/pull/12145
- https://github.com/pingcap/docs-cn/pull/12088
- https://github.com/pingcap/docs-cn/pull/13504
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12181, …

translate four pingcap/docs-cn PRs

---

tidb-cloud/changefeed-replication.md
tidb-cloud/manage-user-access.md
tidb-cloud/tidb-cloud-auditing.md
tidb-cloud/tidb-cloud-console-auditing.md
tidb-cloud/tidb-cloud-support.md

Update the entry of the help info to the ? button 

cloud: update help info

---

tidb-cloud/tidb-cloud-quickstart.md

TiDB Cloud supports a new page: Getting Started Tutorials

add a new page: Getting Started Tutorials

---

alert-rules.md

miss-peer-region-count is correct .
fix rule of PD_miss_peer_region_count
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13455

fix the rule of PD_miss_peer_region_count

---

sql-plan-management.md

Update the `sql-plan-management.md` document to add a note that highlights the required privilege when using SQL bindings.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13161

planner: supply privilege description binding need

---

.github/workflows/dispatch.yml
.github/workflows/link-fail-fast.yaml
.github/workflows/link.yaml

- Remove `assignees` in the Create Issue From File step. 
- Close https://github.com/pingcap/docs/issues/11371

ci: remove assignees in Links, update the deprecated set-output command

---

tidb-lightning/tidb-lightning-configuration.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13461

Lightning: fix default value in configuration

---

sql-statements/sql-statement-grant-privileges.md
sql-statements/sql-statement-revoke-privileges.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13368

Add the incompatibility about `grant` and `revoke`

---

TOC.md
_index.md
tidb-roadmap.md

1. Move tidb roadmap from [tidb repo](https://github.com/pingcap/tidb/blob/master/roadmap.md) to docs.pingcap.com (related: https://github.com/pingcap/tidb/pull/42829)
2. Add to TOC
3. Add to learning path
4. Add to footer in https://github.com/pingcap/website-docs/pull/409
Preview: https://ran-huang-pingcap-docs-website-scaffold-preview-pr-11.surge.sh/tidb/dev/tidb-roadmap
For details, see [tips for choosing the affected versions](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md#guideline-fo …

add tidb roadmap

---

releases/release-6.6.0.md
sql-prepared-plan-cache.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13518

planner: supply description about plan cache supporting limit

---

TOC.md
tidb-configuration-file.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13522

tidb: add missing labels in config file

---

dm/dm-faq.md
dm/dm-overview.md

Add DM's limit for view-related DDL/DML.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/11379

dm: add a faq about view in dm faq

---

.lycheeignore

exclude links like `http://localhost:2379/`

ci: update lycheeignore

---

sync-diff-inspector/sync-diff-inspector-overview.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/13651

sync-diff-inspector: update images for sync diff

---

.github/workflows/ci.yaml
.github/workflows/link-fail-fast.yaml
.github/workflows/link.yaml
.github/workflows/media.yml
.github/workflows/rebase.yml

Node.js 12 actions and the `set-output` command are deprecated.
This PR updates the following actions to use Node.js 16:
- `actions/checkout@v2`
- `actions/setup-node@v1`
- `andstor/file-existence-action@v1`
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13665

ci: update specified actions to the latest version

---

TOC.md
dm/dm-safe-mode.md

Add doc for DM safe mode.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8781

add doc for dm safe mode

---

tidb-cloud/built-in-monitoring.md

cloud: use node-level resource metrics for monitoring

---

tidb-cloud/monitor-prometheus-and-grafana-integration-grafana-dashboard-UI.json
tidb-cloud/monitor-prometheus-and-grafana-integration.md

Prometheus Integartion supports ChangeFeed Metrics

---

TOC-tidb-cloud.md
tidb-cloud/monitor-new-relic-integration.md
tidb-cloud/third-party-monitoring-integrations.md

NewRelic Integration

---

br/backup-and-restore-use-cases.md
check-before-deployment.md
dm/quick-start-create-task.md
download-ecosystem-tools.md
pd-control.md
production-deployment-using-tiup.md
quick-start-with-tidb.md
scale-tidb-using-tiup.md
ticdc/manage-ticdc.md
tidb-binlog/get-started-with-tidb-binlog.md
tiflash/create-tiflash-replicas.md
tiup/tiup-cluster.md
tiup/tiup-component-cluster-deploy.md
tiup/tiup-component-cluster-patch.md
tiup/tiup-component-management.md
tiup/tiup-mirror.md
tiup/tiup-playground.md
upgrade-tidb-using-tiup.md

bump version for v6.1.6

---

tidb-cloud/monitor-prometheus-and-grafana-integration-grafana-dashboard-UI.json

Update the Grafana Json to master

---

sql-statements/sql-statement-alter-user.md
sql-statements/sql-statement-create-resource-group.md
tidb-resource-control.md

as tittle
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/13649

resource_control: add a example to reset user resource group to default value

---

error-codes.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/13658

resource-control: add the error number comments

---

hardware-and-software-requirements.md

as tittle
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/13715

*: add mirror dependency on CPU

---

tidb-cloud/migrate-from-mysql-using-data-migration.md
tidb-cloud/tidb-cloud-dm-precheck-and-troubleshooting.md

cloud dm: support scaling migration jobs

---

command-line-flags-for-tidb-configuration.md

This pull request updates the warning for `--proxy-protocol-networks`. Actually I misunderstood that only if `--proxy-protocol-networks` is `*`, TiDB Dashboard will not be able to connect to TiDB server, which is not true. Adding CIDR or IP addresses of PD server running TiDB Dashboard to `--proxy-protocol-networks` will not help TiDB Dashboard to connect to TiDB server because TiDB Dashboard does not support connecting to TiDB server through proxy.
Also added suggestion to set `--proxy-protocol-fallbackable` to `true` to address TiDB Dashboard connectivity.
By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility …

Update the warning for `--proxy-protocol-networks`

---

develop/dev-guide-build-cluster-in-cloud.md
tidb-cloud/create-tidb-cluster.md
tidb-cloud/tidb-cloud-quickstart.md

cloud: update cluster creation steps

---

tidb-cloud/tidb-cloud-billing.md

cloud: add doc for discounts page

---

system-variables.md
troubleshoot-hot-spot-issues.md

Add a section to describe the scenario of `tidb_load_based_replica_read_threshold`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13584

document `tidb_load_based_replica_read_threshold`

---

system-variables.md

as tittle
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/13748

system-variables: update description of datadir

---

develop/dev-guide-create-table.md
develop/dev-guide-schema-design-overview.md
generated-columns.md
time-to-live.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/13383

*: update doc for generated columns GA

---

TOC.md
releases/release-6.5.2.md
releases/release-notes.md
releases/release-timeline.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/13700

add 6.5.2 release notes

---

identify-slow-queries.md
sql-plan-replayer.md

https://github.com/pingcap/docs-cn/pull/13730

plan-replayer, slow-queries: update new diagnostic information in tidb

---

releases/release-6.5.2.md
ticdc/ticdc-changefeed-config.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13761

v6.5: modify default value descriptions for enable-partition-separator

---

hardware-and-software-requirements.md

Changed disk type from SAS to SSD.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/13770

*: correct TiDB disk type

---

statistics.md
tidb-configuration-file.md

as tittle
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/13719

*: add configuration performance lite-init-stats 

---

sql-plan-management.md

as tittle
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/13769

sql-plan: add description about plan baseline

---

TOC.md
br/br-checkpoint-backup.md
br/br-checkpoint-restore.md
releases/release-6.5.0.md

br v7.1.0 supports checkpoint restore
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13624

br: restore checkpoint

---

tidb-lightning/tidb-lightning-physical-import-mode.md

as tittle
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/13793

lihgtning: add parrallel import method 

---

credits.md

- Remove an outdated link of contributors, which does not work now
- Update the list of repos because multiple repos have been combined or migrated to another repo
**Note:** All the changed will be cherry picked to v6.5, v6.6, v7.0 according to the repo archive date, while the change of removing the outdated contributor link will be cherry picked to all selected versions. The docs-dm repo link will be kept for v5.3 and earlier versions. …

credits: remove outdated contributor link and repos

---

choose-index.md
sql-statements/sql-statement-create-index.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/13396

sql: update doc for multi-valued index GA

---

config-templates/complex-tiflash.yaml
hardware-and-software-requirements.md
tiflash/tiflash-configuration.md
tiup/tiup-cluster-topology-reference.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13579

Remove TiFlash http service

---

tiflash/tiflash-disaggregated-and-s3.md

And temporarily remove "The Write Node has a faster scaling speed" section, because it is not stable yet.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13678

Update S3 TiFlash doc

---

sql-statements/sql-statement-create-index.md

as title
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/13639

add description about the compatibility with tools for multi-valued index

---

tidb-cloud/import-csv-files.md
tidb-cloud/import-parquet-files.md

The import UI has changed:
- Summary is deleted.
- Changed **File Pattern** to a button.

import: update import UI

---

tidb-cloud/built-in-monitoring.md

cloud: update built-in-monitoring.md

---

system-variables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13756
- Other reference link(s): https://github.com/pingcap/tidb/pull/42769

system-variables: update `tidb_ddl_enable_fast_reorg`

---

tidb-cloud/tidb-cloud-release-notes.md

This PR specifies the effective scope of the load balancing improvement.

cloud: update the note for load balancing 

---

releases/release-7.1.0.md

Translate from https://github.com/pingcap/docs-cn/pull/13831
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13831

v7.1: update the description of fast online ddl

---

tidb-lightning/tidb-lightning-physical-import-mode.md

Fix the typo in `tidb-lightning/tidb-lightning-physical-import-mode.md`.

lightning: fix typo

---

tidb-cloud/tidb-cloud-org-sso-authentication.md

cloud: fix a link to basic SSO

---

tidb-lightning/tidb-lightning-physical-import-mode.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13839

update lightning capability desc

---

command-line-flags-for-tidb-configuration.md

Refer to https://github.com/pingcap/docs/pull/13254. I was wrong about the behavior of `proxy-protocol-networks`. It actually accepts connections without Proxy Protocol for the addresses outside the list. 

add description about proxy protocol

---

system-variables.md
tidb-configuration-file.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13697 and https://github.com/pingcap/docs-cn/pull/13509

translate two PRs from pingcap/docs-cn

---

foreign-key.md

Add a note to indicate that the foreign key feature is only applicable to small or medium data sizes and non-distributed systems.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13838

foreign-key: add a note about the usage 

---

system-variables.md

clarify timezone for tidb_auto_analyze_start_time  and tidb_auto_analyze_end_time
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13855

system variable: clarify timezone for tidb_auto_analyze_time

---

.github/pull_request_template.md

chore: add v7.2 to the PR template

---

scripts/release_notes_update_pr_author_info_add_dup.py

chore: update bot author info and add dup notes for release notes

---

identify-slow-queries.md

update slow query doc to add the missing metrics about backoff
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11390

update slow query doc

---

ticdc/ticdc-sink-to-mysql.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13498

add the doc for cache-prep-stmt 

---

tidb-cloud/data-service-get-started.md
tidb-cloud/data-service-manage-endpoint.md
tidb-cloud/tidb-cloud-release-notes.md
tidb-cloud/use-chat2query-api.md

This PRs guides users the difference between the region `<region> data.tidbcloud.com` and global URL `data.tidbcloud.com`

cloud: update data service docs for multi-region suppport

---

TOC.md
_index.md
migration-tools.md

- sort tools in a reasonable order
- remove binlog from tool recommendation
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13698, https://github.com/pingcap/docs-cn/pull/13638

*: sort tools; remove binlog recommendation

---

system-variables.md

The scope of these two variables (tidb_enable_gogc_tuner and tidb_gogc_tuner_threshold) is global acturally.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13574

fix the scope of tidb_enable_gogc_tuner and tidb_gogc_tuner_threshold

---

mysql-compatibility.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13868
- Other reference link(s): https://github.com/pingcap/docs/pull/12425

Remove TRUNCATE PARTITION as non-supported

---

br/backup-and-restore-storages.md
br/backup-and-restore-use-cases.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13872

br: change the permission for external storage when do restore

---

sync-diff-inspector/sync-diff-inspector-overview.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/8180

sync-diff-inspector: update report result

---

dm/dm-worker-intro.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/10883

Modify downstream database permissions

---

tidb-lightning/tidb-lightning-distributed-import.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/12828

lightning: update distributed import

---

statistics.md

refine format
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/7392

statistics: refine format

---

tidb-cloud/serverless-tier-limitations.md
tidb-cloud/tune-performance.md

cloud: provide the SQL Statement tab for Serverless Tier

---

tidb-cloud/tidb-cloud-events.md

cloud: Event page supports displaying more event types

---

tidb-cloud/import-csv-files.md
tidb-cloud/import-sample-data.md

Support the following comression formats: `.gzip`, `.gz`, `.zstd`, `.zst` and `.snappy`.

cloud: add compression formats

---

tidb-cloud/tidb-cloud-release-notes.md
tidb-cloud/tidb-cloud-roadmap.md

cloud: add release notes for 20230509 release

---

tidb-configuration-file.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13653

update description about compatible-kill-query configuration

---

alert-rules.md

Update the solution of some rules in `alert-rules.md`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13625, https://github.com/pingcap/docs-cn/pull/13892

alert rules: update the solution of some rules

---

tispark-overview.md

PDF pipeline is broken due to the svg image https://ci.pingcap.net/job/docs-cn-merge-pipeline/3990/
The log is as follows:
```
[2023-05-10T03:23:28.882Z] [pandoc warning] Unable to convert `/tmp/tex2pdf.84/d16af1cbb691bf7a1581deb103c49bcfa807f7e9.svg' for use with pdflatex.
[2023-05-10T03:39:21.441Z] ! Unable to load picture or PDF file '/tmp/tex2pdf.84/d16af1cbb691bf7a1581deb10
[2023-05-10T03:39:21.441Z] 3c49bcfa807f7e9.svg.'.
[2023-05-10T03:39:21.441Z] <to be read again> 
[2023-05-10T03:39:21.441Z]                    }
[2023-05-10T03:39:21.441Z] l.121941 ...b691bf7a1581deb103c49bcfa807f7e9.svg}}
[2023-05-10T03:39:21.442Z] 
[2023-05-10T03:39:21.442Z] pandoc: Error producing PDF
script returned exit code 43
```
By default, **CHOOSE MASTER …

tispark: remove the svg image

---

TOC-tidb-cloud.md
tidb-cloud/changefeed-overview.md
tidb-cloud/changefeed-sink-to-apache-kafka.md
tidb-cloud/changefeed-sink-to-tidb-cloud.md

change TiCDC to changefeed and label sink to kafka as beta

---

TOC.md
migrate-from-csv-files-to-tidb.md
migrate-from-parquet-files-to-tidb.md
migration-overview.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/11640

add doc for migrating parquet files

---

_index.md

as tittle
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/13952

learning path: update the link for deployment on k8s 

---

sql-statements/sql-statement-alter-resource-group.md
sql-statements/sql-statement-create-resource-group.md
sql-statements/sql-statement-drop-resource-group.md
sql-statements/sql-statement-set-resource-group.md

- This PR is translated from: #pingcap/docs-cn/pull/13957

resource_control: fix resource group related ebnf syntax

---

data-type-numeric.md
functions-and-operators/cast-functions-and-operators.md

Add note about the incompatibility result of SELECT CAST(MeN AS CHAR) between TiDB and MySQL.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7663

Add note about SELECT CAST(MeN AS CHAR) incompatibility 

---

sql-plan-replayer.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13950

sql-plan-replayer: update description about plan replayer zip file GC strategy

---

tidb-cloud/tidb-cloud-release-notes.md

add release notes for 20230516

cloud: add release notes for 20230516

---

tidb-cloud/tidb-cloud-org-sso-authentication.md

cloud: org sso supports automatic invitation

---

foreign-key.md

foreign_key: fix typo

---

benchmark/benchmark-tidb-using-sysbench.md

- Other reference link(s): https://github.com/pingcap/docs-cn/pull/13962

how-to-run-sysbench: update cmd

---

ticdc/ticdc-changefeed-config.md

TiCDC: Refine the ticdc changefeed configuration file.
N/A

ticdc: refine the ticdc changefeed configuration file.

---

pd-recover.md

Users can recover the PD from a PD node.
Translate from https://github.com/pingcap/docs-cn/pull/12186
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12186

pd-recovery: add the new way to recover

---

releases/release-7.1.0.md
ticdc/ticdc-faq.md

Add a note to explain the behavior of lossy DDL in v7.1.0
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13869

cdc: add some explanations about lossy DDL

---

pd-configuration-file.md
releases/release-7.1.0.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13989
- Other reference link(s):https://github.com/tikv/pd/pull/6265

update the behavior change about schedule.enable-diagnostic

---

partitioned-table.md

Fix the admonitions syntax from `**Notes:**` to `**Note:**`.

Fix admonitions syntax

---

sql-statements/sql-statement-load-data.md

https://github.com/pingcap/docs-cn/pull/13968
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/13968

sql-statements: clarify mysql compatibility of load data

---

tidb-cloud/naming-conventions-for-data-import.md

tidb cloud: add compression formats

---

system-variables.md

ja: fix translation of several system variables

---

hardware-and-software-requirements.md
pd-control.md
pd-recover.md
tidb-control.md

Starting from v6.1.3 (2022-12-05), the Golang version required for compiling and running TiDB is **1.19 or later**.
Starting from v7.0.0, the Golang version required for compiling and running TiDB is **1.20 or later**.
This PR updates the Golang version from 1.18.5 to 1.19 and applies to v6.5 and v6.6 …

update Golang version to 1.19

---

tidb-cloud/tidb-cloud-auditing.md

The type of COST_TIME is FLOAT instead of INTEGER.

Fix cost time type

---

.github/ISSUE_TEMPLATE/config.yml
temp.md

Direct users to AskTUG when they try to open a new issue.
The following is an example in pingcap/tidb repo.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13622

update issue template chooser

---

TOC-tidb-cloud.md
TOC.md

fix: MySQL Connect/Python -> MySQL Connector/Python

---

tidb-cloud/tidb-cloud-import-local-files.md
tidb-cloud/tidb-cloud-release-notes.md

cloud: update doc and release note for the column name rule of uploading csv files

---

releases/release-6.2.0.md
tidb-lightning/tidb-lightning-configuration.md
tidb-lightning/tidb-lightning-physical-import-mode-usage.md
tidb-lightning/tidb-lightning-physical-import-mode.md

added four parameters.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/13958

lightning: add parameters to make it more stable to import large mount of data

---

tidb-cloud/serverless-tier-faqs.md
tidb-cloud/tidb-cloud-billing.md
tidb-cloud/tidb-cloud-release-notes.md

Serverless billing date is postponed, and charges start from Jun 1.

update the billing date for serverless

---

dashboard/dashboard-resource-manager.md

Fix a render issue:
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14043

dashboard: fix a render issue

---

pd-configuration-file.md
temp.md
tidb-configuration-file.md
tiflash/tiflash-configuration.md
tikv-configuration-file.md

Give instructions on how to edit component config.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/11284

*: add instruction for editing config

---

br/backup-storage-gcs.md

Fix a command error
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/14044

br: fix a command error

---

tiflash/create-tiflash-replicas.md

Add a note that newly added tables after ALTER DATABASE is executed cannot be replicated to TiFlash automatically.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/14046

tiflash: add description about behavior after executing ALTER DATABASE

---

temp.md
ticdc/ticdc-changefeed-config.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13765

ticdc: Fix some ticdc docs master 6.5

---

temp.md
ticdc/manage-ticdc.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13766

fix ticdc config descriptions in 6.1

---

TOC.md
faq/upgrade-faq.md
smooth-upgrade-tidb.md
upgrade-tidb-using-tiup.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/14013

add doc for smooth upgrade

---

auto-random.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14053

auto-random.md: add description about max allocation times
