pingcap/docs

hardware-and-software-requirements.md

- Update `hardware-and-software-requirements.md` for v7.1
- Support openEuler 22.03 LTS SP1 x86 in v7.1
- Other reference link(s): https://github.com/pingcap/docs/pull/13561

update hardware-and-software-requirements for v7.1

---

temp.md
ticdc/ticdc-sink-to-kafka.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14073
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/13896/files#r1206258847

ticdc: add docs for insecure-skip-verify

---

tidb-cloud/tidb-cloud-glossary.md
tidb-cloud/tidb-cloud-intro.md
tidb-cloud/tidb-cloud-quickstart.md
tidb-cloud/tidb-cloud-roadmap.md

cloud: remove playground

---

TOC-tidb-cloud.md
tidb-cloud/migrate-from-mysql-using-data-migration.md
tidb-cloud/migrate-incremental-data-from-mysql-using-data-migration.md
tiflash/create-tiflash-replicas.md

cloud dm: add start position for incremental data migration

---

README.md

README.md: add release-7.1 branch
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14071

update README for v7.1

---

smooth-upgrade-tidb.md
temp.md

This PR is used to add a limit for smooth upgrade.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14052

*: add a limit for smooth upgrade

---

sql-statements/sql-statement-flashback-to-timestamp.md

Add a warning when using FLASHBACK.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14088

flashback: add alert msg in flashback statement

---

br/backup-and-restore-use-cases.md
dm/quick-start-create-task.md
pd-control.md
quick-start-with-tidb.md
ticdc/deploy-ticdc.md
tidb-binlog/get-started-with-tidb-binlog.md

v7.1: bump tool versions from v7.0.0 to v7.1.0
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14063

bump tool versions for v7.1

---

tikv-overview.md

use sentence case for heading2

---

auto-increment.md
auto-random.md

As tittle.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/14089

sql: add more descriptions about create table parameters

---

tidb-cloud/backup-and-restore.md

fix a wrong description.
The same as https://github.com/pingcap/docs/pull/13732

cloud: remove desc about dumpling and lightning

---

dm/maintain-dm-using-tiup.md
information-schema/information-schema-tidb-servers-info.md
post-installation-check.md
quick-start-with-tidb.md
system-variables.md
ticdc/deploy-ticdc.md
ticdc/ticdc-changefeed-overview.md
ticdc/ticdc-open-api-v2.md
tidb-monitoring-api.md
tiflash/create-tiflash-replicas.md
tiup/tiup-cluster.md
tiup/tiup-component-cluster-upgrade.md
tiup/tiup-component-dm-upgrade.md
upgrade-tidb-using-tiup.md

Bump version for v7.1.0
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14121

bump version for v7.1

---

quick-start-with-tidb.md

4.0: update the usage of on-premises

---

_index.md
overview.md

3.0: update the usage of on-premises

---

tidb-lightning/tidb-lightning-configuration.md
tidb-limitations.md

To make it easy to read.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/14134

lightning: refine comment format in the config file

---

tidb-cloud/tidb-cloud-release-notes.md

cloud: add a note for rename

---

_docHome.md
basic-features.md
basic-sql-operations.md
develop/dev-guide-tidb-crud-sql.md
mysql-compatibility.md
quick-start-with-tidb.md
tidb-cloud/tidb-cloud-quickstart.md

playground: add links to playground

---

system-variables.md

Resource control becomes GA in v7.1.0. Remove experimental note in tidb_enable_resource_control.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14157

remove experimental note in tidb_enable_resource_control

---

releases/release-6.1.6.md
releases/release-6.5.2.md

Fix broken links in release notes from `https://github.com/sojjy` to `https://github.com/sdojjy`.
Fix https://github.com/pingcap/docs/issues/13772
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14159

fix broken links in release notes

---

tidb-cloud/tidb-cloud-faq.md

Removes one cloud FAQ because it's not exactly consistent with the current practical scenario and requires further modification later, as confirmed with @TopScrew
- Other reference link(s): https://github.com/pingcap/docs/pull/13740

tidb-cloud: remove an outdated FAQ

---

tidb-cloud/naming-conventions-for-data-import.md

Deleted the compression format for Parquet because Parquet does not support it.
- Other reference link(s): https://github.com/pingcap/docs/pull/13810

cloud dm: delete compression format for parquet

---

releases/release-6.6.0.md
temp.md

Update release notes for release-6.6.0
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14087

Update release notes for release-6.6.0

---

ticdc/ticdc-changefeed-overview.md

update the description of failed changefeed gc mechanism introduced by [#8646](https://github.com/pingcap/tiflow/pull/8464) 
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14208
- Other reference link(s): none

ticdc: update ticdc failed changefeed gc mechanism description

---

tidb-cloud/size-your-cluster.md

tidbcloud: set max node storage to 6T for 16C TiKV

---

tidb-cloud/configure-maintenance-window.md

Update the doc to reflect that there will be four email notifications for a maintenance window

cloud: update the maintenance window notification

---

tidb-cloud/built-in-monitoring.md

Update the retention time on Serverless 

---

dm/task-configuration-file-full.md

As tittle.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/14213

dm: add some missing translation

---

grafana-tidb-dashboard.md

TiDB v6.5.3 introduces two metrics for Stale Read.
- Other reference link(s): pingcap/docs-cn#14207

add description of stale read metrics

---

grafana-tikv-dashboard.md
pd-control.md
sql-statements/sql-statement-flashback-to-timestamp.md
tikv-control.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14186

tikv-control: support the Flashback command trigger 

---

TOC.md
releases/release-6.5.3.md
releases/release-notes.md
releases/release-timeline.md
temp.md

Add release notes for 6.5.3
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14168

add v6.5.3 release notes 

---

ticdc/deploy-ticdc.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14235

fix deploy-ticdc

---

pd-control.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14243

fix wrong sha256 checksum

---

functions-and-operators/tidb-functions.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12571

tidb functions: remove synopis and copy syntax

---

tidb-lightning/tidb-lightning-configuration.md

Refined description about duplicate-resolution
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/14258

lightning: refined description about duplicate-resolution

---

dm/dm-faq.md
dm/dm-overview.md
dm/handle-failed-ddl-statements.md
error-codes.md
mysql-compatibility.md
overview.md
sql-statements/sql-statement-alter-table.md

This PR enhances the readability and consistency of selected documentation by:
- Writing in a conversational tone
- Organizing content into clear sections with descriptive headlines and subheadings
- Using active voice and avoiding passive verb constructions
- Presenting information in bulleted lists and tables for easier digestion
- Explaining abbreviations and acronyms on their first use
- Using gender-neutral language and being mindful of cultural differences in language usage
For details, see [tips …

*: Improve documentation readability and consistency using GPT-3.5

---

temp.md
tidb-lightning/tidb-lightning-faq.md

The current solution provided in the FAQ is incorrect. The limitation can be bypassed by adjusting two configurations.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14260

lightning: fix a wrong solution in lightning faq

---

best-practices-on-public-cloud.md

Add a blank line to fix the table rendering issue

fix table rendering in best-practices-on-public-cloud.md

---

temp.md
ticdc/ticdc-sink-to-kafka.md

update ticdc acl
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14051

update ticdc acl

---

tidb-lightning/tidb-lightning-configuration.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14172

add "latin1" encoding support for lightning

---

tidb-cloud/serverless-tier-faqs.md

All developer tier clusters were migrated to TiDB serverless since 2022.12. We need to update the related FAQ.

All developer tier clusters were migrated to TiDB serverless since 2022.12.

---

tidb-cloud/delete-tidb-cluster.md

As titles, the info to be typed for confirmation is changed for cluster deletion

cloud: update the step of confirming cluster deletion

---

tidb-cloud/tidb-cloud-release-notes.md

cloud release notes: add 20230620

cloud release notes: add 20230620

---

system-variables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14202

system-variables: add doc for tidb_expensive_txn_time_threshold

---

ticdc/ticdc-changefeed-config.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14182

cdc: add changefeed level config about delete-only-output-handle-key-columns

---

optimizer-hints.md
sql-plan-management.md

It's translated from https://github.com/pingcap/docs-cn/pull/14205
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14205

planner: update the doc of SPM

---

migrate-from-tidb-to-mysql.md

Must use MyLoader v0.10 or earlier versions.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/14309
- Other reference link(s):https://github.com/pingcap/tidb/issues/44922

migration: add MyLoader version requirement

---

dm/feature-shard-merge-optimistic.md
dm/task-configuration-file-full.md
temp.md

https://github.com/pingcap/tiflow/pull/9113
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14232

dm: add description about strict-optimistic-shard-mode

---

constraints.md
sql-statements/sql-statement-create-table.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14227
https://github.com/pingcap/tidb/issues/41711

Add description about check constraint

---

import-example-data.md

import: delete tidb_dml_batch_size

---

statistics.md
system-variables.md

Add system variable `tidb_analyze_skip_column_types`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14221
- Other reference link(s): https://github.com/pingcap/tidb/pull/44653

add system variable tidb_analyze_skip_column_types

---

tidb-lightning/tidb-lightning-configuration.md

As tittle
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/14176

lightning: add doc for send-kv-size

---

system-variables.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14185

add document for system variable "tidb_enable_fast_table_check"

---

tiflash/tiflash-supported-pushdown-calculations.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14042

`FIRST_VALUE()` and `LAST_VALUE()` pushdown

---

read-historical-data.md

As tittle
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/14316
- Other reference link(s):https://github.com/pingcap/docs/pull/5600

sql: correct SELECT statement

---

pd-configuration-file.md
tikv-configuration-file.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/14160

tikv,pd: add config of min-resolved-ts

---

TOC-tidb-cloud.md
develop/dev-guide-insert-data.md
read-historical-data.md
system-variables.md
table-filter.md
tidb-cloud/changefeed-sink-to-mysql.md
tidb-cloud/changefeed-sink-to-tidb-cloud.md
tidb-cloud/export-data-from-tidb-cloud.md
tidb-cloud/migrate-data-into-tidb.md
tidb-cloud/migrate-from-aurora-bulk-import.md
tidb-cloud/migrate-incremental-data-from-mysql.md
tidb-cloud/migrate-sql-shards.md
tidb-cloud/tidb-cloud-poc.md

Delete [Use Dumpling to Export Data](https://docs.pingcap.com/tidb/stable/dumpling-overview) (reused from TiDB) and [Export Data from TiDB](https://docs.pingcap.com/tidbcloud/export-data-from-tidb-cloud) (source maintained in `tidb-cloud`) from TiDB Cloud docs TOC because of inapplicable content
- Other …

cloud: delete Dumpling and Export Data from TiDB links

---

tidb-cloud/data-service-api-key.md
tidb-cloud/data-service-get-started.md
tidb-cloud/data-service-manage-data-app.md
tidb-cloud/data-service-manage-endpoint.md
tidb-cloud/use-chat2query-api.md

- rename API Key section to Authentication
- rename Delete Data App section to Danger Zone

cloud: update Data Service UI element

---

tidb-cloud/tidb-cloud-release-notes.md

cloud: add release notes for 20230627

cloud: add release notes for 20230627

---

sql-statements/sql-statement-alter-user.md
sql-statements/sql-statement-set-resource-group.md

As tittle
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/14315

resource group: change '' to the default resource group

---

TOC-tidb-cloud.md
develop/dev-guide-build-cluster-in-cloud.md
develop/dev-guide-sample-application-python-mysql-connector.md
develop/dev-guide-sample-application-python-mysqlclient.md
develop/dev-guide-sample-application-python-peewee.md
develop/dev-guide-sample-application-python-pymysql.md
develop/dev-guide-sample-application-python-sqlalchemy.md
tidb-cloud/configure-security-settings.md
tidb-cloud/connect-to-tidb-cluster-serverless.md
tidb-cloud/connect-via-standard-connection-serverless.md
tidb-cloud/export-data-from-tidb-cloud.md
tidb-cloud/release-notes-2022.md
tidb-cloud/secure-connections-to-serverless-clusters.md
tidb-cloud/select-cluster-tier.md
tidb-cloud/serverless-faqs.md
tidb-cloud/serverless-limitations.md
tidb-cloud/tidb-cloud-tls-connect-to-dedicated.md

Update two items in TOC and multiple file names to new branding

---

.github/workflows/dispatch.yml
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14342

chore: add v7.2 to dispatch.yml

---

statistics.md
tidb-configuration-file.md

Turn on `lite-init-stats` and `force-init-stats` by default.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14306
- Other reference link(s): https://github.com/pingcap/tidb/pull/44080

turn on lite-init-stats and force-init-stats by default

---

system-variables.md

related to https://github.com/pingcap/docs-cn/pull/14317
TiDB PR: https://github.com/pingcap/tidb/pull/43904
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14317

tidb: update the default value of variable `tidb_enable_non_prepared_plan_cache`

---

temp.md
ticdc/ticdc-bidirectional-replication.md
ticdc/ticdc-filter.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13908

ticdc: add ddl detail to bidirectional replication doc

---

_index.md
temp.md

Update the docs links in v7.2 home page to v7.2 links
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14343

v7.2.0: update v7.2 index page link

---

br/backup-and-restore-use-cases.md
dm/maintain-dm-using-tiup.md
dm/quick-start-create-task.md
information-schema/information-schema-tidb-servers-info.md
pd-control.md
post-installation-check.md
production-deployment-using-tiup.md
quick-start-with-tidb.md
scale-tidb-using-tiup.md
system-variables.md
temp.md
ticdc/deploy-ticdc.md
ticdc/ticdc-changefeed-overview.md
ticdc/ticdc-open-api-v2.md
tidb-binlog/get-started-with-tidb-binlog.md
tidb-monitoring-api.md
tiflash/create-tiflash-replicas.md
tiup/tiup-cluster.md
tiup/tiup-component-cluster-deploy.md
tiup/tiup-component-cluster-patch.md
tiup/tiup-component-cluster-upgrade.md
tiup/tiup-component-dm-upgrade.md
tiup/tiup-component-management.md
tiup/tiup-mirror.md
tiup/tiup-playground.md
upgrade-tidb-using-tiup.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14338

bump tidb and tiup version to 7.2.0

---

ticdc/ticdc-changefeed-config.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14353

fix cdc changefeed config

---

hardware-and-software-requirements.md

Since v6.1.2, only macOS 12+ is supported.

update the supported macos version

---

README.md
temp.md
tidb-roadmap.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14376

add the link of v7.2 release notes to TiDB roadmap

---

temp.md
ticdc/ticdc-open-api.md
ticdc/ticdc-sink-to-kafka.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13424

add encode password description for ticdc doc

---

temp.md
ticdc/ticdc-faq.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14018

ticdc: add a faq for ticdc

---

tidb-resource-control.md

Refine descriptions of RU to make it consistent with TiDB Serverless
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/14033

resource_control: ru consistent with serverless 

---

br/backup-and-restore-storages.md

br: fix the backup code example from `./br restore full -u "${PD_IP}:2379" \` to `./br backup full -u "${PD_IP}:2379" \`

br: fix the backup code example

---

tidb-cloud/backup-and-restore-serverless.md
tidb-cloud/tidb-cloud-faq.md

cloud: TiDB Serverless supports PITR

---

develop/dev-guide-aws-appflow-integration.md
develop/dev-guide-build-cluster-in-cloud.md
information-schema/information-schema-resource-groups.md
information-schema/information-schema-slow-query.md
sql-statements/sql-statement-alter-resource-group.md
sql-statements/sql-statement-create-resource-group.md
sql-statements/sql-statement-drop-resource-group.md
sql-statements/sql-statement-flashback-to-timestamp.md
sql-statements/sql-statement-show-create-resource-group.md
statement-summary-tables.md
system-variables.md
tidb-resource-control.md
time-to-live.md

*: remove serverless beta from urls

---

develop/dev-guide-third-party-support.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14414

feat: change django support level to full cause of we added test cases to pipeline already

---

TOC.md
ticdc/ticdc-avro-checksum-verification.md
ticdc/ticdc-integrity-check.md

ticdc: add Golang examples for checksum verification
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14289 https://github.com/pingcap/docs-cn/pull/14337

ticdc: add Golang examples for checksum verification

---

migrate-large-mysql-to-tidb.md

Add a note for physical import mode of TiDB lightning. The import speed is affected by various factors such as hardware configuration, table schema, and the number of indexes.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14406

lightning: add a note for physical import mode

---

tidb-cloud/tidb-cloud-faq.md

Update lastest default version description on FAQ doc

---

sql-statements/sql-statement-import-into.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14365

import into: add known issue

---

mysql-compatibility.md

Fix the website rendering issue:
preview:

mysql compatibility: fix render issue

---

partitioned-table.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13465, https://github.com/pingcap/docs-cn/pull/13450

fix range columns examples

---

.github/pull_request_template.md

.github: add 7.3 in pr template

---

_docHome.md
quick-start-with-tidb.md
sql-statements/sql-statement-flush-privileges.md
ticdc/ticdc-overview.md

*: optimize 4 docs descriptions

---

.github/workflows/dispatch.yml
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14436

dispatch.yml: remove the achvied release-v6.6 

---

.github/pull_request_template.md
releases/release-6.3.0.md
releases/release-6.4.0.md
releases/release-6.6.0.md
temp.md

1. v6.3/v6.4/v6.6 release notes: add archive info 
2. remove v6.6 from the pull request template
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14437

v6.3/v6.4/v6.6 release notes: add archive info

---

tidb-lightning/data-import-best-practices.md

lightning: refine desciption about analyze

---

releases/release-7.1.0.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14446

add experimental label to smooth upgrade

---

tidb-lightning/tidb-lightning-log-message-explanation.md

lightning: fix all grammar and format issues in log msg explanation

---

tidb-cloud/changefeed-sink-to-apache-kafka.md
tidb-cloud/changefeed-sink-to-mysql.md

Remove "and the TiKV node size is at least 8 vCPU and 16 GiB" from two documents, which is outdated. This change has been confirmed by @grovecai.

tidb-cloud: update a changefeed note to remove outdated info

---

releases/release-7.2.0.md

release-7.2.0: refine the highlight  description of Import Into

---

releases/release-6.5.0.md

Fix the TiCDC throughput description.

release-6.5.0.md: correct TiCDC throughput description

---

temp.md
ticdc/ticdc-alert-rules.md

use the correct metric name for ticdc alert rule, some of them are removed or renamed
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14027

update ticdc alert rule

---

tidb-cloud/backup-and-restore.md
tidb-cloud/configure-maintenance-window.md

Support weekly backup for Dedicated clusters.

cloud: weekly schedule for backup

---

temp.md
tiflash/use-fastscan.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14190

Update Warning Section For FastScan

---

temp.md
tikv-configuration-file.md

Move  `report-region-buckets-tick-interval` to the raftstore directory
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14490

tikv config: correct location of report-region-buckets-tick-interval

---

dashboard/dashboard-overview.md
dashboard/dashboard-slow-query.md
dynamic-config.md
faq/deploy-and-maintain-faq.md
quick-start-with-tidb.md
temp.md
tidb-configuration-file.md

Some configuration items need to be updated
https://asktug.com/t/topic/1009139
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14481

*: modify some deprecated configuration items

---

develop/dev-guide-choose-driver-or-orm.md
develop/dev-guide-third-party-support.md
develop/dev-guide-third-party-tools-compatibility.md

Update the support level of SQLAlchemy and Sequelize to full.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14521

feat: SQLAlchemy and Sequelize were added to test pipeline

---

develop/dev-guide-sample-application-python-mysql-connector.md

Update the code of `mysql_connector_python_example.py` to keep it consistent with https://github.com/pingcap-inc/tidb-example-python/pull/1.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14522

feat: MySQL Connector/Python example add some log to give some instructions

---

tidb-lightning/tidb-lightning-command-line-full.md

Refine description about --check-requirements *bool* 
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/14489

lightning: refine description about --check-requirements *bool* 

---

tidb-lightning/tidb-lightning-configuration.md

Refine dsecription of check-requirements
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/14507

lightning: refine dsecription of check-requirements

---

tidb-lightning/tidb-lightning-configuration.md

Refine description about checksum-via-sql 
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/14518

lightning: refine description about checksum-via-sql 

---

ticdc/ticdc-sink-to-kafka.md

Add the dispatchers configuration example.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14564

cdc matcher rule explaination example

---

tidb-cloud/tidb-cloud-console-auditing.md

Add audit log for branch

---

tidb-cloud/backup-and-restore.md
tidb-cloud/configure-maintenance-window.md
tidb-cloud/monitor-built-in-alerting.md
tidb-cloud/monitor-datadog-integration.md
tidb-cloud/monitor-new-relic-integration.md
tidb-cloud/monitor-prometheus-and-grafana-integration.md
tidb-cloud/set-up-private-endpoint-connections.md
tidb-cloud/set-up-vpc-peering-connections.md
tidb-cloud/third-party-monitoring-integrations.md

Update **Admin** to **Project Settings** for the TiDB Cloud console steps.

cloud: Admin -> Project Settings

---

tidb-cloud/import-csv-files.md

Add a link to a separate section.
- Other reference link(s):https://github.com/pingcap/docs/pull/13860

cloud import: refine description about mapping settings

---

tidb-cloud/tidb-cloud-faq.md

Add an item to TiDB Cloud FAQ about deleting cluster confirmation.

Add FAQ about deleting cluster confirmation

---

hardware-and-software-requirements.md

v7.1.1: support ARM 64 for openEuler
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14511

v7.1.1: support ARM 64 for openEuler

---

optimizer-fix-controls.md
sql-non-prepared-plan-cache.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14581

v7.1.1: introduce two optimizer fix control 44823 and 44855

---

TOC-tidb-cloud.md

cloud: Remove dup spending limit in TOC

---

tidb-cloud/get-started-with-cli.md

Fix the description of connect command

---

releases/release-7.1.1.md

Add some bug fixes in 7.1.1:
- Fix the issue that Avro protocol incorrectly identifies `Enum` type values
- Fix the issue that the behavior of foreign keys in TiDB is inconsistent with MySQL
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14608

cdc update release-note about fix avro handle incorrect enum type value

---

telemetry.md

Update TiSpark close telemetry time

---

releases/release-6.2.0.md

Fix formatting of v620 release notes

---

tidb-cloud/tidb-cloud-release-notes.md

Release notes for July 25 2023

cloud: release notes for July 25 2023

---

check-before-deployment.md
hardware-and-software-requirements.md
system-variables.md
tidb-configuration-file.md
tidb-distributed-execution-framework.md

include privilege check for temp-dir, as incorrect privilege could lead issues like https://asktug.com/t/topic/1008940
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14488

privilege check on temp-dir

---

tidb-cloud/limited-sql-features.md

ADD SELECT ... INTO OUTFILE to limited SQL on TiDB Cloud which is also disabled by SEM. 

Add SELECT ... INTO OUTFILE to limited sql on TiDB Cloud

---

tidb-cloud/limited-sql-features.md

Remove the variables that are already readonly

---

releases/release-7.1.1.md

In TiDB v7.1.1, the default value of compaction-guard-min-output-file-size is 8MB
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14643
- Other reference link(s):  https://github.com/tikv/tikv/pull/15180

revert "change compaction-guard-min-output-file-size to 1MB"

---

partitioned-raft-kv.md
releases/release-7.1.0.md

Partitioned Raft KV: add incompatibility with TiFlash
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14642

Partitioned Raft KV: add incompatibility with TiFlash

---

tidb-cloud/data-service-manage-endpoint.md

cloud: remove hyphen from the automatically generated endpoint name

---

tidb-cloud/branch-github-integration.md

cloud: Alter branch pic size

---

basic-features.md
choose-index.md
releases/release-6.6.0.md
releases/release-7.1.0.md
sql-statements/sql-statement-create-index.md
system-variables.md

When we refer to the feature, use the plural form "multi-valued indexes". @lilin90 has confirmed this update with @songrijie.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14614

update wording in multi-valued indexes

---

grafana-pd-dashboard.md
temp.md

fix the wrong position of `store limit`
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14572

fix pd dashboard

---

character-set-and-collation.md
partitioned-table.md
sql-statements/sql-statement-create-binding.md
sql-statements/sql-statement-create-table.md
sql-statements/sql-statement-drop-binding.md
sql-statements/sql-statement-show-bindings.md
temp.md
tidb-cloud/migrate-sql-shards.md
transaction-overview.md

Command examples should be easily copy-pasteable.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14587

*: remove unnecessary character from sql examples

---

tidb-cloud/connect-to-tidb-cluster.md
tidb-cloud/explore-data-with-chat2query.md

cloud: update "Dedicated Tier" to "TiDB Dedicated" for Chat2Query related content

---

TOC-tidb-cloud.md
tidb-cloud/data-service-app-config-files.md
tidb-cloud/data-service-get-started.md
tidb-cloud/data-service-manage-data-app.md
tidb-cloud/data-service-manage-endpoint.md
tidb-cloud/data-service-manage-github-connection.md
tidb-cloud/data-service-oas-with-nextjs.md

data service: support OpenAPI Specification

data service: support OpenAPI Specification

---

TOC-tidb-cloud.md
tidb-cloud/data-service-manage-data-app.md
tidb-cloud/data-service-manage-endpoint.md
tidb-cloud/data-service-postman-integration.md

Cloud: run Data App in Postman

---

tidb-cloud/monitor-tidb-cluster.md
tidb-cloud/pause-or-resume-tidb-cluster.md

cloud: add the cluster pausing status

---

tidb-cloud/data-service-oas-with-nextjs.md

fix: add missing "step" in data-service-oas-with-nextjs.md

---

develop/dev-guide-sample-application-golang-gorm.md
develop/dev-guide-sample-application-golang-sql-driver.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14650

fix: gorm serverless dsn

---

br/backup-and-restore-storages.md
encryption-at-rest.md

add `encryption-scope` and `encryption-key` for azure blob storage
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14355

br: support to write/ready azure blobs with customer provided key

---

dumpling-overview.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/14639

dumpling: refined description about the -r parameter 

---

ticdc/ticdc-avro-protocol.md
ticdc/ticdc-csv.md
ticdc/ticdc-faq.md
ticdc/ticdc-sink-to-kafka.md

Add FAQ about the old value feature
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13623

ticdc: add docs for old value behavior

---

.github/workflows/cron.yml

Update the version to 7.1 for Japanese website
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13623

Update the version to 7.1

---

tidb-cloud/import-csv-files.md
tidb-cloud/import-parquet-files.md

Create a troubleshooting section

cloud import: create a troubleshooting section

---

explain-walkthrough.md
system-variables.md

optimizer: add docs for shared cte and explain enhancement
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14634

optimizer: add docs for shared cte and explain enhancement

---

system-variables.md
tiflash/create-tiflash-replicas.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14179

add a tidb system variable tiflash_replica_read

---

partitioned-raft-kv.md
tikv-configuration-file.md

- update the compatibility with tikv-ctl
- update the default value of write-buffer-size and format-version
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14598

v7.3: update user doc for multirocksdb

---

temp.md
ticdc/ticdc-changefeed-config.md
ticdc/ticdc-csv.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14692

cdc: add hex encoding to csv

---

mysql-schema.md

- This PR is translated from:  https://github.com/pingcap/docs-cn/pull/14702

add sys table `mysql.tidb_timers`

---

TOC-tidb-cloud.md
TOC.md
explain-joins.md
runtime-filter.md
system-variables.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14517

Add runtime filter docs

---

releases/release-6.5.0.md

release-6.5.0: update the release note introduction 

---

temp.md
ticdc/ticdc-avro-protocol.md
ticdc/ticdc-changefeed-config.md
ticdc/ticdc-manage-changefeed.md
ticdc/ticdc-overview.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14681

cdc update about force-replicate

---

develop/dev-guide-third-party-support.md

full support for prisma 
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14570

feat: full support for prisma

---

tidb-lightning/tidb-lightning-logical-import-mode-usage.md
tidb-lightning/tidb-lightning-physical-import-mode-usage.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/14734
- Other reference link(s):https://github.com/pingcap/docs/pull/14343

lightning: refine description about conflict.strategy

---

tidb-cloud/tidb-cloud-release-notes.md

cloud: add release notes 20230808

---

_index.md

Use v7.3 links in v7.3 learning path.

update learning path for v7.3

---

comment-syntax.md
temp.md

remove a redundant `copyable` label
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14744

trigger 7.3 pdf build

---

tidb-cloud/manage-user-access.md

cloud: update the step to join a project

---

functions-and-operators/information-functions.md
functions-and-operators/tidb-functions.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14467, https://github.com/pingcap/docs-cn/pull/14515

distinct tidb only information function

---

develop/dev-guide-choose-driver-or-orm.md
develop/dev-guide-sample-application-golang-gorm.md
develop/dev-guide-sample-application-golang-sql-driver.md
develop/dev-guide-sample-application-java-hibernate.md
develop/dev-guide-sample-application-java-mybatis.md
develop/dev-guide-sample-application-python-peewee.md
develop/dev-guide-third-party-support.md

Fix the Errors that was founded by dividing CN examples document

---

.github/pull_request_template.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/14762

pr template: add v7.4 

---

temp.md
tidb-configuration-file.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14755

add configs for in memory slow query

---

sql-statements/sql-statement-add-index.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14276

sql-statements: tiny update for smooth upgrade TiDB 

---

temp.md
ticdc/ticdc-faq.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13895

update ticdc faq

---

README.md
br/backup-and-restore-use-cases.md
dm/maintain-dm-using-tiup.md
dm/quick-start-create-task.md
information-schema/information-schema-tidb-servers-info.md
pd-control.md
post-installation-check.md
production-deployment-using-tiup.md
quick-start-with-tidb.md
scale-tidb-using-tiup.md
system-variables.md
temp.md
ticdc/deploy-ticdc.md
ticdc/ticdc-changefeed-overview.md
ticdc/ticdc-open-api-v2.md
tidb-binlog/get-started-with-tidb-binlog.md
tidb-monitoring-api.md
tiflash/create-tiflash-replicas.md
tiup/tiup-cluster.md
tiup/tiup-component-cluster-deploy.md
tiup/tiup-component-cluster-patch.md
tiup/tiup-component-cluster-upgrade.md
tiup/tiup-component-dm-upgrade.md
tiup/tiup-component-management.md
tiup/tiup-mirror.md
tiup/tiup-playground.md
upgrade-tidb-using-tiup.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14730

bump version to 7.3.0

---

clinic/clinic-introduction.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14764

clinic: extend free expiration

---

tidb-cloud/tidb-cloud-release-notes.md

cloud: add release notes 20230815

---

sql-statements/sql-statement-analyze-table.md
temp.md

- Updated the `analyze` statement.
- Explained the `pseudo` stats.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14760

tidb: explain the `pseudo` stats

---

tidb-cloud/serverless-faqs.md

Add more Serverless FAQ items

---

tidb-lightning/tidb-lightning-physical-import-mode-usage.md
tidb-lightning/tidb-lightning-physical-import-mode.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/14798

lightning: delete content about tpcc

---

statement-summary-tables.md

Add more details about the number of SQL statements that will be stored.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14738

sql: update statement summary doc

---

choose-index.md
tidb-configuration-file.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14815

planner: update document about multi-valued indexes

---

develop/dev-guide-choose-driver-or-orm.md

Do not use tidb-loadbalance in your production environment.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/14838

dev-guide: add note about not using tidb-loadbalance in production environments 

---

tidb-cloud/limited-sql-features.md

Disable custom auto_id_cache on tidb-serverless 6.5.
It currently contains some bugs on tidb-serverless and will be disabled temporarily.

Disable custom auto_id_cache on tidb-serverless 6.5

---

develop/dev-guide-choose-driver-or-orm.md

Revert "dev-guide: add note about not using tidb-loadbalance in production environments "

---

develop/dev-guide-choose-driver-or-orm.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14867

TiDB-JDBC SM3 introduce

---

develop/dev-guide-choose-driver-or-orm.md
develop/dev-guide-insert-data.md
develop/dev-guide-sample-application-python-mysqlclient.md

- Other reference link(s):https://github.com/pingcap/docs-cn/pull/14663

develop: refactor Python mysqlclient tutorial

---

auto-increment.md

Does not support using ALTER TABLE to add or modify columns with AUTO_INCREMENT
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/14883

sql: does not support using ALTER TABLE to add or modify columns with AUTO_INCREMENT

---

faq/tidb-faq.md
schedule-replicas-by-topology-labels.md

Added port numbers in the example.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/14888

update an example and tiflash faq

---

sql-plan-management.md

Add SQL examples to make the binding doc clearer.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14879

sql plan management: make binding doc clearer with examples

---

br/backup-and-restore-storages.md
br/backup-and-restore-use-cases.md

Update the permission for TiKV and BR to access the backup directory on S3.

s3: fix s3 put object permission

---

br/backup-and-restore-use-cases.md
dm/maintain-dm-using-tiup.md
dm/quick-start-create-task.md
pd-control.md
production-deployment-using-tiup.md
quick-start-with-tidb.md
scale-tidb-using-tiup.md
ticdc/deploy-ticdc.md
ticdc/ticdc-changefeed-overview.md
tidb-binlog/get-started-with-tidb-binlog.md
tiflash/create-tiflash-replicas.md
tiup/tiup-cluster.md
tiup/tiup-component-cluster-deploy.md
tiup/tiup-component-cluster-patch.md
tiup/tiup-component-cluster-upgrade.md
tiup/tiup-component-dm-upgrade.md
tiup/tiup-component-management.md
tiup/tiup-mirror.md
tiup/tiup-playground.md
upgrade-tidb-using-tiup.md

bump version to v6.5.4
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/14882

bump version to v6.5.4

---

tidb-cloud/tidb-cloud-intro.md

cloud: add TiDB Serverless and TiDB Dedicated to TiDB Cloud Introduction

---

support.md

add discord to support resources

---

tidb-cloud/config-s3-and-gcs-access.md
tidb-cloud/tidb-cloud-import-local-files.md

- Add a note to importing local files
- Change the order of the simpletab as per the new UI

cloud: add a note to importing local files

---

tidb-cloud/data-service-get-started.md
tidb-cloud/data-service-manage-endpoint.md

Move endpoint properties **Timeout(ms)** and **Max rows** from **Basic** to **Advanced**

cloud: update endpoint properties according to UI changes

---

tidb-cloud/data-service-get-started.md
tidb-cloud/data-service-manage-data-app.md
tidb-cloud/data-service-overview.md
tidb-cloud/integrate-tidbcloud-with-vercel.md
tidb-cloud/tidb-cloud-glossary.md

cloud: rephrase a group of endpoints -> a collection of endpoints

---

OWNERS_ALIASES
develop/OWNERS

develop: add develop docs OWNERS

---

tidb-roadmap.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14889

roadmap: add v7.3.0 release notes

---

two-data-centers-in-one-city-deployment.md

The `rule.json` in two-data-centers-in-one-city-deployment.md is invalid.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14810

placement rules: fix duplicate id in rule.json

---

develop/dev-guide-choose-driver-or-orm.md
develop/dev-guide-insert-data.md
develop/dev-guide-sample-application-python-pymysql.md

develop: refactor PyMySQL dev guide

---

develop/dev-guide-choose-driver-or-orm.md
develop/dev-guide-insert-data.md
develop/dev-guide-sample-application-python-mysql-connector.md

develop: refactor MySQL Connector/Python dev guide

---

scripts/filterUpdateFiles.js

ci: filter md

---

scripts/filterUpdateFiles.js

ci: filter md (#14713)

---

tidb-cloud/migrate-from-mysql-using-data-migration.md

As in the title, this change uses https://www.pingcap.com/tidb-cloud-pricing-details/#dm-cost to replace the current list to reduce the maintenance effort. 

cloud: replace the DM supported region list with a link

---

tidb-cloud/changefeed-sink-to-tidb-cloud.md

cloud: add sao paulo as a region

---

tidb-cloud/serverless-limitations.md
tidb-cloud/tidb-cloud-events.md

serverless support cluster events

---

tidb-cloud/configure-ip-access-list.md

cloud: Update ip filter

---

tidb-cloud/tidb-cloud-release-notes.md

cloud: add release notes about the IP access list changes

---

tidb-cloud/serverless-faqs.md

add serverless faq for import data

---

TOC.md

TOC: update the title form Errors Codes to Error Codes

TOC: update the title form Errors Codes to Error Codes

---

TOC-tidb-cloud.md
TOC.md
performance-schema/performance-schema-session-connect-attrs.md
performance-schema/performance-schema.md

- https://github.com/pingcap/tidb/pull/44340

Document performance_schema.session_connect_attrs system table

---

develop/dev-guide-choose-driver-or-orm.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14987

develop: include Django in Python ORM

---

tiflash/tiflash-supported-pushdown-calculations.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14986

Add window function push down restriction

---

statement-summary-tables.md
temp.md

Fix the description error about the proper size of the statement summary table 
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14973

fix the size description of the statement summary table 

---

develop/dev-guide-insert-data.md
develop/dev-guide-playground-gitpod.md
develop/dev-guide-prepared-statement.md
develop/dev-guide-sample-application-java-hibernate.md
develop/dev-guide-sample-application-java-jdbc.md
develop/dev-guide-sample-application-java-mybatis.md
develop/dev-guide-sample-application-java-spring-boot.md

translate: simplify examples for java documents from the docs-cn

---

keywords.md

Update the keyword docs
- https://github.com/pingcap/tidb/pull/46649

Add FLOAT4, FLOAT8 and MIDDLEINT to the docs

---

mysql-compatibility.md

Follow-up for https://github.com/pingcap/docs/pull/14740

mysql-compatibility: Remove FLOAT4/FLOAT8 from the not supported list

---

TOC-tidb-cloud.md
TOC.md
develop/dev-guide-sample-application-nodejs-typeorm.md

develop: add typeorm quickstart

---

keywords.md

Add two non-reserved keywords ROLLUP and HYPO, which have been introduced since v7.2 in https://github.com/pingcap/tidb/pull/43607 and https://github.com/pingcap/tidb/pull/43429

add keywords ROLLUP and HYPO

---

.github/workflows/cron.yml

This PR suspends the JP translation cron action to prevent building failures.

chore(.github): suspend JP translation cronjob

---

temp.md
ticdc/ticdc-changefeed-config.md
ticdc/ticdc-sink-to-cloud-storage.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14272

ticdc: fix date-separator config of storage sink

---

temp.md
ticdc/ticdc-sink-to-cloud-storage.md

update storage sink doc
ref https://github.com/pingcap/tiflow/pull/8954
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13956

ticdc: update storage sink doc

---

_docHome.md

use discord in doc home

---

TOC-tidb-cloud.md
tidb-cloud/notification-2023-09-26-console-maintenance.md

Add 9/26 maintanence notification

---

tidb-cloud/changefeed-overview.md
tidb-cloud/changefeed-sink-to-apache-kafka.md
tidb-cloud/changefeed-sink-to-mysql.md
tidb-cloud/changefeed-sink-to-tidb-cloud.md

fix changefeed to kafka and MySQL version >= v6.1.3

cloud: Cdc/fix changefeed version

---

br/br-snapshot-manual.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14926

snapshot br: restore execution plan bindings

---

develop/dev-guide-sample-application-ruby-mysql2.md

Resolve the https://github.com/pingcap/docs-cn/pull/15025#discussion_r1322628989 comment in https://github.com/pingcap/docs-cn/pull/15025

fix dev guide dialog info

---

explore-htap.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14961

Update explore-htap.md, add tiflash recommendation

---

faq/faq-overview.md
hardware-and-software-requirements.md
migration-tools.md
releases/release-5.4.0.md
releases/release-6.0.0-dmr.md
releases/release-6.1.0.md
releases/versioning.md
tidb-cloud/set-up-private-endpoint-connections-on-google-cloud.md
tidb-lightning/tidb-lightning-overview.md
tidb-lightning/tidb-lightning-physical-import-mode-usage.md
tiup/tiup-component-dm-import.md

Add blank lines to mdx tags

---

br/backup-and-restore-overview.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15012

docs: fix br tools compatibility

---

tidb-cloud/backup-and-restore.md
tidb-cloud/tidb-cloud-glossary.md

cloud: clarify the retention period for automatic backup

---

tiflash-performance-tuning-methods.md

fix tiflash resource usage picture error

---

optimizer-hints.md

As tittle
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/15054
- Other reference link(s):https://github.com/pingcap/tidb/pull/44111

sql planner: add ORDER_INDEX and NO_ORDER_INDEX hints for planner 

---

tidb-cloud/terraform-use-cluster-resource.md

terraform: remove 2C8G in spec datasource

---

hardware-and-software-requirements.md

The current "Instance Number" refers to the specific identification or label given to each instance. "Number of Instances" should refers to the quantity or count of instances, that is needed here.

*: Replace `Instance Number` with `Number of Instances`

---

tidb-cloud/scale-tidb-cluster.md
tidb-cloud/size-your-cluster.md
tidb-cloud/tidb-cloud-performance-reference.md

delete 2 vCPU description.

---

tidb-cloud/tidb-cloud-release-notes.md

add cloud release notes

---

dumpling-overview.md

As tittle
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/15055

dumpling: add PROCESS privilege

---

.github/ISSUE_TEMPLATE/config.yml

Update the TiDB Forum text and link to that of Discord, as requested by the community team
- Other reference link(s): https://github.com/pingcap/docs/pull/14641, #14817

Update forum in the issue template to Discord

---

tidb-cloud/serverless-driver-config.md

Add encode note in serverless driver 

---

config-templates/complex-tiflash.yaml

* Add the missing field "log_dir" in the yaml file tiflash section
* Use `"..."` for the dir path, use the same style as other components
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14748

Add missing field in deploy example yaml file

---

br/backup-and-restore-storages.md
temp.md

Updates the description of `session-token`
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15034

br: update description of session token

---

dm/dm-faq.md
dm/dm-online-ddl-tool-support.md
dm/feature-online-ddl.md

- Cleanup typo in feature-online-ddl 
- Remove obsolete config `online-ddl-scheme` and replace with existing config `online-ddl`
- Other reference link(s): https://docs.pingcap.com/tidb/stable/feature-online-ddl

dm: Cleanup typo in feature-online-ddl and update dm-faq

---

configure-memory-usage.md

sql: delete restriction about some sql statement

---

tidb-cloud/branch-github-integration.md

Opt branching github integration doc

---

tidb-cloud/backup-and-restore.md

br: remove pitr limitation on tikv's resource

---

system-variables.md

In v6.0, Top SQL becomes GA. This PR removes the experimental warning from v6.1 to master.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15091
- Other reference link(s): https://github.com/pingcap/docs/pull/7914

top sql: remove experimental warning

---

sql-statements/sql-statement-alter-resource-group.md
sql-statements/sql-statement-create-resource-group.md
tidb-resource-control.md

TiDB v7.4 supports managing background tasks.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14970

resource_control: add background task resource control

---

.github/pull_request_template.md
CONTRIBUTING.md
resources/doc-templates/template-concept.md
resources/doc-templates/template-new-feature.md
resources/doc-templates/template-reference.md
resources/doc-templates/template-task.md
resources/doc-templates/template-troubleshooting.md

resources: add doc templates

---

exporting-grafana-snapshots.md

metricstool: fix a broken link

---

optimizer-fix-controls.md
sql-non-prepared-plan-cache.md
sql-prepared-plan-cache.md
system-variables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14919

planner: update document about non-prepared plan cache

---

system-variables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14866

system-variables: add docs for new variable `tidb_opt_objective`

---

system-variables.md
temp.md
tidb-configuration-file.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15080

update tidb_stats_cache_mem_quota description

---

hardware-and-software-requirements.md
pd-control.md
pd-recover.md
tidb-control.md

Update go to v1.21
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/15033

*: update go to v1.21

---

system-variables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14972

add doc for sysvar `tidb_session_alias`

---

temp.md
ticdc/ticdc-changefeed-config.md
ticdc/ticdc-overview.md

update ticdc sink configuration, close https://github.com/pingcap/docs-cn/issues/14281
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14347

Update ticdc sink configuration

---

releases/release-6.5.4.md

Add a missing not in release-6.5.4
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15116

release-6.5.4: add missing fix note

---

TOC-tidb-cloud.md
tidb-cloud/api-overview.md
tidb-cloud/tidb-cloud-release-notes.md

cloud: add doc for api v1beta1

---

br/br-snapshot-guide.md
br/br-snapshot-manual.md

Add the --with-sys-table option
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15077

docs: add --with-sys-table detail description

---

tidb-cloud/branch-github-integration.md

add example in branching doc

---

temp.md
ticdc/ticdc-changefeed-config.md
ticdc/ticdc-sink-to-kafka.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15074

cdc: add docs about the claim check.

---

constraints.md

As tittle
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/15132

sql: refine description about compatibility with msql 

---

tiflash/tiflash-configuration.md

- This PR is translated from:  https://github.com/pingcap/docs-cn/pull/15039

tiflash: add descriptions for some conf items under [flash] section

---

tiflash/tiflash-disaggregated-and-s3.md

Remove experimental note of tiflash disaggregated arch
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15052

Remove experimental note of tiflash disaggregated arch

---

tidb-roadmap.md

Add v7.4.0 release notes
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/15136

roadmap: add v7.4.0 release notes

---

tidb-roadmap.md

Revert "roadmap: add v7.4.0 release notes"

---

hardware-and-software-requirements.md

Close https://github.com/pingcap/docs-cn/issues/15138
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15139

hardware-and-software-requirements: clarify UOS name

---

tidb-resource-control.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15121

resource_control: fix resource control limitation

---

ticdc/ticdc-sink-to-kafka.md

As tittle
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/15115

cdc: update topic expression description

---

temp.md
tiflash-upgrade-guide.md
tiflash/tiflash-configuration.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14963; https://github.com/pingcap/docs-cn/pull/14751

DTFile use V3 version as default

---

temp.md
ticdc/ticdc-avro-protocol.md
ticdc/ticdc-changefeed-config.md
ticdc/ticdc-csv.md
ticdc/ticdc-faq.md
ticdc/ticdc-manage-changefeed.md
ticdc/ticdc-open-api-v2.md
ticdc/ticdc-open-api.md
ticdc/ticdc-open-protocol.md
ticdc/ticdc-sink-to-kafka.md
ticdc/troubleshoot-ticdc.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15114

cdc: remove description about the enable-old-value

---

sql-statements/sql-statement-lock-stats.md
sql-statements/sql-statement-show-stats-locked.md
sql-statements/sql-statement-unlock-stats.md
statistics.md
temp.md

The experimental feature warnings were removed in https://github.com/pingcap/docs-cn/pull/15075. This PR reinstates those warnings.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15151

add experimental warning for lock/unlock stats

---

tidb-cloud/changefeed-overview.md

cloud: Update changefeed-overview.md

---

temp.md
tidb-lightning/tidb-lightning-physical-import-mode-usage.md

Fix https://github.com/pingcap/docs-cn/issues/15148
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15156

tidb-lightning: fix strategy number

---

tidb-cloud/backup-and-restore.md
tidb-cloud/pause-or-resume-tidb-cluster.md
tidb-cloud/tidb-cloud-faq.md
tidb-cloud/tidb-cloud-poc.md
tidb-cloud/tidb-cloud-release-notes.md

Revert "docs: add dual region backup"

---

_index.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/15163

learning path: update learning path for v7.4

---

develop/dev-guide-choose-driver-or-orm.md
develop/dev-guide-insert-data.md
develop/dev-guide-sample-application-python-peewee.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15081

develop: update peewee guide

---

tidb-cloud/backup-and-restore.md
tidb-cloud/pause-or-resume-tidb-cluster.md
tidb-cloud/tidb-cloud-faq.md
tidb-cloud/tidb-cloud-poc.md
tidb-cloud/tidb-cloud-release-notes.md

docs: add dual region backup"

---

tidb-cloud/integrate-tidbcloud-with-cloudflare.md

Update Cloudflare workers

---

tidb-cloud/manage-user-access.md
tidb-cloud/tidb-cloud-console-auditing.md

Modify the relevant content of the Organization Console Audit Admin role

Modify the relevant content of the Organization Console Audit Admin role

---

.github/pull_request_template.md

Add v7.5 to the PR template
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15198

add v7.5 to the PR template

---

basic-features.md
temp.md

as title
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14806

update links to clustered index in basic feature

---

releases/release-7.4.0.md

Add deprecation plan to release-7.4.0.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15199

Update 7.4.0 release notes to add deprecation plan

---

releases/release-7.4.0.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15208

v7.4: remove a note

---

keywords.md
scripts/check-keywords.sh

- The TPCH_10 keyword is introduced in https://github.com/pingcap/tidb/pull/47095
- The parser/parser.y is moved to pkg/parser/parser.y in https://github.com/pingcap/tidb/pull/47123
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15213

keywords: add TPCH_10 and update the check-keywords.sh script

---

statistics.md
system-variables.md

cloud: update the default value of tidb_analyze_version

---

temp.md
ticdc/ticdc-canal-json.md
ticdc/ticdc-open-api-v2.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14837

Update ticdc canal json doc

---

sql-plan-management.md

The description was mistakenly deleted in https://github.com/pingcap/docs/pull/12279/files#diff-361475f3328cc7ffc8b281404195f6cefc2a7f86c9ea64542aa269a0ad10d459L181
The original Chinese version: https://github.com/pingcap/docs-cn/commit/8e6c502a941ec79aa333f2b48e6a5009dc3d0432#diff-361475f3328cc7ffc8b281404195f6cefc2a7f86c9ea64542aa269a0ad10d459
For details, see [tips for choosing the affected versions](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md#guideline-for-choosing-the-affected-versi …

fix a description in sql-plan-management.md

---

releases/release-7.4.0.md

As tittle
- https://github.com/pingcap/docs/pull/14780
- https://github.com/pingcap/docs/pull/14719
- https://github.com/pingcap/docs/pulls?q=is%3Apr+label%3Av7.4+author%3Adveeden+is%3Aclosed

release notes: add more items in 7.4

---

temp.md
ticdc/ticdc-server-config.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14992

ticdc: Update cdc server config

---

TOC.md
releases/release-6.3.0.md
sync-diff-inspector/sync-diff-inspector-overview.md
temp.md
ticdc/ticdc-changefeed-config.md
ticdc/ticdc-upstream-downstream-check.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14880

ticdc: refine changefeed scheduler configuration description

---

.lycheeignore
deploy-monitoring-services.md
functions-and-operators/precision-math.md
maintain-tidb-using-tiup.md
performance-tuning-methods.md
production-deployment-using-tiup.md
tidb-binlog/binlog-consumer-client.md
tidb-configuration-file.md
troubleshoot-lock-conflicts.md

- Update some GitHub links for `pingcap/tidb` repo reorganization (move most of the packages to 'pkg')
- `.lycheeignore`: exclude `https://github\.com/\$user/(docs|docs-cn)` when checking links 
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15221
- Other reference link(s): https://github.com/pingcap/tidb/pull/47123

update some GitHub links for tidb repo reorganization

---

statistics.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15189

statistics: add info about tidb_auto_analyze_partition_batch_size

---

statistics.md
tidb-cloud/data-service-get-started.md

cloud data service: support sample Data App

---

tidb-cloud/scale-tidb-cluster.md

you cannot manually scale a serverless cluster.

fix serverless scale description

---

releases/release-6.5.5.md

add an item in v6.5.5 release notes

---

tidb-cloud/changefeed-overview.md
tidb-cloud/changefeed-sink-to-apache-kafka.md

changefeed: remove sink-to-kafka beta status 

---

tidb-cloud/backup-and-restore.md

br: add dual region support for google cloud platform

---

tidb-cloud/tidb-cloud-org-sso-authentication.md

Add the support of the username and password authentication method to the Org SSO doc

cloud: org sso supports the username and password authentication method

---

tidb-cloud/tidb-cloud-release-notes.md

Add TiDB Cloud release notes for 20231025.

cloud: add release notes for 20231025

---

tiup/tiup-documentation-guide.md

Add the GitHub link of TiUP release notes
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15321

tiup: add the GitHub link of release notes

---

releases/release-6.5.3.md
releases/release-6.5.5.md

- https://github.com/tikv/tikv/issues/15279 and https://github.com/tikv/tikv/issues/13638 were fixed in v6.5.4. This PR removes duplicate note in v6.5.5
- https://github.com/tikv/tikv/issues/14547 was fixed in v6.5.3
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15331

release notes: remove duplicate notes

---

tidb-cloud/tidb-cloud-support.md

Support upgrading to Enterprise support plan in the TiDB Cloud console.

cloud: support upgrading to Enterprise Support Plan in console

---

TOC-tidb-cloud.md
tidb-cloud/tidb-cloud-faq.md
tidb-cloud/tidb-cloud-release-notes.md

Add TiDB Cloud release notes for 20231031.

cloud: add release notes for 20231031

---

tidb-resource-control.md

Add info about unbinding resource groups

tidb-resource-control: Add info about unbind

---

mysql-schema.md
sql-statements/sql-statement-admin.md

- Added two system tables related to metadata locks
- Added an output example of `ADMIN SHOW t NEXT_ROW_ID`
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/15303

sql: fix two oncall issues

---

temp.md
ticdc/ticdc-manage-changefeed.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15045

ticdc: delete useless contents 

---

tidb-cloud/backup-and-restore.md

br: add time-zone's description of restoration

---

best-practices/massive-regions-best-practices.md
geo-distributed-deployment-topology.md
hardware-and-software-requirements.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15382, https://github.com/pingcap/docs-cn/pull/15368

update TiKV hardware requirements

---

tidb-cloud/tidb-cloud-release-notes.md

tidb cloud: add release notes for 20231107

---

temp.md
ticdc/ticdc-bidirectional-replication.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15392

ticdc: remove source id desciption

---

tidb-cloud/connect-to-tidb-cluster-serverless.md

add user interface for each connection method

---

hardware-and-software-requirements.md

server recommendations: add a note for production environment
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15390

server recommendations: add a note for production environment

---

grafana-tikv-dashboard.md
troubleshoot-stale-read.md

Add description about slow logs in resolved-ts.
- Other reference link(s): https://github.com/tikv/tikv/pull/15416

add slow logs in troubleshoot-stale-read.md

---

basic-features.md
constraints.md
develop/dev-guide-sample-application-nodejs-prisma.md
develop/dev-guide-sample-application-nodejs-typeorm.md
foreign-key.md
releases/release-6.6.0.md

As in the title, the foreign key feature still has some limitations. It is not recommended to use this feature in production environments.

mark the support of foreign key as experimental

---

dm/dm-continuous-data-validation.md
temp.md

Add documention for feature `Real-time Checkpoint Update upon Completion of Incremental Data Validation`.
v7.5
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15329

dm: add update validation description

---

system-variables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15375
- Other reference link(s): https://github.com/pingcap/tidb/pull/47148

add tidb_gogc_tuner_max_value and tidb_gogc_tuner_min_value

---

hardware-and-software-requirements.md

TiDB v7.5 supports Rocky Linux 9.0
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15348

v7.5 supports Rocky Linux 9.1

---

ddl-introduction.md
sql-statements/sql-statement-admin-pause-ddl.md
sql-statements/sql-statement-admin-resume-ddl.md
temp.md

GA the feature of pause/resume ddl jobs
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15395

sql: pause and resume ddl jobs GA

---

system-variables.md
tidb-distributed-execution-framework.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/15336

tidb: `tidb_service_scope` GA 

---

system-variables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15335

system-variable: add tidb_enable_async_merge_global_stats

---

br/br-snapshot-guide.md
br/br-snapshot-manual.md
faq/backup-and-restore-faq.md

Add description about `--ignore-stats`
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/15305

br: public parameter --ignore-stats to backup statistic data

---

system-variables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15333

system-variable: update variable for analyze

---

tidb-cloud/connect-to-tidb-cluster-serverless.md
tidb-cloud/serverless-driver.md

make it more clear about serverless driver & Data Service

---

binary-package.md
download-ecosystem-tools.md

remove TiSpark from offline package

---

tidb-cloud/backup-and-restore.md

br: support restore account by default

---

tidb-cloud/tidb-cloud-release-notes.md

cloud: release notes for November 14, 2023

---

tidb-cloud/config-s3-and-gcs-access.md

cloud: fix tag issues

---

tidb-cloud/changefeed-sink-to-cloud-storage.md
tidb-cloud/import-sample-data.md

cloud: add a slash gsutil uri

---

TOC-tidb-cloud.md

fix: add maintenance notification to toc

---

develop/dev-guide-overview.md

Updated the Read more section in the https://docs.pingcap.com/tidbcloud/dev-guide-overview#read-more. This is a intermediate update to align with our email campaign which will be launched soon. Eventually a new redesigned developer overview page will replace this one https://github.com/pingcap/docs/issues/15219 …

Update TiDB Cloud overview page read more section

---

TOC-tidb-cloud.md
tidb-cloud/_index.md
tidb-cloud/import-with-mysql-cli.md

Import with MySQL CLI

---

system-variables.md
temp.md
tidb-distributed-execution-framework.md

tidb-distributed-execution-framework (GA) in V7.5.0
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15448

GA- tidb-distributed-execution-framework 

---

.github/workflows/dispatch.yml

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15453

update dispatch for release-7.5

---

develop/dev-guide-third-party-support.md

develop: update the third party support table

---

upgrade-tidb-using-tiup.md

Add a new FAQ to describe how to resolve upgrade issues in TiDB v6.2.0 and later versions.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15434

upgrade using tiup: add FAQ for concurrent DDL

---

tidb-cloud/backup-and-restore.md

tidb-cloud: add incompatiblities between br and lightning

---

tidb-cloud/migrate-from-mysql-using-data-migration.md
tidb-cloud/tidb-cloud-dm-precheck-and-troubleshooting.md

cloud: added an error, and removed some links

---

releases/release-7.1.0.md

The link of user guide is included in release note.  The readers can quickly get what are improved and how to use it. 

include the link of user guide for database audit

---

functions-and-operators/string-functions.md
temp.md

This PR converts the table of supported string functions to a list of sections so we can add instructions for each function in different PRs.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15473

string-functions: convert the table of supported functions to a list

---

tidb-cloud/migrate-from-mysql-using-data-migration.md
tidb-cloud/tidb-cloud-release-notes.md

Dm supports google cloud

---

sql-statements/sql-statement-import-into.md

Add a limitation for "Import Into" SQL statement

---

backup-and-restore-using-dumpling-lightning.md
dm/dm-hardware-and-software-requirements.md
migrate-large-mysql-to-tidb.md
tidb-lightning/tidb-lightning-requirements.md

1. The statement to install lightning wasn't correct
2. There is no need to "start" dumpling or lightning
3. Make it clear that the "50 MB" is just a recommendation about when to use Dumpling/Lightning and when to use BR.
4. Format SQL statements so no horizontal scrolling is needed. Also use `FORMAT_BYTES()` instead of manual conversion to MiB. And remove the `WHERE TABLE_SCHEMA=...` to make the statements copy-pasteable.    …

Clarify statement on backup-and-restore-using-dumpling page

---

tidb-cloud/data-service-manage-data-app.md

cloud: add integration with GPT

---

dm/dm-hardware-and-software-requirements.md
migrate-large-mysql-to-tidb.md
tidb-lightning/tidb-lightning-requirements.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/15488
- Other reference link(s):https://github.com/pingcap/docs/pull/15423

updated SQL for `DATA_LENGTH`

---

dashboard/continuous-profiling.md
dashboard/dashboard-profiling.md

Add the support of TiKV for heap profiling
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15495

dashboard: Add the support of TiKV for heap profiling

---

develop/dev-guide-gui-datagrip.md
develop/dev-guide-gui-dbeaver.md
develop/dev-guide-gui-vscode-sqltools.md
develop/dev-guide-sample-application-aws-lambda.md
develop/dev-guide-sample-application-golang-gorm.md
develop/dev-guide-sample-application-golang-sql-driver.md
develop/dev-guide-sample-application-java-hibernate.md
develop/dev-guide-sample-application-java-jdbc.md
develop/dev-guide-sample-application-java-mybatis.md
develop/dev-guide-sample-application-java-spring-boot.md
develop/dev-guide-sample-application-nextjs.md
develop/dev-guide-sample-application-nodejs-mysql2.md
develop/dev-guide-sample-application-nodejs-mysqljs.md
develop/dev-guide-sample-application-nodejs-prisma.md
develop/dev-guide-sample-application-nodejs-sequelize.md
develop/dev-guide-sample-application-nodejs-typeorm.md
develop/dev-guide-sample-application-python-django.md
develop/dev-guide-sample-application-python-mysql-connector.md
develop/dev-guide-sample-application-python-mysqlclient.md
develop/dev-guide-sample-application-python-peewee.md
develop/dev-guide-sample-application-python-pymysql.md
develop/dev-guide-sample-application-python-sqlalchemy.md
sql-statements/sql-statement-admin-cleanup.md
sql-statements/sql-statement-admin-recover.md
tidb-cloud/tidb-cloud-support.md

The right support channel might depend on:
- Region (US, EMEA, China, ASIA)
- Service (TiDB Cloud, On prem)
- Support contract (Enterprise or Community)
- Type of request (Question on Slack, bugreport on GitHub, support on zendesk/jirasd)
So best to link to https://docs.pingcap.com/tidb/stable/support instead.
I have left:
- Links directly to a specific form ( https://support.pingcap.com/hc/en-us/requests/new?ticket_form_id=7800003722519 )
- Links to email ( `mailto:tidbcloud-support@pingcap.com`)
- `tidb-cloud/*`
Maybe we should add a link to email or otherwise reach sales to `support.md`.
Previous PR: https://github.com/pingcap/docs/pull/14648
By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor …

Use the support page instead of direct links

---

.github/workflows/cron.yml

ci: cron for jp translation

---

tidb-cloud/tidb-cloud-release-notes.md

cloud: delete description about upgrading to v7.1.2

---

.github/workflows/cron.yml

workflow: fix yaml syntax error

---

tidb-cloud/data-service-manage-endpoint.md

cloud: update Data Service endpoint instructions per UI changes

---

ticdc/ticdc-overview.md

Update the best practices for TiCDC
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15516

ticdc: update best practices

---

TOC.md
filter-binlog-event.md
filter-dml-event.md
migrate-large-mysql-to-tidb.md
migrate-small-mysql-to-tidb.md
migrate-with-more-columns-downstream.md
migrate-with-pt-ghost.md
migration-overview.md
two-data-centers-in-one-city-deployment.md

migration: refine titles about migrating small datasets and large datasets from MySQL to TiDB

---

.github/pull_request_template.md

pr template: add the option for v7.6 

---

download-ecosystem-tools.md
temp.md

As in title
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10570

v5.4: update downloading links of sync_diff_inspector

---

download-ecosystem-tools.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10579

v5.3: update downloading links of sync_diff_inspector

---

migrate-small-mysql-to-tidb.md

Fix build error in https://github.com/pingcap/website-docs/actions/runs/7018193736/job/19093050214

resolve conflicts in migrate-small-mysql-to-tidb

---

tidb-cloud/backup-and-restore.md

Br cloud restore sql bindings

---

tidb-cloud/serverless-faqs.md

Update serverless faqs with RU cost

---

migrate-from-tidb-to-tidb.md
replicate-between-primary-and-secondary-clusters.md
sql-statements/sql-statement-backup.md
sql-statements/sql-statement-restore.md

Add experimental note for BACKUP and RESTORE statements
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15528

add experimental note for BACKUP and RESTORE statements

---

functions-and-operators/expressions-pushed-down.md

functions-and-operators/expressions-pushed-down.md: Fix typo

---

tidb-cloud/migrate-from-mysql-using-data-migration.md
tidb-cloud/tidb-cloud-release-notes.md

cloud dm: add a note about using physical mode and enabling PITR and changefeed

---

hardware-and-software-requirements.md

Update hardware-and-software-requirements for v7.5:
- Divide the original table into two tables: **provides enterprise-level production quality** and **does not guarantee enterprise-level production quality**
- Starting from v7.5.0, TiDB support **Rocky Linux 9.1 or later** as enterprise-level production quality …

update hardware-and-software-requirements for v7.5

---

.github/workflows/ja-full-translation-google.yaml

Add full translation workflow of Japanese for TiDB LTS version.

chore(.github): add workflow for JA full translation by gcp

---

.github/workflows/ja-full-translation-google.yaml

Fix `git push` problems in `ja-full-translation-google` workflow.

chore(.github): fix `ja-full-translation-google` workflow

---

tidb-cloud/tidb-cloud-release-notes.md

cloud: add release notes for 20231205

---

ticdc/ticdc-canal-json.md

TiCDC introduces content-compatible for Canal-JSON. 
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15579
https://github.com/pingcap/tiflow/pull/10014

cdc: add description about canal-json content-compatible

---

temp.md
ticdc/ticdc-changefeed-config.md
ticdc/ticdc-open-api-v2.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15614

Add cdc redo configuration

---

br/br-pitr-guide.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15640

fix redundant quotation marks

---

system-variables.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15654

fix version comment

---

information-schema/information-schema-variables-info.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15655

update the variable scope 

---

sql-non-prepared-plan-cache.md

Fix https://github.com/pingcap/docs/issues/15599
Fixed a typo, using `t` as table name instead of `t1`, since the previous examples using `t`.
Close: https://github.com/pingcap/docs/issues/15599

Table name typo fixed

---

tidb-cloud/dev-guide-wordpress.md

Update the connection panel of TiDB Serverless clusters

update: with wordpress connection panel

---

releases/release-7.5.0.md
tidb-configuration-file.md

Starting from v7.5.0, TiDB configuration item copr-req-timeout is introduced.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15669

 tidb config doc: coprocessor request timeout

---

tidb-cloud/tidb-cloud-org-sso-authentication.md

org sso: add a note about email configuration for IdP

---

releases/release-7.3.0.md
system-variables.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/15671

add doc for tidb_allow_tiflash_cop

---

develop/dev-guide-build-cluster-in-cloud.md
develop/dev-guide-gui-datagrip.md
develop/dev-guide-gui-dbeaver.md
develop/dev-guide-gui-mysql-workbench.md
develop/dev-guide-gui-navicat.md
develop/dev-guide-gui-vscode-sqltools.md
develop/dev-guide-sample-application-aws-lambda.md
develop/dev-guide-sample-application-golang-gorm.md
develop/dev-guide-sample-application-golang-sql-driver.md
develop/dev-guide-sample-application-java-hibernate.md
develop/dev-guide-sample-application-java-jdbc.md
develop/dev-guide-sample-application-java-mybatis.md
develop/dev-guide-sample-application-java-spring-boot.md
develop/dev-guide-sample-application-nextjs.md
develop/dev-guide-sample-application-nodejs-mysql2.md
develop/dev-guide-sample-application-nodejs-mysqljs.md
develop/dev-guide-sample-application-nodejs-prisma.md
develop/dev-guide-sample-application-nodejs-sequelize.md
develop/dev-guide-sample-application-nodejs-typeorm.md
develop/dev-guide-sample-application-python-django.md
develop/dev-guide-sample-application-python-mysql-connector.md
develop/dev-guide-sample-application-python-mysqlclient.md
develop/dev-guide-sample-application-python-peewee.md
develop/dev-guide-sample-application-python-pymysql.md
develop/dev-guide-sample-application-python-sqlalchemy.md
develop/dev-guide-sample-application-ruby-mysql2.md
develop/dev-guide-sample-application-ruby-rails.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/15596

update serverless connect steps

---

tidb-cloud/migrate-from-mysql-using-aws-dms.md

cloud migration: add a limitation to migrating data using AWS DMS

---

temp.md
ticdc/ticdc-changefeed-config.md

Remove a miss added config item.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14283

ticdc: fix changefeed config doc

---

data-type-json.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12777

br: restore json type

---

resources/doc-templates/template-new-feature.md
temp.md

For details, see [tips for choosing the affected versions](https://github.com/pingcap/docs-cn/blob/master/CONTRIBUTING.md#版本选择指南).
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12177

feature doc template: update experimental feature description 

---

dm/dm-query-status.md

dm: optimize query status doc

---

dm/dm-open-api.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/15750

dm: add new openapi config about import_mode

---

basic-features.md
temp.md

closes https://github.com/pingcap/docs-cn/issues/15719
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15757

use code format in basic features

---

sql-statements/sql-statement-load-data.md
temp.md

Add the behavior description about committing rows for v7.0.0 and later versions.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15663

load data: update the notes about committing rows

---

system-variables.md
temp.md

require_secure_transport is forbidden to be set to on when SEM is enabled.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15583

v7.1.2: update doc of `require_secure_transport`

---

migrate-from-tidb-to-mysql.md
replicate-data-to-kafka.md
ticdc/deploy-ticdc.md
ticdc/integrate-confluent-using-ticdc.md
ticdc/ticdc-changefeed-overview.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/15842

ticdc: fix tiup cmd, change `tiup ctl:v<CLUSTER_VERSION> cdc` to `tiup cdc:v<CLUSTER_VERSION> cli`

---

br/backup-and-restore-use-cases.md
develop/dev-guide-sample-application-nodejs-mysql2.md
develop/dev-guide-sample-application-nodejs-mysqljs.md
develop/dev-guide-sample-application-nodejs-typeorm.md
develop/dev-guide-sample-application-ruby-mysql2.md
develop/dev-guide-sample-application-ruby-rails.md
dm/maintain-dm-using-tiup.md
dm/quick-start-create-task.md
information-schema/information-schema-tidb-servers-info.md
pd-control.md
post-installation-check.md
production-deployment-using-tiup.md
quick-start-with-tidb.md
scale-tidb-using-tiup.md
ticdc/deploy-ticdc.md
ticdc/ticdc-changefeed-overview.md
ticdc/ticdc-open-api-v2.md
tidb-binlog/get-started-with-tidb-binlog.md
tidb-monitoring-api.md
tiflash/create-tiflash-replicas.md
tiup/tiup-cluster.md
tiup/tiup-component-cluster-deploy.md
tiup/tiup-component-cluster-patch.md
tiup/tiup-component-cluster-upgrade.md
tiup/tiup-component-dm-upgrade.md
tiup/tiup-component-management.md
tiup/tiup-mirror.md
tiup/tiup-playground.md
upgrade-tidb-using-tiup.md

bump version for 7.1.3

---

releases/release-6.1.0.md
temp.md
tune-region-performance.md

Recorrect the previous release notes on the configuration `region-split-size` in tikv.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15600

tikv: recorrect the descriptions on the feature `region-split-size` part.

---

tidb-resource-control.md

Include warnings to recommend eligible deployments for resource control test
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15903

recommend eligible deployments for resource control test

---

sql-statements/sql-statement-flashback-cluster.md
tidb-cloud/limited-sql-features.md

cloud: add an alias for flashback cluster

---

hardware-and-software-requirements.md

- https://docs.fedoraproject.org/en-US/releases/eol/
- https://en.opensuse.org/Lifetime
- https://wiki.debian.org/LTS
- https://www.debian.org/releases/stretch/
- https://ubuntu.com/about/release-cycle
- https://www.oracle.com/a/ocom/docs/elsp-lifetime-069338.pdf

Update OS support page

---

tikv-control.md

The output of bad-ssts command is not up-to-date
- Other reference link(s): https://github.com/tikv/tikv/pull/12049

Update tikv-ctl bad-ssts output

---

CONTRIBUTING.md

1. Add info about TiDB Docs Dash 2024 to the contribution guide. 
2. Simplify the instructions about doc-versions and cherry-pick labels.
3. Update the contact info.
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/15911

contribution guide: add info about TiDB Docs Dash 2024

---

upgrade-tidb-using-tiup.md

When upgrading TiDB, check the DDL and backup status before checking cluster health.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15936

upgrade tidb: check DDL and backup status before checking cluster health status

---

temp.md
upgrade-monitoring-services.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15955

upgrade-monitoring-services: fix path errors

---

ticdc/ticdc-alert-rules.md

ticdc-alert-rules: change the heading level from H2 to H3

---

tidb-lightning/tidb-lightning-configuration.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/15961

tidb-lightning: replace `NO_ENGINE_SUBSTITUTION` with `NO_AUTO_CREATE_USER`

---

system-variables.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15976

system-variable: indicate that max_allowed_packet is ready only in the session scope

---

tidb-cloud/backup-and-restore.md
tidb-cloud/tidb-cloud-release-notes.md

br: GA dual region backup

---

releases/release-6.5.6.md
releases/release-7.1.3.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15990

move `FLASHBACK CLUSTER TO TSO` to TiDB improvements

---

.github/workflows/cron.yml

- update base branch of jp translation

ci: update base branch of jp translation

---

tiflash/tiflash-configuration.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15991

Change the default log level of tiflash

---

TOC.md
releases/release-6.5.7.md
releases/release-notes.md
releases/release-timeline.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15934

releases: add 6.5.7 release notes

---

templates/copyright.tex

Update year to 2024 in copyright.tex

---

releases/release-6.5.7.md

remove tidb_opt_fix_control from 6.5.7 release notes

---

releases/release-6.5.4.md
releases/release-6.5.5.md
releases/release-6.5.6.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16051

fix a release note for v6.5.4

---

dm/task-configuration-file-full.md
system-variables.md

dm: add a note about DM to `sql_require_primary_key`

---

TOC-tidb-cloud.md
tidb-cloud/release-notes-2022.md
tidb-cloud/tidb-cloud-billing.md

cloud: add doc for billing profile

---

system-variables.md
tidb-configuration-file.md

TiDB v7.6.0 supports tidb_txn_entry_size_limit
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15695

add doc for tidb_txn_entry_size_limit

---

tidb-cloud/serverless-driver.md

Add documents and example for Serverless driver decoders config.
- Other reference link(s): https://github.com/tidbcloud/serverless-js/pull/38

Add decoders config and example

---

TOC.md
control-execution-plan.md
optimizer-fix-controls.md
system-variables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16017

update tidb_opt_fix_control for v6.5

---

tidb-cloud/connect-via-standard-connection-serverless.md

Combined first two sentences to remove redundancy and change 'laptop' to 'computer'.
The Docs Dash instructions say to use release-7.5. 
#15741

Update first two lines of connect-via-standard-connection-serverless.md

---

choose-index.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15943

add multi value index case from cnf and dnf combination

---

sql-statements/sql-statement-create-index.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15945

create-index: remove the description that no stats are collected for mv index

---

auto-random.md
system-variables.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/15960

Add explanation for auto_random ID allocation

---

dynamic-config.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15571

tikv: add dynamic config item 'readpool.unified.max-tasks-per-worker'

---

temp.md
ticdc/ticdc-open-api-v2.md

https://github.com/pingcap/tiflow/pull/10133
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15766

Add docs for `TiCDC support checking if data is entirely replicated to Downstream`

---

tidb-cloud/tidb-cloud-import-local-files.md

change shell script in docs to split the local file for importing to tidb cloud
Original shell script didn't consider the division issue. 
Before
```bash
lines_per_file=$(( $(wc -l < $file_path) / $n ))
split -d -a 1 -l $lines_per_file $file_path $file_name.
```
After
```bash
total_lines=$(wc -l < $file_path)
lines_per_file=$(( (total_lines + n - 1) / n ))
split -d -a 1 -l $lines_per_file $file_path $file_name.
```
See #15739 for more details. …

Fix: split local files for importing to tidb cloud

---

develop/dev-guide-choose-driver-or-orm.md

Update format and wording to make them consistent within one file
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16125

develop: make format and wording consistent

---

br/backup-and-restore-tool.md

translate doc/cn to en #15708
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15708

backup: add experimental description for sql br

---

ticdc/ticdc-changefeed-config.md
ticdc/ticdc-sink-to-kafka.md

translate 2 docs in doc-cn to en #15356
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/15356

add ticdc aws glue schema registry config docs

---

faq/backup-and-restore-faq.md

Translate docs cn pr#14383
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14383

restore: add faq for rule not found

---

tiup/tiup-component-cluster-template.md

fix PR16009 https://github.com/pingcap/docs-cn/pull/16009
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16009

tiup: add instructions for the --local option

---

TOC-tidb-cloud.md
tidb-cloud/data-service-custom-domain.md
tidb-cloud/data-service-manage-data-app.md
tidb-cloud/serverless-driver.md

TiDB Cloud: data service custom domain feature

---

TOC-tidb-cloud.md
tidb-cloud/api-overview.md

cloud: add apikey references

---

tidb-configuration-file.md

TiProxy is going to be released. This option is no more a pure warning.

tidb: fix config value for tiproxy

---

tidb-cloud/tidb-cloud-release-notes.md

cloud: add release notes for 0116

---

.vaunt/config.yaml

Correct dates for PR merged date plus PR bonus point condition.

Update config.yaml for Docs Dash

---

system-variables.md

system-variable: add `tidb_analyze_distsql_scan_concurrency`

---

ticdc/ticdc-csv.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15905

ticdc: add explanation for csv delimiter config

---

identify-slow-queries.md
information-schema/information-schema-slow-query.md
mysql-schema.md
statement-summary-tables.md
system-variables.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/15935

resource_control: enhance observability

---

dm/dm-compatibility-catalog.md
dm/dm-overview.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/15985

DM: support for MySQL 8.0 GA

---

system-variables.md

…as 128
- Other reference link(s): https://github.com/pingcap/tidb/issues/48674

system-variables: set default tidb_auto_analyze_partition_batch_size as 128

---

ddl-v2.md
migrate-from-parquet-files-to-tidb.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/16181

data migration: add an example Parquet file name

---

sql-statements/sql-statement-truncate.md

Use ebnf diagram for `TRUNCATE`
https://github.com/pingcap/docs/issues/4389

truncate statement ebnf

---

ticdc/ticdc-canal-json.md

TiDB v7.6.0 supports compatibility with the data format of the official Canal
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16179

ticdc: v7.6.0 supports compatibility with the data format of the official Canal

---

enable-tls-between-clients-and-servers.md
tidb-configuration-file.md

The default minimum TLS version has changed from TLS v1.1 to TLS v1.2
https://github.com/pingcap/tidb/pull/36037

upgrade default minimum TLS version

---

tidb-troubleshooting-map.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/16232

Add MDL for DDL troubleshooting

---

README.md

- Add German and Spanish
- Translate the website instead of the docs markdown

Change Google Translate info

---

tidb-lightning/tidb-lightning-configuration.md

Add configuration parameter `TikvImporter.BlockSize`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16231
- Other reference link(s): https://github.com/pingcap/tidb/pull/49514

tidb-lightning: add `block-size`

---

tidb-lightning/tidb-lightning-configuration.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/16242
- Other reference link(s):https://github.com/pingcap/docs/pull/16205

lightning: refine description for `block-size`

---

tidb-cloud/tidb-cloud-release-notes.md

cloud: add release notes for 20240123 release

---

faq/backup-and-restore-faq.md
system-variables.md

https://github.com/pingcap/tidb/issues/38045 was fixed in v7.0.0 and https://github.com/pingcap/tidb/issues/37207 was fixed in v6.6.0. This PR updates the description of these two issues in FAQ document. https://github.com/pingcap/docs-cn/pull/15366 will remove these issues from v7.3, v7.4, v7.5, and master branch. …

br: update PITR FAQ for v7.1 branch

---

releases/release-7.1.1.md

translate docs cn to en pr#15287
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15287

br: add one missing pitr bugfix

---

cached-tables.md

Use clearer words in usage scenarios section.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15926

cached table: clarify usage scenarios

---

faq/backup-and-restore-faq.md
system-variables.md

fix PR 15366 https://github.com/pingcap/docs-cn/pull/15366
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15366

br: modify the faqs of pitr

---

br/br-snapshot-guide.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16297

Br add experimental description for acceleration restore speed

---

develop/dev-guide-sample-application-java-spring-boot.md

Remove Hibernate doc link (unnecessary) from spring boot part.
https://docs.pingcap.com/tidb/stable/dev-guide-sample-application-java-spring-boot#next-steps

dev-guide-sample-application-java-spring-boot: remove an unnecessary link to Hibernate docs

---

develop/dev-guide-gui-mysql-workbench.md

…tup New Connection dialogue box
I use MySQL Workbench version 8.034 on Windows. Instead of the "Store in Keychain" placeholder contained in the documentation, I had "Store in Vault" on the Setup New Connection dialogue box. This pull request is to prevent confusion for users who may not see "Store in Keychain" when trying to connect to TiDB through MySQL Workbench.
For details, see [tips for choosing the affected versions](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md#guideline-for-choosi …

MySQL Workbench: Added the alternative password placeholder on the Setup New Connection dialogue box

---

develop/dev-guide-gui-mysql-workbench.md

from the TiDB Cloud connection dialog, `host` should be `HOST`

develop: update dev-guide-gui-mysql-workbench.md

---

dm/dm-overview.md
error-codes.md
faq/tidb-faq.md
generated-columns.md
overview.md
tidb-architecture.md
tidb-cloud/tidb-cloud-faq.md
tidb-cloud/tidb-cloud-poc.md

- Update for MySQL 8.0 compatibility
- Update for Foreign Key support

More MySQL 8.x compatibility updates

---

tidb-global-sort.md

global sort: fix rendering issue in code block

---

sql-statements/sql-statement-rename-user.md

Fix typo in `RENAME USER`

---

temp.md
tidb-roadmap.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16377

tidb-roadmap.md: add a link to the v7.6 release notes

---

storage-engine/titan-configuration.md
storage-engine/titan-overview.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/16344
- Other reference link(s):https://github.com/pingcap/docs/pull/15986

update titan doc to provide guidline on min-blob-size

---

tikv-configuration-file.md

Update the description of `initial-scan-rate-limit` to make it more accurate.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16298

log_backup: fix initial scan rate limit description

---

sql-statements/sql-statement-create-index.md

update description of multi-valued index

---

optimizer-hints.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15068 https://github.com/pingcap/docs-cn/pull/15890

add a reasonable example for INL_JOIN

---

sql-statements/sql-statement-admin-cancel-ddl.md
sql-statements/sql-statement-kill.md

add KILL statement can kill DDL jobs describe

---

storage-engine/titan-configuration.md

titan: fix a typo, convertion > conversion

---

tiflash/tiflash-configuration.md

* The config item in `flash.flash_cluster` are deprecated since v6.0 https://github.com/pingcap/tidb/issues/29924
* Align the style of `flash.proxy` with other config items
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16111
- Other reference link(s): https://github.com/pingcap/tidb/issues/29924

tiflash: Clean deprecated configs; align style of flash.proxy

---

tiup/tiup-overview.md

update according the latest TiUP
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16166

tiup: update tiup-overview.md

---

tidb-cloud/_index.md
tidb-cloud/changefeed-sink-to-apache-kafka.md
tidb-cloud/changefeed-sink-to-cloud-storage.md
tidb-cloud/changefeed-sink-to-mysql.md
tidb-cloud/changefeed-sink-to-tidb-cloud.md

add summary to tidbcloud docs

---

_docHome.md
_index.md
control-execution-plan.md
identify-expensive-queries.md
sql-logical-optimization.md
sql-physical-optimization.md
sql-tuning-overview.md

add summary to other docs

---

releases/release-2.1.17.md
releases/release-3.0.1.md
releases/release-4.0.15.md
releases/release-5.1.4.md
releases/release-5.4.1.md

fix build failure

---

.vaunt/config.yaml

Update config.yaml to update PR bonus points

---

tidb-cloud/data-service-api-key.md
tidb-cloud/use-chat2query-api.md

cloud data service: add API expiration instructions

---

functions-and-operators/string-functions.md

Fix https://github.com/pingcap/docs/issues/15490
This PR adds instructions `LIKE` and `LOCATE()`

Enrich instructions for string functions LIKE and LOCATE()

---

tidb-cloud/create-tidb-cluster.md
tidb-cloud/manage-user-access.md
tidb-cloud/tidb-cloud-billing.md
tidb-cloud/tidb-cloud-encrypt-cmek.md
tidb-cloud/tidb-cloud-org-sso-authentication.md

Dev environment: https://deploy-preview-2868--dbaas-dev.netlify.app/

cloud: update ui description for org settings

---

functions-and-operators/string-functions.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16119
- Other reference link(s): #15487

Fix: Enrich instructions for string functions FORMAT() and FROM_BASE64() (#15487)

---

develop/dev-guide-sample-application-java-jdbc.md

add MySQL Connector/J version requirement note

---

tikv-configuration-file.md

v6.5.8: add TiKV configuration item num-threads
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16379

v6.5.8: add TiKV configuration item num-threads

---

.github/pull_request_template.md
README.md
temp.md

1. Add the info about v7.6.
2. Add the info about archived docs.
3. PR template: remove v7.3 and add v8.0
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16371, https://github.com/pingcap/docs-cn/pull/16477

README.md: add info about v7.6

---

TOC.md
releases/release-6.5.8.md
releases/release-notes.md
releases/release-timeline.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16373

add release note for v6.5.8

---

non-transactional-dml.md

fix wrong link anchors

---

tidb-cloud/_index.md

fix(tidb-cloud): glossary missing

---

quick-start-with-htap.md
temp.md

Add `USE test` command before running the SQL to avoid error like "ERROR 1046 (3D000): No database selected".
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16178
- Other reference link(s):https://github.com/pingcap/docs-cn/issues/15774

Update quick-start-with-htap.md to add `USE test` command  

---

sql-statements/sql-statement-show-profiles.md

Add a link to statement summary tables to help users looking for how to get profiling information in TiDB.

Update sql-statement-show-profiles.md to reference statement summary tables

---

tikv-configuration-file.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16522

fix the description of wal_dir

---

information-schema/information-schema-ddl-jobs.md
temp.md
tiup/tiup-component-cluster-template.md

fix #14180 
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16117, https://github.com/pingcap/docs-cn/pull/16127

translate two PRs for DDL jobs intro and TiUP component description

---

develop/dev-guide-sample-application-ruby-mysql2.md
develop/dev-guide-sample-application-ruby-rails.md

develop: replace angle brackets with curly brackets

---

releases/release-6.5.7.md

- This PR is translated from:  https://github.com/pingcap/docs-cn/pull/16545

add missing release note in 6.5.7

---

tidb-cloud/set-up-vpc-peering-connections.md

Update cidr doc on 20240207

---

faq/migration-tidb-faq.md

It seems the docs has been a bit stale since we released the region merge feature.
Thus, update on it and present an appropriate link for more details

To handle issue after big delete, since region merge feature is already released, update on it

---

encryption-at-rest.md

Fix a file size issue introduced in https://github.com/pingcap/docs/pull/2410. The unit in the Chinese doc is correct (https://github.com/pingcap/docs-cn/pull/3928/files).

encryption-at-rest: fix the file size

---

tidb-cloud/migrate-from-mysql-using-data-migration.md

Remove `TRUNCATE` from the "[Grant required privileges to the downstream TiDB Cloud cluster](https://docs.pingcap.com/tidbcloud/migrate-from-mysql-using-data-migration#grant-required-privileges-to-the-downstream-tidb-cloud-cluster)" section in [Migrate MySQL-Compatible Databases to TiDB Cloud Using Data Migration](https://docs.pingcap.com/tidbcloud/migrate-from-mysql-using-data-migration).
For details, see [tips for choosing the affected versions](https://github.com/pingcap/docs/blob/master/CONTRIBUTING …

tidb-cloud: remove TRUNCATE privilege in migration

---

tidb-cloud/limitations-and-quotas.md

The "Number of data replicas" could be understood as having a limit of 3 TiKV nodes. This isn't the case it is 3 replicas for every data region. 
And the Cluster Quotas are quite low. This should get a note that customers can raise a support ticket to increase these. (just like the note for Cluster Limits)
- …

tidbcloud: Update limits

---

external-storage-uri.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/16579

reference: add an example for S3 URI in sink-uri

---

pd-control.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/16375

pd-ctl: add resource-manager command

---

tiflash/tiflash-disaggregated-and-s3.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/16583

tiflash: fix scale-in command argument -R

---

faq/migration-tidb-faq.md

In the migration FAQ, dumpling was not listed as a way to export data from TiDB. 
I belive this is the recommended method than mysqldump. So I added it.

Add method to use Dumpling if you want to export data from TiDB

---

temp.md
ticdc/ticdc-upstream-downstream-check.md

add some notes when using async point feature 
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16184

Update syncpoint doc

---

tidb-storage.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/16590

tikv: refine description of MVCC

---

configure-placement-rules.md
temp.md
tiflash/troubleshoot-tiflash.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16410

update placement-rules doc about max-replica

---

tidb-cloud/tidb-cloud-release-notes.md

cloud: add 20240220 release notes

---

dumpling-overview.md

I was reading the section regarding Dumpling's GC auto extension feature.
I understood that if data is less than 1 TB this feature works, but if larger it does not.
Given this, I thought the part that I changed could be a typo. Thus raised this fix.
Changed "more" to "less"
https://docs.pingcap.com/tidb/stable/dumpling-overview

Correct typo in Dumpling's GC auto extend feature spec

---

best-practices/java-app-best-practices.md
develop/dev-guide-connection-parameters.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16521

fix: wait_timeout update for the best practices

---

quick-start-with-tidb.md
tiup/tiup-faq.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/15977

update playground doc

---

identify-slow-queries.md

fix: transactin_ts in slow query is start_ts, not commit_ts
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16578

fix: transactin_ts in slow query is start_ts, not commit_ts

---

system-variables.md
tidb-distributed-execution-framework.md

Add a warning about variable `tidb_enable_dist_task` in v7.1.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16601

system-variables: add a warning about tidb_enable_dist_task in v7.1

---

temp.md
ticdc/ticdc-sink-to-pulsar.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16587

ticdc: fix pulsar sink documentation error

---

scripts/get-en-duplicated-notes.py

Add a script to replace Chinese duplicated release notes with the corresponding English translation according to the release and issue number information of the duplicated release notes.

chore: get English duplicated release notes

---

temp.md
upgrade-tidb-using-tiup.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16640

v7.6: update upgrade-tidb-using-tiup.md

---

faq/sql-faq.md
foreign-key.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/16642

*: fix two oncall issues

---

tidb-cloud/set-up-vpc-peering-connections.md
tidb-cloud/tidb-cloud-release-notes.md

Update cidr and release note on 20240223

---

tidb-configuration-file.md

tidb: add status.record-db-label docs

---

tidb-cloud/serverless-driver.md

improve serverless-driver

---

releases/release-7.5.0.md
releases/release-7.6.0.md
temp.md

As in title
- [x ] v7.5 (TiDB 7.5 versions)
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16648

release-7.5.0 release notes: add two TiCDC parameter changes 

---

ticdc/ticdc-changefeed-overview.md
ticdc/ticdc-faq.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/16388

ticdc: update cdc gc service doc and failed changefeed faq

---

basic-features.md
releases/release-7.4.0.md
sql-statements/sql-statement-lock-stats.md
sql-statements/sql-statement-show-stats-locked.md
sql-statements/sql-statement-unlock-stats.md
statistics.md

Lock statistics becomes GA in v7.4.0.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16351

tidb: remove experimental warnings for stats lock

---

tiflash/tiflash-disaggregated-and-s3.md

`mycuster` should be `mycluster`

fix: `mycuster` should be `mycluster`

---

certificate-authentication.md
enable-tls-between-clients-and-servers.md
sql-statements/sql-statement-alter-user.md
sql-statements/sql-statement-create-user.md
sql-statements/sql-statement-grant-privileges.md
sql-statements/sql-statement-revoke-privileges.md
tidb-configuration-file.md

1. The documentation of statements that have syntax like `REQUIRE X509` didn't seem to be complete.
2. TLS is not only encrypting the connection, but is also providing other security properties like authentication. I've replaced some mentions of "encryption" with either "secure" or "TLS".
3. The startup messages no longer match the documentation. (related to https://github.com/pingcap/tidb/pull/15287 and  https://github.com/pingcap/tidb/pull/34261)
4. The `GRANT` statement should not be used to create users and/or to modify users.
5. Some places weren't consistently putting things like `REQUIRE` in uppercase.
6. Add a note to `tls-version` about TLSv1.0 and TLSv1.1 deprecation.
By default, **CHOOSE MASTER ONLY** so your changes will be …

Various TLS related updates

---

tiproxy/tiproxy-overview.md

Add experimental warning for TiProxy
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16687

tiproxy: add experimental warning

---

expression-syntax.md

Update the link of parser.y from [parser.y](https://github.com/pingcap/parser/blob/master/parser.y) to [`parser.y`](https://github.com/pingcap/tidb/blob/master/pkg/parser/parser.y)
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16175

fix link, parser.y

---

tidb-cloud/changefeed-sink-to-cloud-storage.md

changefeed: fix wrong description

---

tikv-configuration-file.md

v7.5.1 adds `num-threads`
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16628

v7.5.1: tikv configuration doc: add gc thread number

---

develop/dev-guide-third-party-support.md

Use absolute URLs in `<a href="">`
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16490

develop: use absolute URLs in href

---

basic-features.md
security-compatibility-with-mysql.md
sql-statements/sql-statement-alter-user.md
sql-statements/sql-statement-create-user.md
system-variables.md
tidb-configuration-file.md

Add description for tidb_auth_token, which can be used not only inside TiDB Cloud, but also by normal tidb users.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15818

Add description for `tidb_auth_token` authentication

---

sql-statements/sql-statement-create-table.md
tidb-cloud/limited-sql-features.md

Update limited-sql-features about serverless

---

best-practices/haproxy-best-practices.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/16463

HAProxy: update the recommended hardware configuration for HAProxy

---

troubleshoot-lock-conflicts.md

If using `tidb_trx` for troubleshooting, it will get wrong results, e.g.
use `cluster_tidb_trx` to fix it.

use cluster_tidb_trx for lock troubleshooting

---

tidb-cloud/tidb-cloud-faq.md

cloud: upgrade the default TiDB Dedicated cluster version from v7.5.0 to v7.5.1

cloud: upgrade the default TiDB Dedicated cluster version from v7.5.0 to v7.5.1

---

TOC-tidb-cloud.md
tidb-cloud/manage-user-access.md
tidb-cloud/tidb-cloud-billing.md

TiDB Cloud supports Billing > Cost Explorer.

cloud: billing cost explorer

---

tidb-cloud/built-in-monitoring.md

cloud: add limit label for metrics

---

tidb-cloud/tidb-cloud-release-notes.md

cloud: add 20240305 release notes

cloud: add 20240305 release notes

---

ticdc/ticdc-changefeed-config.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/16759

ticdc: add example of how to show bdr role

---

ticdc/ticdc-open-api-v2.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16204

cdc: Remove useless code in filter

---

tikv-configuration-file.md

v7.1.4 introduces num-threads
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16738

v7.1.4: tikv configuration doc: add gc thread number

---

sql-statements/sql-statement-flashback-cluster.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16741

*: add notice on flashback cluster usage

---

tidb-resource-control.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/16838

resource-control: reduce misunderstandings

---

faq/backup-and-restore-faq.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16847

br: add faq - why oom when restore stats

---

system-variables.md
temp.md
tikv-configuration-file.md

Modify the storage units in [System Variables](https://docs.pingcap.com/tidb/stable/system-variables) & [TiKV Configuration File](https://docs.pingcap.com/tidb/stable/tikv-configuration-file) from KB/MB/GB/TB to KiB/MiB/GiB/TiB
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16844

*: update storage unit in system variables and config file

---

sql-statements/sql-statement-alter-index.md
sql-statements/sql-statement-create-index.md
system-variables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16835
https://github.com/pingcap/tidb/pull/50654

*: add tidb_opt_use_invisible_indexes

---

data-type-default-values.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/16751

*: add data type default values 

---

tiproxy/tiproxy-grafana.md
tiproxy/tiproxy-overview.md
tiproxy/tiproxy-performance-test.md

Update performance test of TiProxy
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16685

tiproxy: update performance test and metrics

---

optimistic-transaction.md
temp.md

Add description about deprecating the `tidb_disable_txn_auto_retry` system variable
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16602
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/16592, https://github.com/pingcap/docs/pull/16530

txn: add description about deprecating the tidb_disable_txn_auto_retry system variable 

---

system-variables.md

Update the description for deprecating the `tidb_disable_txn_auto_retry` system variable in v8.0.0
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16592
- Other reference link(s): v7.6 PR https://github.com/pingcap/docs-cn/pull/16010

txn: deprecate the tidb_disable_txn_auto_retry system variable

---

ticdc/ticdc-filter.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16689
- Other reference link(s): https://github.com/pingcap/tiflow/pull/10644

Add sql mode format restrictions to expr in ticdc filter

---

br/backup-and-restore-storages.md
temp.md

Add description about PITR supporting S3 Object Lock
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16739

pitr: support s3 object lock

---

choose-index.md
sql-prepared-plan-cache.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16776

planner: update Plan Cache doc

---

system-variables.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/16769

add explaination for log densitive feat

---

TOC.md
dm/dm-command-line-flags.md
dm/dm-customized-secret-key.md
dm/dm-export-import-config.md
dm/dm-manage-source.md
dm/dm-master-configuration-file.md
dm/dmctl-introduction.md
dm/maintain-dm-using-tiup.md
dm/quick-start-create-source.md
dm/quick-start-create-task.md
dm/quick-start-with-dm.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16683

dm: support customized secret key

---

tikv-configuration-file.md
tune-tikv-thread-performance.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16767
- Other reference link(s): issue: https://github.com/tikv/tikv/issues/16614, tikv-pr: https://github.com/tikv/tikv/pull/16615

tikv: enable async-io by setting raftstore.store-io-pool-size == 1 as default. 

---

ticdc/troubleshoot-ticdc.md

Remove inappropriate descriptions about the canal protocol
- Other reference link(s): https://github.com/pingcap/docs/pull/16797, https://github.com/pingcap/docs/pull/16792

ticdc: remove canal protocol descriptions

---

dm/deploy-a-dm-cluster-using-tiup-offline.md
dm/deploy-a-dm-cluster-using-tiup.md
dm/dm-error-handling.md
dm/dm-faq.md
dm/quick-start-with-dm.md
dm/shard-merge-best-practices.md
tidb-troubleshooting-map.md

https://github.com/pingcap/dm has been archived. DM has moved to https://github.com/pingcap/tiflow/tree/master/dm

DM: Update GitHub URLs for DM

---

encryption-at-rest.md
sql-statements/sql-statement-import-into.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16869

add warnings for two experimental features:  Google Cloud KMS and IMPORT INTO SELECT

---

_index.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/16893

V8.0.0: update learning path

---

br/br-snapshot-manual.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16871

restore: add load stats description

---

ticdc/ticdc-changefeed-config.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16874

Add config output-handle-key/output-old-value doc for ticdc

---

temp.md
tiup/tiup-playground.md

修改语句保持与上文习惯一致。
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16916

tiup: Update tiup-playground.md

---

system-variables.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16910

fix descriptions for tidb_stmt_summary_max_sql_length

---

hardware-and-software-requirements.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16924

hardware-and-software-requirements: fix the name of the instruction set

---

TOC.md
releases/release-8.0.0.md
releases/release-notes.md
releases/release-timeline.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/16935

delete release notes 8.0

---

functions-and-operators/string-functions.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16864

Add the introduction of capture group for regexp function

---

TOC.md
releases/release-8.0.0.md
releases/release-notes.md
releases/release-timeline.md

Revert "delete release notes 8.0"

---

tidb-cloud/notification-2024-04-18-dm-feature-maintenance.md

cloud: Update the DM maintenance

---

ticdc/ticdc-open-api-v2.md
ticdc/ticdc-open-api.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/16768

ticdc: fix incompatiable config description

---

develop/dev-guide-build-cluster-in-cloud.md
tidb-cloud/create-tidb-cluster-serverless.md
tidb-cloud/manage-serverless-spend-limit.md
tidb-cloud/release-notes-2023.md
tidb-cloud/select-cluster-tier.md
tidb-cloud/serverless-faqs.md
tidb-cloud/serverless-limitations.md
tidb-cloud/tidb-cloud-quickstart.md
tidb-cloud/tidb-cloud-release-notes.md

Adding Free and Scalable Cluster Plans in Serverless

Free and Scalable Cluster Plans in Serverless

---

basic-features.md

Update the link for invisible indexes to point correctly from `/sql-statements/sql-statement-add-index.md` to `/sql-statements/sql-statement-create-index.md#invisible-index`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16973

basic features: fix anchor link

---

functions-and-operators/string-functions.md

Add examples for FIELD() and FIND_IN_SET()

---

TOC.md
releases/release-6.5.3.md
releases/release-6.5.4.md
releases/release-7.1.1.md
releases/release-7.1.2.md
releases/release-7.2.0.md
releases/release-7.4.0.md
ticdc/ticdc-behavior-change.md

Add description about protocol behavior change
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16621

cdc: Add description about protocol behavior change

---

sql-statements/sql-statement-kill.md

This PR explains how users can find information about the session that has been killed.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11669

Update KILL TIDB descriptions for v5.3

---

clinic/quick-start-with-clinic.md

update UI elements on the Clinic Server login page
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16991

clinic: update UI elements on the login page

---

tiup/tiup-cluster-topology-reference.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16114

tiup: add additional_args

---

sql-statements/sql-statement-show-warnings.md

enbf show warnings

---

.github/pull_request_template.md

Remove TiDB 5.0 from the PR template as it is EOL

Remove TiDB 5.0 from PR template

---

sql-statements/sql-statement-show-errors.md

ebnf show errors

---

dashboard/dashboard-profiling.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/16221

Add perl dependency requirement for tikv heap profiling

---

br/br-snapshot-manual.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/17037

br: add memory for restoration of table statistics

---

br/backup-and-restore-overview.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/16223

br: not support executing backup task and restore task at the same time

---

TOC-tidb-cloud.md
tidb-cloud/notification-2024-04-09-monitoring-features-maintenance.md
tidb-cloud/notification-2024-04-16-monitoring-features-maintenance.md

cloud: add maintenance notification for monitoring features

---

tidb-cloud/size-your-cluster.md

cloud: Update size-your-cluster.md

---

tidb-cloud/tidb-cloud-release-notes.md

cloud: add release note 20240409 

---

functions-and-operators/string-functions.md

Add REPEAT() example

---

sql-statements/sql-statement-set-password.md

ebnf set password

---

sql-statements/sql-statement-show-variables.md

ebnf show variables

---

two-data-centers-in-one-city-deployment.md

add dr-auto-sync configuration description
Note: release-7.x should be merged after cherry-pick pd code.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17051

dr-autosync: add configuration description

---

sql-statements/sql-statement-show-builtins.md

ebnf show builtins

---

sql-statements/sql-statement-shutdown.md

ebnf shutdown

---

releases/release-timeline.md

Tag 8.0.0 as DMR.
docs-cn https://github.com/pingcap/docs-cn/pull/17074

fix release-timeline

---

sql-statements/sql-statement-show-stats-meta.md

ebnf show stats_meta

---

sql-statements/sql-statement-show-processlist.md

ebnf show processlist

---

sql-statements/sql-statement-show-databases.md

ebnf show databases

---

sql-statements/sql-statement-show-bindings.md

ebnf show bindings

---

sql-statements/sql-statement-set-default-role.md

ebnf set default role

---

br/backup-and-restore-storages.md
br/backup-and-restore-use-cases.md

This pull request adds  `s3:DeleteObject` permission because TiDB 7.1+ checkpoint restore requires it.
- Other reference link(s): Refer to https://github.com/pingcap/docs/issues/16961#issuecomment-2046728026
Fix #16961

TiDB 7.1+ checkpoint restore requires `s3:DeleteObject` permission

---

sql-statements/sql-statement-show-warnings.md

The EBNF for `SHOW WARNINGS` isn't formatted correctly
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/17090#discussion_r1561221776

Fix EBNF for SHOW WARNINGS

---

releases/release-6.5.9.md
releases/release-7.1.4.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17107

release-6.5.9: update the issue description for #8803

---

sql-statements/sql-statement-show-create-database.md

Correct the EBNF for `SHOW CREATE DATABASE`

Fix EBNF for SHOW CREATE DATABASE

---

sql-statements/sql-statement-with.md

Fix WITH ebnf

---

sql-statements/sql-statement-show-create-sequence.md

ebnf show create sequence

---

TOC-tidb-cloud.md
TOC.md
sql-statements/sql-statement-show-stats-histograms.md

ebnf show stats_histograms

---

dynamic-config.md
system-variables.md
temp.md
user-account-management.md

Address a few minor changes in user docs, which can be merged into v7.1.0 or later version.
* [include the unit of variable "tidb_stats_cache_mem_quota"](https://github.com/pingcap/docs-cn/commit/bf73e81ecf2606a4ff4b44bb0e056f35eefae783)
* [Mention resource control in user management](https://github.com/pingcap/docs-cn/commit/befd1cc3ed2de64de0df6e4002a659ab1b1090eb)
* [append the missing dynamic config in TiDB](https://github.com/pingcap/docs-cn/commit/0224e2e782ae8bef6d5b679eb59c2730f0fb066b)
For …

Address a few minor changes in user docs as of 7.1

---

.github/pull_request_template.md
README.md
temp.md

1. Mark v4.0/v5.0/v7.4 docs as archived
2. Remove v7.4 from PR tempalte
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17121

Mark v4.0/v5.0/v7.4 docs as archived

---

dm/deploy-a-dm-cluster-using-tiup-offline.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17015

deploy-a-dm-cluster-using-tiup-offline: fix a command

---

tidb-lightning/tidb-lightning-physical-import-mode-usage.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/17127
- Other reference link(s):https://github.com/pingcap/docs/pull/14531

lightning: add back content about tpcc

---

functions-and-operators/locking-functions.md

locking-functions: Update reference manual

---

tidb-cloud/cli-reference.md

Add note for cli profile

---

sql-statements/sql-statement-set-names.md

ebnf set names

---

sql-statements/sql-statement-savepoint.md

Add EBNF for SAVEPOINT related statements

ebnf savepoint

---

sql-statements/sql-statement-show-grants.md

ebnf show grants

---

sql-statements/sql-statement-unlock-stats.md

The UnlockStatsStmt indicated it doesn't have to start with "UNLOCK STATS", which is wrong.

Fix EBNF for UNLOCK STATS and partitions

---

sql-statements/sql-statement-show-stats-healthy.md

ebnf show stats healthy

---

sql-statements/sql-statement-show-create-user.md

ebnf show create user

---

functions-and-operators/date-and-time-functions.md

date-and-time-functions: Update reference manual

---

tiflash-upgrade-guide.md
upgrade-tidb-using-tiup.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/17138

upgrade: refine upgrade steps 

---

data-type-default-values.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16909

modify descriptions of column default value 

---

sql-statements/sql-statement-show-columns-from.md

ebnf show columns from

---

dm/manually-handling-sharding-ddl-locks.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/17162

dm: refine details format

---

develop/dev-guide-timeouts-in-tidb.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17097

GC Timeout is Out of Date

---

tidb-cloud/tidb-cloud-dm-precheck-and-troubleshooting.md

Update TiDB Cloud docs with MySQL 8.0 Reference Manual links

---

develop/dev-guide-sample-application-python-sqlalchemy.md

add disconnect handling note when using sqlalchemy against TiDB Serverless

---

hardware-and-software-requirements.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/17179

*: add openEuler 22.03 LTS SP3

---

functions-and-operators/json-functions.md

json-functions: Update for MySQL 8.0 compat

---

sql-statements/sql-statement-show-create-table.md

ebnf show create table

---

TOC-tidb-cloud.md
tidb-cloud/api-overview.md
tidb-cloud/managed-service-provider.md

- Update the URL for TiDB Cloud IAM API from https://docs.pingcap.com/tidbcloud/api/v1beta1/apikey to https://docs.pingcap.com/tidbcloud/api/v1beta1/iam
- Update the URL for TiDB Cloud MSP API from https://docs.pingcap.com/tidbcloud/api/msp/v1beta1 to https://docs.pingcap.com/tidbcloud/api/v1beta1/msp
- Other …

cloud: update URLs for API docs
