pingcap/docs

tidb-cloud/migrate-from-mysql-using-data-migration.md

cloud dm: only support logical mode to migrate existing data

---

functions-and-operators/string-functions.md

Add MAKE_SET() and LTRIM() examples

---

functions-and-operators/miscellaneous-functions.md

miscellaneous-functions: Update reference manual

---

error-codes.md

Fix 8216 error code explanation

---

system-variables.md

Add incompatibility between Pipelined-DML and BR
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17187

Pipelined-DML: document incompatibility with BR

---

binary-package.md
upgrade-monitoring-services.md

Update the TiDB server package download link in [Upgrade Cluster Monitoring Services](https://docs.pingcap.com/tidb/dev/upgrade-monitoring-services) from https://www.pingcap.com/download/ to `https://download.pingcap.org/tidb-community-server-{version}-linux-{arch}.tar.gz`.

Update TiDB server package download links in monitoring upgrade

---

_docHome.md

For the background, see https://github.com/pingcap/docs/pull/17318
Request from and confirmed with @jiwei2021
- https://github.com/pingcap/docs/pull/17318
- https://github.com/pingcap/docs/pull/17319
- https://github.com/pingcap/docs/pull/17328

Update TiDB download link to View on GitHub

---

functions-and-operators/information-functions.md
tidb-configuration-file.md

information-functions: Update reference manual and more

---

releases/release-8.0.0.md

Add an enhancement:
Optimized the query performance of the four system tables INFORMATION_SCHEMA.TABLES, INFORMATION_SCHEMA.STATISTICS, INFORMATION_SCHEMA.KEY_COLUMN_USAGE, and INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS. Compared to previous versions, the performance has been improved by up to 100 times. …

*: add performance improvement of system tables in release notes v8.0

---

troubleshoot-high-disk-io.md

Fix incorrect panel name (https://github.com/pingcap/docs/pull/3046) from `append log` to `apply log` in `troubleshoot-high-disk-io.md`
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3237

fix incorrect panel name in troubleshoot-high-disk-io

---

character-set-and-collation.md
character-set-gbk.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17171

character-set-and-collation: support use `LIKE` to build range for new collation columns

---

sql-statements/sql-statement-show-indexes.md

Update `SHOW INDEXES` ebnf diagram according to comments https://github.com/pingcap/docs-cn/pull/17211#discussion_r1580558878 & https://github.com/pingcap/docs/pull/17085#discussion_r1558192119

Update ebnf show indexes

---

TOC.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/17246

lightning: updated toc sections 

---

develop/dev-guide-use-common-table-expression.md
sql-statements/sql-statement-with.md

Link CTE docs

---

tidb-cloud/monitor-prometheus-and-grafana-integration.md
tidb-cloud/third-party-monitoring-integrations.md

Fix formatting on third party monitoring integrations page

---

basic-features.md
temp.md

Change the support info for PD microservices from `Y` to `E`
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17269

basic-features: fix the support info for PD microservices

---

system-variables.md

Updated the range of `tidb_auto_analyze_ratio`.
We don't allow users to set it to 0 anymore.
See https://github.com/pingcap/tidb/pull/52190
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17108

tidb: update tidb_auto_analyze_ratio range

---

mysql-schema.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/17275

mysql schema: delete `request_unit_by_group` in v7.5.0

---

.github/workflows/ci.yaml
.github/workflows/cron.yml
.github/workflows/ja-full-translation-google.yaml
.github/workflows/link-fail-fast.yaml
.github/workflows/link.yaml
.github/workflows/media.yml
.github/workflows/prevent-deletion.yaml
.github/workflows/rebase.yml
.github/workflows/translation.yaml

CI: Update actions

---

external-storage-uri.md
releases/release-7.6.0.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16349

br: support session-token and assume-role for backup & restore

---

tidb-roadmap.md

Update the TiDB roadmap for the upcoming year.  
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17225

update TiDB roadmap for CY24-CY25

---

sql-prepared-plan-cache.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/17232

sql: remove warning for issue 51407 in plan cache

---

data-type-default-values.md

https://github.com/pingcap/docs-cn/pull/17184

*: update defalut value for expression

---

command-line-flags-for-tidb-configuration.md
system-variables.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/17156

tidb: add a new command line flag for redact

---

information-schema/information-schema-runaway-watches.md
sql-statements/sql-statement-query-watch.md
tidb-resource-control.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17209

resource-control: remove warning about runaway

---

functions-and-operators/string-functions.md
mysql-compatibility.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/17320

sql: add a link about regular expression compatibilit with MySQL 

---

sql-statements/sql-statement-backup.md
sql-statements/sql-statement-restore.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17273

sql: update br docs about some sql options

---

sql-statements/sql-statement-import-into.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17178

GA import into from select

---

sql-statements/sql-statement-create-index.md

- Uppercase SQL keywords
- Remove copyable hints
- Add more links

Update CREATE INDEX statement docs

---

tidb-cloud/manage-serverless-spend-limit.md
tidb-cloud/select-cluster-tier.md
tidb-cloud/serverless-faqs.md
tidb-cloud/serverless-limitations.md

update to the throttled serverless limitations

---

information-schema/information-schema-analyze-status.md
information-schema/information-schema-character-sets.md
information-schema/information-schema-collation-character-set-applicability.md
information-schema/information-schema-collations.md
information-schema/information-schema-columns.md
information-schema/information-schema-engines.md
information-schema/information-schema-memory-usage.md
information-schema/information-schema-partitions.md
information-schema/information-schema-processlist.md
information-schema/information-schema-referential-constraints.md
information-schema/information-schema-schemata.md
information-schema/information-schema-sequences.md
information-schema/information-schema-session-variables.md
information-schema/information-schema-slow-query.md
information-schema/information-schema-table-constraints.md
information-schema/information-schema-user-privileges.md
information-schema/information-schema-variables-info.md
information-schema/information-schema-views.md
information-schema/information-schema.md

Add links to I_S pages where applicable

information_schema: Add links

---

mysql-compatibility.md

We now have this: https://docs.pingcap.com/tidb/dev/sys-schema
I think it is best to remove this from the list and later on add specific sys schemas if required.

mysql-compatibility: Remove sys schema

---

tidb-cloud/set-up-vpc-peering-connections.md

tidb-cloud: support creating a VPC peering across different VPCs

---

tidb-cloud/tidb-cloud-release-notes.md

tidb-cloud: add release notes for 20240514

---

sql-statements/sql-statement-admin-show-ddl.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/17349

sql: add more states for ADMIN SHOW DDL

---

sql-statements/sql-statement-prepare.md

Add information about some limits
See also: https://github.com/pingcap/tidb/blob/cfbabfa705dbbc97c8e1e00af7f2d2620406304c/pkg/planner/core/plan_cache_utils.go#L101-L105

Add info to PREPARE statement docs

---

tidb-cloud/serverless-faqs.md

cloud: update free cluster limitations

---

tidb-lightning/tidb-lightning-requirements.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/17357

tidb-lightning: add contents about `REFERENCES`

---

tidb-lightning/troubleshoot-tidb-lightning.md

Fix the link of start `tidb-lightning`
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17376

lightning: fix the link of start `tidb-lightning`

---

tidb-lightning/tidb-lightning-configuration.md

Fix the behavior of the TiDB Lightning configuration item "tidb.tls"
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17356

lightning: fix the behavior of "tidb.tls"

---

functions-and-operators/set-operators.md

remove ebnf images in set operator

---

develop/dev-guide-gui-datagrip.md
develop/dev-guide-gui-dbeaver.md
develop/dev-guide-sample-application-golang-gorm.md
develop/dev-guide-sample-application-golang-sql-driver.md
develop/dev-guide-sample-application-java-hibernate.md
develop/dev-guide-sample-application-java-jdbc.md
develop/dev-guide-sample-application-java-mybatis.md
develop/dev-guide-sample-application-java-spring-boot.md
develop/dev-guide-sample-application-nodejs-mysql2.md
develop/dev-guide-sample-application-nodejs-mysqljs.md
develop/dev-guide-sample-application-nodejs-prisma.md
develop/dev-guide-sample-application-nodejs-sequelize.md
develop/dev-guide-sample-application-nodejs-typeorm.md
develop/dev-guide-sample-application-python-django.md
develop/dev-guide-sample-application-python-mysql-connector.md
develop/dev-guide-sample-application-python-mysqlclient.md
develop/dev-guide-sample-application-python-peewee.md
develop/dev-guide-sample-application-python-pymysql.md
develop/dev-guide-sample-application-python-sqlalchemy.md
develop/dev-guide-sample-application-ruby-mysql2.md
develop/dev-guide-sample-application-ruby-rails.md
temp.md
tidb-cloud/tidb-cloud-console-auditing.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15437

update the UI string for downloading CA

---

system-variables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17342

remove warning for tidb_analyze_partition_concurrency

---

sql-plan-replayer.md

Add description for how to **remove** `PLAN REPLAYER CAPTURE` to make docs complete
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17417

sql-plan-replayer: add description for `PLAN REPLAYER CAPTURE REMOVE`

---

ticdc/ticdc-behavior-change.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17053

cdc: fix the description about the behavior change 

---

tidb-cloud/tidb-cloud-release-notes.md

tidb cloud: release notes for 20240521

---

tidb-cloud/branch-overview.md

update branch size limitation

---

auto-increment.md

https://github.com/pingcap/docs-cn/pull/17396
https://github.com/pingcap/tidb/pull/53315

auto-increment: modify the description about the case of non-continuous auto increment id

---

br/br-snapshot-guide.md
faq/backup-and-restore-faq.md

`https://github.com/pingcap/tidb/blob/master/br/pkg/restore/systable_restore.go` is moved to `https://github.com/pingcap/tidb/blob/master/br/pkg/restore/snap_client/systable_restore.go` in https://github.com/pingcap/tidb/pull/53197
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17434

br: fix broken links

---

ticdc/ticdc-manage-changefeed.md

remove multiple spaces

---

.github/workflows/ja-full-translation-google.yaml

This PR updates TiDB version in the ja full translation workflow from 7.5 to 8.1.

ci: update TiDB version in the ja full translation workflow

---

system-variables.md
temp.md

Fix the default value description for `tidb_enable_outer_join_reorder`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15665
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/12342

v6.1: update the description for tidb_enable_outer_join_reorder

---

releases/release-7.5.0.md
releases/release-notes.md
releases/release-timeline.md

Add support for LTS release notes subscription
- Other reference link(s): https://github.com/pingcap/docs-staging/pull/76

releases: add release notes subscription

---

sql-statements/sql-statement-add-index.md
sql-statements/sql-statement-import-into.md
tidb-distributed-execution-framework.md

Add links for DXF

---

TOC-tidb-cloud.md
tidb-cloud/oauth2.md

add oauth 2.0

---

tiproxy/tiproxy-overview.md
tiup/tiup-documentation-guide.md

Fix the build error in https://github.com/pingcap/website-docs/actions/runs/9251718260

i18n: fix build error

---

tidb-distributed-execution-framework.md

- Other reference link(s):https://github.com/pingcap/docs/pull/17522

DFX: support running multiple ADD INDEX in parallel

---

tiproxy/tiproxy-overview.md

Fix a syntax error in the MDX code for machine translation. ref: https://github.com/pingcap/docs/pull/17636
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17449

fix MDX syntax error in machine translation

---

tidb-cloud/delete-tidb-cluster.md

In current cluster deleting panel, there's no message to remind customers that backups will generate the charging fee , which make customers surprised when checking the bills. So this time, we redesign the UX to remind the customers of the charging policy of automatic and manual backups after deleting clusters. …

cloud: add the reminder message of charging policy for backups when customers delete dedicated clusters

---

releases/release-6.1.6.md
releases/release-6.2.0.md
releases/release-6.5.1.md
releases/release-7.0.0.md
releases/release-7.2.0.md
temp.md

Modify the 404 link [gozssky](https://github.com/gozssky) to [sleepymole](https://github.com/sleepymole), [HappyUncle](https://github.com/HappyUncle) to [happy-v587](https://github.com/happy-v587)
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17451

releases: fix two outdated 404 links

---

tidb-cloud/ticloud-config-set.md

cloud: fix admonitions syntax

---

alert-rules.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17450

fix the description of tidb_query_duration

---

best-practices/uuid.md

uuid: Link to functions etc

---

TOC.md
tiproxy/tiproxy-api.md
tiproxy/tiproxy-command-line-flags.md

Add a document to introduce TiProxy API and add some `tiproxyctl` commands.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17340

tiproxy: add tiproxyctl commands and http api

---

releases/release-7.5.1.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/17489

TiKV: supplement missing release docs on optimizing the HA

---

mysql-schema.md

Add missing system tables to v6.5 docs
Note: The added content in this PR already exists in v7.5 and later versions. See [mysql Schema](https://docs.pingcap.com/zh/tidb/v7.5/mysql-schema#%E5%85%83%E6%95%B0%E6%8D%AE%E9%94%81%E7%9B%B8%E5%85%B3%E7%B3%BB%E7%BB%9F%E8%A1%A8) (zh), [mysql Schema](https://docs.pingcap.com/tidb/v7.5/mysql-schema#system-tables-related-to-metadata-locks) (en).
For details, see [tips for choosing the affected versions (in …

Add description for some system tables

---

br/br-snapshot-guide.md

Fix https://github.com/pingcap/docs/issues/17679
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/16740

br-snapshot-guide: remove the experimental note of the coarse-grained Region scatter algorithm

---

tikv-configuration-file.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17505

Add cases for full compaction config for non-utc time zone

---

information-schema/information-schema-tikv-region-status.md
temp.md

Fix https://github.com/pingcap/docs-cn/issues/17482
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17490

information-schema: update the description for the tikv-region-status table

---

ticdc/ticdc-sink-to-kafka.md

TiCDC supports multiple Kafka addresses, but the document does not indicate this. And `userinfo@` is unused.
- Other reference link(s): https://asktug.com/t/topic/1026783

TiCDC: modify Kafka sink uri format

---

temp.md
ticdc/ticdc-alert-rules.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17464

Fix ticdc alert rules

---

basic-features.md

Remove fast analyze from the list of basic features [TiDB Features | PingCAP Docs](https://docs.pingcap.com/tidb/stable/basic-features)

Remove fast analyze from the list of basic features

---

ticdc/ticdc-overview.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17495

ticdc: Fix sql case error

---

statistics.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17467

statistics: update the note for sampling rate

---

tiproxy/tiproxy-configuration.md

Fix the API addr, it should be 3080, not 3090.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17552

tiproxy: fix tiproxy api addr

---

mysql-schema.md
tidb-cloud/limited-sql-features.md
tidb-cloud/serverless-limitations.md
time-to-live.md

cloud: enabling ttl table in serverless

---

tidb-cloud/manage-serverless-spend-limit.md
tidb-cloud/select-cluster-tier.md
tidb-cloud/serverless-faqs.md
tidb-cloud/serverless-limitations.md

cloud: update the free quota of columnar storage

---

br/br-snapshot-manual.md

Fix one word typo in https://docs.pingcap.com/tidb/stable/br-snapshot-manual#restore-cluster-snapshots
Note: The description is correct in the Chinese version. See [TiDB 快照备份与恢复命令行手册 | PingCAP 文档中心](https://docs.pingcap.com/zh/tidb/v7.5/br-snapshot-manual#%E6%81%A2%E5%A4%8D%E5%BF%AB%E7%85%A7%E5%A4%87%E4%BB%BD%E6%95%B0%E6%8D%AE).
- This PR …

br: fix one word typo

---

temp.md
tikv-configuration-file.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17581

track-and-verify-wals-in-manifest: add v7.5.2 as a supported version

---

br/br-incremental-guide.md
temp.md

Add some restriction of incremental restore
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17579

br: add restriction for incremental restore

---

migrate-from-csv-files-to-tidb.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/17475

lightning: add description about terminator for strict-format CSV files

---

br/br-snapshot-guide.md
releases/release-7.6.0.md
temp.md
tidb-cloud/tidb-cloud-release-notes.md

Remove inappropriate description from br doc
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17513

br: adjust br related statement

---

tidb-cloud/tidb-cloud-faq.md
tidb-cloud/tidb-cloud-release-notes.md

cloud: update the the default TiDB version of new TiDB Serverless clusters

---

system-variables.md
temp.md

Adds the type info for the `tidb_adaptive_closest_read_threshold` system variable
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17606

Add type info for tidb_adaptive_closest_read_threshold

---

temp.md
upgrade-monitoring-services.md

Adds the `--overwrite` option to the command of upgrading monitoring services
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17607

Update the command of upgrading monitoring services

---

tidb-cloud/terraform-get-tidbcloud-provider.md
tidb-cloud/terraform-use-cluster-resource.md

Terraform add sync configuration

---

dm/deploy-a-dm-cluster-using-tiup.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/17626

DM: add a step about encrypting the database password

---

br/backup-and-restore-overview.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/17636

br: refine description for snapshot backup

---

tidb-distributed-execution-framework.md

dxf: link to data type

---

tidb-lightning/tidb-lightning-configuration.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/17603

tidb lightning: expose [tidb.session-vars] in lightning config

---

external-storage-uri.md

fix format in external-storage-uri.md

---

scripts/release_notes_update_pr_author_info_add_dup.py

1. Support collecting dup release notes based on the combination of the issue number and authors 
2. Support applying the grey color to the rows with dup release notes

chore: support collecting dup release notes based on the combination of the issue number and authors

---

TOC-tidb-cloud.md
tidb-cloud/serverless-driver-drizzle-example.md
tidb-cloud/serverless-driver-kysely-example.md

Add drizzle example

---

ticdc/ticdc-sink-to-kafka.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/17685

ticdc: clarify description about compression

---

tiproxy/tiproxy-deployment-topology.md

Close https://github.com/pingcap/docs-cn/issues/17690
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17698

tiproxy: change instance count from 3 to 1

---

tidb-cloud/tidb-cloud-htap-quickstart.md
tiflash/create-tiflash-replicas.md
tiflash/tiflash-results-materialization.md

modify samples for serverless, and add note for create tiflash replica
1. Modify the sample dataset for HTAP quickstart
2. Fix https://github.com/pingcap/docs/issues/17645

modify try out htap samples

---

clinic/clinic-data-instruction-for-tiup.md
clinic/clinic-user-guide-for-tiup.md

Clinic: Various fixes

---

tidb-cloud/data-service-manage-endpoint.md
tidb-cloud/explore-data-with-chat2query.md

add response limit for chat2query and tcds

---

tidb-cloud/tidb-cloud-billing-ticdc-rcu.md

changefeed: add more tips for RCU performance

---

tidb-cloud/tidb-cloud-release-notes.md

cloud: add release notes 20240618
- https://github.com/pingcap/docs/pull/17916
- https://github.com/pingcap/docs/pull/17914

cloud: add release notes 20240618

---

tidb-cloud/tidb-cloud-faq.md

update the default TiDB version of new TiDB Dedicated clusters from v7.5.1 to v7.5.2

cloud: update the default TiDB version of new TiDB Dedicated clusters

---

tidb-cloud/size-your-cluster.md

Increase the maximum node storage of 16 vCPU TiFlash and 32 vCPU TiFlash for TiDB Dedicated clusters from 2048 GiB to 4096 GiB.

cloud: update TiFlash max node storage

---

sql-plan-replayer.md

fix typo: change 'PLAN PLAYER CAPTURE' to 'PLAN REPLAYER CAPTURE'
```
mysql> PLAN PLAYER CAPTURE 'example_sql' 'example_plan';
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 11 near "PLAYER CAPTURE 'example_sql' 'example_plan'"
``` …

fix typo: change 'PLAN PLAYER CAPTURE' to 'PLAN REPLAYER CAPTURE'

---

migrate-with-more-columns-downstream.md
temp.md

Fix https://asktug.com/t/topic/1028156
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17774

dm: fix the command for querying migration status

---

functions-and-operators/functions-and-operators-overview.md

Update function and operator overview

---

information-schema/information-schema-tiflash-segments.md
information-schema/information-schema-tiflash-tables.md
tidb-cloud/limited-sql-features.md

serverless: Support TiFlash system tables

---

develop/dev-guide-choose-driver-or-orm.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17789

feat: updated suggest jdbc to 8.x

---

sql-statements/sql-statement-create-index.md
system-variables.md

1. The default value of `tidb_allow_function_for_expression_index` was incorrect as it was formatted not a single string, but as a set of strings.
2. Link from the variable to the expression index doc
3. Link to the functions from the expression index doc

Update docs for tidb_allow_function_for_expression_index

---

_index.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17796

v8.1: fix the link to roadmap

---

temp.md
troubleshoot-tidb-oom.md

update the incorrect command, add double quotes
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17601

troubleshoot-tidb-oom：update the incorrect command, add double quotes

---

tidb-cloud/tidb-cloud-release-notes.md

cloud: add release notes 20240625

cloud: add release notes 20240625

---

tidb-cloud/tidb-cloud-faq.md

cloud: fix the link to CLA

---

tidb-configuration-file.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17788

deprecate tidb config enable-replica-selector-v2

---

ticdc/ticdc-upstream-downstream-check.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17710

ticdc: add new rules and information for syncpoint 

---

optimizer-hints.md
privilege-management.md
sql-statements/sql-statement-set-resource-group.md
sql-statements/sql-statement-show-privileges.md
system-variables.md
tidb-resource-control.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17681

resource_control: add new privilege `RESOURCE_GROUP_USER`

---

system-variables.md
tiflash/tiflash-configuration.md

Enhance log densensitation in tiflash.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17627

tiflash: Add "marker" for security.redact_info_log in tiflash.toml

---

system-variables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17731

Modify doc for parallel sort

---

glossary.md
tikv-configuration-file.md

Small updates to TiKV config docs

---

temp.md
tidb-configuration-file.md

Close https://github.com/pingcap/docs-cn/issues/17195
Set the max value of `token-limit` to 1048576.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17365
- Other reference link(s): https://github.com/pingcap/tidb/pull/53361

config: update token-limit max value

---

develop/dev-guide-choose-driver-or-orm.md
develop/dev-guide-transaction-restraints.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17797

feat: adjust description of hibernate

---

dynamic-config.md
temp.md
tikv-configuration-file.md

Add description for new config `raftstore.max-apply-unpersisted-log-limit`
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17044

tikv: add doc for new config `max-apply-unpersisted-log-limit`

---

tidb-cloud/vector-search-get-started-using-python.md

update vector-search python guide

---

cached-tables.md

cached table: add links

---

ticdc/ticdc-sink-to-kafka.md

Add a table to introduce the minimum supported Kafka versions for each TiCDC version.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17395

cdc: add kafka supported version table

---

hardware-and-software-requirements.md

Add descriptions about CentOS 7 EOL and CentOS Stream 8 EOL
**Note:** "CentOS 7" also exists in many other documents, which will be updated as needed later in another PR.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17785

Add CentOS 7 EOL to OS descriptions

---

system-variables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17686

change the default value of `tidb_enable_historical_stats` to `OFF`

---

system-variables.md
tidb-configuration-file.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17688

*: increase the performance of loading stats

---

br/backup-and-restore-use-cases.md
br/br-snapshot-guide.md
br/br-snapshot-manual.md

Add more details about `backupts` with time zone. 
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17705

backup: add time zone in examples

---

functions-and-operators/json-functions.md
sql-statements/sql-statement-show-builtins.md

Document `JSON_SCHEMA_VALID()`
https://github.com/pingcap/tidb/pull/52780

Add JSON_SCHEMA_VALID

---

pd-control.md

Add a description for `scheduler config evict-leader-scheduler` in the PD control doc.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17755

pd-control: add description for `scheduler config evict-leader-scheduler`

---

optimizer-hints.md
sql-prepared-plan-cache.md
statement-summary-tables.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/17315

planner: update the doc about Plan Cache

---

tidb-cloud/vector-search-overview.md

vector-search: fix typo in use cases

---

tidb-cloud/vector-search-data-types.md
tidb-cloud/vector-search-functions-and-operators.md

Add compare and arithmetic rules for Vector data types.

tidbcloud: Add compare and arithmetic rules for Vector data types

---

hardware-and-software-requirements.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/17834
- Other reference link(s): https://github.com/pingcap/tiflash/issues/7193

TiFlash: update LLVM requirements

---

dashboard/dashboard-resource-manager.md
sql-statements/sql-statement-calibrate-resource.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17773

resource_control: add privilege requirement for dashboard capacity estimation

---

system-variables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17687

*: adaptive analyze scan concurrency

---

performance-tuning-methods.md
temp.md

- Fix several typos
- Update wording
Note: Some issues don't exist in the English version [Performance Analysis and Tuning | PingCAP Docs](https://docs.pingcap.com/tidb/stable/performance-tuning-methods).
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17837
- [Performance Analysis and Tuning | PingCAP …

Fix several typos and update wording for perf tuning

---

tidb-cloud/data-service-app-config-files.md
tidb-cloud/data-service-manage-endpoint.md

add description of system query endpoint to dataservice documentation

---

tidb-cloud/tidb-cloud-release-notes.md

TiDB Cloud release notes for 20240702

---

grafana-tikv-dashboard.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17845
- Other reference link(s): https://github.com/tikv/tikv/issues/16837

tikv-grafana: add compaction job size(files) metric

---

temp.md
ticdc/ticdc-behavior-change.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17839

ticdc: add more description about how cdc split update kv entries 

---

_docHome.md
best-practices/high-concurrency-best-practices.md
best-practices/tidb-best-practices.md
dashboard/dashboard-key-visualizer.md
develop/dev-guide-build-cluster-in-cloud.md
develop/dev-guide-proxysql-integration.md
develop/dev-guide-use-subqueries.md
explore-htap.md
faq/migration-tidb-faq.md
faq/sql-faq.md
releases/release-6.0.0-dmr.md
releases/versioning.md
system-variables.md
telemetry.md
tidb-cloud/_index.md
tidb-cloud/release-notes-2021.md
tidb-cloud/release-notes-2022.md
tidb-cloud/tidb-cloud-billing-dm.md
tidb-cloud/tidb-cloud-billing.md
tidb-cloud/tidb-cloud-faq.md
tiflash-upgrade-guide.md
tiflash/tiflash-overview.md

**Note**: Another option would be to make en.pingcap.com a cname for www.pingcap.com in the DNS settings. I'm not sure which option is best.

Update outdated https://en.pingcap.com/ links

---

tidb-cloud/vector-search-get-started-using-python.md

Add `python-dotenv` in pip install command since it's required in the Python script.

Add dotenv in pip install command for vector-search python guide

---

ddl-introduction.md

- Other reference link(s):https://github.com/pingcap/docs/pull/18126

fix a minor wording issue in ddl-introduction.md

---

upgrade-tidb-using-tiup.md

tiup: add a ref to limitation on users operation during upgrade using tiup

---

tidb-cloud/tidb-cloud-faq.md
tidb-cloud/tidb-cloud-release-notes.md

cloud: add release notes 20240709

---

tidb-cloud/tidb-cloud-intro.md

cloud: Update tidb-cloud-intro.md

---

tidb-lightning/troubleshoot-tidb-lightning.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/17892

fix the solution 8025 error

---

statistics.md

Fix https://github.com/pingcap/docs/issues/18036
- Other reference link(s): The typo is also fixed in https://github.com/pingcap/docs-cn/pull/17827.

statistics.md: fix a typo for analyze

---

TOC-tidb-cloud.md
TOC.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/17915

*:fix a typo in toc

---

sql-statements/sql-statement-analyze-table.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/17933
- Other reference link(s):https://github.com/pingcap/docs/pull/16594

sql: fix a synopsis error

---

releases/release-7.5.2.md
releases/release-8.2.0.md

v8.2: fix the description for issue #53871

---

tidb-cloud/oauth2.md

tidb cloud: add steps about viewing and revoking authorized OAuth apps

---

optimizer-hints.md

optimizer-hints: fix a section level

---

tidb-cloud/use-chat2query-api.md

- Other reference link(s):https://github.com/pingcap/docs/pull/17984

review use-chat2query-api.md

---

system-variables.md

fix a typo for "scope"

---

functions-and-operators/string-functions.md

- MySQL 8.0 is a LTS release
- MySQL 8.3 is an older innovation release
This link was causing a HTTP 302 redirect to the 8.4 page.

string-functions: Use MySQL 8.0 url instead of 8.3

---

tispark-overview.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17979

Update tispark-overview.md version matrix

---

releases/release-8.2.0.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/18031

Add missing release note for issue tidb#53540

---

migration-overview.md

Redirect `https://docs.pingcap.com/tidb/stable/migrate-full-data-from-mysql` to `https://docs.pingcap.com/tidb/stable/migration-overview`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18038

add aliases for migrate-full-data-from-mysql

---

explain-joins.md

Keep the description of column name to be consistent with the command.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18046

fix incorrect column name in Index Join

---

releases/release-7.4.0.md

Fix a broken Github link from `https://github.com/ZhuohaoHe` to `https://github.com/ZzzhHe`. ref: https://github.com/tikv/pd/pull/6996#issuecomment-1696575707
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18052

release (contributors): fix a broken GitHub link

---

dm/dm-worker-intro.md
temp.md

Add the missing `;` to one SQL statement
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18063

dm: fix SQL statement syntax

---

migration-tools.md

Improve descriptions to avoid confusion. Because the example uses `dumpling` but `dumpling` doesn't show in the preceding command output.

Improve step description for installing tools using TiUP

---

TOC-tidb-cloud.md
tidb-cloud/use-chat2query-api.md
tidb-cloud/use-chat2query-knowledge.md
tidb-cloud/use-chat2query-sessions.md

add intro of domain knowledge api

---

temp.md
tidb-configuration-file.md
tikv-configuration-file.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17990

doc: add more details to grpc-compression configs

---

TOC-tidb-cloud.md
tidb-cloud/tidb-cloud-budget.md

cloud: add a doc for the budget feature

---

partitioned-table.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/18094

partitioned-table: create strictly increasing range columns partition

---

smooth-upgrade-tidb.md
temp.md
upgrade-tidb-using-tiup.md

Improve descriptions of upgrading limitations to make it more clear
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18076

Improve upgrade limitations

---

temp.md
tiflash/tiflash-configuration.md

* Add more details about tiflash && tiflash-proxy logging config.
* Remove `raftstore.store-batch-retry-recv-timeout` from tiflash-proxy config. This item have been removed from tiflash-proxy since v6.5
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18099, https://github.com/pingcap/docs-cn/pull/18138

tiflash: refine TiFlash configuration parameters

---

sync-diff-inspector/sync-diff-inspector-overview.md

add upcount downcount description
add result summary description
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18125

sync-diff-inspector: add UPCOUNT and DOWNCOUNT

---

tidb-cloud/tidb-cloud-faq.md
tidb-cloud/tidb-cloud-release-notes.md

There is only one default version for TiDB Serverless. Upgrading the TiDB Serverless version takes effect for both new and existing clusters.

cloud: update serverless upgrade note

---

temp.md
ticdc/ticdc-faq.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18163

ticdc-faq: fix typo for commitTS

---

tidb-cloud/tidb-cloud-budget.md

cloud: support editing budget scope

---

temp.md
ticdc/ticdc-faq.md
ticdc/ticdc-sink-to-mysql.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18162

ticdc: move the mysql downstream user permission info to the mysql sink doc

---

temp.md
tune-region-performance.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18187

fix the recommended range for region-split-size

---

temp.md
tidb-configuration-file.md

- "Control+C" is supported since `v7.3.0`. As there is already description about "Control+C" in [`[KILL]`](https://docs.pingcap.com/zh/tidb/v7.5/sql-statement-kill), just simple remove the redundant words.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18126

tidb: Remove description about "Control+C" for `compactible-kill-query`

---

mysql-schema/mysql-schema-user.md

Fix website build fauilre:
```
error "gatsby-plugin-mdx" threw an error while running the onCreateNode lifecycle:
end of the stream or a document separator is expected at line 2, column 8:
title: `mysql.user`
^/home/runner/work/website-docs/website-docs/docs/markdown-pages/en/tidb/master/mysql-schema/mysql-schema-user.md: end of the stream or a document separator is expected at line 2, column 8:
title: `mysql.user`
^
YAMLException:end of the stream or a document separator is expected at line 2  , column 8:
title: `mysql.user`
^/home/runner/work/website-docs/website-docs/docs/markdown-pages/en  /tidb/master/mysql-schema/mysql-schema-user.md: end of the stream or a documen  t separator is expected at line 2, column 8:
title: `mysql.user`
^
``` …

fix: remove backticks from front matter

---

tiproxy/tiproxy-overview.md

The link text `TiProxy Issues` is pointing to https://github.com/pingcap/tiup/issues, but it should be https://github.com/pingcap/tiproxy/issues

Update tiproxy-overview.md to fix the link to TiProxy issue

---

identify-expensive-queries.md
information-schema/information-schema-processlist.md
releases/release-8.2.0.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18181

doc: add session_alias to information_schema.processlist and expensive queries

---

develop/dev-guide-timeouts-in-tidb.md
dumpling-overview.md
migrate-from-tidb-to-mysql.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18215

dumpling: update the gc info

---

alert-rules.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/18227

alert: remove keep_alive_total metric

---

sql-logical-optimization.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18242

sql-logical-optimization: add an entry for derive topN and limit

---

information-schema/information-schema-keywords.md

v7.5.3: add information_schema.keywords
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18257

v7.5.3: add information_schema.keywords

---

br/use-br-command-line-tool.md
temp.md

Adds descriptions for "tiup br debug" command and subcommands
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18161

br: add "tiup br debug" command

---

pd-recover.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/18228

pd: add an example for pd-recover

---

keywords.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/18285

sql: delete PLACEMENT(S) in keywords

---

temp.md
tune-region-performance.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18293

update the maximum region size for TiFlash

---

tidb-cloud/tidb-cloud-release-notes.md

cloud: add release note for 20240806
- Other reference link(s): https://github.com/pingcap/docs/pull/18469

cloud: add release note for 20240806

---

releases/release-8.2.0.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18292

add ticdc pulsar sink related release note

---

system-variables.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/18323

sys var: add more contents to `tidb_remove_orderby_in_subquery`

---

ticdc/ticdc-changefeed-config.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18308

cdc: update output-raw-change-event comment link

---

tiproxy/tiproxy-configuration.md

Use `""` to represent empty string.
Close https://github.com/pingcap/docs/issues/16511
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18341

fix: use `""` to represent empty string

---

auto-random.md

add pre_split_region information.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18339

add an example of using AUTO_RANDOM with PRE_SPLIT_REGIONS

---

sql-statements/sql-statement-split-region.md

Clarify that PRE_SPLIT_REGIONS is also recommended for tables with AUTO_RANDOM attribute
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18340

update pre_split_regions usage scenario

---

scripts/release_notes_update_pr_author_info_add_dup.py

chore: fix a bug that caused delays in fetching duplicate release notes

---

system-variables.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/18359

sys-var: add SESSION scope for `ddl_reorg_batch_size` and `ddl_reorg_worker_cnt`

---

glossary.md

- The current TTL in glossary the specifically refers to the row-level time-to-live feature
- Removal prevents confusion with other TTL concepts in documentation
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18361

remove ambiguous TTL from glossary

---

ticdc/ticdc-canal-json.md
ticdc/ticdc-sink-to-kafka.md

cdc: canal-json dml event `commit-ts` should be TSO
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18360

cdc: canal-json dml event commit-ts should be TSO

---

system-variables.md

v8.3: Changes the default value of `tidb_opt_projection_push_down` from `OFF` to `ON`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17891

Change tidb_opt_projection_push_down default value to ON

---

performance-tuning-practices.md

fix bug in performance tuning practices

---

pd-control.md
temp.md

Add a new config item: batch in evict-leader-scheduler from v8.3.0, so add the instructions for use.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18387

PD: add description of batch in evict-leader-scheduler config

---

_index.md

…18623)
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/18394

v8.3.0: update learning path

---

tidb-cloud/tidb-cloud-release-notes.md

cloud: add release note for 20240820

cloud: add release note for 20240820

---

tidb-cloud/use-chat2query-api.md

update chat2query api, add doc for data_summary_id

---

command-line-flags-for-pd-configuration.md

ref [tikv/pd@10cbdcf/server/config/config.go#L364-L370](https://github.com/tikv/pd/blob/10cbdcf0c551c3e337ebc1b885b1f2ccd874b163/server/config/config.go#L364-L370)
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18402

pd: Fix the default name of the configuration

---

command-line-flags-for-scheduling-configuration.md
command-line-flags-for-tso-configuration.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18391
- Other reference link(s): ref https://github.com/tikv/pd/pull/8461

PD: Add the name field to the startup parameters 

---

.github/pull_request_template.md

pull_request_template: add v8.4
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18421

pull_request_template: add v8.4

---

TOC.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18423

TOC: add v8.3 release notes

---

tiflash/create-tiflash-replicas.md

The config `raftstore-proxy.server.snap-max-write-bytes-per-sec` has been changed to `raftstore-proxy.server.snap-io-max-bytes-per-sec` since v7.1. Ref https://github.com/pingcap/docs-cn/pull/13336
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18362

*: Rename snap-max-write-bytes-per-sec (tiflash)

---

README.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/18444

*: add 8.2 and 8.3 to README.md

---

keywords.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/18447

*: add keywords for 8.3

---

system-variables.md

v8.1.1: Turn off hash agg spill by default

---

migrate-from-tidb-to-tidb.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17689

ticdc: Update migrate from tidb to tidb doc

---

dashboard/dashboard-monitoring.md
grafana-overview-dashboard.md
grafana-performance-overview-dashboard.md
grafana-tidb-dashboard.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18463

Revise TSO related Grafana monitoring metrics description

---

scripts/release_notes_auto_tw_assignment.py

This script aims to assign editorial and translation tasks of "Improvements" and "Bug Fixes" in release notes among technical writers evenly based on the number of release note items for each component.

chore: add a script to assign release note tasks to writers automatically

---

TOC-tidb-cloud.md
tidb-cloud/notification-2024-09-15-console-maintenance.md

Add notification-2024-09-15-console-maintenance.md

---

.github/pull_request_template.md
README.md
temp.md

Remove v5.2/v8.0 from the PR template because v5.2/v8.0 docs have been archived at https://docs-archive.pingcap.com/tidb and will no longer receive new updates.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18497

chore: remove v5.2/v8.0 from PR template

---

character-set-and-collation.md
faq/sql-faq.md

This PR updates outdated character set descriptions in SQL FAQ, but doesn't introduce new content.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17854

faq: update character set description

---

develop/dev-guide-gui-datagrip.md
develop/dev-guide-gui-dbeaver.md
develop/dev-guide-gui-mysql-workbench.md
develop/dev-guide-gui-navicat.md
develop/dev-guide-gui-vscode-sqltools.md
develop/dev-guide-sample-application-golang-gorm.md
develop/dev-guide-sample-application-golang-sql-driver.md
develop/dev-guide-sample-application-java-hibernate.md
develop/dev-guide-sample-application-java-jdbc.md
develop/dev-guide-sample-application-java-mybatis.md
develop/dev-guide-sample-application-java-spring-boot.md
develop/dev-guide-sample-application-nodejs-mysql2.md
develop/dev-guide-sample-application-nodejs-mysqljs.md
develop/dev-guide-sample-application-nodejs-prisma.md
develop/dev-guide-sample-application-nodejs-sequelize.md
develop/dev-guide-sample-application-nodejs-typeorm.md
develop/dev-guide-sample-application-python-django.md
develop/dev-guide-sample-application-python-mysql-connector.md
develop/dev-guide-sample-application-python-mysqlclient.md
develop/dev-guide-sample-application-python-peewee.md
develop/dev-guide-sample-application-python-pymysql.md
develop/dev-guide-sample-application-python-sqlalchemy.md
develop/dev-guide-sample-application-ruby-mysql2.md
develop/dev-guide-sample-application-ruby-rails.md

develop: update connection page for TiDB Dedicated clusters

---

develop/dev-guide-bookshop-schema-design.md

develop: update TiDB Cloud Import page

develop: update TiDB Cloud Import page

---

sql-plan-management.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/18523

sql_plan_management: use idx_a for index name

---

tidb-cloud/vector-search-data-types.md

Add info about conversion to single-precision floats until double precision is supported.
(per [this discussion](https://discord.com/channels/1083300679386406923/1098161518182400021/threads/1273819443847495832) during the TiDB Future App Hackathon). 

Update the Resctrictions section for Vector Search

---

tidb-configuration-file.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/18544

tidb: add a note for `cross-join`

---

pd-control.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18378

pd: remove shuffle schedulers

---

dashboard/dashboard-access.md

dashboard: add SSO for dashboard access

---

information-schema/information-schema-inspection-result.md

Corrected "tikv_critical_error_total_coun" to "tikv_critical_error_total_count"
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18577

fix typo in information-schema-inspection-result.md

---

ticdc/ticdc-simple-protocol.md

ticdc: fix typo

---

pd-configuration-file.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18526 None, just optimize some descriptions.

PD: optimize the description of label-property

---

tidb-cloud/tidb-cloud-release-notes.md

cloud: add release notes for 20240910

---

sql-statements/sql-statement-import-into.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/18603

add limit to import into

---

_docHome.md
_index.md
tidb-cloud/_index.md

Update title for all home pages (Home, TiDB Cloud and TiDB Self-Managed) to make them more consistent.
All
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18606

Update homepage titles

---

_docHome.md
_index.md

This PR redesigns the global home doc.

refactor(doc): redesign the global home doc

---

develop/dev-guide-overview.md

This PR adds a developer guide overview doc for TiDB Cloud.

feat(doc): add a dev guide overview for TiDB Cloud

---

develop/dev-guide-create-table.md
develop/dev-guide-insert-data.md
develop/dev-guide-playground-gitpod.md
dm/task-configuration-file-full.md
migrate-large-mysql-shards-to-tidb.md
placement-rules-in-sql.md
tidb-resource-control.md

Remove Chinese doc links from English documentation.

fix: remove Chinese doc links

---

tidb-lightning/tidb-lightning-logical-import-mode-usage.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/18641

change lightning conflict resolution ignore

---

dm/dm-best-practices.md

Fixing broken link. It was [Use the relay log](#use-the relay-log). Changed to [Use the relay log](#use-the-relay-log).

Fix broken link in DM best practices

---

tidb-lightning/tidb-lightning-data-source.md

Update the link <https://docs.pingcap.com/tidb/v6.6/backup-and-restore-storages#uri-format> to that of the corresponding TiDB version.

Update a link in TiDB Lightning data sources

---

tidb-lightning/tidb-lightning-data-source.md

This is a follow-up to https://github.com/pingcap/docs/pull/18927. 

Update a link in Lightning data sources

---

migrate-aurora-to-tidb.md

add missing quote migrate-aurora-to-tidb.md

---

faq/sql-faq.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18660

faq: update the description of "Information schema is out of date"

---

dr-secondary-cluster.md

Deleted: Removed all binlog-related content from the TiCDC documentation as binlog is completely deprecated.

Remove All Binlog References from CDC Documentation

---

_index.md

fix _index.md in ja

---

_index.md

Update the product name in the index in Japanese for v7.5, as that for v8.1 https://github.com/pingcap/docs/pull/18967
- Other reference link(s): https://github.com/pingcap/docs/pull/18967

Update _index.md in ja

---

tidb-cloud/size-your-cluster.md

cloud: add a new TiFlash vCPU and RAM size `32 vCPU, 128 GiB`

---

pd-configuration-file.md
temp.md

Signed-off-by: Ryan Leung <rleungx@gmail.com>
Just as the title says.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12674

Add a notice for pd configuration

---

sql-statements/sql-statement-change-drainer.md
sql-statements/sql-statement-change-pump.md
sql-statements/sql-statement-show-drainer-status.md
sql-statements/sql-statement-show-pump-status.md
temp.md
tidb-binlog-deployment-topology.md
tidb-binlog/bidirectional-replication-between-tidb-clusters.md
tidb-binlog/binlog-consumer-client.md
tidb-binlog/binlog-control.md
tidb-binlog/deploy-tidb-binlog.md
tidb-binlog/get-started-with-tidb-binlog.md
tidb-binlog/handle-tidb-binlog-errors.md
tidb-binlog/maintain-tidb-binlog-cluster.md
tidb-binlog/monitor-tidb-binlog-cluster.md
tidb-binlog/tidb-binlog-configuration-file.md
tidb-binlog/tidb-binlog-faq.md
tidb-binlog/tidb-binlog-glossary.md
tidb-binlog/tidb-binlog-overview.md
tidb-binlog/tidb-binlog-relay-log.md
tidb-binlog/tidb-binlog-reparo.md
tidb-binlog/troubleshoot-tidb-binlog.md
tidb-binlog/upgrade-tidb-binlog.md

This PR adds aliases for 21 TiDB Binlog document files deleted from the master branch via #18908. This is for the release of v8.4.0.
Note: The content in the `aliases` section comes from that in the files of the master branch. In addition to that, I add the alias for the URL of the current dev version. …

*: add aliases for 21 deleted TiDB Binlog docs from dev

---

mysql-schema/mysql-schema.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/18730

sql: fix error in tidb_ddl_job

---

tidb-cloud/_index.md

chore: typo of ja tidb-cloud/_index.md

---

temp.md
tidb-lightning/tidb-lightning-physical-import-mode.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18698

tidb-lightning: refine the PITR support info

---

non-transactional-dml.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/18746

non-transactional-dml: update t3. to t3.id 

---

br/br-snapshot-guide.md
mysql-schema/mysql-schema.md

This table has been removed since v8.0.0 (and it's basically not functional from the very beginning).
It should be removed from document.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/18745

system tables: remove table `schema_index_usage`

---

character-set-and-collation.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/18757

character-set-and-collation: fix an error

---

system-variables.md

We have defined the correct range for tidb_analyze_partition_concurrency in [this pull request](https://github.com/pingcap/tidb/pull/55409).

statistics: set the right range for tidb_analyze_partition_concurrency

---

configure-placement-rules.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/18758

cfg: fix wrong pd-ctl cmd

---

ticdc/ticdc-sink-to-pulsar.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18756

ticdc: add description for pulsar topic config

---

best-practices/massive-regions-best-practices.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/18775

tikv: customized Region size is an experimental feature before TiDB v6.5.0

---

temp.md
ticdc/ticdc-open-protocol.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18794

cdc: fix open protocol example data

---

TOC.md

Adds [TiDB Release Support Policy](https://www.pingcap.com/tidb-release-support-policy/) to `TOC.md` according to @likidu's suggestion.

toc: add TiDB release support policy

---

functions-and-operators/string-functions.md

string-functions: Explain binary-as-hex behavior

---

system-variables.md

Add docs for hash join v2

---

system-variables.md

planner: change default of tidb_opt_prefer_range_scan

---

tidb-configuration-file.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18613
- Other reference link(s): https://github.com/pingcap/tidb/pull/55985

config: update doc of tidb tikv-client.grpc-keepalive-timeout config

---

sql-statements/sql-statement-change-column.md
sql-statements/sql-statement-modify-column.md
tidb-limitations.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/18774

add description about limitation

---

functions-and-operators/string-functions.md

https://github.com/pingcap/tidb/pull/55541

TiDB supports `MID(str, pos[, len])`

---

performance-tuning-practices.md

performance-tuning-practices: fix wrong number

---

hardware-and-software-requirements.md
pd-control.md
pd-recover.md
tidb-control.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18772

update Go to v1.23

---

TOC-tidb-cloud.md
tidb-cloud/api-overview.md
tidb-cloud/tidb-cloud-partners.md
tidb-cloud/tidb-cloud-release-notes.md

cloud: MSP API deprecation

---

tidb-lightning/tidb-lightning-configuration.md

add logical-import-prep-stmt

---

partition-pruning.md
partitioned-table.md

See https://github.com/pingcap/tidb/issues/54210 / https://github.com/pingcap/tidb/pull/54209
https://github.com/pingcap/tidb/issues/54210 / https://github.com/pingcap/tidb/pull/54209

Added EXTRACT(<time unit> FROM <date/datetime/time col) as partition pruning function

---

certificate-authentication.md

Add a section to Certificate-Based Authentication for Login to claim the support of PBAC for certifications.
- Other reference link(s): https://github.com/pingcap/docs/pull/19151

Add a section to explian the PBAC support for certs

---

dr-multi-replica.md
pd-control.md
placement-rules-in-sql.md
temp.md
three-data-centers-in-two-cities-deployment.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18866

pd: add note for member `leader_priority`

---

sql-statements/sql-statement-commit.md

Close #19163 
https://github.com/pingcap/docs/issues/19163

Removed extra/duplicated ' a'.

---

keywords.md

TiDB v8.4.0:
- introduces APPLY and RECOMMEND as non-reserved keywords (ref https://github.com/pingcap/tidb/pull/55258)
- updates a reserved keyword from `TiDB_CURRENT_TSO` to `TIDB_CURRENT_TSO` (ref https://github.com/pingcap/tidb/pull/55947)
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18820 …

v8.4: add APPLY, RECOMMEND, TIDB_CURRENT_TSO keywords

---

tidb-cloud/tidb-cloud-faq.md
tidb-cloud/tidb-cloud-release-notes.md

cloud: add release notes 2024-10-22

---

_index.md

update the links in the index page to v8.4
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18897

update the links in the index page to v8.4

---

vector-search-integrate-with-langchain.md

vector-search: minor wording updates for the langchain integration doc

---

sql-statements/sql-statement-add-index.md
sql-statements/sql-statement-create-index.md
system-variables.md

Add limitations for adding/creating indexes in TiDB Dedicated

Add limitations for add/create index

---

system-variables.md

system variables: fix version-mark for tidb_hash_join_version

system variables: fix version-mark

---

dm/dm-best-practices.md

dm-best-practices: Update for MySQL Compatible AUTO_INCREMENT

---

tidb-cloud/tidb-cloud-release-notes.md

cloud: add release notes 2024-10-29

---

tidb-cloud/serverless-driver.md

Fix wrong serverless driver package name

---

alert-rules.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18541

remove by name for alert of TiKV_raftstore_thread_cpu_seconds_total

---

ticdc/ticdc-sink-to-kafka.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/18294

cdc: add more detail about the authorization

---

br/br-monitoring-and-alert.md

br: add link to snapshot backup&restore metrics

---

temp.md
tikv-configuration-file.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18776

Correct some configs' notes

---

.github/pull_request_template.md

pull_request_template: add the option for v8.5

---

system-variables.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/19014

sys-var: add 2 for mpp_version

---

sql-prepared-plan-cache.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/19040

planner: update sql-prepared-plan-cache.md

---

sql-statements/sql-statement-import-into.md
statistics.md
tidb-distributed-execution-framework.md

unify TiDB product name ("TiDB Self-Hosted"-> "TiDB Self-Managed") for release-7.5

unify TiDB product name for release-7.5

---

dm/dm-compatibility-catalog.md

dm: update compatibility info

---

tidb-cloud/vector-search-changelogs.md
tidb-cloud/vector-search-get-started-using-python.md
tidb-cloud/vector-search-get-started-using-sql.md
tidb-cloud/vector-search-integrate-with-django-orm.md
tidb-cloud/vector-search-integrate-with-jinaai-embedding.md
tidb-cloud/vector-search-integrate-with-langchain.md
tidb-cloud/vector-search-integrate-with-llamaindex.md
tidb-cloud/vector-search-integrate-with-peewee.md
tidb-cloud/vector-search-integrate-with-sqlalchemy.md
tidb-cloud/vector-search-integration-overview.md
tidb-cloud/vector-search-limitations.md
tidb-cloud/vector-search-overview.md

close https://github.com/pingcap/docs/issues/19373
This PR standardizes the capitalization of “vector search” and “Vector Search” across the TiDB Cloud documentation to improve consistency and readability. The changes follow these rules:
- "TiDB Vector Search": Used when referring to TiDB’s specific product feature.
- "vector search": Used when referring to the concept of vector search in a general or technical context. …

tidb-cloud: unify the capitalization of vector search

---

tidb-cloud/changefeed-sink-to-tidb-cloud.md

cloud: remove TiDB Cloud Dedicated support for AWS sa-east-1 region

cloud: remove TiDB Cloud Dedicated support for AWS sa-east-1 region

---

tidb-cloud/tidb-cloud-release-notes.md

Add release notes for November 12, 2024
- Other reference link(s): https://github.com/pingcap/docs/pull/19368, https://github.com/pingcap/docs/pull/19349

cloud: add release notes 2024-11-12

---

ticdc/ticdc-compatibility.md
tidb-lightning/tidb-lightning-compatibility-and-scenarios.md

cdc: add description about compatibility with TiDB Lightning
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19047

cdc: add description about compatibility with TiDB Lightning

---

ticdc/ticdc-faq.md

This PR introduces a comprehensive guide on how to check if TiCDC has synchronized all updates from an upstream TiDB cluster to downstream systems. These steps ensure that users can confidently verify the synchronization completeness of TiCDC in scenarios where upstream updates have stopped. …

ticdc: add detailed instructions for verifying if TiCDC has replicated all updates to downstream

---

tidb-cloud/tidb-cloud-auditing.md

Removes two inappropriate notes from audit logging
- Other reference link(s): https://docs.pingcap.com/tidbcloud/tidb-cloud-auditing#step-2-configure-gcs-access

tidb-cloud: remove notes from audit logging

---

clustered-indexes.md

Fixes a heading level error in [Clustered Indexes | TiDB Docs](https://docs.pingcap.com/tidb/stable/clustered-indexes)

Fix a heading level error

---

README.md

Adds active contributors to this repo in the last 28 days
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19115

readme: add active contributors

---

tidb-cloud/ticloud-help.md

Fix a typo in ticloud docs: from `serveless` to `serverless`.

cloud: fix typo in ticloud

---

hardware-and-software-requirements.md

TiDB ends support for CentOS 7 from v8.4
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19097

update description about CentOS 7 EOL

---

develop/dev-guide-build-cluster-in-cloud.md
hardware-and-software-requirements.md
ticdc/deploy-ticdc.md

Update CentOS 7-related descriptions for TiDB v8.4.0.
Note: "CentOS 7" also exists in many other documents, which will be updated as needed later in another PR.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18773

v8.4: update CentOS 7-related descriptions

---

TOC.md

- Moves TiCDC docs from **TiDB Tools** > [**TiCDC**](https://docs.pingcap.com/tidb/dev/ticdc-overview) to the first level in left navigation, to make it easier to find
- Renames TiCDC to **Stream Data** in the left navigation
- Combines the exiting first-level [**Integrate**](https://docs.pingcap.com/tidb/dev/integration-overview) with the TiCDC docs
For details, see [tips for choosing the affected versions](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md#guideline-for-choosing-the-affected- …

toc: reorganize TiCDC docs in left navigation

---

tidb-cloud/branch-github-integration.md
tidb-cloud/branch-manage.md
tidb-cloud/branch-overview.md

update branch page to include instructions for creating branch from branch/timestamp and reseting

---

tiflash/tiflash-mintso-scheduler.md

Fix a heading level in https://docs.pingcap.com/tidb/dev/tiflash-mintso-scheduler

tiflash: fix a heading level

---

constraints.md
develop/dev-guide-sample-application-nodejs-prisma.md
develop/dev-guide-sample-application-nodejs-typeorm.md
foreign-key.md
sql-statements/sql-statement-alter-table.md

The foreign key feature is about to GA in v8.4. Let's remove the experiment mark for it in v8.4.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18705
- Other reference link(s): https://github.com/pingcap/tidb/issues/55861

tidb: make Foreign Key GA

---

tikv-configuration-file.md

- This PR is translated from: https://github.com/tikv/tikv/pull/17821

raftstore: increase the default raft-client-queue-size from 8192 to 16384

---

partitioned-table.md
system-variables.md
temp.md
tiflash/use-tiflash-mpp-mode.md

Deprecated static prune mode, ref https://github.com/pingcap/tidb/issues/56490
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18857
- Other reference link(s): ref https://github.com/pingcap/tidb/pull/56543

system-variable: add a warning for `tidb_partition_prune_mode`

---

system-variables.md
tune-region-performance.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19025

pd: GA actieve follower

---

encryption-at-rest.md

encryption: remove experimental for GCP KMS

---

temp.md
ticdc/ticdc-debezium.md

add key field for Debezium protocol. see https://github.com/pingcap/tiflow/issues/11652
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18894

cdc: update debezium protocol 

---

releases/release-7.1.6.md

Fix an issue number number for #52294

---

.github/workflows/cron.yml

- update base branch of jp translation

ci: update base branch of jp translation to i18n-ja-release-8.1

---

system-variables.md
tidb-cloud/limited-sql-features.md

Serverless has now supported letting user specify gc life time, so previous description regarding this limit need to be modified.
It only applys to Serverless, so master should be enough.

update serverless tidb_gc_life_time restriction

---

CONTRIBUTING.md

As the default version for new TiDB Dedicated clusters has been updated to v8.1.0, the source branch of Cloud docs is now in release-8.1 as well.

CONTRIBUTING: update the source branch of TiDB Cloud docs to release-8.1

---

releases/release-6.2.0.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19169

add the removal reason for `tidb_enable_change_multi_schema`

---

.github/workflows/ja-full-translation-google.yaml

- force push for full translation.

fix: ja-full-translation-google.yaml

---

tidb-cloud/tidb-cloud-auditing.md

Add prompt information for database audit logging

Improve DB audit logging documentation

---

br/br-pitr-manual.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19175

br-pitr-manual: remove an unnecessary quotation mark

---

system-variables.md

Hash join v2 supports spill in v8.5

---

hardware-and-software-requirements.md
temp.md

According to https://github.com/pingcap/docs/pull/19539/files, TiDB ends the support for Red Hat Enterprise Linux 7 starting from the 8.4 DMR version. This PR adds a note about this for release-8.1 users.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19189

release-8.1: add a note for Red Hat Enterprise Linux 7 

---

privilege-management.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/19195

privilege: change privilege for SHOW PROCESSLIST from SUPER to PROCESS

---

releases/release-8.3.0.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/19203

remove https://github.com/apps/renovate from release notes

---

tiflash/tiflash-configuration.md

The description of `format_version` in the doc of English version is incorrect. Make it aligned with the Chinese version.

tiflash: Fix format_version description

---

configure-store-limit.md
pd-control.md
releases/release-7.1.0.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19131

store limit v2: add more experimental description

---

configure-time-zone.md

Update timezone docs

---

ticdc/ticdc-alert-rules.md

Ref: https://github.com/pingcap/docs-cn/pull/19221
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/19221

ticdc: fix alert doc

---

online-unsafe-recovery.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18628

Emphasis the importance of input of unsafe recovery

---

hardware-and-software-requirements.md

This is a follow-up to https://github.com/pingcap/docs-cn/pull/17785, confirmed with @JasonWu0506.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17828
- Other reference link(s): https://github.com/pingcap/docs/pull/19547

Update CentOS Stream 8 End of Builds

---

develop/dev-guide-overview.md

Sync the latest tidb-cloud dev-guide-overview changes.
https://github.com/pingcap/docs/blob/release-7.5/develop/dev-guide-overview.md

tidb-cloud: update dev-guide-overview.md

---

sync-diff-inspector/sync-diff-inspector-overview.md

Add description for the check-data-only configuration item, which is introduced in https://github.com/pingcap/tidb-tools/pull/691
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19228

sync_diff_inspector: add the check-data-only configuration item

---

.github/workflows/dispatch.yml

release-8.5: add release-8.5 to dispatch.yml

---

faq/sql-faq.md
sql-statements/sql-statement-insert.md
sql-statements/sql-statement-replace.md
sql-statements/sql-statement-select.md
sql-statements/sql-statement-update.md

- With resource control enabled, `PRIORITY` in SQL statements is no longer recommended.
- Recommend `QUERY WATCH` to manage SQL blacklist.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19227

Recommend RC instead of SQL Priority

---

tidb-performance-tuning-config.md

performance: remove tidb_enable_batch_dml

---

sql-statements/sql-statement-revoke-privileges.md

sql: fix the synopsis of `REVOKE <privileges>`
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19270

sql: fix the synopsis of `REVOKE <privileges>`

---

optimizer-fix-controls.md

planner: update the fix-control doc

---

hardware-and-software-requirements.md

add GLIBC 2.28 requirements
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19279

deploy: add glibc 2.28 requirements

---

quick-start-with-tidb.md
tiup/tiup-playground.md

tiup: refine description about `tiup playground --tag`

---

optimizer-fix-controls.md

planner: update the default value of 46177. Its default value changes from OFF to ON starting from v8.5.0.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19300

planner: update the default value of 46177

---

develop/dev-guide-tidb-crud-sql.md

develop: fix CURD to CRUD

---

tidb-cloud/backup-and-restore-serverless.md

- Other reference link(s):https://github.com/pingcap/docs/pull/19679

fix format error in backup-and-restore-serverless.md

---

basic-features.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19140

update basic-features.md for v8.5

---

tune-tikv-memory-performance.md

Add `toml` to the code block of the TiKV config file

Add the "toml" code fence to TiKV config

---

dm/quick-start-with-dm.md

dm: update the example version to 8.5.0

---

.github/pull_request_template.md

add v9.0 in pull_request_template.md

---

tidb-performance-tuning-config.md

removed concurrently-init-stats due to issue https://github.com/pingcap/tidb/issues/58378

Remove concurrently-init-stats due to known issue

---

temp.md
tiup/tiup-playground.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19360

tiup-playground: update instructions for deploying TiProxy

---

ticdc/ticdc-changefeed-config.md
ticdc/ticdc-server-config.md

**This PR is a first step.** It converts the existing format of code blocks to the body heading format for config descriptions in [CLI and Configuration Parameters of TiCDC Changefeeds | TiDB Docs](https://docs.pingcap.com/tidb/dev/ticdc-changefeed-config) and [TiCDC Server Configurations | TiDB Docs](https://docs.pingcap.com/tidb/dev/ticdc-server-config), like that in [TiDB Configuration File | TiDB Docs](https://docs.pingcap.com/tidb/dev/tidb-configuration-file).
This PR doesn't add new descriptions, except describe some config value as 示例值 for now, because those config items have no description or default value. **Some missing explanations need to be added in new PRs.**
cdc: reformat Changefeed config and Server config
ref: https://github.com/pingcap/docs/issues/19522 and …

cdc: reformat Changefeed config and Server config

---

releases/release-8.5.0.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19342

release-8.5.0.md: add the performance test section

---

sql-statements/sql-statement-flashback-cluster.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/18388

sql: Update sql-statement-flashback-cluster.md

---

information-schema/information-schema-tidb-index-usage.md

Previously, the table schema for `cluster_tidb_index_usage` is wrong 🤦 . It's caused by a careless copy-paste. Now it's modified to the correct table schema.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18525

fix the table schema for cluster_tidb_index_usage

---

sql-statements/sql-statement-show-builtins.md

- https://github.com/pingcap/docs/pull/19715
- https://github.com/pingcap/tidb/pull/51678
- https://github.com/pingcap/tidb/pull/58327
- https://github.com/pingcap/tidb/pull/58312

Update output of SHOW BUILTINS

---

tidb-cloud/v8.5-performance-benchmarking-with-sysbench.md

v8.5.0 lts-perftest: fix 8.5 update non-index test result

---

dynamic-config.md

v8.1.2: dynamic config add `import.num-threads`
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19318
- Other reference link(s): https://github.com/tikv/tikv/issues/17807

v8.1.2: dynamic config add `import.num-threads`

---

sql-statements/sql-statement-create-index.md
system-variables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19399
- Other reference link(s): https://github.com/pingcap/tidb/pull/52780

add `json_schema_valid` into `tidb_allow_function_for_expression_index`

---

schema-cache.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/19404

Update the limitations of schema-cache

---

pd-control.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19407

pd-control: update the section level of service-middleware configurations

---

pd-control.md

Move "config placement-rules [disable | enable | load | save | show | rule-group]" to the same level as its previous section

pd-control: update the section level of placement-rules configurations 

---

sql-statements/sql-statement-admin-alter-ddl.md
system-variables.md

v7.5.5: introduce tidb_ddl_reorg_max_write_speed
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19282

v7.5.5: introduce tidb_ddl_reorg_max_write_speed

---

clinic/clinic-introduction.md

update Clinic free period

---

hardware-and-software-requirements.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19445

v7.5.5: support Kylin SP3 (master branch)

---

hardware-and-software-requirements.md

v7.5.5: support Kylin SP3
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19444

v7.5.5: support Kylin SP3

---

tidb-binlog/tidb-binlog-configuration-file.md

Add descriptions of load schema snapshot
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/19421

Add descriptions of load schema snapshot

---

tidb-cloud/manage-user-access.md
tidb-cloud/sql-proxy-account.md
tidb-cloud/tidb-cloud-billing.md
tidb-cloud/tidb-cloud-budget.md
tidb-cloud/tidb-cloud-console-auditing.md
tidb-cloud/tidb-cloud-release-notes.md

cloud: refine roles in organizations and projects

---

templates/copyright.tex

update year to 2025 in copyright.tex

---

tikv-configuration-file.md

Update recent TiKV default configuration changes
* `enable-compaction-guard`: https://github.com/tikv/tikv/pull/14009
* `min-blob-size`:  https://github.com/tikv/tikv/pull/16402
* `target-file-size-base`: https://github.com/tikv/tikv/pull/14361
* `ribbon-filter-above-level`: https://github.com/tikv/tikv/pull/14527
* `write-buffer-limit`: https://github.com/tikv/tikv/pull/15453
* `ttl`/`periodic-compaction-seconds`: https://github.com/tikv/tikv/pull/14880
Touch: https://github.com/tikv/tikv/issues/18068
Touch: https://github.com/pingcap/docs-cn/pull/19422
By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, …

Update recent TiKV config changes

---

tidb-cloud/setup-self-hosted-kafka-private-link-service.md
tidb-cloud/setup-self-hosted-kafka-private-service-connect.md

cloud: fix Kafka download link

---

best-practices/tidb-best-practices.md
tidb-storage.md
tso.md

Fix Percolator URL

---

partitioned-table.md

partitioned-table: remove incorrect limitation

---

br/backup-and-restore-overview.md
releases/release-notes.md
releases/release-timeline.md
statistics.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/19536

br: add a note about backing up tables that are being restored

---

tidb-cloud/tidb-cloud-release-notes.md

cloud: add 20250114 release notes

---

TOC-tidb-cloud.md
tidb-cloud/connected-care-announcement.md

1. Adding FAQ on how to change support plan
2. Modify the title of the doc

Support Plan: minor changes for clarity 

---

system-variables.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/10354

clarify the time zone used for parsing tidb_auto_analyze_start_time

---

auto-increment.md
auto-random.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/19116

auto_increment: add steps and notices to auto_increment and auto_random 

---

.github/workflows/ja-full-translation-google.yaml

- add branch params for the ja translation ci

tweak(ci): ja translation

---

.github/workflows/cron.yml

- update the cron CI to support JA Docs translation for LTS & Cloud versions

tweak(ci): translation cron

---

information-schema/information-schema-data-lock-waits.md

remove unnecessary white space

---

tiup/tiup-component-cluster-check.md

- The status about CentOS 7 is not true (anymore)
- For SELinux it is not just a recommendation, it is required.

tiup-component-cluster-check: Update

---

tiup/tiup-component-cluster-clean.md
tiup/tiup-component-cluster-deploy.md
tiup/tiup-component-cluster-destroy.md
tiup/tiup-component-cluster-display.md
tiup/tiup-component-cluster-edit-config.md
tiup/tiup-component-cluster-list.md
tiup/tiup-component-cluster-patch.md
tiup/tiup-component-cluster-reload.md
tiup/tiup-component-cluster-rename.md
tiup/tiup-component-cluster-scale-out.md
tiup/tiup-component-cluster-start.md
tiup/tiup-component-cluster-stop.md
tiup/tiup-component-cluster-upgrade.md

TiUP: Link docs

---

geo-distributed-deployment-topology.md
hybrid-deployment-topology.md
minimal-deployment-topology.md
pd-microservices-deployment-topology.md
ticdc-deployment-topology.md
tiflash-deployment-topology.md
tiproxy/tiproxy-deployment-topology.md
tispark-deployment-topology.md

Resolves https://github.com/pingcap/docs/issues/20002: adds a note to clarify IP addresses in eight topology documents.
The added note is the same with that in [Quick Start with TiDB Self-Managed](https://docs.pingcap.com/tidb/stable/quick-start-with-tidb#prepare).

*: add a note to clarify IP addresses

---

temp.md
tiflash/tiflash-configuration.md

Adds two more TiFlash configuration items to doc
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19569

tiflash: add two more TiFlash config items

---

ticdc/ticdc-changefeed-config.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/19595

ticdc: add a deprecate warning to user doc

---

br/br-checkpoint-restore.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/19186

br: add checkpoint restore restriction

---

tidb-cloud/monitor-prometheus-and-grafana-integration-grafana-dashboard-UI.json

Update prometheus grafana integration dashboard

---

ticdc/ticdc-changefeed-config.md
ticdc/ticdc-sink-to-mysql.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/17052

ticdc: clarify that you don't escape the whole URL but just the parameters

---

tidb-cloud/tidb-cloud-release-notes.md

cloud: add release notes 20250121

---

dashboard/dashboard-ops-reverse-proxy.md
post-installation-check.md
production-deployment-using-tiup.md
quick-start-with-tidb.md
schedule-replicas-by-topology-labels.md
ticdc/deploy-ticdc.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/15664

tiup: add `--user`

---

temp.md
ticdc/ticdc-changefeed-config.md
ticdc/ticdc-ddl.md
ticdc/ticdc-overview.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19151

ticdc: update doc about ddl white list

---

faq/deploy-and-maintain-faq.md

faq: remove ansible related things

---

temp.md
ticdc/ticdc-changefeed-config.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19144

cdc: add description about support versions for redo log parameters

---

tidb-cloud/set-up-private-endpoint-connections.md

cloud: update AWS private endpoint steps

---

tidb-limitations.md

With default values
```
mysql-8.0.11-TiDB-v8.5.0> ALTER TABLE t1 ADD KEY (`c1`);
ERROR 1071 (42000): Specified key was too long (60000 bytes); max key length is 3072 bytes
```
With max-index-length increased
```
mysql-8.0.11-TiDB-v8.5.0> ALTER TABLE t1 ADD KEY (`c1`);
ERROR 1071 (42000): Specified key was too long (60000 bytes); max key length is 12288 bytes
```
For details, see [tips for choosing the affected versions](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md#guideline-for-choosing-t …

tidb-limitations: add index length limitation

---

TOC.md
_index.md
overview.md
quick-start-with-tidb.md

Update multiple terms for translated Japanese docs

Update multiple terms for ja docs

---

_index.md

Updates wording for product name.
This is a follow-up to https://github.com/pingcap/docs/pull/20150.

Update wording for product name

---

ticdc/ticdc-sink-to-kafka.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/14439

TiCDC: Add 3 kafka addresses and correct the names of parameters

---

sql-plan-replayer.md

This is translation of https://github.com/pingcap/docs-cn/pull/19715

Fix keywords orders

---

pd-configuration-file.md

Updates the default value of `read-base-cost` from 0.25 to 0.125 for v7.5 and later versions
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19721
- Other reference link(s): https://github.com/tikv/pd/blob/17f3ae3609fc50bae07e8783c0a373419b7daf9b/client/resource_group/controller/config.go#L66

pd: update the default value of read-base-cost

---

system-variables.md

Fix https://github.com/pingcap/docs/issues/19778

system-variables: add the experimental info for tidb_evolve_plan_baselines

---

sql-statements/sql-statement-create-table.md

Add syntax and description about `ENGINE_ATTRIBUTE` table option, to be consistent with TiDB. The `ENGINE_ATTRIBUTE` is added to TiDB by https://github.com/pingcap/tidb/pull/59201.
- Other reference link(s): https://github.com/pingcap/tidb/pull/59201

tidb: Add ENGINE_ATTRIBUTE table option

---

tidb-troubleshooting-map.md

Fix https://github.com/pingcap/docs/issues/20046

tidb-troubleshooting-map: fix a spelling mistake

---

tidb-lightning/tidb-lightning-configuration.md

lighting: reorder tidb.session-vars
Move the `tidb.session-vars` section after `[tidb.security]` for better organization
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19730

lighting: reorder tidb.session-vars

---

tidb-resource-control-ru-groups.md

Add URL aliases to handle redirects after `tidb-resource-control.md` was removed. Users who visit the old URL (`.../tidb-resource-control/`) will now be automatically redirected to the new location (`.../tidb-resource-control-ru-groups/`), preventing 404 errors.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19743
- …

 v8.5: add doc aliases to prevent 404 errors on tidb-resource-control page

---

tidb-resource-control-ru-groups.md

Add URL aliases to handle redirects after `tidb-resource-control.md` was removed. Users who visit the old URL (`.../tidb-resource-control/`) will now be automatically redirected to the new location (`.../tidb-resource-control-ru-groups/`), preventing 404 errors.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19742
- …

fix: add doc aliases to prevent 404 errors on tidb-resource-control page

---

ticdc/ticdc-ddl.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16856

ticdc: add event filter example

---

tiproxy/tiproxy-overview.md

close #20084
Add tiproxy topology definition to the usage section

tiproxy: add tiproxy topology definition to the usage section

---

ticdc/ticdc-faq.md

Make the explanation of safe-mode more understandable.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19785

ticdc: update "safe-mode" description

---

.github/workflows/media.yml

ci: sync media folder to cos

---

subquery-optimization.md

The correct symbol should be `>` instead of `<`.

doc: correct subquery optimization examples for clarity

---

tidb-lightning/tidb-lightning-configuration.md

update outdated link in tidb lightning configuration

---

tidb-cloud/set-up-private-endpoint-connections-serverless.md

- Other reference link(s): https://github.com/pingcap/docs/pull/20253

cloud: update the category type name for AWS endpoint creations

---

support.md

internals.tidb.io is now inaccessible.  The alternative option is https://github.com/orgs/pingcap/discussions. 

support: replace internals.tidb.io with discussions on GitHub

---

ticdc/ticdc-open-api-v2.md

There's a typo on the API intro. https://docs.pingcap.com/tidb/stable/ticdc-open-api-v2#examples 

Document bug: API command for changefeed (/api/v2/changefeed/test1/synced)

---

information-schema/information-schema-slow-query.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19848

Fix incorrect slow query table desc row count

---

tidb-configuration-file.md

tidb-configuration-file: Add like to Coprocessor Cache docs

---

mysql-compatibility.md

MySQL:
```
mysql-9.2.0> WITH a AS (SELECT 1 id), b AS (SELECT 1 id UNION ALL SELECT 2)
-> SELECT * FROM a JOIN b ON a.id=(SELECT id FROM b LIMIT 1);
+----+----+
| id | id |
+----+----+
|  1 |  1 |
|  1 |  2 |
+----+----+
2 rows in set (0.00 sec)
```
TiDB:
```
mysql-8.0.11-TiDB-v8.5.1> WITH a AS (SELECT 1 id), b AS (SELECT 1 id UNION ALL SELECT 2)
-> SELECT * FROM a JOIN b ON a.id=(SELECT id FROM b LIMIT 1);
ERROR 1105 (HY000): ON condition doesn't support subqueries yet
```
For details, see [tips for …

mysql-compatibility.md: Add note about JOIN on subquery

---

br/backup-and-restore-overview.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/19880

br: cluster in-place upgrade to v7.2.0 might encounter cross-version faulure.

---

system-variables.md

system-variables: fix a typo

---

br/use-br-command-line-tool.md
tidb-binlog/tidb-binlog-configuration-file.md
tidb-cloud/setup-self-hosted-kafka-private-link-service.md

 release-8.1: fix typo

---

generated-columns.md

generated columns: list disallowed functions 

---

tidb-cloud/import-sample-data-serverless.md
tidb-cloud/import-sample-data.md

cloud: update the titles of sample data import docs to clearly indicate which TiDB Cloud product each document relates to

cloud: update sample data import docs titles to clarify serverless and dedicated

---

TOC-tidb-cloud.md
develop/dev-guide-gui-datagrip.md
develop/dev-guide-gui-dbeaver.md
develop/dev-guide-gui-mysql-workbench.md
develop/dev-guide-gui-navicat.md
develop/dev-guide-gui-vscode-sqltools.md
develop/dev-guide-sample-application-golang-gorm.md
develop/dev-guide-sample-application-golang-sql-driver.md
develop/dev-guide-sample-application-java-hibernate.md
develop/dev-guide-sample-application-java-jdbc.md
develop/dev-guide-sample-application-java-mybatis.md
develop/dev-guide-sample-application-java-spring-boot.md
develop/dev-guide-sample-application-nodejs-mysql2.md
develop/dev-guide-sample-application-nodejs-mysqljs.md
develop/dev-guide-sample-application-nodejs-prisma.md
develop/dev-guide-sample-application-nodejs-sequelize.md
develop/dev-guide-sample-application-nodejs-typeorm.md
develop/dev-guide-sample-application-python-django.md
develop/dev-guide-sample-application-python-mysql-connector.md
develop/dev-guide-sample-application-python-mysqlclient.md
develop/dev-guide-sample-application-python-peewee.md
develop/dev-guide-sample-application-python-pymysql.md
develop/dev-guide-sample-application-python-sqlalchemy.md
develop/dev-guide-sample-application-ruby-mysql2.md
develop/dev-guide-sample-application-ruby-rails.md
tidb-cloud/serverless-export.md

cloud: update product name

---

scripts/report_md_files_not_in_toc.py

This PR adds a script to report .md files not in TOC.md and TOC-tidb-cloud.md. This helps us remove unused files if necesary. 

chore: add a script to report .md files not in TOC.md and TOC-tidb-cloud.md

---

tidb-cloud/v8.5-performance-highlights.md

Update Cloud:v8.5-performance-highlights.md with suggestion 

---

tiflash/tiflash-configuration.md

tiflash: reformat TiFlash config file
ref: https://github.com/pingcap/docs/issues/19524
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19168

tiflash: reformat TiFlash config file

---

TOC-tidb-cloud.md
sql-statements/sql-statement-overview.md

sql-statement-overview.md: add four SQL statements 

---

tiflash/tiflash-configuration.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19929

tiflash: update config max_threads and task_scheduler_active_set_soft_limit

---

dm/dm-master-configuration-file.md
dm/dm-source-configuration-file.md
dm/dm-worker-configuration-file.md
dm/task-configuration-file-full.md

dm: reformat DM config
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19879

dm: reformat DM config

---

sql-statements/sql-statement-admin-pause-ddl.md
sql-statements/sql-statement-admin-resume-ddl.md
sql-statements/sql-statement-admin-show-ddl.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19891

refine admin related docs

---

production-deployment-using-tiup.md
temp.md

Adds a TiUP note to production deployment, to make it clear and avoid user confusion
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19943

Add a TiUP note to production deployment

---

tidb-cloud/branch-github-integration.md
tidb-cloud/migrate-from-mysql-using-data-migration.md
tidb-monitoring-api.md
tiproxy/tiproxy-load-balance.md
tiproxy/tiproxy-overview.md
tiproxy/tiproxy-traffic-replay.md

update media resource links to point to new locations

---

tidb-cloud/branch-github-integration.md
tidb-cloud/migrate-from-mysql-using-data-migration.md
tidb-monitoring-api.md
tiproxy/tiproxy-overview.md

ja (v8.1): update media resource links to point to new locations

---

tidb-cloud/branch-github-integration.md
tidb-cloud/migrate-from-mysql-using-data-migration.md
tidb-monitoring-api.md
tiproxy/tiproxy-load-balance.md
tiproxy/tiproxy-overview.md
tiproxy/tiproxy-traffic-replay.md

i18n(v8.5): update media resource links to point to new locations

---

migration-tools.md

migration-tools: update the descriptions for Dumpling

---

TOC-tidb-cloud.md
tidb-cloud/connected-ai-chat-in-im.md
tidb-cloud/connected-lark-ticket-creation.md
tidb-cloud/connected-lark-ticket-interaction.md
tidb-cloud/connected-slack-ticket-creation.md
tidb-cloud/connected-slack-ticket-interaction.md

cloud: remove the beta info for IM via Lark

---

temp.md
tikv-configuration-file.md
tikv-in-memory-engine.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19968

add the memory requirements for TiKV IME

---

tidb-cloud/serverless-limitations.md

As we offered the enhanced encryption for serverless Scalable Cluster, we can change the document in limitations page about it. 

Refresh the state of Encryption at Rest in serverless limitations

---

sql-statements/sql-statement-create-table.md

sql-statements: expand DefaultValueExpr defination

---

benchmark/benchmark-sysbench-v6.0.0-vs-v5.4.0.md
benchmark/benchmark-sysbench-v6.1.0-vs-v6.0.0.md
benchmark/v6.0-performance-benchmarking-with-tpcc.md
benchmark/v6.0-performance-benchmarking-with-tpch.md
benchmark/v6.1-performance-benchmarking-with-tpcc.md
benchmark/v6.1-performance-benchmarking-with-tpch.md

This PR adds aliases for the following stale benchmark docs removed in https://github.com/pingcap/docs/pull/20462.
- ./benchmark/benchmark-sysbench-v6.0.0-vs-v5.4.0.md
- ./benchmark/benchmark-sysbench-v6.1.0-vs-v6.0.0.md
- ./benchmark/v6.0-performance-benchmarking-with-tpcc.md
- ./benchmark/v6.0-performance-benchmarking-with-tpch.md
- ./benchmark/v6.1-performance-benchmarking-with-tpcc.md
- ./benchmark/v6.1-performance-benchmarking-with-tpch.md …

v6.1: add aliases for stale benchmark docs

---

benchmark/benchmark-sysbench-v2.md
benchmark/benchmark-sysbench-v3.md
benchmark/benchmark-sysbench-v4-vs-v3.md
benchmark/benchmark-sysbench-v5-vs-v4.md
benchmark/benchmark-sysbench-v5.1.0-vs-v5.0.2.md
benchmark/benchmark-sysbench-v5.2.0-vs-v5.1.1.md
benchmark/benchmark-sysbench-v5.3.0-vs-v5.2.2.md
benchmark/benchmark-sysbench-v5.4.0-vs-v5.3.0.md
benchmark/benchmark-tpch.md
benchmark/v3.0-performance-benchmarking-with-sysbench.md
benchmark/v3.0-performance-benchmarking-with-tpcc.md
benchmark/v4.0-performance-benchmarking-with-tpcc.md
benchmark/v4.0-performance-benchmarking-with-tpch.md
benchmark/v5.0-performance-benchmarking-with-tpcc.md
benchmark/v5.1-performance-benchmarking-with-tpcc.md
benchmark/v5.2-performance-benchmarking-with-tpcc.md
benchmark/v5.3-performance-benchmarking-with-tpcc.md
benchmark/v5.4-performance-benchmarking-with-tpcc.md
benchmark/v5.4-performance-benchmarking-with-tpch.md

This PR adds aliases for the following stale benchmark docs removed in https://github.com/pingcap/docs/pull/20462.
- ./benchmark/benchmark-sysbench-v2.md
- ./benchmark/benchmark-sysbench-v3.md
- ./benchmark/benchmark-sysbench-v4-vs-v3.md
- ./benchmark/benchmark-sysbench-v5-vs-v4.md
- ./benchmark/benchmark-sysbench-v5.1.0-vs-v5.0.2.md
- ./benchmark/benchmark-sysbench-v5.2.0-vs-v5.1.1.md
- ./benchmark/benchmark-sysbench-v5.3.0-vs-v5.2.2.md
- ./benchmark/benchmark-sysbench-v5.4.0-vs-v5.3.0.md
- ./benchmark/benchmark-tpch.md
- ./benchmark/v3.0-performance-benchmarking-with-sysbench.md
- ./benchmark/v3.0-performance-benchmarking-with-tpcc.md
- ./benchmark/v4.0-performance-benchmarking-with-tpcc.md
- ./benchmark/v4.0-performance-benchmarking-with-tpch.md
- …

v5.4: add aliases for stale benchmark docs

---

tiup/tiup-cluster-no-sudo-mode.md

1. Add hint about `ssh-copy-id`
2. Use a variable for the user id in the systemctl command
3. Add a note about the `tar` package
4. *important*: replace the description for fixing things with a reference. The description contained changes like changing THP and disabling swap that were done in a way that is not persistent across reboots, basically boobytrapping the setup.
For details, see [tips for choosing the affected versions](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md#guideline-for-c …

tiup: Update/fix no sudo mode docs

---

hardware-and-software-requirements.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/20021
- Other reference link(s):https://github.com/pingcap/docs/pull/20463

add openEuler 22.03 LTS SP3/SP4

---

tidb-cloud/config-s3-and-gcs-access.md
tidb-cloud/serverless-external-storage.md

cloud: use sections instead of tabs for S3 configuration instructions

---

tidb-cloud/backup-and-restore.md

cloud: clarify the retention policy for manual backups

---

transaction-isolation-levels.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/20048

Add a section to change isolation level in transaction-isolation-levels.md

---

keywords.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/19941

tidb_enable_window_function can control the keyword list

---

system-variables.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/20042

sys var: clarify the description of tidb_ddl_reorg_max_write_speed

---

tiflash/tiflash-supported-pushdown-calculations.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19845

Support pushdown to tiflash for some aggregation functions

---

tidb-cloud/tidb-node-group-management.md
tidb-cloud/tidb-node-group-overview.md

tidb node group support gcp

---

tidb-cloud/tidb-cloud-release-notes.md

cloud: add 20250318 release notes

---

tiflash/tiflash-configuration.md

We found that the tiflash-learner config param "raftstore.store-batch-retry-recv-timeout" has been removed during the code refactor since v5.4. But the doc is not updated.
tiflash-proxy for release-5.3
https://github.com/pingcap/tidb-engine-ext/blob/a80f64730d66da71f98e1f83534ce79ea6779ea4/components/raftstore/src/store/config.rs#L203-L204
tiflash-proxy for release-5.4
https://github.com/pingcap/tidb-engine-ext/blob/c15322fd615c518b0fa2d2204dbdf32dd0b4cfdf/components/raftstore/src/store/config.rs
For …

Remove deleted tiflash param "raftstore.store-batch-retry-recv-timeout"

---

ticdc/ticdc-simple-protocol.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19248

cdc: add release version for the simple protocol

---

br/backup-and-restore-overview.md

Add compatibility-related information to the "Before you use" section of BR docs to help users understand tool limitations and requirements.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19262

br: add compatibility notes to the Before you use section

---

tidb-configuration-file.md

Improve the description of system variables related to TLS between components.
Improve the description of TLS configuration parameters between components.

Improve the description of TLS configuration parameters between components

---

tidb-cloud/monitor-alert-email.md
tidb-cloud/monitor-alert-slack.md
tidb-cloud/monitor-alert-zoom.md
tidb-cloud/tidb-cloud-clinic.md

connected-care: add some notes

---

tidb-cloud/_index.md

This PRs updates links and topics in the `tidb-cloud/_index.md` file.

cloud: update topics and links on index.md learning path

---

accelerated-table-creation.md
migration-overview.md
sql-statements/sql-statement-show-stats-histograms.md
telemetry.md
tidb-cloud/_index.md
tidb-cloud/backup-and-restore-serverless.md
tidb-cloud/connected-care-overview.md
tidb-cloud/secure-connections-to-serverless-clusters.md
tidb-cloud/select-cluster-tier.md
tidb-cloud/serverless-driver.md
tidb-cloud/serverless-faqs.md
tidb-cloud/serverless-limitations.md
tidb-cloud/ticloud-branch-shell.md
tidb-cloud/ticloud-import-start.md
tidb-cloud/ticloud-serverless-region.md
tidb-cloud/ticloud-serverless-shell.md
tidb-cloud/ticloud-upgrade.md
tidb-cloud/tidb-cloud-glossary.md
tidb-cloud/tidb-cloud-htap-quickstart.md
tidb-cloud/tidb-cloud-migration-overview.md
tidb-cloud/tidb-cloud-partners.md
tidb-cloud/tidb-cloud-release-notes.md

release-cloud: remove aliases

---

tikv-configuration-file.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/19999

tikv: add missing tikv configs

---

.github/workflows/dispatch-tidbcloud.yml

ci: dispatch tidbcloud update

---

tidb-limitations.md

Add the limitation of Indexes
Update tidb limitations of Index
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/20105

Update tidb limitations of Index

---

temp.md
tikv-configuration-file.md

Doc of 3 TiKV config items, introduced in https://github.com/tikv/tikv/pull/17917
https://github.com/tikv/tikv/issues/17916
https://github.com/tikv/tikv/pull/17917
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19380

doc: configs of max-ts checker

---

TOC-tidb-cloud.md
tidb-cloud/vector-search-integrate-with-amazon-bedrock.md
tidb-cloud/vector-search-integration-overview.md

This PR adds the integration doc for Amazon Bedrock according to https://www.pingcap.com/blog/building-generative-ai-applications-with-tidb-and-amazon-bedrock/. 

cloud: support Amazon Bedrock integration

---

tidb-cloud/tidb-cloud-release-notes.md

cloud: add 20250326 release notes

---

system-variables.md
temp.md

- update the default value to ON (pd_enable_follower_handle_region)
- apply pd_enable_follower_handle_region to BR/Lightning
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/20000
- Other reference link(s): https://github.com/pingcap/tidb/issues/58651, https://github.com/pingcap/tidb/issues/58384

Update the default value of `pd_enable_follower_handle_region` to ON

---

tidb-cloud/serverless-external-storage.md

ADD `Configure Alibaba Cloud Object Storage Service (OSS) access`

---

encryption-at-rest.md
temp.md

Clarify outdated TiKV SM4 encryption descriptions
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/20126

Clarify TiKV SM4 encryption descriptions

---

tidb-cloud/serverless-driver-kysely-example.md

release-cloud: fix build error

---

pd-microservices.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/19744

pd-microservices GA

---

tidb-cloud/backup-and-restore-serverless.md

AliCloud BR doc optimize

---

tidb-cloud/import-sample-data-serverless.md

delete Import Sample Data from GCS

---

tidb-cloud/import-sample-data-serverless.md

cloud: remove SimpleTab for import-sample-data-serverless.md

---

br/br-pitr-guide.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/20049

log-backup: added an explaination to the log status

---

.github/workflows/doc_review.yml
doc-review-prompt.txt

This PR adds doc_review.yml to trigger AI doc review on PRs and doc-review-prompt.txt to provide a custom prompt.

workflow: add doc_review.yml

---

TOC.md
br/backup-and-restore-overview.md
tidb-upgrade-migration-guide.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/20136

add tidb-upgrade-migration-guide

---

tidb-cloud/release-notes-2022.md
tidb-cloud/size-your-cluster.md
tidb-cloud/tidb-node-group-management.md

cloud: add TiKV node storage types and Note Group GA

---

tidb-cloud/tidb-cloud-release-notes.md

cloud: add 20250401 release note

---

check-before-deployment.md

In case `tiup cluster check` output looks like this:
```
192.168.122.166  chrony        Fail    time offset 3599859.863281ms too high
```
https://chrony-project.org/doc/4.3/chronyc.html#makestep

Chronyc makestep

---

doc-review-prompt.txt
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/20152

doc-review-prompt: add two new guidelines

---

br/backup-and-restore-tool.md
temp.md

This PR updates "BR nightly" with the specific BR version to avoid user confusion. 
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/20156

v5.4: update the BR compatibility info

---

tidb-cloud/ticloud-serverless-shell.md

fix a sample in ticloud shell

---

tidb-cloud/ticloud-branch-create.md
tidb-cloud/ticloud-branch-delete.md
tidb-cloud/ticloud-branch-describe.md
tidb-cloud/ticloud-branch-list.md
tidb-cloud/ticloud-branch-shell.md
tidb-cloud/ticloud-cluster-create.md
tidb-cloud/ticloud-cluster-delete.md
tidb-cloud/ticloud-cluster-describe.md
tidb-cloud/ticloud-cluster-list.md
tidb-cloud/ticloud-serverless-capacity.md
tidb-cloud/ticloud-serverless-export-create.md
tidb-cloud/ticloud-serverless-export-describe.md
tidb-cloud/ticloud-serverless-export-download.md
tidb-cloud/ticloud-serverless-export-list.md
tidb-cloud/ticloud-serverless-region.md
tidb-cloud/ticloud-serverless-shell.md
tidb-cloud/ticloud-serverless-sql-user-create.md
tidb-cloud/ticloud-serverless-sql-user-delete.md
tidb-cloud/ticloud-serverless-sql-user-list.md
tidb-cloud/ticloud-serverless-sql-user-update.md
tidb-cloud/ticloud-serverless-update.md

fix ticloud plan description on tidb.io

---

br/br-checkpoint-restore.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19907

br: provide a storage target option for BR restore checkpoint data

---

ticdc/ticdc-sink-to-cloud-storage.md

The previous notes regarding the table version were incomplete, this PR provides the necessary additions.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/20163

ticdc: add detailed notes for table version

---

optimizer-fix-controls.md

update release for fix control 54337 to 8.3

---

ticdc/ticdc-manage-changefeed.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/20191

ticdc: use `cdc cli changefeed list` to check `checkpoint-ts`

---

TOC-tidb-cloud.md
tidb-cloud/import-csv-files-serverless.md
tidb-cloud/import-parquet-files-serverless.md
tidb-cloud/serverless-external-storage.md

Add import from Alibaba Cloud Object Storage Service

---

tidb-cloud/tidb-cloud-release-notes.md

cloud: add 20250415 release notes

---

best-practices/java-app-best-practices.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/20165

best practices: refine java connection pools

---

releases/release-6.0.0-dmr.md

…lues for system variables"
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/20208

v6.0.0 release notes: update the description of "setting incorrect values for system variables"

---

basic-features.md

fix typo "Vectort types"

---

dashboard/dashboard-diagnostics-report.md

dashboard: fix typo from "exit" to "exist"

---

.github/workflows/doc_review.yml

This PR updates the AI model used for doc review from gpt-4 to gpt-4o as gpt-4 will soon phase out according to https://help.openai.com/en/articles/6825453-chatgpt-release-notes#h_cbb2e4f019.

doc_review.yml: update the AI model

---

TOC-tidb-cloud.md
_docHome.md
tidb-cloud/tidb-cloud-roadmap.md

cloud: remove outdated cloud roadmap

---

keywords.md

v6.5: update keywords according to parser.y
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/20226

v6.5: update keywords according to parser.y

---

.gemini/config.yaml
.gemini/styleguide.md

chore: configure gemini bot for doc review 

---

vector-search/vector-search-index.md

This PR adds the attribution for KNN vector search description.
- Other reference link(s): https://github.com/pingcap/docs/commit/d82307c9bdf10d9ab32d1f23cc02f4f8015e315c#diff-3e844b465efe16415106d9387d4a78a425ee821da4866da5e2021e7007eedd01

docs: add attribution for KNN vector search description

---

character-set-and-collation.md
character-set-gbk.md
sql-statements/sql-statement-show-character-set.md

update the default collation of GBK from gbk_bin to gbk_chinese_ci
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/20234

update the default collation of GBK from gbk_bin to gbk_chinese_ci

---

tidb-cloud/serverless-export.md
tidb-cloud/serverless-external-storage.md

Serverless Export support OSS

---

releases/release-8.5.1.md

release notes: fix version in links

---

tidb-cloud/tidb-cloud-release-notes.md

cloud: add 20250422 release notes

---

sql-statements/sql-statement-cancel-import-job.md
sql-statements/sql-statement-import-into.md
sql-statements/sql-statement-show-import-job.md

serverless support import into

---

tidb-cloud/data-service-get-started.md
tidb-cloud/explore-data-with-chat2query.md
tidb-cloud/tidb-cloud-quickstart.md

Update tidb-cloud-quickstart.md for AI service provider name

---

releases/release-8.1.2.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/20268

releases: add one br entry to v8.1.2

---

faq/sql-faq.md
temp.md

This PR updates `defaultfetchsize` to `defaultFetchSize`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/20288

JDBC URL: update the letter case for defaultFetchSize

---

TOC-tidb-cloud.md
tidb-cloud/create-tidb-cluster.md
tidb-cloud/release-notes-2022.md
tidb-cloud/tidb-cloud-billing.md

Update billing info for Azure Marketplace

---

ticdc/ticdc-ddl.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/20319

ticdc: add [[filter.event-filters]] to the toml example

---

tidb-cloud/vector-search-full-text-search-python.md
tidb-cloud/vector-search-hybrid-search.md

cloud: minor wording changes for full-text search docs

---

br/backup-and-restore-overview.md

br: clarify PITR restrictions

---

tidb-cloud/tidb-cloud-faq.md

tidb-cloud: explain beta

---

tidb-cloud/configure-maintenance-window.md

Maintenace window 2.0 short

---

tidb-cloud/size-your-cluster.md

cloud: add Performance and Plus storage

---

tidb-cloud/size-your-cluster.md

cloud: update TiFlash node storage

---

scripts/concatMdByToc.js
scripts/merge_by_toc.py

Enhance markdown processing: add variable replacement and custom ID anchors in concatMdByToc.js; implement similar functionality in merge_by_toc.py

ci: improve pdf with variables & custom header id

---

ticdc/ticdc-debezium.md
workload-repository.md

*: update wording and format

---

ticdc/ticdc-debezium.md

Corrects the heading level for the "Key format" section from H3 to H4 in [TiCDC Debezium Protocol | TiDB Docs](https://docs.pingcap.com/tidb/stable/ticdc-debezium/)

ticdc: fix heading level

---

tidb-cloud/scale-tidb-cluster.md

cloud: add a note before changing vCPU

---

basic-features.md

basic-features: fix table formatting issue

---

tidb-cloud/vector-search-full-text-search-python.md
tidb-cloud/vector-search-full-text-search-sql.md
tidb-cloud/vector-search-hybrid-search.md

Add APSE1 to the available regions.

fts: Add APSE1

---

tiup/tiup-component-cluster-meta-backup.md

Correct the link of checking clusters using TiUP, introduced in https://github.com/pingcap/docs/pull/11743. The link is correct in [the Chinese document](https://docs.pingcap.com/zh/tidb/stable/tiup-component-cluster-meta-backup/).

tiup: correct the link of checking clusters

---

tidb-cloud/tidb-node-group-overview.md

cloud: add limitations for TiDB Node Group

---

dashboard/dashboard-resource-manager.md

Description of "Total RU of user resource groups" should say "more than" and not "less than"

Correct the description of "Total RU of user resource groups"

---

tidb-cloud/import-sample-data-serverless.md

cloud: update one step in import-sample-data-serverless.md

---

tiproxy/tiproxy-overview.md
tiproxy/tiproxy-performance-test.md

The current performance description sounds scarier than it is. I need to make users comfortable.

tiproxy: rephrase TiProxy performance to make it comfortable

---

system-variables.md

Improves wording in system variables

Improve wording in system variables

---

identify-slow-queries.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/20365

slow-queries: fix inccorect descriptions about `Rocksdb_delete_skipped_count` and `Rocksdb_key_skipped_count`

---

tidb-cloud/manage-user-access.md

cloud: correct the permission for password updates

---

tidb-cloud/tidb-cloud-clinic.md

add metrics dashboard lists of cloud clinic

---

storage-engine/rocksdb-overview.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/20336

tikv: fix the description of write cf short value length

---

tidb-cloud/tidb-cloud-glossary.md

- Other reference link(s):https://github.com/pingcap/docs-cn/issues/20341

cloud: add Full-Text Search in tidb-cloud-glossary

---

TOC.md
best-practices/saas-best-practices.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/20396

update title of saas multi-tenant scenarios best practices

---

tidb-cloud/tidb-cloud-release-notes.md

cloud: add 20250527 release notes

cloud: add 20250527 release notes

---

tidb-cloud/architecture-concepts.md
tidb-cloud/backup-and-restore.md
tidb-cloud/create-tidb-cluster-serverless.md
tidb-cloud/scale-tidb-cluster.md
tidb-cloud/security-concepts.md
tidb-cloud/set-up-vpc-peering-connections.md
tidb-cloud/tidb-cloud-console-auditing.md
tidb-cloud/tidb-cloud-encrypt-cmek.md
tidb-cloud/tidb-cloud-faq.md
tidb-cloud/tidb-cloud-intro.md
tidb-cloud/tidb-cloud-poc.md

cloud: add azure to generic docs

---

statement-summary-tables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/20453
- Other reference link(s):https://github.com/pingcap/docs/pull/18801

Add avg_tidb_cpu_time/avg_tikv_cpu_time for statements summary

---

keywords.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/20458
- https://github.com/pingcap/docs/pull/18493
- https://github.com/pingcap/docs/pull/12510
- https://github.com/pingcap/tidb/commit/c307c0dab5165976ce4694f303dc0851976a7f14#diff-28c98b105c2d87f58bd43aa5f34279eab9b450e359ccf41d50df9713a6a0354 …

delete description about special non-reserved keywords that might still require special treatment

---

maintain-tidb-using-tiup.md

Fix a typo about the data source of Grafana
**Note:** The fix has been involved in https://github.com/pingcap/docs/pull/21142 for the `release-8.5` branch.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/20479

Fix a typo about data source

---

tidb-cloud/tidb-cloud-billing.md

Update notes for
* Some features are in beta mode, therefore they are free of charge for now.
* If customer wants other region, please contact us.

Mention some features are free of charge right now

---

TOC.md
releases/release-8.5.2.md
releases/release-notes.md
releases/release-timeline.md

Reverts pingcap/docs#21123
Translation from https://github.com/pingcap/docs-cn/pull/20498

Revert "Revert "Add TiDB 8.5.2 Release Notes" (#21122)"

---

tidb-resource-control-runaway-queries.md

fix: change SIMILAR pattern matching description to use correct "SQL Digest" terminology instead of "Plan Digest"

fix: change SIMILAR pattern matching description to use correct "SQL Digest" terminology instead of "Plan Digest"

---

sync-diff-inspector/sync-diff-inspector-overview.md

close https://github.com/pingcap/docs/issues/21157
`SHOW DATABASES` privilege is not needed for sync-diff-inspector, and it may cause the data check failed for later version of MySQL.
See https://github.com/pingcap/docs/issues/21157 for more detail.

sync-diff-inspector: update required privilege for sync-diff-inspector

---

tidb-cloud/migrate-from-mysql-using-data-migration.md

This PR corrects the required source database privileges for TiDB Cloud Data Migration in the `migrate-from-mysql-using-data-migration.md` document.
- Internal Ticket: TCOC-3727

Correct the privileges of TiDB Cloud DM

---

tidb-cloud/size-your-cluster.md

offline tikv 6tb disk

---

releases/release-8.5.2.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/20522

remove loong64 arch in release notes v8.5.2

---

tiproxy/tiproxy-configuration.md

Now that a cluster supports multiple virtual IPs, the original description `The virtual IP and the IPs of all TiProxy instances must be within the same CIDR range` is confusing.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/20524

tiproxy: update vip description about CIDR

---

sql-statements/sql-statement-add-index.md
temp.md

Updates add index grammar ebnf
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/20527

sql: update add index grammar ebnf

---

tiproxy/tiproxy-load-balance.md

Revert "tiproxy: fix image link in tiproxy-load-balance.md"

---

storage-engine/titan-configuration.md
temp.md
tikv-configuration-file.md

This PR updates release-8.1 docs according to https://github.com/pingcap/docs-cn/pull/20304. 
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/20526

titan-configuration: remove the unrecommended steps of updating TiKV configuration 

---

tidb-cloud/tidb-cloud-release-notes.md

tidb cloud: add release notes 20250624

---

develop/dev-guide-bookshop-schema-design.md
develop/dev-guide-insert-data.md
tidb-cloud/csv-config-for-import-data.md
tidb-cloud/import-csv-files-serverless.md
tidb-cloud/import-parquet-files-serverless.md
tidb-cloud/import-sample-data-serverless.md
tidb-cloud/import-snapshot-files.md
tidb-cloud/migrate-sql-shards.md
tidb-cloud/tidb-cloud-migration-overview.md

As in the tile, update the titles for the CSV and parquet file import related docs to make them more generic. 
- Other reference link(s): https://github.com/pingcap/docs/pull/20992

release-cloud: update the titles for the CSV and parquet file import related docs

---

develop/dev-guide-third-party-support.md

feat: add navicat into the supported gui part

---

config-templates/simple-tiproxy.yaml
tiproxy/tiproxy-load-balance.md
tiproxy/tiproxy-overview.md

TiProxy needs around 3s to detect TiDB gracefully shutting down and 5s to start migrating the last connection, so it will take another 10s to migrate the connections.
We should recommend a longer graceful-wait-before-shutdown.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/20525

tiproxy: update the recommended graceful-wait-before-shutdown

---

tidb-cloud/dedicated-external-storage.md

rm GetBucketLocation priviledge for dedicated import

---

br/br-log-architecture.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/20577

br: `{checkpoint_ts}-{uuid}.meta` should be `{resolved_ts}-{uuid}.meta`

---

scripts/concatMdByToc.js
scripts/merge_by_toc.py

release-8.1: add variable replacement and custom ID handling in concatMdByToc.js and merge_by_toc.py

---

tiproxy/tiproxy-configuration.md
tiproxy/tiproxy-load-balance.md

According to the feedback from the business team, deploying one TiProxy for each group in a label-based load balance doesn't make sense. To enable label-based load balance, multiple VIP must be supported, so I backported multiple VIP into v.1.3.1.
Most words are the same as the master branch. I added the claim of v1.3.1.
- This PR is …

tiproxy: add multi-vip support to v1.3.1

---

.github/workflows/translation-cron.yml
.github/workflows/translation-zh.yaml
scripts/filterUpdateFiles.js

Update translation workflows and enhance file handling in filterUpdateFiles.js

ci: Update translation workflows and enhance file handling in filterUpdateFiles.js

---

.github/workflows/translation-zh.yaml
scripts/filterUpdateCloudFiles.js

ci: fix translation workflow

---

.github/workflows/translation-cron.yml

update translation workflow to use 'master' branch instead of 'main'

ci: update translation workflow to use 'master' branch instead of 'main'

---

pd-control.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/20642
- Other reference link(s): https://github.com/pingcap/docs-cn/issues/20641

pd-ctl: add notice for `member delete`

---

tidb-cloud/limited-sql-features.md

release-cloud: Update limited sql features for TiDB Cloud Starter

---

TOC-tidb-cloud.md
functions-and-operators/json-functions/json-functions-validate.md
index-advisor.md
schema-cache.md
sql-statements/sql-statement-admin-alter-ddl.md
tidb-cloud/database-schema-concepts.md
tidb-cloud/vector-search-changelogs.md
tidb-cloud/vector-search-integrate-with-amazon-bedrock.md
tidb-resource-control-background-tasks.md
tidb-resource-control-runaway-queries.md
vector-search/vector-search-data-types.md
vector-search/vector-search-functions-and-operators.md
vector-search/vector-search-get-started-using-python.md
vector-search/vector-search-get-started-using-sql.md
vector-search/vector-search-improve-performance.md
vector-search/vector-search-index.md
vector-search/vector-search-integrate-with-django-orm.md
vector-search/vector-search-integrate-with-jinaai-embedding.md
vector-search/vector-search-integrate-with-langchain.md
vector-search/vector-search-integrate-with-llamaindex.md
vector-search/vector-search-integrate-with-peewee.md
vector-search/vector-search-integrate-with-sqlalchemy.md
vector-search/vector-search-integration-overview.md
vector-search/vector-search-limitations.md
vector-search/vector-search-overview.md

This PR updates release-8.5 docs to support TiDB Cloud Dedicated as the default version of new TiDB Cloud Dedicated clusters will be upgraded to v8.5.2.

release-8.5: support TiDB Cloud Dedicated 

---

tidb-cloud/tidb-cloud-console-auditing.md

cloud: add backup completed auditing event

---

.github/workflows/translation-cron.yml
.github/workflows/translation-zh-switch.yaml
scripts/filterUpdateFiles.js

- update the cloud doc branch for ZH and JA translation
- support zh translation switch workflow

ci: update the cloud doc branch for ZH and JA translation & support zh translation switch workflow

---

br/backup-and-restore-use-cases.md

This PR adds an v6.1 alias to `br/backup-and-restore-use-cases.md`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/20673

v6.5 br: add an v6.1 alias to br use cases

---

br/backup-storage-S3.md

A notice was added at the top of the S3 backup storage guide to direct users to the TiDB v7.5 backup and restore use cases documentation.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/20671

v6.1-br: add tip linking to v7.5 BR doc

---

br/backup-and-restore-use-cases.md

Revert "v6.5 br: add an v6.1 alias to br use cases"

---

.github/pull_request_template.md
CONTRIBUTING.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/20678

fix: update CLA link to correct URL

---

tidb-cloud/tidb-cloud-faq.md
tidb-cloud/tidb-cloud-release-notes.md

- Updates outdated TiDB version info in `tidb-cloud/tidb-cloud-faq.md`
- Adds a missing release note about upgrading the TiDB version of Serverless

tidb-cloud: update TiDB versions in FAQ and add version upgrade for serverless

---

temp.md
tidb-configuration-file.md

As stated in the title
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/20689

overload-threshold: update the description of its effective scope

---

tidb-cloud/tidb-cloud-quickstart.md

- Removes outdated description about the "Getting Started" page in the TiDB Cloud console.
> [!NOTE]
> This PR doesn't remove the description in https://docs.pingcap.com/tidbcloud/release-notes-2023/#april-4-2023 when the "Getting Started" page was introduced. Just keep it in release notes. …

tidb-cloud: remove outdated getting started page info

---

develop/dev-guide-sample-application-python-peewee.md

This PR removes an unnecessary space from develop/dev-guide-sample-application-python-peewee.md (including {{{.console-url}}} in Line 70) to test whether the new configurations of variables takes effect now.

release-cloud: test variables

---

tidb-cloud/tidb-cloud-release-notes.md

cloud: minor format changes in release notes

---

tidb-cloud/tidb-cloud-billing.md

- Revised compute and storage pricing for the Singapore region, including new rates for enhanced encryption at rest.
- Updated compute unit to 'per 1 million RUs' and adjusted storage prices accordingly.

release-cloud: update Alibaba Cloud essential pricing details

---

tidb-cloud/cli-reference.md

This PR updates the note in the TiDB Cloud CLI reference doc to clarify that TiDB Cloud CLI is not applicable to TiDB Cloud Dedicated clusters.

cloud: clarify the support of TiDB Cloud CLI on TiDB Cloud Dedicated

---

TOC-tidb-cloud.md
tidb-cloud/architecture-concepts.md
tidb-cloud/create-tidb-cluster-serverless.md
tidb-cloud/select-cluster-tier.md
tidb-cloud/tidb-cloud-glossary.md
tidb-cloud/tidb-cloud-intro.md

This PR updates the usage of "tier" in TiDB Cloud docs to align with UI.

release cloud: use "plan" instead of "tier"

---

maintain-tidb-using-tiup.md

Removed VictoriaMetrics guide from `release-8.5` for now, and will add it back after [TiUP](https://github.com/pingcap/tiup/releases) v1.16.3 is released.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/20731
- Other reference link(s): https://github.com/pingcap/docs/pull/20957

v8.5: remove VictoriaMetrics guide

---

latest_translation_commit.json

i18n(ja-8.5): Update latest_translation_commit.json

---

tiup/tiup-bench.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/20743

tiup: clarify `tiup bench` command

---

basic-features.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/20755

basic-features: remove EOL versions including v5.1, v5.2, and v5.3

---

TOC-tidb-cloud-starter.md
tidb-cloud/create-tidb-cluster-serverless.md
tidb-cloud/tidb-cloud-glossary.md

This PR updates the usage of "tier" in TiDB Cloud docs to align with UI.
- Other reference link(s): https://github.com/pingcap/docs/pull/21536

release-8.5: use "plan" instead of "tier"

---

best-practices/java-app-best-practices.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/20771

best-practices: fix incorrect default value of `wait_timeout`

---

certificate-authentication.md
pd-control.md
performance-schema/performance-schema-session-connect-attrs.md
upgrade-tidb-using-tiup.md

Replaced references to version 8.5.1 with 8.5.3 in certificate authentication, PD control, performance schema, and upgrade guide documents to reflect the latest release.
- #19988, #20086
- #21578

release-8.5: update version to 8.5.3

---

temp.md
tiflash/tiflash-configuration.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/20347

tiflash: add config of enable_version_chain

---

tiflash-upgrade-guide.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/20787

tiflash: Update tiflash upgrade guide

---

.github/workflows/translation-cron.yml
.github/workflows/translation-zh.yaml

fix: copy vars to translator and docs folder

---

tidb-cloud/tidb-cloud-console-auditing.md

adding a new event into audit log

---

temp.md
ticdc/ticdc-faq.md
ticdc/ticdc-sink-to-kafka.md

Added a new FAQ for TiCDC Kafka synchronization scenarios. It explains that a short Kafka idle connection timeout may cause changefeed failures, and suggests adjusting the configuration to avoid the issue. It also clarifies that the problem does not affect continued operation, and only causes a brief lag spike during changefeed restarts. …

cdc: add solution for kafka broken pipe error

---

system-variables.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/20334

sys var: consider global sort for `tidb_ddl_reorg_max_write_speed`

---

TOC.md
tiup/tiup-component-cluster-tls.md
tiup/tiup-component-cluster-upgrade.md

Added documentation for the new 'tiup cluster tls' command, including usage, options, and output. Updated TOC to include the new command. Also documented the '--restart-timeout' flag for 'tiup cluster upgrade'.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/20831

tiup: add `tiup cluster tls`

---

tidb-cloud/configure-maintenance-window.md

cloud: minor wording updates in the maintenance window doc

---

variables.json

i18n-zh-release-8.5: sync variables.json

---

tidb-cloud/tidb-cloud-release-notes.md

cloud: 20250902 cloud release notes

---

tidb-troubleshooting-map.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/20867
- Other reference link(s):https://github.com/pingcap/tidb/pull/12223

troubleshooting: remove outdated `max-txn-time-use`

---

system-variables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/20742

v7.5.7: change the default value of tidb_enable_historical_stats

---

tidb-cloud/serverless-faqs.md

- Other reference link(s): https://github.com/pingcap/docs/pull/21466

cloud: Explain background queries with more details

---

upgrade-tidb-using-tiup.md
variables.json

bump TiDB from v7.5.6 to v7.5.7
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/20854

bump TiDB from v7.5.6 to v7.5.7

---

tidb-cloud/tidb-cloud-release-notes.md

Add the support of the following three new Alibaba Cloud regions for Essential to TiDB Cloud release notes:
- `Jakarta (ap-southeast-5)`
- `Mexico (na-south-1)`
- `Tokyo (ap-northeast-1)`
- Other reference link(s): https://github.com/pingcap/docs/pull/21703

cloud: add the support of three new Alibaba Cloud regions for Essential to release notes

---

tidb-cloud/tidb-cloud-release-notes.md

cloud: fix the link to auto embedding docs in release notes

---

TOC-tidb-cloud-essential.md
TOC-tidb-cloud-starter.md
TOC-tidb-cloud.md
tidb-cloud/import-snapshot-files-serverless.md
tidb-cloud/import-snapshot-files.md

- Other reference link(s):https://github.com/pingcap/docs/pull/13860

cloud: add import snapshot files.md to toc

---

config-templates/simple-tiproxy.yaml
tiproxy/tiproxy-overview.md

Updated to: https://github.com/pingcap/tiproxy/releases/tag/v1.3.2

Update TiProxy version to v1.3.2

---

tidb-cloud/serverless-faqs.md

Newer versions of Vale require YAML values containing template syntax to be quoted to parse correctly.

fix: quote YAML frontmatter values to resolve Vale parsing error

---

tidb-cloud/tidb-cloud-release-notes.md

cloud: add release notes 20250930
