scripts/build.sh
seem that user will compile tikv in one platform like ubuntu and then copy to other, so PORTABLE is necessary. 
@shenli @queenypingcap @iamxy
=> scripts: use PORTABLE rocksdb default

scripts/check_requirement.sh
A user told me that he met compile failed when using go 1.6.3 in CentOS 6.5, but success with go 1.7, we may use go 1.7 here now. 
@shenli @qiuyesuifeng
=> scripts: use go 1.7

README.md, dev-guide/deployment.md, dev-guide/development.md, dev-guide/requirements.md
Previous build instruction is not clear and has some link failed bug. 
I divide the build instruction into two parts: deployment and development.
+ For Deployment: we use static link RocksDB for TiKV and can deploy the binaries to other machines.
+ For Development: we use dynamic link RocksDB for TiKV and can only run tikv-server in local machine, this is convenient for developer because they don't need to re-compile RocksDB after we `cargo clean` the TiKV. 
@shenli @queenypingcap @c4pt0r
=> *: update build instruction

README.md, op-guide/migration.md
This document describes how to migrate data from MySQL to TiDB in detail.
=> op-guide: add a guide for data migration

scripts/build_rocksdb.sh
Minor patch to the rocksdb build script to allow it to work with macports.
=> build_rocksdb.sh: Add support on OSX for macports

op-guide/mysql-compatibility.md
The previous reason is: 
because they cannot be implemented well in distributed scenario.
This is not entirely true. We are planning to support some of these features in the future. Therefore, changing the statement.
@shenli @ngaut PTAL.
=> Remove the reason about unsupported features

scripts/build_rocksdb.sh
`tar xf rocksdb.tar.gz` will create `rocksdb-5.1.2` directory not `rocksdb-v5.1.2`.
And, `cd rocksdb-v5.1.2` will show error: 
> ./build_rocksdb.sh: line 88: cd: rocksdb-v5.1.2: No such file or directory
Then this PR fix the issue
=> fix build_rocksdb.sh

scripts/build_rocksdb.sh
Try to compile tikv with rocksdb 5.1 or 5.2 will cause compile error:
```
cargo build --release --features "default"
Compiling cfg-if v0.1.0
Compiling log v0.3.6
Compiling strsim v0.6.0
Compiling winapi-build v0.1.1
Compiling unicode-normalization v0.1.2
Compiling kernel32-sys v0.2.2
Compiling httparse v1.1.2
Compiling unicode-width v0.1.4
Compiling futures v0.1.13
Compiling bitflags v0.4.0
Compiling threadpool v1.3.0
Compiling vec_map v0.7.0
Compiling fnv v1.0.5
Compiling lazy_static v0.1.16
Compiling kernel32-sys v0.1.4
Compiling backtrace v0.2.3
Compiling semver v0.1.20
Compiling toml v0.2.1
Compiling slab v0.3.0
Compiling ws2_32-sys v0.2.1
Compiling mime v0.2.2
Compiling scoped-tls v0.1.0
Compiling dbghelp-sys v0.2.0
Compiling traitobject v0.0.1
Compiling bitflags v0.8.2
Compiling …
```
=> update rocksdb version to the latest version

op-guide/docker-compose.md
Related to #103 
PD and TiKV ports are used internally, there's no need to publish them
PTAL @iamxy @shenli
=> use expose for pd/tikv internal ports

README.md, tools/loader.md
If the topic with a link is in the table of content, the mark should be '-' instead of '+'.
=> Fix the link in the toc

scripts/build_rocksdb.sh
Error occur when running tikv on ubuntu.
`ERROR, "invalid argument:compression type ZSTD is not linked with the binary apt get install"`
We should install zstd to avoid this error. See https://github.com/pingcap/docs/pull/122.
There is no zstd package in apt-get source.
PTAL @siddontang
=> Add zstd install on ubuntu and fedora for script build_rocksdb.sh.

sql/README.md
Change the original SQL syntax doc to be the landing page of TiDB user guide.
=> Change the document structure

tools/loader.md
Since TiDB has deprecated the environment variable @@session.tidb_skip_constraint_check, so loader is no need to support this feature.
@GregoryIan @buggithubs @queenypingcap @lilin90  @sunhao2017 PTAL
=> loader: deprecate skip unique check

dev-guide/development.md
After install RocksDB, some environment variables should be modified in order to build TiKV.
To make command `make` for TiKV success, RocksDB include path should be added into `CPATH` and  RocksDB lib path should be added into `LIBRARY_PATH`.
To make command `make test` success, RocksDB lib path should be added into `LD_LIBRARY_PATH`.
=> Add RocksDB environment setting descprtions

README.md, overview.md
PTAL @queenypingcap @sunhao2017 @CaitinChen 
Via:
- https://github.com/pingcap/docs-cn/pull/549 
- https://github.com/pingcap/docs-cn/pull/550
- https://github.com/pingcap/docs-cn/pull/552
- https://github.com/pingcap/docs-cn/pull/553
- https://github.com/pingcap/docs-cn/pull/554
=> Update feature description in overview and readme

op-guide/ansible-deployment.md, op-guide/binary-deployment.md, op-guide/offline-ansible-deployment.md
I think the migration in https://github.com/pingcap/docs/pull/347 broke a few links. On master they currently 404.
=> Fix relative links in op-guide

sql/server-command-option.md
=> Typo `start` fixed

README.md, op-guide/gc.md, op-guide/history-read.md
@MyonKeminta  @lilin90 PTAL
via https://github.com/pingcap/docs-cn/pull/679
=> docs/op-guide: create GC document

README.md, tools/tidb-controller.md
@jackysp @CaitinChen PTAL
Via: https://github.com/pingcap/docs-cn/pull/683
=> tools: add TiDB Controller guide

op-guide/binary-deployment.md
Caused by a capitalization mismatch
=> Fix broken link in binary-deployment.md

QUICKSTART.md
@liubo0127 @CaitinChen PTAL
Via: https://github.com/pingcap/docs-cn/pull/696
=> quickstart: update one step description

op-guide/binary-deployment.md
Via: https://github.com/pingcap/docs-cn/pull/677 and https://github.com/pingcap/docs-cn/pull/680
=> op-guide: fix the file name and join

releases/11alpha.md
=> releases: fix typo and update format in 1.1 Alpha

README.md, tools/tikv-control.md
@hicqu @CaitinChen PTAL
Via: https://github.com/pingcap/docs-cn/pull/691
=> tools: add TiKV Control User Guide

sql/ddl.md
@winkyao @CaitinChen PTAL
Via: https://github.com/pingcap/docs-cn/pull/686
=> sql: update ddl table_option

README.md, op-guide/tidb-v2-upgrade-guide.md
@LinuxGit @CaitinChen PTAL. Via the following PRs:
- https://github.com/pingcap/docs-cn/pull/708
- https://github.com/pingcap/docs-cn/pull/709
- https://github.com/pingcap/docs-cn/pull/710
- https://github.com/pingcap/docs-cn/pull/711
- https://github.com/pingcap/docs-cn/pull/712
=> op-guide, readme: add TiDB 2.0 Upgrade Guide

op-guide/tidb-v2-upgrade-guide.md
=> op-guide: fix code block format at website

benchmark/tpch.md
Cleaned up certain parts of the bottom section to provide more clarity.
=> Updated tpch.md

sql/tidb-specific.md
@wsabc01 @CaitinChen PTAL
Via: https://github.com/pingcap/docs-cn/pull/721
=> sql: update tidb_batch_insert/delete autocommit

sql/error.md
@jackysp @CaitinChen PTAL
Via: https://github.com/pingcap/docs-cn/pull/728
=> sql: add two TiDB error codes

FAQ.md
=> faq: update description and delete repeated question

releases/2.0.1.md, releases/rn.md
=> releases: add the release notes for TiDB 2.0.1

scripts/check_requirement.sh
=> update the go version

README.md, releases/202.md, releases/rn.md
=> releases: add the release notes for TiDB 2.0.2

tikv/deploy-tikv-docker-compose.md
=> tikv: add a go client link to docker compose deployment

README.md, tikv/deploy-tikv-using-ansible.md
@siddontang @LinuxGit @queenypingcap  PTAL
=> tikv, readme: add "Install and Deploy TiKV Using Ansible"

sql/mysql-compatibility.md
@shenli @CaitinChen PTAL
Via: https://github.com/pingcap/docs-cn/pull/758
=> sql: update the description of auto id conflicts

README.md, tikv/deploy-tikv-using-docker.md
@siddontang @queenypingcap PTAL
=> tikv, readme: add "Install and Deploy TiKV Using Docker"

op-guide/ansible-deployment.md, op-guide/offline-ansible-deployment.md
=> op-guide: update ansible deployment steps and wording

op-guide/history-read.md, sql/tidb-specific.md
@zhexuany @CaitinChen PTAL
Via: https://github.com/pingcap/docs-cn/pull/757
=> op-guide, sql: add description about TSO support

tools/tikv-control.md
@huachaohuang @breeswish @CaitinChen PTAL
Via: https://github.com/pingcap/docs-cn/pull/754
=> tools: add checking Region properties to TiKV Control

FAQ.md
@zimulala @CaitinChen PTAL
Via: https://github.com/pingcap/docs-cn/pull/732
=> faq: add ERROR 1148 (42000)

op-guide/tidb-config-file.md
@winkyao @XuHuaiyu @CaitinChen PTAL
Via: https://github.com/pingcap/docs-cn/pull/742
=> op-guide: add note for lower-case-table-names

ROADMAP.md
A bulleted list cannot display as expected in PingCAP website. This PR fixes the indentation.
=> roadmap: fix the list format

sql/tidb-specific.md
@zimulala @CaitinChen PTAL
Via: https://github.com/pingcap/docs-cn/pull/764
=> sql: add tidb_retry_limit

op-guide/docker-compose.md, tikv/deploy-tikv-docker-compose.md
@tennix @CaitinChen PTAL
Via: https://github.com/pingcap/tidb-docker-compose/pull/25
=> op-guide, tikv: update docker compose deployment

README.md, releases/204.md, releases/rn.md
=> releases, readme: add the release notes for 2.0.4

op-guide/ansible-deployment.md
Via: https://github.com/pingcap/docs-cn/pull/766, https://github.com/pingcap/docs-cn/pull/782
=> op-guide: update links, format, and port variable

op-guide/ansible-deployment.md, op-guide/tidb-v2-upgrade-guide.md
op-guide/ansible-deployment.md is updated, so the original links in other files need to be updated.
=> op-guide: update deployment links and fix typo

FAQ.md
@lilin90 @lhyPingcap PTAL
via https://github.com/pingcap/docs-cn/pull/751
=> faq: add FAQ questions

README.md, releases/21beta.md, releases/rn.md
=> releases, readme: add the release notes for 2.1 beta

tikv/deploy-tikv-using-ansible.md
Related PR: https://github.com/pingcap/docs/pull/508
=> tikv: update ansible deployment links

tools/tidb-binlog-kafka.md
Via https://github.com/pingcap/docs-cn/pull/788
@lilin90 @GregoryIan PTAL
=> tools: replace generate binlog position with binlogctl

README.md, releases/205.md, releases/rn.md
=> releases, readme: add the release notes for 2.0.5

sql/tidb-specific.md, sql/transaction-isolation.md
@CaitinChen @coocood PTAL
Via: https://github.com/pingcap/docs-cn/pull/784
=> sql: disable transaction auto retry

FAQ.md
@CaitinChen @lhyPingcap PTAL
Via: https://github.com/pingcap/docs-cn/pull/783
=> FAQ: add 4 new questions and answers

op-guide/ansible-deployment.md
Via https://github.com/pingcap/docs-cn/pull/800
@LinuxGit @lilin90 PTAL
=> op-guide: add configuring CPUfreq governor mode

FAQ.md, op-guide/ansible-deployment-rolling-update.md, tools/tidb-binlog-kafka.md, tools/tikv-control.md
=> tools, FAQ, op-guide: update compact, drainer, questions and upgrade info

FAQ.md
"GC too early" is outdated. Filing this PR to correct it. @coocood @zz-jason PTAL
=> correct gc duration error message

tools/pd-control.md
Via: https://github.com/pingcap/docs-cn/pull/790 
Comment addressed. PTAL. @lilin90 @july2993
=> tools: add jq usages for pd-ctl

tools/pd-control.md
@CaitinChen @Connor1996 PTAL
Via: https://github.com/pingcap/docs-cn/pull/809
=> tools: update the code block in PD Control

op-guide/docker-compose.md
@tennix @CaitinChen PTAL
Via: https://github.com/pingcap/tidb-docker-compose/pull/27
=> op-guide: add accessing Spark with Python or R

FAQ.md
=> faq: fix typo and update wording

tools/pd-control.md
Comment addressed. PTAL. @lilin90
Via: https://github.com/pingcap/docs-cn/pull/812
=> tools: add cluster version in pd-control 

tispark/tispark-user-guide.md
=> tispark: update title level and description

op-guide/gc.md
I found three grammar mistakes when reading the 'gc.md' file today, PTAL @lilin90
=> op-guide: fix grammar mistakes in gc

README.md, tools/pd-control.md, tools/pd-recover.md
Via: https://github.com/pingcap/docs-cn/pull/818/ @lilin90 @nolouch PTAL
=> tools, readme: add pd recover usage document

op-guide/ansible-deployment.md, tikv/deploy-tikv-using-ansible.md
@CaitinChen @LinuxGit 
Via: https://github.com/pingcap/docs/pull/508, https://github.com/pingcap/docs/pull/531, ...
Or you can directly see: 
- https://github.com/pingcap/docs/blob/master/op-guide/ansible-deployment.md
- https://github.com/pingcap/docs-cn/blob/master/op-guide/ansible-deployment.md
=> tikv, op-guide: refine TiKV Ansible deployment steps and update IPs

op-guide/configuration.md
this for PR[#7078](https://github.com/pingcap/tidb/pull/7078)
=> op-guide: add advertise-address to TiDB configuration

op-guide/tune-tikv.md, sql/tidb-specific.md, tools/syncer.md
To change the Chinese commas into the English commas in three English documents. PTAL. @lilin90
=> op-guide, sql, tool: fix comma misuse

op-guide/location-awareness.md
@CaitinChen @lhyPingcap PTAL
Via: https://github.com/pingcap/docs-cn/pull/824
=> op-guide: update cross-region deployment description

op-guide/ansible-deployment-scale.md
@LinuxGit @yikeke PTAL
Via: https://github.com/pingcap/docs-cn/pull/836
=> op-guide: update PD scaling steps

op-guide/recommendation.md
Via: https://github.com/pingcap/docs-cn/pull/810 PTAL @lilin90 @datahoecn
=> op-guide: fix some indicators

tools/tikv-control.md
Signed-off-by: qupeng <qupeng@pingcap.com>
=> tools: add more sub commands for tikv-ctl

sql/admin.md
The correct syntax requires no quotes.
=> sql: job_id must not be quoted

FAQ.md
Via: https://github.com/pingcap/docs-cn/pull/832/ PTAL @lilin90 @lhyPingcap
=> FAQ: add 3 questions

tools/tikv-control.md
=> tools: add two commands in tikv-ctl

sql/understanding-the-query-execution-plan.md
In TiDB 2.1 the EXPLAIN output format changes.
=> sql: update explain format for TiDB 2.1

FAQ.md, README.md, op-guide/tidb-config-file.md, sql/slow-query.md, tools/tikv-control.md, trouble-shooting.md
Via: https://github.com/pingcap/docs-cn/pull/849/
Comment addressed. PTAL. @lilin90 @coocood
=> *: add slow-query doc

sql/character-set-configuration.md, sql/mysql-compatibility.md
Via this issue: https://github.com/pingcap/docs/issues/590
@tiancaiamao As for the character set, we say TiDB support UTF-8 or `utf8mb4`? Which one is more appropriate? Related links:
- https://github.com/pingcap/docs/blob/master/sql/character-set-configuration.md
- https://github.com/pingcap/docs/blob/master/sql/system-database.md#character_sets-table
=> sql: add default differences between TiDB and MySQL

op-guide/ansible-deployment-rolling-update.md, tispark/tispark-quick-start-guide.md
- update tikv rolling upate policy
- update tispark user guide
refer: 
https://github.com/pingcap/docs-cn/pull/858
https://github.com/pingcap/docs-cn/pull/857
=> op-guide: update tikv rolling upate policy

sql/tidb-specific.md
Via: https://github.com/pingcap/docs-cn/pull/852/. 
Comment addressed. PTAL. @CaitinChen @lilin90
=> sql: add new tidb specific system variables

QUICKSTART.md, README.md, try-tidb.md
Reorganize the quick start guide to help user find the right information where they need it.
=> readme, quickstart: reorganize the quick start structure

FAQ.md, sql/slow-query.md
@zz-jason @zhexuany @CaitinChen PTAL
=> refine two inaccurate description

QUICKSTART.md, README.md
I think that over time Kubernetes-based quickstart will become more popular than Docker Compose.  Currently, our recommended production deployment is also ansible -- but it is buried a few levels deep in navigation.
I would like to propose a reorganization so that the Quickstart links to all op-guide deployments.  This also reduces duplication since the Docker Compose tutorial is in Quickstart and in op-guide.
Minor/unofficial platforms can also have a link under "community provided blog posts".  I've included the 5-minute quick start and a link to one of my blog posts (which should be removed as newer and better guides are written).
=> *: Reorganize quick start to promote other platforms

op-guide/ansible-deployment-scale.md
=> op-guide: fix a code typo in Ansible scaling

sql/tidb-specific.md
The default value for this variable is `PRIORITY_LOW` (not normal).  It can be verified with:
```
mysql> show global variables like 'tidb_ddl_reorg_priority';
+-------------------------+--------------+
| Variable_name           | Value        |
+-------------------------+--------------+
| tidb_ddl_reorg_priority | PRIORITY_LOW |
+-------------------------+--------------+
```
This PR also fixes minor formatting, where options are at the incorrect header level.
=> sql: Default tidb_ddl_reorg_priority is slow

README.md, architecture.md, features.md, overview.md
The main navigation has anchor links into `overview.md` for introduction and architecture (but not features).    I think it makes sense to add an anchor link for 'Features', but in this PR I propose an alternative -- which is to break this document in three:
- `overview.md`
- `architecture.md`
- `features.md`
The advantage to breaking the document up, is that we can track their individual popularity in Google Analytics etc.  I suspect that `architecture.md` will be very popular :-)
Note: I've changed heading levels as part of this, but no other changes.  I will suggest other small changes after this merges.
=> *: split overview.md into sub documents

sql/datatype.md
Fixing minor errors.
Integer(M) is display width.
YEAR(2) is not supported in MySQL or TiDB:
```
MySQL [test]> create table tt1 ( a int not null primary key, b year(2));
ERROR 1105 (HY000): line 1 column 57 near ""Supports only YEAR or YEAR(4) column. (total length 57)
```
=> sql: YEAR(2) is not supported, M is display width

sql/string-functions.md
The following functions are not supported in TiDB, but are in the documentation.
I suggest removing them and add them back once implemented.
=> sql: Remove unsupported functions

sql/character-set-configuration.md
Improved clarity of changing character set, linked back to mysql compatibility/differences in defaults so users can discover other differences.
=> sql: Clarify default character-set is utf8

sql/transaction-isolation.md
The read committed isolation level is removed in https://github.com/pingcap/tidb/pull/7280, we should remove it in the docs.
Via: https://github.com/pingcap/docs-cn/pull/871
=> sql: remove documentation about read committed

op-guide/ansible-deployment.md
Via: https://github.com/pingcap/docs-cn/pull/872
Note: Since the note about version is already covered in the English doc, it is omitted in this PR.
=> op-guide: update tidb-ansible and version note

README.md, bikeshare-example-database.md
The MySQL manual makes use of sample databases which are available for [download here](https://dev.mysql.com/doc/index-other.html).  i.e. sakila, world, employees, menagerie.
The problem with re-using these databases is they are too small for TiDB to demonstrate HTAP.  This pull request includes a sample data set from Capital Bikeshare.  It takes 18m43s to import on my desktop.
https://github.com/pingcap/docs/pull/599 covers adding examples in the manual (`sql/understanding-the-query-execution-plan.md`).
This PR depends on https://github.com/pingcap/tidb/pull/7576 (recently merged).
=> *: Include bikeshare example database in manual

sql/understanding-the-query-execution-plan.md
This adds an example to the Query Execution Plan page.
It depends on https://github.com/pingcap/docs/pull/596 which is also ready to merge.
=> sql: Add example to QEP manual page

README.md, sql/time-zone.md
Via: https://github.com/pingcap/docs-cn/pull/876
=> sql, readme: update timezone support

sql/mysql-compatibility.md
events, sys do not exist
pfs exists but returns empty.
=> sql: Added incompatibilities with MySQL

sql/mysql-compatibility.md
The manual page is currently broken:
https://pingcap.com/docs/sql/mysql-compatibility/
It broke after push of https://github.com/pingcap/docs/pull/604 although it looks like it was a change in the markdown parser, since this line was not modified.
I investigated it, and think this might fix it - but it's difficult to tell since GitHub's markdown parser works fine.
=> Fix broken manual page

op-guide/history-read.md
To me, a user variable is one that has no impact on the system.  i.e. `set @kjdfsjdfksdjf='a'`;
I've changed the text to call it a "session variable" or "global variable", but it is probably technically a system variable with [global | session] scope.
=> op-guide: Improved consistency of variable descriptions

tools/pd-control.md
This PR adds 5 more commands in pd-control: 
- `region store`
- `region topread`
- `region topwrite`
- `region topconfver`
- `region topversion`
=> tools: add more commands in pd-control 

sql/system-database.md
This was recently improved in https://github.com/pingcap/tidb/pull/7647
=> sql: Document character sets / collations

FAQ.md, ROADMAP.md
@GregoryIan @queenypingcap 
PTAL
=> faq: some adjustments to Syncer related content

tikv/deploy-tikv-docker-compose.md
Via: https://github.com/tikv/tikv/pull/3643
=> tikv: update docker compose steps

op-guide/ansible-deployment-rolling-update.md
@LinuxGit @CaitinChen PTAL
Via: https://github.com/pingcap/docs-cn/pull/899
=> op-guide: update TiDB download links

op-guide/monitor-overview.md, op-guide/monitor.md
=> op-guide: fix monitor typos

op-guide/ansible-deployment.md
=> op-guide: fix a typo in ansible deployment

tools/tikv-control.md
This PR fixes some tikv-ctl parameters.
=> tools: fix some tikv-ctl parameters

README.md
=> readme: link TiKV docs to the tikv repo

tools/pd-control.md
@hicqu @CaitinChen PTAL
Via: https://github.com/pingcap/docs-cn/pull/866
=> tools: update operator Region split

sql/encryption-and-compression-functions.md
=> sql: Remove deprecation note

FAQ.md, README.md, op-guide/backup-restore.md, tools/mydumper.md
The `mydumper` upstream is unsafe, since it relies on `ftwrl` instead of `tidb_snapshot`.  Soon the server will produce an error when attempting this unsafe statement: https://github.com/pingcap/tidb/pull/7712
The `mydumper` currently in enterprise tools is unsafe by default, but can be made safe by setting the `tidb_snapshot` as an option.
In https://github.com/morgo/mydumper/tree/tidb-head I have re-implimented the `tidb_snapshot` option to aut-set, so backups are safe by default.  It is also based on upstream's master branch, so it includes the last couple of years of bug fixes and support for generated columns.
`tidb-head` also includes all features that were in the master branch of `pingcap/mydumper`, so I am hoping we can switch it to be `pingcap/master`.  At which point the docs …
=> op-guide, tools: Recommend mydumper from enterprise tools

FAQ.md
=> FAQ: Restore deleted content

FAQ.md, sql/server-command-option.md, sql/tidb-specific.md
=> faq, sql: Document tidb_force_priority

README.md, sql/tidb-specific.md
I had a chat with @gregwebs, and we agreed that while not incorrect - the word "proprietary" has too strong of an association with "not open source" (which is not the case here).
So I've changed the name to TiDB specific to reduce confusion.
=> sql: Rename TiDB proprietary variables to TiDB specific

README.md, sql/sql-optimizer-overview.md
@zz-jason @CaitinChen PTAL
Via: https://github.com/pingcap/docs-cn/pull/865
=> sql, readme: add SQL optimization process

sql/mysql-compatibility.md
TiDB does not support updatexml or extractvalue:
https://dev.mysql.com/doc/refman/5.7/en/xml-functions.html
=> sql: Add XML functions to incompatible

README.md, overview.md, tispark/tispark-user-guide.md
=> *: update ETL description

README.md, releases/208.md, releases/rn.md
=> releases, readme: add 2.0.8 release notes

sql/aggregate-group-by-functions.md
Incorrectly stated only-full-group-by was not supported.
**Note**: This PR references aggregate functions that are in development and have not been merged yet.  If they are not complete after review, I will move them to the unsupported functions section.
=> sql: improve aggregation docs

sql/json-functions.md
Added in https://github.com/pingcap/tidb/pull/7776
=> sql: Add JSON_KEYS function

tools/pd-control.md
This PR is based on pingcap/pd#1298.
=> pd-ctl: update the usage of region key

tools/mydumper.md
In https://github.com/pingcap/mydumper/pull/8 our `mydumper` recently changed it's default from NOW()-1 second to the current TSO from `SHOW MASTER STATUS`.  This PR updates the docs.
=> tools: update mydumper default tidb_snapshot

sql/tidb-server.md, sql/tidb-specific.md, sql/variable.md
The title was renamed in https://github.com/pingcap/docs/pull/666
=> sql: update tidb specific link description

sql/datatype.md, sql/user-manual.md
I don't believe anything links to sql/user-manual.md, but I've updated it anyway.
Found the links via a grep search.
=> sql: Fix broken links

sql/mysql-compatibility.md, sql/privilege.md
I noticed a few small errors in the privileges page.  While few users use column-level privileges, I think it is still worth calling out on the compatibility page.
=> sql: improve privileges docs

op-guide/kubernetes.md
=> op-guide: add tabs for TiDB deployment tutorials on gcp and local

sql/understanding-the-query-execution-plan.md
Since "executor" and "operator" indicate the same thing, we need to keep the term consistent in this doc. zz-jason suggests using "operator" so I replace "executor" with "operator".
@morgo @zz-jason PTAL. Thanks.
=> sql: replace "executor" with "operator"

tools/lightning-deployment.md, tools/lightning-faq.md
Recently we fixed a bug in RocksDB which would cause loss of data due to race condition (pingcap/rocksdb#59). So we need to increase the TiKV requirement to 2.0.9.
=> lightning: increase the required version from 2.0.4 to 2.0.9

sql/mysql-compatibility.md
Fixes #606.
Depends on `NO_AUTO_CREATE_USER` being merged, but expected soon:
https://github.com/pingcap/tidb/pull/8160
=> sql: Add SQL mode details

tools/lightning-errors.md
This adds a list of common causes and fixes about why Lightning is slower than expected.
Chinese version: pingcap/docs-cn#998
=> tools: added a checklist for debugging speed problem

README.md, releases/2.1.1.md, releases/rn.md
=> releases, readme: add TiDB 2.1.1 Release Notes

README.md, op-guide/ansible-deployment-rolling-update.md, op-guide/ansible-deployment.md, op-guide/tidb-v2.0-upgrade-guide.md, op-guide/tidb-v2.1-upgrade-guide.md, tools/tidb-binlog-cluster.md, tools/tidb-binlog-kafka.md, v2.0/README.md, v2.0/op-guide/ansible-deployment-rolling-update.md, v2.0/op-guide/tidb-v2.0-upgrade-guide.md
@liubo0127 @CaitinChen PTAL
Via: https://github.com/pingcap/docs-cn/pull/999, https://github.com/pingcap/docs-cn/pull/1014
=> *: add TiDB 2.1 Upgrade Guide

README.md, tools/lightning/checkpoints.md, tools/lightning/deployment.md, tools/lightning/errors.md, tools/lightning/filter.md, tools/lightning/monitor.md, tools/lightning/overview-architecture.md
* Added description of the table filter (black-white-list)
* Included the new metrics
* Use a permanent download link for ~~v2.1.0~~ ~~v2.1.1~~ v2.1.2; added download link for latest build
* Included a brief description what flags should be passed to mydumper (mostly copied from the Migration Guide, but adjusted for Lightning)
* Included several new config flags
* Included troubleshooting for timezone issues
* Checkpoints can be stored as a local file now; updated descriptions
=> tools, readme: adjust Lightning docs for the latest version

tikv/go-client-api.md
Signed-off-by: disksing <i@disksing.com>
- use go module to manage dependency
- adapt API change: `Seek` -> `Iter`
Fix https://github.com/pingcap/docs/issues/826
/cc @pingcap/techwriter
=> tikv: update go-client usage doc

scripts/check_requirement.sh
The location of rustup.sh has moved.
Run the following command to install from the new location:
curl https://sh.rustup.rs -sSf | sh
=> scripts: update rustup.sh location

tools/lightning/deployment.md, tools/lightning/errors.md, tools/lightning/faq.md, tools/lightning/monitor.md
1. Updated the config to include the new `io-concurrency` setting, and delete the `region-min-size` setting.
2. Included several new metrics introduced recently.
3. **Removed description about mixed deployment** (putting Lightning and Importer together). This deployment mode causes too many problem in the past and is no longer officially supported.
4. Clarified some SSD and network requirement with explicit numbers.
5. **Clarified the space requirement of the TiKV cluster** (6 × SQL size).
=> tools: update docs for Lightning

FAQ.md
Via: https://github.com/pingcap/docs-cn/pull/1083 Comment addressed. PTAL. @lilin90
=> FAQ: update slow log, DDL and Syncer related questions

sql/mysql-compatibility.md
Checksum table: https://github.com/pingcap/tidb/issues/1895
Check table: https://github.com/pingcap/tidb/issues/4673
Lock table is in the [ROADMAP](https://github.com/pingcap/docs/blob/master/ROADMAP.md) items.
=> sql: Add LOCK TABLE, CHECK TABLE, CHECKSUM TABLE to incompatible

sql/mysql-compatibility.md
via https://github.com/pingcap/tidb/pull/9027
=> sql: allow_invalid_dates is now supported

tools/loader.md, tools/mydumper.md, tools/syncer.md, tools/tidb-binlog.md
The other manual pages have direct links to download.  We should harmonize on `download.md`.
=> tools: harmonize download links

tikv/go-client-api.md
This PR fixes the transactional API example. The related issue is tikv/client-go#4.
=> tikv: fix the transactional API example

sql/understanding-the-query-execution-plan.md
As @zz-jason said, our "Coprocessor" in TiKV is not the same as a coprocessor with a conventional meaning “a microprocessor circuit that operates alongside and supplements the capabilities of the main processor, providing, for example, high-speed arithmetic”. Therefore, we replace "the coprocessor in TiKV" with "TiKV Coprocessor".
@morgo @lilin90 @zz-jason PTAL ^_^
=> sql: update wording

contribute.md, report-issue.md, support.md
(There are a few very safe changes in the DITA re-org we can make now. This pre-work helps reduce the scope of the conversion.)
This adds new content which will be used in the DITA version of the manual
=> report-issue, contribute, support: new documents

TOC.md, sql/constraints.md
(There are a few very safe changes in the DITA re-org we can make now. This pre-work helps reduce the scope of the conversion.)
This PR adds some initial documentation for constraints.
=> SQL: Add constraints

TOC.md, sql/mysql-compatibility.md, sql/transaction-compatibility.md
(There are a few very safe changes in the DITA re-org we can make now. This pre-work helps reduce the scope of the conversion.)
This PR slightly reorganizes how we talk about compatibility by splitting it into two pages, and creating an explicitly "Transactions" menu item.
It does not change any of the content (other than the general compatibility intro).  The general intro also now links to the sub-topics.
=> sql, TOC: Reorganize Compatibility for DITA

sql/constraints.md
Important to document it is both types of constraints.
=> sql: update constraints to show lazy checking occurs on primary key too

op-guide/tidb-config-file.md, sql/statistics.md, v2.1/op-guide/tidb-config-file.md, v2.1/sql/statistics.md
@yikeke PTAL
Via: https://github.com/pingcap/docs-cn/pull/1163
=> sql, op-guide: fix the default value of feedback-probability

TOC.md, op-guide/binary-deployment.md, op-guide/binary-local-deployment.md, op-guide/binary-testing-deployment.md
This is required for the DITA manual where these appear in different sections.
=> op-guide: split binary deployment into three sections

op-guide/recommendation.md
Some parts of the requirements are really recommendations. We should make the language clearer, so someone does not think it won't work without this.
=> op-guide: differentiate requirement vs. recommend

sql/character-set-support.md
This was removed in https://github.com/pingcap/docs/pull/982
I just learned how to do aliases, so this redirects from the removed location to the closest match.
=> sql: add alias for deleted file

sql/transaction-model.md
This page was previously called "transactions: mysql compatibility".  Because that was dropped the differences heading makes less sense.. differences from what?
Updating the sub-heading to be differences from MySQL.
=> sql: Update transaction-model.md subheading

op-guide/migration-overview.md
The parser used by the website is different to github pages.
It broke the formatting of this page.
=> op-guide: Fix for buggy .md parser

op-guide/migration-overview.md
Sorry, it is still broken: https://pingcap.com/docs/op-guide/migration-overview/
=> op-guide: attempted fix #2

tools/syncer.md
Via: https://github.com/pingcap/docs-cn/pull/1215/
PTAL @amyangfei  @lilin90
=> tools: add more argument description of Syncer

TOC.md, key-features.md, overview.md
This PR moves the key-features introduction under concepts/key-features. The index page becomes what was QUICKSTART (for now).
The plan is to change QUICKSTART to be a proper quickstart, with an overview of each of the key sections of the manual. We will work with the designers to make this possible.
It is important to merge this intermediate version because of an inconsistency:
If you visit pingcap.com/docs you will land on key-features, but if you click on the 'introduction' heading again you will get Quickstart.
=> overview, intro: move content around

benchmark/sysbench-v4.md, sql/transaction-isolation.md, sql/transaction-model.md
Related to: https://github.com/pingcap/docs-cn/pull/1231 @morgo PTAL
=> Sql/transaction: changes on variables

benchmark/sysbench-v4.md
Related PR: https://github.com/pingcap/docs-cn/pull/1247
@jackysp @huangxiuyan PTAL
=> benchmark: update wording

dev/how-to/get-started/local-cluster/install-from-dbdeployer.md
There seems to be a problem with the website in that the filename in the current directory is not relative.  This is not a problem in the GitHub markdown parser, making it difficult to test.
I am not sure if this will fix it, but I have to try, since including the full path (/dev/how-to/..) makes version split more difficult, since only one version will be /dev
=> dev/how-to: Attempt to fix relative link

dev/how-to/get-started/local-cluster/install-from-dbdeployer.md
@YiniXu9506 confirmed that we have to use absolute urls for now. We can take a look at using a regex to help porting between versions easier.
=> dev/how-to/get-started: Fix broken link using absolute reference

TOC.md, sql/system-database.md
Via https://github.com/pingcap/docs-cn/pull/1262
@tiancaiamao @lilin90 PTAL
=> sql, TOC: update doc title

sql/util.md, v1.0/sql/util.md, v2.0/sql/util.md, v2.1/sql/util.md
User provided feedback that our explanation of TiDB 'USE' command in util document is not quite accurate: the meaning of default database is confusing.
Detailed at the issue link: https://github.com/pingcap/docs-cn/issues/1112
And the docs-cn PR link: https://github.com/pingcap/docs-cn/pull/1269
I updated the explanation of TiDB 'USE' command in sql/util.md documents (1.0/2.0/2.1).
Previously: 'The USE statement is used to switch the default database. If the table in this SQL statement does not correspond to an explicitly specified database, then the default database is used.'
Updated: 'The `USE` statement is used to switch the default database. If the table in this SQL statement does not correspond to an explicitly specified database, then the current selected database will be used by …
=> sql: update the USE command explanation in util document

tools/loader.md
This PR updates the pprof-addr default port in Loader documents.
According to the https://internal.pingcap.net/confluence/pages/viewpage.action?pageId=21273346, Loader pprof-addr default port has changed from 10084 to 8272 while the public documents is out of date.
Loader code for reference:
https://github.com/pingcap/tidb-enterprise-tools/blob/master/loader/config.go
fs.StringVar(&cfg.PprofAddr, "pprof-addr", ":8272", "Loader pprof addr")
And the same PR in docs-cn： https://github.com/pingcap/docs-cn/pull/1256
=> tools: update the loader pprof-addr default port

dev/how-to/deploy/geographic-redundancy/overview.md
Changed all references of "synchronization" to "replication", because it's more accurate for 2DC + binlog deployment. (Synchronization implies data is replicated in both direction, which is not the case here, that's why replication is more accurate.)
=> dev/how-to: refine 2-DC deployment solution

tools/syncer.md
TiDB only supports limited charset, so it's necessary for users to check the charset before running the Syncer.
=> Add charset check in Syncer precheck

tools/lightning/deployment.md, tools/lightning/errors.md, tools/lightning/monitor.md
Update Lightning documentations for the new release (v2.1.9).
* Fixed a typo in the Troubleshooting docs.
* Increased Importer's memory requirement to 40 GB+ due to tikv/tikv#4566, and included a formula to estimate the average memory usage.
* Included config changes from pingcap/tidb-lightning#175, tikv/tikv#4412, tikv/tikv#4423 and tikv/tikv#4611.
* Included metrics changes from tikv/tikv#4386, tikv/tikv#4423 and pingcap/tidb-lightning#145.
=> tools/lightning: update Lightning docs for v2.1.9

op-guide/dashboard-tikv-info.md, op-guide/tune-tikv.md, tools/tikv-control.md
Update docs to reflect that in tikv3.0 block cache will be shared among column families by default.
=> op-guide: update docs for shared block cache

dev/how-to/maintain/identify-slow-queries.md, op-guide/tidb-config-file.md
Related PR: https://github.com/pingcap/docs/pull/1083
Via
- pingcap/docs-cn#1277
- pingcap/docs-cn#1276
- pingcap/docs-cn#1266
- pingcap/docs-cn#1182
- pingcap/docs-cn#1271
@lilin90 PTAL
=> op-guide, dev/how-to/maintain: update slow query and config file content

dev/reference/performance/tune-tikv.md, tools/tikv-control.md
Description for shared block cache was added in #1114, but it fail to mention the change is for 3.0 only.
=> dev-reference: mention shared block cache is only for 3.0

TOC.md, dev/how-to/scale/horizontally.md, dev/how-to/scale/with-ansible.md, dev/how-to/upgrade/data-migration.md, dev/how-to/upgrade/from-previous-version.md, dev/how-to/upgrade/rolling-updates-with-ansible.md
It doesn't seem to me like "scale" and "upgrade" are necessarily natural fits for the "maintain" section. I like the idea that semantically meaningful phrases can be formed by combining "how to" and the verb of the sections that fall below it, for example "how to" + "scale" = "how to scale", and "how to" + "upgrade" = "how to upgrade". That didn't work very well when you had "how to" + "maintain" + "scale".
So, I moved "scale" and "upgrade" from under "maintain" to being top-level items under "how-to".
=> Moved "scale" and "upgrade" from "maintain" to top-level "how-to"

dev/how-to/get-started/tidb-binlog.md
Fixed wording of section explaining TiDB-Binlog's role in a migration *from* MySQL/MariaDB *to* TiDB
=> Updated TiDB-Binlog tutorial

TOC.md, dev/reference/error-codes.md
This PR moves the error codes page, which was temporarily moved back in a hotfix: https://github.com/pingcap/docs/pull/1131
Please notify the EE team before merging, since it could break CI -- but I am not sure why it did last time.
=> sql: move error codes page

dev/reference/tools/data-migration/dm-worker-intro.md, dev/reference/tools/data-migration/precheck.md, dev/reference/tools/data-migration/query-status.md, dev/reference/tools/data-migration/relay-log.md, dev/reference/tools/data-migration/skip-replace-sqls.md, dev/reference/tools/data-migration/table-selector.md, dev/reference/tools/sync-diff-inspector.md, dev/reference/tools/tikv-control.md
Moves the remainder of tools/* to a versioned location using the new structure (dev/reference/tools).
Redirects are put in place to move users to new location.
=> tools: Move tools to new location

dev/reference/tools/syncer.md
The instructions in the syncer docs told users to dynamically change settings in MySQL that would not persist after a restart of the service. That's a bad practice, so I updated the doc to provide better instructions.
=> Changed instructions for modifying MySQL settings

releases/3.0.0-rc.2.md
Checked with devs, tidb binlog doesn't upgrade the Parser in 3.0, it's in 2.1. So remove this note.
=> releases: remove one note of tidb binlog

dev/reference/sql/statements/alter-table.md, dev/reference/sql/statements/create-database.md, dev/reference/sql/statements/flush-privileges.md, dev/reference/sql/statements/flush-tables.md, dev/reference/sql/statements/show-variables.md
These files do not exist. Invalid links affect SEO ranking, so I remove them.
Once these files are ready, we can add these links back.
@dcalvin @morgo @lilin90
=> dev/reference/sql/statements: remove invalid links

dev/reference/transactions/transaction-isolation.md
This PR replaced  "phantom reads" with "phantom" to be technically accurate.
=> reference/.../transaction-isolation: use phantoms instead of phantom reads

dev/reference/configuration/tidb-server/tidb-specific-variables.md, dev/reference/transactions/transaction-model.md
This PR modified the possible values of `tidb_disable_txn_auto_retry` to **on** and **off**. PTAL @lilin90 @jackysp
=> reference/.../tidb-specific-variables: update possible values and default of tidb_disable_txn_auto_retry

tidb-in-kubernetes/gcp-gke-tutorial.md, tidb-in-kubernetes/google-kubernetes-tutorial.md
Related PR: https://github.com/pingcap/docs-cn/pull/1467
Preview:
https://github.com/DanielZhangQD/docs/blob/google-migration/tidb-in-kubernetes/gcp-gke-tutorial.md
https://github.com/DanielZhangQD/docs/blob/google-migration/tidb-in-kubernetes/google-kubernetes-tutorial.md
=> tidb-in-kubernetes: migrate google deployment doc to docs repo

dev/reference/security/privilege-system.md
1. Update description about "grant" to a non-exist user in privilege-system.md. Via: [#1414](https://github.com/pingcap/docs-cn/pull/1414/files)
2. Fix a mistake.
PTAL @lilin90 @tiancaiamao
=> dev/reference/security: update description about "grant" to a non-exist user

dev/reference/mysql-compatibility.md, v3.0/reference/mysql-compatibility.md
Support for views
New defaults
Supercedes https://github.com/pingcap/docs/pull/771 and https://github.com/pingcap/docs/pull/957
Relates to 3.0 and dev only. Not a 2.1 feature
=> reference/mysql-compatibility: Update MySQL compat for 3.0

dev/reference/security/privilege-system.md, v2.1/reference/security/privilege-system.md, v3.0/reference/security/privilege-system.md
2.1 Does not support ONLY_FULL_GROUP_BY.
2.1: Remove an example that shows bad practice.
2.1/3.0/dev: Remove advice about direct edits to privilege tables.
This is a followup PR to https://github.com/pingcap/docs/pull/1229
Mainly 2.1, but some 3.0/dev changes.
=> reference/security: update 2.1 advice

dev/reference/sql/character-set.md, v2.1/reference/sql/character-set.md, v3.0/reference/sql/character-set.md
The 3.0 and dev output shows only supported collations.
The 2.1 output includes all collations.
https://github.com/pingcap/tidb/pull/10186
All
=> reference/sql/character-set: update examples

v2.1/TOC.md, v2.1/how-to/maintain/identify-slow-queries-21.md, v2.1/how-to/maintain/identify-slow-queries.md
Solve the 2.1.8 log format change a little better, by including
a manual page for each for 2.1 series only.
Previously the page linked direct to GitHub (now a broken link), which should not be done.
2.1 only.
=> how-to/maintain: fix broken link

circle.yml, scripts/generate_pdf.sh
CI failed at generating PDF for v2.1 and v3.0, so remove v2.1 and v3.0 from generate_pdf.sh
=> generate_pdf.sh: stop generating PDFs for v3.0 and v2.1

dev/reference/mysql-compatibility.md, dev/reference/transactions/transaction-model.md, v2.1/reference/mysql-compatibility.md, v2.1/reference/transactions/transaction-model.md, v3.0/reference/mysql-compatibility.md, v3.0/reference/transactions/transaction-model.md
- Do not explain "get_lock" as different from MySQL: it doesn't work and should be on incompatibility.
- Explain in dev/ that optimistic is only the default.
- Better clarify that retry differs between 2.1 and 3.0 and could cause upgrade issues (document on both sides).
- Change dev/ mysql-compatibility for LOCK TABLES from incompatible to having an explanation.
- Document SELECT FOR UPDATE as a transaction model behavior difference
Also fixes https://github.com/pingcap/docs/issues/807
All
=> reference/transactions: improve version diffs

dev/TOC.md, dev/how-to/deploy/tidb-binlog.md, dev/how-to/maintain/tidb-binlog.md, dev/how-to/monitor/tidb-binlog.md, dev/how-to/upgrade/tidb-binlog.md, dev/reference/tidb-binlog-overview.md, v2.1/TOC.md, v2.1/how-to/deploy/tidb-binlog.md, v2.1/how-to/maintain/tidb-binlog.md, v2.1/how-to/monitor/tidb-binlog.md, v2.1/how-to/upgrade/tidb-binlog.md, v2.1/reference/tidb-binlog-overview.md, v3.0/TOC.md, v3.0/how-to/deploy/tidb-binlog.md, v3.0/how-to/maintain/tidb-binlog.md, v3.0/how-to/monitor/tidb-binlog.md, v3.0/how-to/upgrade/tidb-binlog.md, v3.0/reference/tidb-binlog-overview.md
* In **/reference/tidb-binlog-overview.md**, the `reparo` link is wrong and should be correct to **/reference/tools/tidb-binlog/reparo.md**; also  the `Binlog Slave Client User Guide` link is wrong and should be correct to **/reference/tools/tidb-binlog/binlog-slave-client.md**
* In **how-to/upgrade/tidb-binlog.md**， the `Kafka version` link should be correct to **/reference/tools/tidb-binlog/tidb-binlog-kafka.md** and `Local version` should be correct to **/reference/tools/tidb-binlog/tidb-binlog-local.md**
PTAL https://github.com/pingcap/docs-cn/pull/1522
apply in dev/v3.0/v2.1
=> dev/v3.0/v2.1: fix wrong binlog links

dev/reference/sql/statements/create-table-like.md, dev/reference/sql/statements/create-table.md, v2.1/reference/sql/statements/create-table-like.md, v2.1/reference/sql/statements/create-table.md, v3.0/reference/sql/statements/create-table-like.md, v3.0/reference/sql/statements/create-table.md
I found that we used two different names for the SQL statement - CREATE TABLE LIKE and CREATE TABLE AS in our documents. According to the usage examples in the document, I think we should use the former one.
@morgo PTAL
=> v2.1, v3.0, dev: fix inconsistent word usage

dev/reference/mysql-compatibility.md, v3.0/reference/mysql-compatibility.md
fix incorrect links in dev and v3.0 folders @CaitinChen  PTAL
dev and v3.0
=> dev, v3.0: fix incorrect links

dev/benchmark/sysbench-v4.md, v3.0/benchmark/sysbench-v4.md
modify: simple bug fix
wrong VM info in TiDB 3.0's sysbench doc.
- [] Use *four* spaces for each level of indentation except that in `TOC.md`
=> Fix TiDB 3.0 sysbench test's machine information

v3.0/how-to/get-started/tidb-binlog.md
I bumped the package version for the TiDB-Binlog tutorial to use stable 3.0 releases rather than the "latest" packages.
n/a
v3.0
=> v3.0: bumped binlog tutorial to use stable 3.0 packages

dev/TOC.md, dev/reference/tools/tikv-control.md, v2.1/TOC.md, v3.0/TOC.md, v3.0/reference/tools/tikv-control.md
This PR updated the TOC to link **tikv-control.md** to local instead of the TIKV repo. Files in V3.0 and dev are also updated based on the TiKV repo version.
TiDB Dev/3.0/2.1
=> *reference/tools: fix links to tikv control file

v2.1/TOC.md, v2.1/reference/sql/statements/alter-database.md
This PR adds the alter-database document to the v2.1 directory.
https://github.com/pingcap/docs-cn/pull/1610
v2.1
=> v2.1/reference/sql: add alter-database doc in v2.1

dev/reference/mysql-compatibility.md, v3.0/reference/mysql-compatibility.md
Via: https://github.com/pingcap/docs-cn/pull/1556
+ Update the descriptions of compatibility.
+ Add a paragraph to `# Compatibility with MySQL` that was missing in the English version.
dev and v3.0
=> v3.0, dev/reference: update the descriptions of compability

dev/TOC.md, dev/how-to/deploy/orchestrated/tidb-in-kubernetes/access-tidb.md, v3.0/TOC.md, v3.0/how-to/deploy/orchestrated/tidb-in-kubernetes/access-tidb.md
Via: https://github.com/pingcap/docs-cn/pull/1428
The document `tidb-in-kubernetes/expose-servics.md` added in #1428 had been changed in title, description, and place by the time when I did the translation. Therefore, this is not a literal translation. 
(the new address: https://github.com/pingcap/docs-cn/blob/master/dev/how-to/deploy/orchestrated/tidb-in-kubernetes/access-tidb.md)
The `## NodePort` section might be a little different from the original Chinese version. @weekface has given me some technical details to change the description of NodePort to make it more understandable.
Anyway, PTAL, thanks!
=> dev/how-to/deploy: add access-tidb-clusters-on-kubernetes

dev/reference/garbage-collection/configuration.md, v3.0/reference/garbage-collection/configuration.md
* This PR is corresponding with https://github.com/pingcap/docs-cn/pull/1634 :
* Add the example of mysql.tidb's content back to make it easier for reader to understand how the configurations are represented.
* Use tikv_gc_life_time as the example of updating configurations, which is more frequently used.
* Additionally, this PR fixed an inconstancy of dev and 3.0, at configuration.md L41
* Chinese version: https://github.com/pingcap/docs-cn/pull/1634
dev, v3.0
=> dev, 3.0: Refine document of GC

dev/TOC.md, dev/reference/sql/generated-columns.md, dev/reference/sql/partitioning.md, v3.0/TOC.md, v3.0/reference/sql/generated-columns.md, v3.0/reference/sql/partitioning.md
1. add TiDB partitioning table document
2. add the new file into TOC
3. minor change in generated-columns.md to unify format 
Aligned from: https://github.com/pingcap/docs-cn/pull/1431
PTAL @lilin90 @tiancaiamao 
dev, v3.0
=> dev, v3.0: add TiDB partitioning table document

dev/TOC.md, dev/how-to/configure/initialize-cluster.md, v3.0/TOC.md, v3.0/how-to/configure/initialize-cluster.md
Adding a document about how to initialize TiDB cluster on Kubernetes deployment.
https://github.com/pingcap/docs-cn/pull/1591
dev and v3.0
=> v3.0,dev/how-to/configure: initialize cluster managed by tidb-operator 

dev/tidb-in-kubernetes/deploy/general-kubernetes.md, dev/tidb-in-kubernetes/deploy/tidb-operator.md, dev/tidb-in-kubernetes/tidb-operator-overview.md, v3.0/tidb-in-kubernetes/deploy/general-kubernetes.md, v3.0/tidb-in-kubernetes/deploy/tidb-operator.md, v3.0/tidb-in-kubernetes/tidb-operator-overview.md
This PR fixes 3 broken links found in the `TiDB Operator Overview` document, the `Get-Started` and the `Deploy` directories.
`dev`  `v3.0`
=> dev, v3.0/tidb-in-kubernetes: fix broken links in the K8s docs

dev/how-to/get-started/deploy-tidb-from-docker-compose.md, v3.0/how-to/get-started/deploy-tidb-from-docker-compose.md
This tidb-docker-compose repo is for testing only. Users may lose their data when they used it in production. We should warn the user not to use this repo in production.
There is a warning on the Chinese docs site: https://pingcap.com/docs-cn/v3.0/how-to/get-started/deploy-tidb-from-docker-compose/
https://github.com/pingcap/tidb-docker-compose/pull/76
dev
v3.0
=> dev, v3.0/how-to/get-started: Warn the user not to use tidb-docker-compose in production!

v2.1/faq/tidb.md, v2.1/how-to/deploy/orchestrated/ansible.md, v3.0/faq/tidb.md, v3.0/how-to/deploy/orchestrated/ansible.md
This PR recovers the link of `docker-compose` document (of the `dev` version) in the `v2.1` and `v3.0` documents.
https://github.com/pingcap/docs/pull/1401
`v3.0` `v2.1`
=> v.3.0, V2.1/how-to/deploy, */faq: recover the docker-compose link

dev/how-to/maintain/tidb-binlog.md, v2.1/how-to/maintain/tidb-binlog.md, v3.0/how-to/maintain/tidb-binlog.md
- Add a tip for binlogctl's usage
https://github.com/pingcap/docs-cn/pull/1663
dev, v3.0, v2.1
=> dev/v3.0/v2.1: add a tip for binlogctl's usage

.circleci/config.yml, dev/reference/system-databases/information-schema.md, scripts/markdown-link-check.tpl, scripts/verify-links.sh, v3.0/how-to/get-started/read-historical-data.md, v3.0/reference/system-databases/information-schema.md
This has been merged into [docs-cn repo](https://github.com/pingcap/docs-cn/pull/1693).
Add a script to verify internal links and fix some broken links under dev and v3.0 directories.
- External links are ignored in CI because these links may go down out of our control.
- Anchors are ignored
- Internal links conventions
- Links starting with '/media/' are relative to the site root
- Links starting with one or two dots are relative to the directory in which files reside
- Other links are relative to the root of the version directory (e.g. v1.0, v2.0, v3.0)
- When a file was moved, all other references are required to be updated for now, even if alias is given
- This is recommended because of fewer redirects and better anchors support.
Why: Avoid broken links in CI phrase.
dev
v3.0
=> scripts: add verify links check and fix some broken links

dev/tidb-in-kubernetes/deploy/gcp-gke.md, v3.0/tidb-in-kubernetes/deploy/gcp-gke.md
restore content that was removed in the transfer from tidb-operator
Added to tidb-operator: https://github.com/pingcap/tidb-operator/pull/585/files
Removed: https://github.com/pingcap/tidb-operator/pull/705/files#diff-ea4293f64d3f0d34ff19896800cda238L67
Latest version: https://raw.githubusercontent.com/aylei/tidb-operator/fc2e27dae2e699e523d493ec21dced77ea5719ae/deploy/gcp/README.md
=> k8s/gke terraform: missing content

dev/reference/sql/language-structure/keywords-and-reserved-words.md, v2.1/reference/sql/language-structure/keywords-and-reserved-words.md, v3.0/reference/sql/language-structure/keywords-and-reserved-words.md
Reorganize the list of keywords and reserved words
dev, v2.1, v3.0
=> dev, v2.1, v3.0: reorganize the list of keywords and reserved words

v2.1/reference/sql/language-structure/keywords-and-reserved-words.md
v2.1/reference/sql: remove "ROWS (R)" from the reserved word list
https://github.com/pingcap/docs/pull/1428
v2.1
=> v2.1/reference/sql: remove "ROWS (R)" from the reserved word list

scripts/check_requirement.sh
1. After `golang.tar.gz` was unzipped, we can append a command `export PATH=...` to profile settings.
2. We can add a tip to let the developers know that they need to update env variables if they don't have Rust or Go installed before.
@siddontang PTAL
=> scripts: append go/bin to $PATH

dev/reference/tools/tidb-binlog/reparo.md, v2.1/reference/tools/tidb-binlog/reparo.md, v3.0/reference/tools/tidb-binlog/reparo.md
- Add a `safe-mode` config in binlog reparo doc
https://github.com/pingcap/docs-cn/pull/1558 (original)
https://github.com/pingcap/docs/pull/1422 (with CLA error)
dev, v3.0, v2.1
=> dev, v3.0, v2.1: add safe-mode config in binlog reparo doc (new)

dev/releases/3.0.2.md, v3.0/releases/3.0.2.md
The release in TiDB Binlog has a mistake in 
```
Add the node-id configuration in Drainer to specify a specific logic used by Drainer
```
The configuration should be `node-id` rather than `note-id`
docs-cn: https://github.com/pingcap/docs-cn/pull/1733
V3.0, Dev
=> dev/releases, v3.0/releases: fix the 3.0.2 tidb binlog releaes mistake

dev/tidb-in-kubernetes/reference/configuration/tidb-cluster.md, v3.0/tidb-in-kubernetes/reference/configuration/tidb-cluster.md
Fix `extraLabels` description in TiDB in K8s doc
https://github.com/pingcap/docs-cn/pull/1736
dev, v3.0
=> tidb-in-kubernetes: fix "extraLabels" description

dev/reference/configuration/tidb-server/tidb-specific-variables.md, v2.1/reference/configuration/tidb-server/tidb-specific-variables.md, v3.0/reference/configuration/tidb-server/tidb-specific-variables.md
This PR renames `tidb_back_off_weight` to `tidb_backoff_weight` to make it consistent with `tidb_backoff_lock_fast`.
https://github.com/pingcap/docs-cn/pull/1722
dev, v3.0, v2.1
=> dev/v3.0/v2.1: rename tidb_back_off_weight to tidb_backoff_weight

dev/tidb-in-kubernetes/monitor/tidb-in-kubernetes.md, dev/tidb-in-kubernetes/reference/tools/in-kubernetes.md, v3.0/tidb-in-kubernetes/monitor/tidb-in-kubernetes.md, v3.0/tidb-in-kubernetes/reference/tools/in-kubernetes.md
Signed-off-by: Aylei <rayingecho@gmail.com>
Run port-forward in background to not blocking users
Related PR: https://github.com/pingcap/docs-cn/pull/1753
`dev` `3.0`
=> dev,3.0: run port-forward in background to not blocking users

dev/reference/configuration/tidb-server/tidb-specific-variables.md, v2.1-legacy/sql/tidb-specific.md, v2.1/reference/configuration/tidb-server/tidb-specific-variables.md, v3.0/reference/configuration/tidb-server/tidb-specific-variables.md
- Correct the scope of a tidb_opt_insubquery_unfold for release-2.1
- Remove tidb_opt_insubquery_unfold since master and 3.0 do not support it
https://github.com/pingcap/docs-cn/pull/1763
dev, v3.0, v2.1, v2.1-legacy
=> dev, v3.0, v2.1, v2.1-legacy: correct the scope of a tidb_opt_insubquery_unfold

dev/reference/configuration/tidb-server/configuration-file.md, v3.0/reference/configuration/tidb-server/configuration-file.md
- Remove the description of `retry-limit` in the configuration-file document, because retry-limit is removed after v3.0
- Update format
https://github.com/pingcap/docs-cn/pull/1791
dev, v3.0
=> reference/configuration: remove retry-limit from the config file

dev/tidb-in-kubernetes/deploy/gcp-gke.md, v3.0/tidb-in-kubernetes/deploy/gcp-gke.md
Adds a section to gke terraform guide on using fluent bit instead of fluentd (default log collector on gke)
N/A
3.0 and dev
=> Gke terraform add section fluentbit vs fluentd

dev/reference/sql/data-types/string.md, v2.0/sql/datatype.md, v2.1/reference/sql/data-types/string.md, v3.0/reference/sql/data-types/string.md
Change `TINYTEXT[(M)]` to `TINYTEXT`. 
Because both MySQL and TiDB don't support create a column with type `TINYTEXT(number)` but `TINYTEXT`.
```SQL
> select tidb_version() \G
tidb_version() | Release Version: v4.0.0-alpha-103-g9d71884e0
Git Commit Hash: 9d71884e0fc6a7ccb31bf0bfc91baec6b85e79a7
Git Branch: master
UTC Build Time: 2019-08-21 03:43:29
GoVersion: go version go1.12.5 darwin/amd64
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
> create table t_1(tt5 tinytext(5))  -- This will throw error
(1064, 'You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 30 near "(5))" ')
> create table t_1(tt5 tinytext) -- This is OK
``` …
=> reference/sql/data-types/string : fix syntax for tinytext

dev/reference/sql/statements/modify-column.md, v2.1/reference/sql/statements/modify-column.md, v3.0/reference/sql/statements/modify-column.md
Add a description to prohibit modifying the precision of decimals
https://github.com/pingcap/docs-cn/pull/1790
dev, v3.0, v2.1
=> reference/sql: prohibit modifying decimal precision

dev/reference/tools/pd-control.md, v2.1-legacy/tools/pd-control.md, v2.1/reference/tools/pd-control.md, v3.0/reference/tools/pd-control.md
This PR fixes a command typo in `pd-control.md`.
https://github.com/pingcap/docs-cn/pull/1845
`dev`, `v2.1`, `v3.0`
=> reference/tools: fix a command typo

dev/reference/performance/statistics.md, v2.1/reference/performance/statistics.md, v3.0/reference/performance/statistics.md
This PR changes the value of tidb_distsql_scan_concurrency from 10 to 15 in `statistics.md`
https://github.com/pingcap/docs-cn/pull/1904
dev, v2.1, v3.0
=> reference: modify the default value description of tidb_distsql_scan_concurrency

dev/reference/configuration/tidb-server/configuration-file.md, v3.0/reference/configuration/tidb-server/configuration-file.md
This PR fixes the default capacity of `txn-local-latches` in `configuration-file.md`.
https://github.com/pingcap/docs-cn/pull/1908
dev, v3.0
=> reference: fix the default capacity of txn-local-latches

dev/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-minikube.md, v3.0/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-minikube.md
This PR fix a grep command error which will appear on macOS.
https://github.com/pingcap/docs/issues/1580
https://github.com/pingcap/docs/blob/master/v3.0/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-minikube.md#install-helm
dev
I'll update v3.0 when I get two LGTM.
=> tidb-in-kubernetes/get-started: fix grep error on macOS

dev/reference/configuration/tidb-server/tidb-specific-variables.md, v2.1/reference/configuration/tidb-server/tidb-specific-variables.md
TiDB supports the `tidb_allow_remove_auto_inc` variable from v2.1.18. This PR changes `v2.1.8` to `v2.1.18`.
https://github.com/pingcap/docs-cn/pull/2007
dev, v2.1
=> reference/configuration: fix feature introduced-version

dev/reference/security/cert-based-authentication.md, v3.0/reference/security/cert-based-authentication.md
fix type OpenSS to OpenSSL
https://pingcap.com/docs/stable/reference/security/cert-based-authentication/
https://github.com/pingcap/docs/pull/1737
3.0, 3.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/docs/1739)
=> security: fix typo in cert-base-auth

dev/reference/sql/functions-and-operators/expressions-pushed-down.md, v3.0/reference/sql/functions-and-operators/expressions-pushed-down.md, v3.1/reference/sql/functions-and-operators/expressions-pushed-down.md
This PR updates description about pushdown expression alias before v3.0.3.
=> reference/sql: correct description about push_down expression alias before v3.0.3

dev/reference/tools/tidb-lightning/config.md, v3.0/reference/tools/tidb-lightning/config.md, v3.1/reference/tools/tidb-lightning/config.md
Adds reference to `-tidb-password` command line flag for tidb-lightning in the config section
https://github.com/pingcap/tidb-lightning/pull/253
dev, 3.0, 3.1
=> reference/tools: add "-tidb-password" cli flag in tidb-lightning config

dev/faq/tidb.md, dev/reference/configuration/tidb-server/tidb-specific-variables.md, v1.0/FAQ.md, v2.0/FAQ.md, v2.1-legacy/FAQ.md, v2.1-legacy/sql/tidb-specific.md, v2.1/faq/tidb.md, v2.1/reference/configuration/tidb-server/tidb-specific-variables.md, v3.0/faq/tidb.md, v3.0/reference/configuration/tidb-server/tidb-specific-variables.md, v3.1/faq/tidb.md, v3.1/reference/configuration/tidb-server/tidb-specific-variables.md
Remove warnings for `tidb_batch_insert` and `tidb_batch_delete`.
=> *: remove tidb_batch_insert and tidb_batch_delete

dev/reference/sql/statements/admin.md
Update `admin` syntax for TiDB 4.0.
=> reference: update sql admin syntax

dev/how-to/get-started/deploy-tidb-from-docker-compose.md, dev/tidb-in-kubernetes/reference/tools/in-kubernetes.md, v2.1-legacy/op-guide/docker-compose.md, v3.0/tidb-in-kubernetes/reference/tools/in-kubernetes.md, v3.1/tidb-in-kubernetes/reference/tools/in-kubernetes.md
=> *: add specific Helm version

dev/how-to/get-started/deploy-tidb-from-docker-compose.md
Fix repeated sentence introduced by previous pr.
=> how-to/get-started: remove repeated sentence

dev/reference/error-codes.md
Add error codes in dev/reference.
=> reference: add error codes

README.md, dev-guide/deploy.md, dev-guide/develop.md, dev-guide/requirements.md, scripts/markdown-link-check.tpl, scripts/verify-links.sh
=> 3.1/scripts: update verify links to fix current layout 

dev-guide/deploy.md, dev-guide/develop.md, dev-guide/requirements.md, scripts/markdown-link-check.tpl, scripts/verify-links.sh
re-enable links must start with slash check
- This PR is to align with:
=> scripts: re-enable links must start with slash check

how-to/maintain/identify-abnormal-queries/identify-slow-queries.md, reference/configuration/tidb-server/configuration-file.md
TiDB supports turn on/off `slow-log` by a config variable in 4.0, the config variable `enable-slow-log` is added in this PR into docs.
- This PR is to align with:pingcap/docs-cn#2259
=> *: add config variable enable-slow-log

reference/tools/download.md
Remove the latest version from the download document.
Some users use the latest version, but the latest version is built from our develop branch, which is unstable and may be incompatible with the release version. We don't suggest users use the latest version.
- This PR is to align with: https://github.com/pingcap/docs-cn/pull/2296
=> reference/tools: remove latest from download document

reference/mysql-compatibility.md
Added a note about ALTER TABLE in TiDB not supporting multiple ALTER operations in a single statement.
=> Add note about not supporting multiple ALTER TABLE operations

reference/performance/optimizer-hints.md
Moved several optimizer hints from "runtime" chapter to "optimizer" chapter.
- This PR is to align with:pingcap/docs-cn#2252
=> reference/performance: move optimizer hints to proper section

CONTRIBUTING.md, README.md
- Rewrite `README.md` to make it more like a docs readme (replace simply intro to TiDB)
- Rewrite `CONTRIBUTING.md` to add more resources
**Note:** Markdownlint rules will be added to a separate file (in `resources`) later in another PR.
- This PR is to align with: https://github.com/pingcap/docs-cn/pull/2017
=> readme, contributing: rewrite contribution resources

reference/performance/understanding-the-query-execution-plan.md
In `explain analyze` statements, `count` should be compared to `rows`, instead of `rows/loops`.
This PR fixed it.
=>  reference/performance: Fix `EXPLAIN ANALYZE output format`. 

faq/tidb.md
=> faq: fix the sysbench link

reference/configuration/tidb-server/tidb-specific-variables.md
```
change tidb_ddl_reorg_worker_cnt 's default value from 16 to 4
change tidb_ddl_reorg_batch_size 's default value from 1024 to 256
```
```
tidb_ddl_reorg_worker_cnt 's default value is 4
tidb_ddl_reorg_batch_size 's default value is 256 
```
- [ ✅] master (the latest development version, including v4.0 changes for now)
=> change default value for  tidb_ddl_reorg_worker_cnt and tidb_ddl_reorg_batch_size

reference/configuration/tidb-server/tidb-specific-variables.md
```
change tidb_ddl_reorg_worker_cnt 's default value from 16 to 4
change tidb_ddl_reorg_batch_size 's default value from 1024 to 256
```
```
tidb_ddl_reorg_worker_cnt 's default value is 4
tidb_ddl_reorg_batch_size 's default value is 256 
```
- [ ✅] v3.1 (TiDB 3.1 versions)
=> change default value for tidb_ddl_reorg_worker_cnt and tidb_ddl_reorg_batch_size

reference/configuration/tidb-server/configuration-file.md
`stmt-count-limit` does not work for all types of transactions. Update its note.
`[事务重试](/reference/transactions/transaction-optimistic.md#事务的重试)` is still being translated into English in [#1695](https://github.com/pingcap/docs/pull/1695), so I remove this link in this PR and will add it back when #1695 is merged.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/2363
=> reference/configuration: update note for stmt-count-limit

reference/configuration/tidb-server/configuration-file.md
Update a note for `stmt-count-limit` in v3.0/3.1.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/2371 https://github.com/pingcap/docs-cn/pull/2370
- Other reference link(s): https://github.com/pingcap/docs/pull/1984
=> reference/configuration: update note for stmt-count-limit in 3.0/3.1

TOC.md
Fix a wrong link in TOC for DM relay log.
N/A
=> TOC: fix a wrong link for DM relay log

reference/sql/generated-columns.md
clarify unsupported behavior in generated column 
- This PR is translated from: pingcap/docs-cn#2262
=> sql: clarify unsupported behavior in generated column

TOC.md
add TOC for sync-diff-inspector
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/2345
=> tools: add TOC for sync-diff-inspector

TOC.md, _index.md, faq/tidb.md, how-to/deploy/data-migration-with-ansible.md, how-to/deploy/geographic-redundancy/location-awareness.md, how-to/deploy/orchestrated/ansible.md, how-to/deploy/orchestrated/offline-ansible.md, how-to/monitor/monitor-a-cluster.md, how-to/scale/horizontally.md, how-to/upgrade/from-previous-version.md, overview.md, reference/key-monitoring-metrics/overview-dashboard.md, reference/key-monitoring-metrics/pd-dashboard.md, reference/key-monitoring-metrics/tidb-dashboard.md, reference/key-monitoring-metrics/tikv-dashboard.md, reference/tidb-binlog/deploy.md, reference/tidb-binlog/monitor.md, reference/tidb-binlog/tidb-binlog-kafka.md, reference/tidb-binlog/tidb-binlog-local.md, reference/tidb-binlog/upgrade.md, reference/tools/data-migration/cluster-operations.md, reference/tools/data-migration/faq.md, reference/tools/tidb-lightning/deployment.md, reference/tools/tikv-control.md
Change `Ansible` to `TiDB Ansible` or `DM-Ansible` in proper places.
v2.1 is updated in [#2110](https://github.com/pingcap/docs/pull/2110) to avoid excessive conflicts.
=> *: unify ansible names

.github/pull_request_template.md, CONTRIBUTING.md
update guiding resources
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/2628
=> *: update guiding resources

reference/tiflash/maintain.md
Explain how to set query tso to 1 second earlier
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/2659
=> TiFlash: Explain how to set query tso to 1 second earlier

reference/tiflash/scale.md
Update TiFlash scale doc for the latest TiDB version.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/2641
=> tiflash: update scale doc for 4.0

TOC.md, reference/tiflash/upgrade.md
Add `upgrade.md` doc for TiFlash 3.1
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/2655
=> tiflash: add upgrade doc for 3.1

reference/performance/optimizer-hints.md
Add a note to specify index name of primary key for USE_INDEX_MERGE
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/2350
=> reference/performance: specify index name of primary key for USE_INDEX_MERGE

TOC.md, reference/tiflash/deploy.md
=> toc, tiflash: fix link to tiup

how-to/deploy/orchestrated/tiup.md
fix deploy stop command
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/2757
=> tiup: fix deploy stop command

reference/configuration/tidb-server/tidb-specific-variables.md
Add description for new variable tidb_row_format_version.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/2605
=> reference/configuration: add tidb_row_format_version

reference/configuration/tikv-server/configuration-file.md
Signed-off-by: Yilin Chen <sticnarf@gmail.com>
Add more descriptions to the unified read pool. It would help users understand better.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/2776
=> reference: add more descriptions to readpool.unified

TOC.md, releases/3.1.0-ga.md, releases/rn.md
Add 3.1 GA release notes.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/2777
=> releases, toc: add 3.1.0 GA release notes

reference/transactions/overview.md
Align a sentence in https://github.com/pingcap/docs-cn/pull/2456.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/2456
- Other reference link(s): https://github.com/pingcap/docs/pull/2002
=> reference/transaction: add a description

_index.md, faq/tidb.md, how-to/deploy/orchestrated/ansible.md, how-to/deploy/orchestrated/docker.md, how-to/deploy/orchestrated/tiup.md, how-to/get-started/deploy-tidb-from-docker-compose.md, overview.md
Update recommended deployment methods in multiple docs to TiUP.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/2768
=> *: update recommended deployment to TiUP

_index.md, overview.md
Remove offline ansible deployment from `_index.md` and `overview.md` because we recommended users use TiUP to deploy TiDB clusters.
- Other reference link(s): #2308
=> index, overview: remove offline ansible deployment

reference/sql/statements/split-region.md
Update doc for the `split table` statement.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/2810
=> sql: update doc for split partition table

quick-start-with-tidb.md
The `copyable` code snippet misses a `{`.
=> quick-start-with-tidb: fix typo

reference/configuration/tidb-server/configuration-file.md
Add a description of `max-index-length`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/2748
=> reference: add a description of max-index-length

how-to/deploy/orchestrated/tiup.md, quick-start-with-tidb.md
TiUP: fix grammar and format for topology.example.yaml
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/2846
- Other reference link(s):pingcap-incubator/tiup-cluster#298
=> TiUP: fix grammar and format for topology.example.yaml

reference/configuration/tidb-server/configuration-file.md
Add a new config `temp-storage-quota` in tidb-server config document.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/2685 https://github.com/pingcap/docs-cn/pull/2771
=> reference: add a new config in tidb-server config doc

TOC.md, reference/tools/ticdc/column-ddl-type.md, reference/tools/ticdc/open-protocol.md, reference/tools/ticdc/overview.md
Add TiCDC Open Protocol documents.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/2550 https://github.com/pingcap/docs-cn/pull/2700 https://github.com/pingcap/docs-cn/pull/2763
=> reference/tools: add ticdc open protocol docs

how-to/deploy/orchestrated/tiup.md, quick-start-with-tidb.md
Update the default value for `readpool.storage.use-unified-pool`
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/2877
=> tiup: update the default value for `readpool.storage.use-unified-pool`

reference/tidb-binlog/reparo.md
Remove useless config of reparo from `reference/tidb-binlog/reparo.md`
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/2828
=> tidb-binlog: remove config of reparo

reference/mysql-compatibility.md
Remove the limit of adding index on generated columns.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/2988 https://github.com/pingcap/docs-cn/pull/2989
=> reference: remove limit of adding index on generated columns

reference/configuration/tidb-server/tidb-specific-variables.md
add explaination about a new system variable `last_plan_from_cache` to tidb-specific-variables.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3023
=> add explaination about `last_plan_from_cache`

reference/sql/statements/admin.md
`admin show`, `admin cancel`, `admin check`, and `admin repair` appear twice in `admin.md`. This PR remove the duplicate content from 4.0
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/2749
=> sql: remove duplicate content from 4.0

pd-control.md, pd-recover.md
Update the Go version.
- Other reference link(s): https://github.com/pingcap/docs/pull/2600
=> update go version

functions-and-operators/expressions-pushed-down.md
=> functions-and-operators: fix 32 broken links

TOC.md, hardware-and-software-requirements.md
Update hardware-and-sofware-requirements.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/3228
=> how-to: update hardware-and-sofware-requirements

TOC.md, releases/release-3.0.13.md, releases/release-3.0.14.md, releases/release-3.1.2.md, releases/release-4.0.0-rc.1.md, releases/release-4.0.0-rc.2.md, releases/release-4.0.0-rc.md, releases/release-notes.md
Add TiDB 3.1.2 release notes.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3487
=> add 3.1.2 TiDB release notes

best-practices/haproxy-best-practices.md, functions-and-operators/expressions-pushed-down.md, functions-and-operators/operators.md, sql-statements/sql-statement-grant-privileges.md, sql-statements/sql-statement-revoke-privileges.md, sql-statements/sql-statement-set-names.md, sql-statements/sql-statement-set-transaction.md, sql-statements/sql-statement-set-variable.md, sql-statements/sql-statement-show-privileges.md, tidb-lightning/tidb-lightning-tidb-backend.md, tiflash/maintain-tiflash.md
=> *: fix unclosed tags

best-practices/haproxy-best-practices.md, sql-statements/sql-statement-revoke-privileges.md, sql-statements/sql-statement-set-names.md, sql-statements/sql-statement-set-transaction.md, sql-statements/sql-statement-show-privileges.md
=> *: fix unclosed tags in 2.1

TOC.md, releases/release-3.0.15.md, releases/release-notes.md
Add TiDB 3.0.15 release notes.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3510
=> releases: add tidb 3.0.15 release notes

transaction-overview.md
- This PR is translated from: https://github.com/pingcap/docs/pull/2815 
=> Fix a multiple times issue in transaction-overview.md

.github/assign-by-files.yml, .github/workflows/auto-assign.yml
makes yikeke the default reviewer for all prs in docs repo
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3637
=> add auto assign reviewer github action

_index.md, maintain-tidb-using-tiup.md, tidb-lightning/tidb-lightning-faq.md
Update the `_index.md` file with [new landing page format](https://github.com/pingcap/website-docs#landing-page-for-tidb)
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3393
=> *: update the index file with new format

TOC.md, sql-statements/sql-statement-load-stats.md
Add syntax gram of `load stats`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3362
=> sql statement: Add syntax gram of `load stats`

sql-statements/sql-statement-drop-sequence.md, sql-statements/sql-statement-show-character-set.md, sql-statements/sql-statement-show-collation.md
Update:
- sql-statements/sql-statement-drop-sequence.md
- sql-statements/sql-statement-show-character-set.md
- sql-statements/sql-statement-show-collation.md
https://github.com/pingcap/docs-cn/pull/3294
=> update several sql statement docs

sql-plan-management.md, sql-statements/sql-statement-show-bindings.md
- add descriptions about the parameter source introduced by pingcap/tidb#17254
- fix pingcap/tidb#16748
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3449
=> add descriptions about binding source

tiup/tiup-cluster.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3685
=>  tiup: update pd status description

.github/assign-by-files.yml, .github/workflows/auto-assign.yml
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3649, https://github.com/pingcap/docs-cn/pull/3778
=> fix auto assign reviewers github action

data-type-json.md, functions-and-operators/json-functions.md, generated-columns.md, tidb-configuration-file.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3752
=> add experimental feature warnings

tidb-specific-system-variables.md, tiflash/tune-tiflash-performance.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3265/, and a small part of https://github.com/pingcap/docs-cn/pull/3159/files#diff-36f1f55efb0294795b77879ecad344a0R869, https://github.com/pingcap/docs-cn/pull/3508
=> Add explaination about tidb_allow_batch_cop

sync-diff-inspector/upstream-downstream-diff.md
update master/slave to primary/secondary for binlog and sync-diff-inspector
- Other reference link(s): https://github.com/pingcap/tidb-binlog/pull/982
=> tools: update master/slave to primary/secondary for binlog and sync-diff-inspector

CONTRIBUTING.md, README.md, TOC.md, _index.md, architecture.md, br/backup-and-restore-use-cases.md, dashboard/dashboard-ops-deploy.md, deploy-test-cluster-using-docker-compose.md, download-ecosystem-tools.md, ecosystem-tool-user-case.md, ecosystem-tool-user-guide.md, load-misuse-handling.md, migrate-from-aurora-mysql-database.md, overview.md, quick-start-with-tidb.md, test-deployment-using-docker.md, tidb-troubleshooting-map.md
- Update links: `stable` to `v4.0` for tidb, `v1.1` for tidb-operator, `v1.0` for dm
- Updata old links to new links with `docs.pingcap.com`
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3789
=> *: update links from stable to v4.0 and new docs urls

production-deployment-using-tiup.md, ticdc/manage-ticdc.md, tiflash/maintain-tiflash.md, tiflash/tiflash-configuration.md
part of https://github.com/pingcap/docs-cn/pull/3532, 
https://github.com/pingcap/docs-cn/pull/3599, 
a link from https://github.com/pingcap/docs-cn/pull/3341
=> update tiflash configs and maintain-tiflash.md

command-line-flags-for-tidb-configuration.md, tidb-configuration-file.md, tidb-specific-system-variables.md
Update the `tidb` config file and command-line argument documents, add new configs and remove deprecated ones .
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3148, https://github.com/pingcap/docs-cn/pull/3421/, a variable description from https://github.com/pingcap/docs-cn/pull/3159
=> update the tidb configuration documents

telemetry.md
Add a note about TiDB Operator v1.1.2 requirement 
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3842
=> en: Add operator version requirement for telemetry config

.circleci/config.yml, certificate-authentication.md, glossary.md, optimistic-transaction.md, pessimistic-transaction.md, scripts/verify-link-anchors.sh, scripts/verify-links.sh, sql-statements/sql-statement-recover-table.md, tidb-binlog/handle-tidb-binlog-errors.md, tidb-lightning/deploy-tidb-lightning.md, tidb-lightning/tidb-lightning-faq.md, tune-operating-system.md
=>  Add scripts to verify anchors in CI (#3128)

.circleci/config.yml, faq/tidb-faq.md, glossary.md, optimistic-transaction.md, scripts/verify-link-anchors.sh, scripts/verify-links.sh, tidb-binlog/handle-tidb-binlog-errors.md, tidb-lightning/deploy-tidb-lightning.md, tune-operating-system.md
=> Add scripts to verify anchors in CI (#3128)

production-deployment-using-tiup.md
`deploy-tiflash.md` is reorganized as part of `production-deployment-using-tiup.md`.
This PR adds an alias for TiFlash deployment in `production-deployment-using-tiup.md`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3877
=> add aliases for tiflash deployment

mysql-compatibility.md, sql-statements/sql-statement-analyze-table.md
This improves some aspects of describing MySQL compatibility.
I thought it was important to point to GitHub issues on some of the more common feature requests, and explain in more detailed context than ROI why some features may not be available.
The DDL section was hard to read, so I reformatted it to focus on what was missing versus what was supported.
The ANALYZE TABLE update fixes #2478
fixes #2478 + some additional changes.
=> mysql-compatibility: Improve MySQL Compatibility

benchmark/v3.0-performance-benchmarking-with-sysbench.md, benchmark/v3.0-performance-benchmarking-with-tpcc.md
Add aliases for `benchmark/v3.0-performance-benchmarking-with-sysbench.md` and `benchmark/v3.0-performance-benchmarking-with-tpcc.md` deleted in `release-4.0` branch.
- Other reference link(s): https://github.com/pingcap/docs/pull/3181
=> Add aliases for 3.0 sysbench docs

optimistic-transaction.md
The documentation claimed optimistic transactions are the default. This is only true for v2.1.
=> optimistic-transaction: remove reference to being "default"

tikv-configuration-file.md
- Correct the default value of `hibernate_regions`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3980
=> Correct the default value of `hibernate_regions`

br/backup-and-restore-tool.md
Refine an expression.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3656
=> br: refine an expression

sql-statements/sql-statement-show-table-regions.md
The examples in `SHOW TABLE REGIONS` were not paste-reproducible with multiple regions included. This makes it a bit harder for users to understand how these features work.
I have rewritten the first example, and added a section at the bottom to show this is an extension to MySQL syntax.
=> sql-statements: improve SHOW TABLE REGIONS examples

TOC.md, sql-statements/sql-statement-show-stats-healthy.md
Adds a statement guide for `SHOW STATS_HEALTHY`. It looks like a really useful command for pointing directly to from support issues, such as https://github.com/pingcap/tidb/issues/18720
=> sql-statements: add SHOW STATS_HEALTHY

daily-check.md, post-installation-check.md, production-deployment-using-tiup.md, quick-start-with-tidb.md, tidb-best-practices.md, tiflash/use-tiflash.md, tiup/tiup-cluster.md, tiup/tiup-playground.md, whats-new-in-tidb-4.0.md
This PR add links to places that mention TiDB Dashboard.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3823
=> Reference TiDB Dashboard intro for TiDB Dashboard links

query-execution-plan.md
=> fix aliases in query-execution-plan.md

tiup/tiup-cluster.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3489
=> Add environment checks for target machines

tikv-configuration-file.md
Update the calculation of block-cache-size.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/4086, https://github.com/pingcap/docs-cn/pull/3420
=> Unify the calculation of defaultCF - block-cache-size

auto-increment.md
The AUTO_INCREMENT doc used the word "continuous" when it should be "monotonic". Continuous means "without any abrupt changes", i.e. at a constant rate (which could be up or down). Auto_increment is not really constant - since restarts could make values jump quite a bit. So could requesting a new batch of cached values.
Monotonic means "either never decreases or never increases". Which is the property it guarantees on a per-server basis.
The language will need version-specific changes because it says "30 thousand by default", but it needs to be 30 thousand explicitly for 2.1 which does not support `AUTO_ID_CACHE`.
=> auto-increment: change "continuous" to monotonic

sql-statements/sql-statement-alter-index.md, sql-statements/sql-statement-create-index.md
This only applies to master, which features invisible indexes.
It improves the consistency of the docs for ALTER INDEX to follow the common format (including `## MySQL compatibility`). There is some duplication in the page where it has examples, and then a section for invisible indexes with examples. Since the main use case for this statement is for invisible indexes, I merged the two together. The `## syntax` section is also somewhat redundant with both the synposis and examples sections. So I've removed it.
The `CREATE INDEX` docs are also updated to remove a broken link, pointing to `ALTER INDEX` for invisible index docs. Really invisible indexes should have its own documentation page, with these pages just being for statement reference - but that's for a different task. The text also …
=> sql-statements: improve alter index docs

system-variables.md
update description of the added variable.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4172
=> system-variables: add variable description

experimental-features-4.0.md, ticdc/manage-ticdc.md, ticdc/ticdc-overview.md
- add TiUP deployment prompt in TiCDC docs.
- update the doc link of filter rule.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4199; https://github.com/pingcap/docs-cn/pull/3965
- Other reference link(s): [TiCDC Overview](https://docs.pingcap.com/tidb/stable/ticdc-overview/#ticdc-overview); [Manage TiCDC Cluster and Replication Tasks](https://docs.pingcap.com/tidb/stable/manage-ticdc#manage-ticdc-cluster-and-replication-tasks)
=> ticdc: update tiup deployment prompt and filter rule link

sql-statements/sql-statement-commit.md, sql-statements/sql-statement-rollback.md, sql-statements/sql-statement-start-transaction.md
The rollback docs mentioned the completiontype, but didn't include the definition of it.
The mysql compatibility sections of commit and rollback talked about completiontype, but should have explained the syntax better, and the recommended alternative - since in both cases its pretty straight forward.
I have also mentioned savepoints, since it wasn't covered.
=> sql-statements: readability of commit/rollback

dumpling-overview.md
The example for dumpling shows usage of the `-F` flag without a unit of measurement. This works, but produces a warning saying you shouldn't :-) So lets not in our examples.
=> dumpling: add unit to -F

mydumper-overview.md
The way the current warning is written, it is a bit ambiguous as to which maintainers have stopped development. Let's be more careful not to throw mydumper developers under a bus and imply their project is end of life :-)
=> mydumper: Improve clarity of mydumper warning

role-based-access-control.md
To close [#2496](https://github.com/pingcap/docs-cn/issues/2496)
make example easier to understand.
user can try RBAC by simply copy and paste sql in doc.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/2570
=> sql: make example in RBAC doc easier to understand

tidb-binlog/maintain-tidb-binlog-cluster.md
tidb v4.0 modify show log_bin result, just use 0 and 1 , not use ON and OFF.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4431
=> Change the returned value of log-binlog from on/off to 1/0

optimizer-hints.md
Add dos for `nth_plan()`hint in optimizer-hints.md.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4227
- Other reference link(s): https://github.com/pingcap/tidb/issues/17580
=> optimizer-hints: add docs for `nth_plan()` hint

system-variables.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4442
=> Fix the incorrect version for allow_auto_random_explicit_insert

download-ecosystem-tools.md
remove unnecessary download version(kafka specific version) for binlog. it's is confusing because current binlog version already support kafka sink.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4443
=> tools: remove unnecessary kafka version binlog

br/backup-and-restore-faq.md
Add use constraint with TiCDC and Drainer.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3750
- Other reference link(s): https://github.com/pingcap/docs/pull/3833
=> br: add use constraint with TiCDC and Drainer

import-example-data.md, sql-statements/sql-statement-load-data.md, system-variables.md
Part of https://github.com/pingcap/docs/issues/3155
Only relevant to master.
=> stmt-reference, sysvars: Document dml-batch-size

ticdc/manage-ticdc.md
After test, the minimum Kafka version that CDC supports is 0.11.0.2.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4483
=> ticdc: update kafka minumum version

statistics.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4331
=> Change the default value of `feedback-probability`

system-variables.md
add system variable 'tidb_enable_clustered_index' for v5.0
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4385
=> add system variable 'tidb_enable_clustered_index' for v5.0

connectors-and-apis.md, faq/tidb-faq.md, security-compatibility-with-mysql.md, user-account-management.md
Documentation for my patch in https://github.com/pingcap/tidb/pull/19603
It can be backported to 4.0 once https://github.com/pingcap/tidb/pull/19959 merges
Because TiDB now supports MySQL 8.0 connectors, the warnings on these pages are no longer required.
=> auth: Remove note about MySQL 8.0 auth plugin

sql-statements/sql-statement-select.md, system-variables.md
This PR updates a docs case for https://github.com/pingcap/tidb/pull/19506 that was missed earlier.
This only applies to master.
I fixed another case of inconsistent formatting that is unrelated.
=> stmt reference: update sql_calc_found_rows

system-variables.md
These variables do not take any effect, are deprecated in current version, and will be removed in the next major release.
So I remove them from the documentation now.
=> system-variables: remove the useless memory quota variables

TOC.md, enable-disk-spill-encrypt.md
add the `enable-disk-spill-encrypt.md` to descript the usage of the `spilled-file-encryption-method`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4557
- Other reference link(s): https://github.com/pingcap/tidb/pull/19070 https://github.com/pingcap/docs/pull/3700
=> Add `enable-disk-spill-encrypt.md` to decrypt the usage of the `spilled-file-encryption-method`

faq/tidb-faq.md, sql-statements/sql-statement-create-index.md, tidb-configuration-file.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4641
=> *: remove expression index out of experimental feature

dashboard/dashboard-faq.md, optimizer-hints.md, sql-prepare-plan-cache.md, tidb-configuration-file.md
This PR covers the docs portion of https://github.com/pingcap/tidb/issues/20306
It only applies to master. It can be reviewed now, but should merge after https://github.com/pingcap/tidb/pull/20416 is merged.
=> prepared plan cache: Enable by default

ticdc/manage-ticdc.md
Add more protocol in ticdc sink config.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4691
=> ticdc: add more protocol in ticdc sink config

mysql-compatibility.md
The "Type system differences" section was updated as it TiDB supports some of the types that were listed as unsupported.
TiDB:
```
mysql> SELECT tidb_version()\G
tidb_version(): Release Version: v4.0.8
Edition: Community
Git Commit Hash: 66ac9fc31f1733e5eb8d11891ec1b38f9c422817
Git Branch: heads/refs/tags/v4.0.8
UTC Build Time: 2020-10-30 08:21:16
GoVersion: go1.13
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
mysql> CREATE TABLE t1 (id SERIAL, y SQL_TSI_YEAR, f FIXED(4,2));
Query OK, 0 rows affected (0.11 sec)
mysql> SHOW CREATE TABLE t1\G
Table: t1
Create Table: CREATE …
```
=> Update "Type system differences" for MySQL Compatibility

auto-increment.md
why: issue: #699
Capitalize sql keywords
=> AUTO_INCREMENT: Capitalize sql keywords

sql-logical-optimization.md, system-variables.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4771
=> Migrate contributor PRs with pending CLA

ticdc/ticdc-open-protocol.md
Fixed some typos in the CDC open protocol.
TINTTEXT → TINYTEXT
Too little backslashes in the VARBINARY/BINARY examples, there should be two backslashes in the rendered JSON, and thus four backslashes in markdown.
\x80...\xFF are not ASCII, just don't mention ASCII.
BinaryFlag is used for VARBINARY/BINARY too, don't just mention the BLOB family.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4741
=> ticdc: fix some typos in the open protocol 

sql-statements/sql-statement-show-variables.md, system-variables.md, tidb-configuration-file.md
`enable-streaming` is not well maintained because we are focusing on optimizing the non-streaming coprocessor API for its performance and resource usage and don’t have time to optimize streaming's currently, I propose to deprecate it temporarily until somebody has time to pick it up again and prove it could be GA in the future.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4781
=> config: hide & deprecate enable-streaming

pessimistic-transaction.md
After TiDB v4.0.6, autocommit transactions will turn to use pessimistic transaction during retries.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4807
=> tidb: update autocommit behavior description of pessimistic transactions

tikv-configuration-file.md
Remove storage.scheduler-notify-capacity config.
- Other reference link(s): https://github.com/tikv/tikv/pull/5827
=> tikv: remove storage.scheduler-notify-capacity

dumpling-overview.md
add how to dump to amazon s3 for dumpling
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4626
=> add how to dump to amazon s3 for dumpling

sql-statements/sql-statement-admin.md
Replace backticks with `<code>` for the inline code. This fixes a display error.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4903
=> sql: replace backticks with <code> for the inline code

tiflash/use-tiflash.md
Add `round without fraction` to TiFlash's push down expression list.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4910
=> tiflash: update TiFlash's pushdown expression list

partitioned-table.md, tiflash/tiflash-configuration.md
+ Support `INFORMATION_SCHEMA.PARTITION` since 4.0.8
+ Fix wrong default value in tiflash config doc
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4916 https://github.com/pingcap/docs-cn/pull/4911
=> Fix wrong default value in tiflash config doc

br/backup-and-restore-use-cases.md
Add BR adaptive GC description.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4885
=> br: update adaptive GC description

character-set-and-collation.md
Fix a typo in character-set-and-collation.md:
update the charset name from ut8mb4 to utf8mb4.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4949
=> Fix a typo in character-set-and-collation.md

tiflash/use-tiflash.md
update document to use tiflash in tispark
parameter `spark.tispark.use.tiflash` is replaced with `spark.tispark.isolation_read_engines`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5030
=> update document to use tiflash in tispark

tiflash/tiflash-configuration.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5078
=> tiflash: add config item about tiflash io rate limit

tiflash/tiflash-configuration.md
Add description of `delta_index_cache_size` configuration for TiFlash.
- This PR is translated from: [https://github.com/pingcap/docs-cn/pull/5086](https://github.com/pingcap/docs-cn/pull/5086)
=> TiFlash config: Add description for delta_index_cache_size

alert-rules.md, benchmark/benchmark-tidb-using-sysbench.md, explain-walkthrough.md, functions-and-operators/aggregate-group-by-functions.md, tidb-troubleshooting-map.md, troubleshoot-tidb-lightning.md, whats-new-in-tidb-4.0.md
Change ordinal numbers to numbers or to spell-out format according to the rules of Google developer documentation style guide.
- Other reference link(s): https://developers.google.com/style/numbers#ordinal-numbers https://developers.google.com/style/dates-times#partial-dates-abbreviations
=> Change ordinal numbers to numbers or spell-out format 

pd-configuration-file.md, pd-control.md
Add a new configuration `region-score-formula-version` and updated the default value of `enable-cross-table-merge` for v5.0.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5153
=> pd: add new configurations 

tiflash/tiflash-configuration.md
Make `bg_task_io_rate_limit` setting in tiflash.toml experimental. Since it is released as experimental feature in 5.0.0-rc.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5180
=> Make bg_task_io_rate_limit setting experimental

clustered-indexes.md
Fix double h1 headlines in `clustered-indexes.md`
=> fix headline md lint issue

garbage-collection-configuration.md, tikv-configuration-file.md
Set gc in compaction filter by default.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5183
=> disable gc in compaction filter by default

system-variables.md
Add docs for the new system variable, tidb_executor_concurrency.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3975
=> Add doc for tidb_executor_concurrency

TOC.md, _index.md, clustered-indexes.md, log-redaction.md, maintain-tidb-using-tiup.md, pd-configuration-file.md, production-deployment-using-tiup.md, production-offline-deployment-using-tiup.md, releases/release-5.0.0-rc.md, releases/release-notes.md, scale-tidb-using-tiup.md, system-variables.md, tidb-configuration-file.md, tikv-configuration-file.md, upgrade-tidb-using-tiup.md
+ Add TiDB 5.0-rc release notes
+ Uncomment v5.0 version marks
+ Update anchors
+ Minor wording changes
+ Add What's New in TiDB 5.0 to TOC and `_index.md`
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5295
=> releases: add tidb 5.0-rc release notes

system-variables.md
The system variables documentation is incomplete and out of date. This helps improve it, but there are still many issues.
The following issues were fixed:
- https://github.com/pingcap/docs/issues/4532 variables did not appear in alphabetical order
- https://github.com/pingcap/docs/issues/4531 Default values for booleans are incorrect
- ~TiDB executor concurrency is not documented (this was introduced in master and is an important setting. If https://github.com/pingcap/docs-cn/pull/3975 merges, the translation can be overwritten here.)~
- ~The defaults for other executor concurrency options were incorrect. They also did not document if they were deprecated by executor concurrency.~
- The new options added have backticks in the heading. I've removed them for consistency.
- The options …
=> improve system-variables documentation

tikv-configuration-file.md
Update the default value of `use-unified-pool` from `false` to `true`.
- Other reference link(s): https://github.com/pingcap/docs/issues/4676
=> tikv-config-file: update the default value of use-unified-pool

production-offline-deployment-using-tiup.md, tiup/tiup-mirror.md
Remove the link of [Download TiDB | PingCAP](https://en.pingcap.com/download/) in `production-offline-deployment-using-tiup.md` because the [Download TiDB | PingCAP](https://en.pingcap.com/download/) page is designed not to provide the download link for TiUP offline package.
=> tiup: remove a false download link for tiup offline package

quick-start-with-tidb.md
tiflash does not support address 0.0.0.0
`[2021/01/04 14:30:48.404 +08:00] [FATAL] [setup.rs:254] ["invalid configuration: [src/server/config.rs:204]: invalid advertise-addr: \"0.0.0.0:20170\""]`
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5273
=> tiflash does not support address 0.0.0.0

expression-syntax.md, sql-statements/sql-statement-add-column.md, sql-statements/sql-statement-add-index.md, sql-statements/sql-statement-admin-cancel-ddl.md, sql-statements/sql-statement-admin-check-table-index.md, sql-statements/sql-statement-admin-checksum-table.md, sql-statements/sql-statement-admin-show-ddl.md, sql-statements/sql-statement-admin.md, sql-statements/sql-statement-alter-database.md, sql-statements/sql-statement-alter-index.md, sql-statements/sql-statement-alter-instance.md, sql-statements/sql-statement-alter-table.md, sql-statements/sql-statement-alter-user.md, sql-statements/sql-statement-analyze-table.md
This PR changes the synopsis sections of ADD, ALTER and ANALYZE statements to use the ```ebnf+diagrm block, replacing the original image-based sqlgrams.
To avoid making one single PR too large, I will open 4-5 follow-up PRs to process sql-statements files in batches. And I will delete all image files in the last PR in case of any display issues.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5324
=> sql-statements: use EBNF to render syntax diagrams for ADD, ALTER and ANALYZE statements

maintain-tidb-using-tiup.md, production-deployment-using-tiup.md, production-offline-deployment-using-tiup.md, scale-tidb-using-tiup.md, upgrade-tidb-using-tiup.md
This PR addresses https://github.com/pingcap/docs/issues/4529.
+ Remove the links to deprecated v4.0 Ansible docs in TiUP docs 
+ Remove the Ansible-related aliases from TiUP docs and add them to v4.0 Ansible docs (added in https://github.com/pingcap/docs/pull/4947)
=> Remove notes & aliases for deprecated Ansible in TiUP docs

log-redaction.md, pd-configuration-file.md, tiflash/tiflash-configuration.md
TiFlash and PD have picked the feature "redact-log" to the release-4.0 branch(released in 4.0.10), but forgot to add documents to the release-4.0 branch.
Add redact log configurations for TiFlash and PD.
=> Log redact on TiFlash and PD (4.0)

system-variables.md
Correct the heading level for a variable.
- Other reference link(s): https://github.com/pingcap/docs/pull/4741
=> system-variable: correct the heading level for a variable

tidb-configuration-file.md
`max-txn-ttl` should be in the `[performance]` section.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5707
=> tidb-configuration-file: fix wrong location of max-txn-ttl

benchmark/v4.0-performance-benchmarking-with-tpch.md, geo-distributed-deployment-topology.md, hybrid-deployment-topology.md
+ benchmark: add description to explain the non-index test result
+ Fix a typo: Region Group --> Raft Group
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5719 https://github.com/pingcap/docs-cn/pull/5689
=> benchmark: add description to explain the non-index test result

system-variables.md, transaction-overview.md
There are 3 variables and configurations to control the retrial of transactions:
Optimistic transactions: `tidb_disable_txn_auto_retry` and `tidb_retry_limit`.
Pessimistic transactions: `max-retry-count`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5725
=> Add declaration for scopes of transaction related variables and configurations

dashboard/dashboard-faq.md, optimizer-hints.md, sql-prepare-plan-cache.md, tidb-configuration-file.md
This reverts commit 6000b9584ce20466d64b4da1b7112e21b4284678.
https://github.com/pingcap/docs/pull/4036, previous docs PR link
https://github.com/pingcap/tidb/pull/23240, related tidb PR link
=> Revert "prepared plan cache: Enable by default (#4036)"

system-variables.md
remove system variable `tidb_track_aggregate_memory_usage`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5704
=> remove system variable `tidb_track_aggregate_memory_usage` 

statistics.md
=> Update statistics.md to remove the duplicate the

system-variables.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4819
=> SQL variables: add a new variable `tidb_enable_parallel_apply`

explain-joins.md, explain-subqueries.md, optimizer-hints.md, sql-statements/sql-statement-kill.md, tidb-configuration-file.md
The feature is not an experimental feature, thus we need to hide the config description.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5770
=> hide the config global-kill

releases/release-5.0.0-rc.md, sql-statements/sql-statement-start-transaction.md, system-variables.md, tidb-configuration-file.md, transaction-overview.md
TiDB 5.0 GA will not contain configurations related to async commit or 1PC. So they are removed.
And we also introduce a weaker consistency model for transactions. Add documentation about it.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5607
=> update async commit related documentation

alert-rules.md, error-codes.md, faq/sql-faq.md, faq/tidb-faq.md, garbage-collection-configuration.md, garbage-collection-overview.md, read-historical-data.md, sql-statements/sql-statement-flashback-table.md, system-variables.md, tidb-troubleshooting-map.md
This PR addresses the comments in https://github.com/pingcap/docs-cn/pull/5856 made by @MyonKeminta: The default mode of the GC scan lock is still LEGACY in 5.0 GA.
- This PR is translated from: Comments in https://github.com/pingcap/docs-cn/pull/5856
=> Update the default GC scan lock mode back to LEGACY

error-codes.md, system-variables.md
Synchronize two changes made in https://github.com/pingcap/docs-cn/pull/5856 to English 
- This PR is translated from: Two comments in https://github.com/pingcap/docs-cn/pull/5856
=> Synchronize two changes in docs-cn/pull/5856

sql-plan-management.md
Update SPM documentation for DML SQL Bind and baseline capture
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5740
- Other reference link(s):  https://github.com/pingcap/tidb/pulls?q=is%3Apr+is%3Aclosed+label%3Aepic%2Fsql-plan-management
=> SPM: update DML SQL Bind and baseline capture description

clustered-indexes.md, system-variables.md
Update the user documentation of clustered index feature introduced in v5.0-rc & v5.0.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5771, https://github.com/pingcap/docs-cn/pull/5834, https://github.com/pingcap/docs-cn/pull/5864
- clustered index project: https://github.com/pingcap/tidb/projects/45
=> update clustered indexes docs

tidb-binlog/tidb-binlog-overview.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5832
=> add binlog usage restrictions

command-line-flags-for-tidb-configuration.md, sql-statements/sql-statement-backup.md, sql-statements/sql-statement-restore.md
In 'dev' and 'v5.0' version, the default value of `--store` TiDB command-line argument has been changed to 'unistore'.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5874
- Other reference link(s): https://github.com/pingcap/tidb/pull/17674
=> update the local storage description from 'mocktikv' to 'unistore'

tidb-configuration-file.md
Changed default value of `tikv-client.grpc-connection-count` from 16 to 4. This default value is actually changed before releasing 4.0, and is included in all 4.x versions, without updating the document.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5884
=> tidb: Fix default value of grpc-connection-count

tikv-configuration-file.md
tikv/tikv#8499 changed the default value for `pessimistic-txn.pipelined`, this PR documents it.
tikv/tikv#8499
=> tikv: change default value for pessimistic-txn.pipelined

br/backup-and-restore-use-cases.md, telemetry.md, troubleshoot-hot-spot-issues.md, tune-tikv-thread-performance.md
Minor changes on version-specific info
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5900, https://github.com/pingcap/docs-cn/pull/5924, https://github.com/pingcap/docs-cn/pull/5903, https://github.com/pingcap/docs-cn/pull/5910
=> Update the descriptions of BR, telemetry, hot spot issues, and TiKV thread pool for 5.0 GA

partitioned-table.md
List partitioning requires the `tidb_enable_list_partition` variable to be set to ON, not just `tidb_enable_table_partition`. Updating the text for this.
=> partitioned-table: Correct the variable name for list partitioning

tiflash/use-tiflash.md
refine TiFlash doc to add executor pushdown white list
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5966 https://github.com/pingcap/docs-cn/pull/5979
=> refine TiFlash doc to add executor pushdown white list

pessimistic-transaction.md
Pipelined lock in pessimistic is enabled by default in latest version and release-5.0.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5984
=> update pipelined lock default value

tikv-configuration-file.md
Signed-off-by: you06 <you1474600@gmail.com>
The default value of pipelined lock is wrong.
=> fix default value of pipelined lock

get-started-with-tidb-lightning.md, tidb-lightning/deploy-tidb-lightning.md
Updated the version information from v4.0 to v5.0
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5897
=> lightning: update lightning example binary version and download link #5897

tidb-lightning/tidb-lightning-backends.md
=> Clarify Local-backend in tidb-lightning-backends.md

releases/release-5.0.0.md, system-variables.md
Add the `New in v5.0` mark to three system variables that are introduced in 5.0.
- `tidb_opt_prefer_range_scan`
- `tidb_skip_ascii_check`
- `tidb_mem_quota_apply_cache`
=> Add the New in v5.0 mark in system-variables.md

releases/release-5.0.0.md
Fixed the description of the `tidb_enable_clustered_index` setting.
Reported on #sig-docs in community slack by jun.seok.heo@samsung.com
https://tidbcommunity.slack.com/archives/CTW5HG9FH/p1618297103003000
=> release-5.0.0: Fix 'tidb_enable_clustered_index' values

tiup/tiup-command-completion.md, tiup/tiup-command-list.md, tiup/tiup-command-mirror-clone.md, tiup/tiup-command-mirror-init.md, tiup/tiup-command-mirror-rotate.md, tiup/tiup-component-cluster-patch.md
Add documents for commands `mirror init`, `mirror rotate`, and `cluster patch`.
Add 3 docs:
- tiup/tiup-component-mirror-init.md
- tiup/tiup-component-mirror-rotate.md
- tiup/tiup-component-cluster-patch.md
=> tiup: add 3 docs mirror-init/mirror-rotate/cluster-patch

tiup/tiup-cluster-topology-reference.md
add tiup-cluster-topology-reference.md
=> add tiup-cluster-topology-reference.md

tiup/tiup-component-cluster-rename.md, tiup/tiup-component-cluster-restart.md, tiup/tiup-component-dm-import.md
Add documents for commands `cluster rename`, `cluster restart`, and `dm import`.
Add 3 docs:
- tiup/tiup-component-cluster-rename.md
- tiup/tiup-component-cluster-restart.md
- tiup/tiup-component-dm-import.md
=> tiup: add 3 docs cluster-rename/cluster-restart/dm-import

explain-overview.md, sql-statements/sql-statement-explain.md
Add a hint to the `EXPLAIN` documentation about how to use `less -S` to view large explain output without line wrapping.
=> explain: add hint about disabling line wrapping with less

tiup/tiup-command-mirror-rotate.md, tiup/tiup-command-mirror.md, tiup/tiup-component-cluster-check.md, tiup/tiup-component-cluster-deploy.md, tiup/tiup-component-cluster-edit-config.md, tiup/tiup-component-cluster-patch.md, tiup/tiup-component-cluster-prune.md, tiup/tiup-component-cluster-scale-out.md, tiup/tiup-component-cluster.md, tiup/tiup-component-dm-deploy.md, tiup/tiup-component-dm-edit-config.md, tiup/tiup-component-dm-reload.md, tiup/tiup-component-dm-scale-in.md, tiup/tiup-component-dm-scale-out.md, tiup/tiup-component-dm-start.md, tiup/tiup-component-dm-stop.md
Batch uncomment links in TiUP docs.
=> tiup: batch uncomment links

br/backup-and-restore-tool.md
+ Tidy up the incompatible issues in using BR tools.
+ update minimum BR requirements
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5224 https://github.com/pingcap/docs-cn/pull/5905 https://github.com/pingcap/docs-cn/pull/5842  https://github.com/pingcap/docs-cn/pull/6018 https://github.com/pingcap/docs-cn/pull/6047
=> br:tidy up the incompatible issues in using BR tools

tiup/tiup-component-cluster-start.md, tiup/tiup-component-cluster-stop.md, tiup/tiup-component-dm-display.md, tiup/tiup-component-dm-upgrade.md
=> TiUP: Fix broken links and errors

user-defined-variables.md
user-defined-variables: Add note about SELECT...INTO <var>
=> user-defined-variables: Add note about SELECT...INTO <var>

CONTRIBUTING.md
Add the info about the 5.0 branch to CONTRIBUTING.md
=> Add the 5.0 branch info to CONTRIBUTING.md

br/use-br-command-line-tool.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5859
=> Update use-br-command-line-tool.md 

sql-statements/sql-statement-explain.md
This is a follow-up of #5349.
- Other reference link(s): #5349
=> explain: update the expression of the hint about disabling line wrapping with less

tidb-scheduling.md
update the GitHub external links that do not point to master.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6057
=> update the external links

best-practices/pd-scheduling-best-practices.md, information-schema/information-schema-cluster-info.md, pd-configuration-file.md, production-deployment-using-tiup.md, sync-diff-inspector/sync-diff-inspector-overview.md, ticdc/ticdc-open-protocol.md, tidb-binlog/binlog-consumer-client.md, tidb-binlog/binlog-control.md, tidb-binlog/maintain-tidb-binlog-cluster.md, tidb-binlog/tidb-binlog-overview.md, tidb-configuration-file.md, tidb-scheduling.md, tikv-configuration-file.md, tispark-deployment-topology.md, tiup/tiup-faq.md, tiup/tiup-playground.md, troubleshoot-lock-conflicts.md
Update the external GitHub links that contain `/master/` and `/release-3.0/` to `/release-4.0/`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6056
=> update the external links that contains master to release-4.0

tiup/tiup-cluster.md
=> Fix typos in tiup-cluster.md

benchmark/benchmark-sysbench-v5-vs-v4.md
The parameter prevent the TiKV startup.
unknown configuration options: server.request-batch-enable-cross-command
=> no server.request-batch-enable-cross-command in V5.0.0

comment-syntax.md
With the 8.0.23 MySQL client TiDB specific comments are cleared out, so
even with the latest client you still need to add `--comments`.
- Other reference link(s): https://github.com/pingcap/tidb/issues/24176#issuecomment-823835619
=> comment-syntax: Correct the note about `--comments`

tikv-configuration-file.md
ttl-poll-check-interval -> ttl-check-poll-interval
ttl-**poll-check**-interval -> ttl-**check-poll**-interval
```mysql
mysql> show config;
| tikv | 10.186.1.1:20160 | storage.ttl-check-poll-interval | 12h
```
- Other reference link(s):  https://github.com/pingcap/docs-cn/pull/6073
=> correct a tikv config name

dynamic-config.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5274; https://github.com/pingcap/docs-cn/pull/6114
=> Added attention to online parameter changes 

dumpling-overview.md
add full backup ftwrl details
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6060
=> add full backup ftwrl details in dumpling-overview.md

telemetry.md
To clarify, you can't enable/disable telemetry on Dashboard
To clarify that, you can't enable/disable telemetry from dashboard now.
- This PR is translated from: It will be great if all Chinese/EN documentation could be updated.
- Other reference link(s):https://docs.pingcap.com/zh/tidb/stable/telemetry
=> Clarify telemetry on Dashboard

ticdc/troubleshoot-ticdc.md
TiCDC provides two parameters to control the message size and batch size of Kafka messages.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5650
=> ticdc: fix kafka message size limit

br/use-br-command-line-tool.md
add a description about br's s3 permission.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/6016
=> Update use br command line tool

mysql-compatibility.md
Chinese part of #5137 
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5872
=> mention mysql replication 

quick-start-with-tidb.md
Update outdated description in quick-start-with-tidb.md.
To close https://github.com/pingcap/docs/issues/5485.
- Other reference link(s): https://github.com/pingcap/docs/issues/5485
=> Update oudated description in quick-start-with-tidb.md

pd-control.md, tidb-binlog/binlog-control.md, tidb-control.md, tikv-control.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6096
=> ctl: add a note for all ctl docs

geo-distributed-deployment-topology.md
Fix misinformation in geo-distributed-deployment-topology
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/5651
=> Fix misinformation in geo-distributed-deployment-topology.md

sql-statements/sql-statement-begin.md, sql-statements/sql-statement-change-column.md, sql-statements/sql-statement-commit.md, sql-statements/sql-statement-create-binding.md, sql-statements/sql-statement-create-database.md, sql-statements/sql-statement-create-index.md, sql-statements/sql-statement-create-role.md, sql-statements/sql-statement-create-sequence.md, sql-statements/sql-statement-create-table-like.md, sql-statements/sql-statement-create-table.md, sql-statements/sql-statement-create-user.md, sql-statements/sql-statement-create-view.md, sql-statements/sql-statement-deallocate.md, sql-statements/sql-statement-delete.md, sql-statements/sql-statement-do.md, sql-statements/sql-statement-drop-binding.md, sql-statements/sql-statement-drop-column.md, sql-statements/sql-statement-drop-database.md, sql-statements/sql-statement-drop-index.md, sql-statements/sql-statement-drop-role.md, sql-statements/sql-statement-drop-sequence.md, sql-statements/sql-statement-drop-stats.md, sql-statements/sql-statement-drop-table.md, sql-statements/sql-statement-drop-user.md, sql-statements/sql-statement-drop-view.md
This PR changes the synopsis sections of BEGIN, CHANGE, COMMIT, CREATE, DEALLOCATE, DELETE, DO, and DROP statements to use the ` ```ebnf+diagrm ` block, replacing the original image-based sqlgrams. It is a follow-up PR to https://github.com/pingcap/docs/issues/4389. 
To avoid making one single PR too large, I will open 4-5 follow-up PRs to process sql-statements files in batches. And I will delete all image files in the last PR in case of any display issues.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5376
=> sql-statements: use EBNF to render syntax diagrams - second batch

mysql-compatibility.md, tiflash/maintain-tiflash.md
Removed the descriptions about the lower product versions according to the conclusion made in #4549 
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5775
=> master/5.0: remove low-version descriptions

tiflash/tune-tiflash-performance.md
add some tiflash tune instructions
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/6041
=> Add some Tiflash tune instructions.md

sql-statements/sql-statement-execute.md, sql-statements/sql-statement-explain-analyze.md, sql-statements/sql-statement-explain.md, sql-statements/sql-statement-flashback-table.md, sql-statements/sql-statement-flush-privileges.md, sql-statements/sql-statement-flush-status.md, sql-statements/sql-statement-flush-tables.md, sql-statements/sql-statement-grant-privileges.md, sql-statements/sql-statement-grant-role.md, sql-statements/sql-statement-insert.md, sql-statements/sql-statement-kill.md, sql-statements/sql-statement-load-data.md, sql-statements/sql-statement-load-stats.md, sql-statements/sql-statement-modify-column.md, sql-statements/sql-statement-prepare.md, sql-statements/sql-statement-recover-table.md, sql-statements/sql-statement-rename-index.md, sql-statements/sql-statement-rename-table.md, sql-statements/sql-statement-replace.md, sql-statements/sql-statement-revoke-privileges.md, sql-statements/sql-statement-revoke-role.md, sql-statements/sql-statement-rollback.md
This PR changes the synopsis sections of BEGIN, CHANGE, COMMIT, CREATE, DEALLOCATE, DELETE, DO, and DROP statements to use the ```ebnf+diagrm block, replacing the original image-based sqlgrams. It is a follow-up PR to https://github.com/pingcap/docs/issues/4389.
To avoid making one single PR too large, I will open 4-5 follow-up PRs to process sql-statements files in batches. And I will delete all image files in the last PR in case of any display issues.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5540
=> sql-statements: use EBNF to render syntax diagrams - third batch

pd-control.md
The usage of `tiup ctl` with version in pd-ctl is wrong. Fix it.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6079
=> fix tiup ctl with cluster version

literal-values.md
The insert of TiDB does not support yyyymmdd hhmmss or yyyymmdd hh:mm:ss format, consistent with the behavior of mysql. But this format may appear in user case ( Oracle behavior ). Because there are corresponding comments in the source code, I think it's better to add it to the official doc.
https://github.com/pingcap/tidb/blob/master/types/time.go#L1919
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5671
=> tidb: Add time format description

system-variables.md
The sysvar docs imply that the 2 second delay is propagation to other servers. This is not the case, there is no propagation at all, because the table is stored in TiKV. The delay is the global values cache, and thus it affects the issuing server as well.
This affects all versions, but master will hopefully have a [fix soon](https://github.com/pingcap/tidb/pull/24359) so I'll create a separate PR to document the different semantics.
For GA releases it is https://github.com/pingcap/tidb/issues/22808
(I will leave the issue open until master is fixed)
=> add a better clarification on how sysvar changes "propagate"

sql-mode.md
Update the support 'PAD_CHAR_TO_FULL_LENGTH', remove the 'full support' description due to https://github.com/pingcap/tidb/pull/14007.
- Other reference link(s): https://github.com/pingcap/tidb/pull/14007
- None
=> sql-mode: remove 'full support' for 'PAD_CHAR_TO_FULL_LENGTH'

tidb-lightning/tidb-lightning-overview.md
TiFlash does not support Lightning currently. We must explicitly notify the issue.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5841
=> Highlight TiFlash does not support Lightning

br/use-br-command-line-tool.md, ticdc/manage-ticdc.md, ticdc/ticdc-overview.md
- Add documentation about the `local://` and `s3://` sinks in TiCDC
- Add documentation about `br restore cdclog`
=> ticdc: Include local:// and s3:// sink support

system-variables.md, tidb-configuration-file.md
This adds the docs for https://github.com/pingcap/tidb/blob/master/docs/design/2021-03-09-security-enhanced-mode.md
Which was merged in a series of PRs to master. The exact restrictions may evolve over time, so the wording is kept to use simple language to say "restrictions include". It is intended for use in cloud environments where the "root" privilege is considered too powerful.
This only affects master.
https://github.com/pingcap/tidb/pull/24416
https://github.com/pingcap/tidb/pull/24412
https://github.com/pingcap/tidb/pull/24279
https://github.com/pingcap/tidb/pull/23978
- Other reference link(s): https://github.com/pingcap/tidb/blob/master/docs/design/2021-03-09-security-enhanced-mode.md
=> Add documentation for SEM

.github/pull_request_template.md
Add v5.1 in pull_request_template.md.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6348
=> Add v5.1 in pull_request_template.md

system-variables.md, telemetry.md, tidb-configuration-file.md, tiflash/tune-tiflash-performance.md
The system variables are not in alphabetical order. This is useful for users when a list is long because it makes it easier to search for them. I also plan to auto-generate the system-variables page from the server's variables list, but it's not possible to do when the order is non-deterministic.
I have made one other small edit, which is to normalize the introduced version and remove the text " version" when it appears. I will fix the CI if this breaks any anchors.
=> system-variables: ensure alphabetical order

pd-control.md
Fix description about hot-region-cache-hits-threshold.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6339
=> Fix description about hot-region-cache-hits-threshold

check-before-deployment.md
On CentOS 8 Chrony is used by default for NTP services.
- https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/using-chrony-to-configure-ntp#sect-checking_if_chrony_is_synchronized
=> check-before-deployment: Add info about chronyd/chronyc on CentOS 8

TOC.md, functions-and-operators/information-functions.md, functions-and-operators/tidb-functions.md
Add documentation for SQL functions `TIDB_PARSE_TSO` and `TIDB_BOUNDED_STALENESS`.
Related:
- https://github.com/pingcap/tidb/pull/8385
=> Add documentation for TiDB specific SQL functions

system-variables.md
This is the docs for https://github.com/pingcap/tidb/pull/24359 which has not merged yet. It more accurately reflects the future-state of sysvars.
There is another PR for GA releases which describes how it previously worked better: https://github.com/pingcap/docs/pull/5562
It needs a "followup" to insert the version the change is effective from.
=> Add docs for sysvar cache

releases/release-4.0.13.md
Fix typos in 4.0.13 release notes
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6431
=> Fix typos in 4.0.13 release notes

releases/release-5.0.2.md
Change pr to issue in 5.0.2 release notes
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6436
=> Change pr to issue

statistics.md, tidb-configuration-file.md
The feature`feedback-probability` has been disabled by default since v4.0.9 because its behavior is unstable (see https://github.com/pingcap/tidb/pull/21923). So I update the default value of it to `0` and modify some descriptions.
After this PR is cherry-picked to the release-4.0 branch, I will add the information that the feature`feedback-probability` is disabled from the patch version v4.0.9.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6113
=> config: update the default value of `feedback-probability`

sql-statements/sql-statement-backup.md, sql-statements/sql-statement-restore.md
TIDB v5.1 supports fine grained privileges (aka Dynamic privileges), so it's recommended to use these over `SUPER`. This adds the fine grained privileges for `BACKUP` and `RESTORE` commands.
=> update permissions required for BACKUP and RESTORE

system-variables.md
This updates the system variables, generated against the tidb source code. i.e. this PR is derived from https://github.com/pingcap/docs/pull/5720 , but the generator source code will be submitted separately.
This allows this PR to potentially be cherry picked and handled like a regular contribution.
=> system-variables: update from generated source

best-practices/massive-regions-best-practices.md, experimental-features.md, system-variables.md, ticdc/ticdc-overview.md, tikv-configuration-file.md
Hibernate region is enabled by default since v5.0.2. Remove experimental warning for hibernate region and update default value.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6397
=> tikv config: hibernate region GA

statistics.md
We've updated the analyze behavior when setting tidb_analyze_version=2 and change its default value to 2.
This pr is to make the doc compatible with it.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6410
=> optimizer: modify docs for analyze behavior

experimental-features.md, partitioned-table.md, system-variables.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6467
=> update docs related to partition table dynamic mode

tidb-configuration-file.md
Closes: #5823
tidb-configuration-file: add graceful-wait-before-shutdown
=> tidb-configuration-file: add graceful-wait-before-shutdown

.circleci/config.yml, .github/workflows/dispatch.yml
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6483
=> change docs configs to release-5.1

statistics.md, system-variables.md
Add the variable which is added in https://github.com/pingcap/docs/pull/5781.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6494
=> system variables: add tidb_analyze_version

releases/release-5.1.0.md
Fix the display issues of two lists in v5.1 release notes
=> Fix the display issues of two lists

releases/release-5.1.0.md
Add a missing sentence in 5.1 rn
=> Add a missing sentence in 5.1 rn

tikv-configuration-file.md
`writecf` and `lockcf` only listed partial configuration items, and their selections aren't consistent.
=> Overhauling TiKV RocksDB configuration file

scale-tidb-using-tiup.md
Remove the content related to setting Tombstone, they are no longer supported.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6549
=> Not support to set Tombstone

system-variables.md
This adds 2 missing system variables that function correctly in TiDB: datadir and license.
The language is intentionally a little vague and says "typically" because in mocktikv/unistore cases it will show a path, but that is for developers to know. I don't believe we ever change the license string for enterprise edition but the language doesn't preclude that.
=> system-variables: add datadir and license

CONTRIBUTING.md, README.md
Add `release-5.1` where it was missing.
Related to fff8d90edfa8a4bf23aa9d4fa3e1ab247b046b13
=> Add v5.1.0 / release-5.1 where it is missing

tidb-lightning/deploy-tidb-lightning.md, tidb-lightning/tidb-lightning-backends.md
Clarify tidb lightning backend description
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6468
=> Clarify tidb lightning backend description

system-variables.md
Add documentation for these:
<pre><span style="background-color:#E4E4E4"><font color="#005F5F">5.7.25-TiDB-v5.2.0-alpha-164-g8434069c5</font></span><span style="background-color:#3A3A3A"><font color="#E4E4E4"></font></span><span style="background-color:#3A3A3A"><font color="#FDF6E3"> 127.0.0.1:4000 </font></span><span style="background-color:#6C6C6C"><font color="#3A3A3A"></font></span><span style="background-color:#6C6C6C"><font color="#FDF6E3"> test </font></span><span style="background-color:#D75F00"><font color="#6C6C6C"></font></span><span style="background-color:#D75F00"><font color="#FDF6E3"> SQL </font></span><span style="background-color:#073642"><font color="#D75F00"> </font></span>show global variables like &apos;char%&apos;; …
=> system-variables: Add charset documentation

system-variables.md
Fix incorrect changes in sysvar doc introduced in https://github.com/pingcap/docs/pull/5793.
=> Fix incorrect changes in sysvar doc

tikv-configuration-file.md
Signed-off-by: Yi Wu <yiwu@pingcap.com>
Titan only works on the defaultcf. The `rocksdb.defaultcf.titan` configs do not apply to `writecf` and `lockcf`. Fixing it. It looks like the Chinese version doesn't have such mistake.
- Other reference link(s): https://github.com/pingcap/docs/pull/5746
=> TiKV configuration: defaultcf.titan config should not apply to other CFs

sql-statements/sql-statement-alter-table.md, sql-statements/sql-statement-change-column.md, sql-statements/sql-statement-modify-column.md
update ctc doc in 3 files.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6522
=> fix ctc doc

clustered-indexes.md
Corrected NONCLUSTERED (from NONCLUSTERD)
Corrected NONCLUSTERED from NONCLUSTERD (missing E in the end).
=> clustered-index.md: nonclusterd -> nonclustered

tikv-configuration-file.md
=> Overhauling TiKV RocksDB configuration file (#5746)

dumpling-overview.md
removed two parts of default consistency description
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/6668
=> Dumping default consistency description

pd-configuration-file.md
Signed-off-by: disksing <i@disksing.com>
Make description of `max-replcias` more specific.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6669
- Other reference link(s): https://github.com/pingcap/docs/issues/5866
=> update max-replicas description

system-variables.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6409
=> Change tidb_memory_usage_alarm_ratio scope to instance

system-variables.md
change the default value of tidb_multi_statement_mode in v4.0.14
=> sysvar: change the default value of tidb_multi_statement_mode in v4.0.14

config-templates/complex-cdc.yaml, tiup/tiup-cluster-topology-reference.md
Updated data_dir for TiUP cluster document
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6333
=> TiUP cluster: update data_dir

config-templates/complex-tidb-binlog.yaml
Add kafka downstream example for convenience, and change the dirs of pumps to a better path that correspond to its default port.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6416
=> Add kafka downstream example

tikv-configuration-file.md
Updated description for pin-l0-filter-and-index-blocks in TiKV configuration document
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6667
=> TiKV configuration: Update description for pin-l0-filter-and-index-blocks

partitioned-table.md
Clarified currently supported partitioning management, and added experimental feature EXCHANGE PARTITION.
Fixes https://github.com/pingcap/docs/issues/5424
Clarified currently supported partitioning management, and added experimental feature EXCHANGE PARTITION.
Fixes https://github.com/pingcap/docs/issues/5424
It mentioned split, merge and redefine, which is not clear what operations it refers to (REORGANIZE PARTITION, which is not supported)
- Other reference link(s): https://github.com/pingcap/docs/issues/5424
=> partitioning: Corrected partition management

tidb-binlog/deploy-tidb-binlog.md, tidb-binlog/tidb-binlog-configuration-file.md
- updated descriptions about passwords in TiDB binlog
- updated descriptions about commit ts in TiDB binlog
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6271
=> TiDB binlog: update descriptions about commit ts and passoword

as-of-timestamp.md, experimental-features.md, stale-read.md
update stale read doc for ga
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6715
=> update stale read doc for ga

configure-time-zone.md
Without this you will see `SYSTEM` for both in most cases, which still doesn't tell you which timezone is used.
```
mysql> SELECT @@global.time_zone, @@session.time_zone, @@global.system_time_zone;
+--------------------+---------------------+---------------------------+
| @@global.time_zone | @@session.time_zone | @@global.system_time_zone |
+--------------------+---------------------+---------------------------+
| SYSTEM             | SYSTEM              | UTC                       |
+--------------------+---------------------+---------------------------+
1 row in set (0.17 sec)
```
=> configure-time-zone: mention `system_time_zone`

security-compatibility-with-mysql.md, system-variables.md
Update Security Compatibility with MySQL
Related to https://github.com/pingcap/tidb/pull/24991
=> Update Security Compatibility with MySQL

br/backup-and-restore-tool.md
the docuement of using to backup and restore system tables is not correct, this pr would correct it
=> correct document of using br backup and restore system tables

telemetry.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6731
=> Add description about telemetry of builtin functions usage

br/backup-and-restore-faq.md
=> update br faq

tidb-binlog/deploy-tidb-binlog.md
make the expression on deployment clearer to close #6684.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6708
=> deploy-tidb-binlog: make the expression on deployment clearer

ticdc/manage-ticdc.md
Add documentation on how to modify gcttl by tiup.
#1825
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6471
=> Add documentation on how to modify gcttl by tiup

ticdc/troubleshoot-ticdc.md
Add mysql sink privilege in TiCDC FAQ
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6400
=> ticdc: add mysql sink user privilege

releases/release-5.1.0.md
Fix a link in the English TiDB v5.1.0 release notes that pointed to the Chinese version of the telemetry docs.
=> 5.1.0 release notes: Fix link to telemetry docs

tidb-monitoring-api.md
added table storage info status API in the "TiDB monitoring API" document.
- This PR is translated from: [#6706](https://github.com/pingcap/docs-cn/pull/6706)
=> TiDB monitoring: add table storage info status api

config-templates/complex-cdc.yaml, tikv-control.md
Signed-off-by: Xintao <hunterlxt@live.com>
- Other reference link(s): https://github.com/tikv/tikv/pull/10259
=> Add print the bad sst files and related information for tikv-ctl

tikv-control.md
add a missing note from https://github.com/pingcap/docs/pull/6109#discussion_r684157602.
=> add a missing note

tiflash/tune-tiflash-performance.md
removed outdated tune advise 
- This PR is translated from: [#6705](https://github.com/pingcap/docs-cn/pull/6705)
=> TiFlash: remove outdated tune advise

tidb-lightning/tidb-lightning-backends.md, tidb-lightning/tidb-lightning-configuration.md
Removed default backend setting from the configuration and move local backend to the first.
- [] master (the latest development version)
- This PR is translated from: [#6534](https://github.com/pingcap/docs-cn/pull/6534)
=> TiDB lightning: remove default backend setting

encryption-at-rest.md
Suggest using Log Redaction when enabling TDE
=> Suggest Log Redaction when using TDE

TOC.md, information-schema/information-schema-referential-constraints.md, information-schema/information-schema.md
This provides documentation for https://github.com/pingcap/tidb/pull/26450
The motivation for adding this to TiDB was for ruby-on-rails compatibility. The value is limited however, because foreign keys are not enforced. I am documenting it however for correctness.. but the documentation is brief.
- Other …
=> Add infoschema.referential_constraints

tidb-lightning/tidb-lightning-faq.md
update FAQ from ONCALL
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6411
=> Add steps to get lightning goroutine

best-practices/high-concurrency-best-practices.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6856
=> high-concurrency-best-practices: fix the support info of follower read

tiflash/use-tiflash.md
Add function list pushed down to tiflash.
master, 5.2
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6862
=> Update function list pushed down to tiflash

minimal-deployment-topology.md
Make IP address of Monitoring & Grafana for Minimal Topology consistent. 
Refer these IP addresses are `10.0.1.10`, not `10.0.1.11`
https://github.com/pingcap/docs/blob/fc8169b094035d777cd81a160df153a0101f6777/config-templates/simple-mini.yaml#L24-L31
=> Make IP address of Monitoring & Grafana for Minimal Topology consistent

tikv-configuration-file.md
tikv: add storage flow control doc
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6826
=> tikv: add storage flow control doc

tidb-configuration-file.md
updated the default value of `stmt_max_count` (the value in statement-summary-tables.md has already been changed.)
- This PR is translated from: [#6863](https://github.com/pingcap/docs-cn/pull/6863)
=> TiDB configuration: update the default value of `stmt_max_count`

TOC.md, ticdc/manage-ticdc.md, ticdc/ticdc-open-api.md, ticdc/ticdc-overview.md
ticdc-open-api: add an file about ticdc open api
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6846
=> ticdc-open-api: add ticdc open api doc

tiflash/tiflash-configuration.md
Add configuration `io_rate_limit` for TiFlash.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6820
=> TiFlash configuration: update `io_rate_limit`

best-practices/high-concurrency-best-practices.md, configure-memory-usage.md, troubleshoot-write-conflicts.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6819
=> Add information of hashAgg for memory control

sql-plan-management.md
In version5.2, we try to ban the feature for baseline evolution. So we need to forbid to open the switch.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6790
=> update doc for SPM

config-templates/geo-redundancy-deployment.yaml, geo-distributed-deployment-topology.md, multi-data-centers-in-one-city-deployment.md, three-data-centers-in-two-cities-deployment.md, tiup/tiup-cluster-topology-reference.md
updated `label-property` related descriptions in the documents below:
- ”geo-redundancy-deployment.yaml"
- "geo-distributed-deployment-topology.md"
- “multi-data-centers-in-one-city-deployment.md” 
- “three-data-centers-in-two-cities-deployment.md”
The changes in the document "configure-memory-usage.md" is not included in this PR since this part's translation is included in https://github.com/pingcap/docs/pull/6171/files. …
=> docs: update rereject leader docs

sql-statements/sql-statement-create-index.md, system-variables.md, tidb-configuration-file.md
- updated descriptions about expression indexes in the document “SQL statement" and "system variables".
- removed the `expression` related part in the document "TiDB configuration"
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6643 https://github.com/pingcap/docs-cn/pull/6897
=> SQL statement, system variables: update expression indexes

sql-plan-management.md
Added upgrade checklist for SPM
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6866 and https://github.com/pingcap/docs-cn/pull/6896
=> Updated sql-plan-management.md

system-variables.md
Added two new variables:
- Scope: SESSION | GLOBAL
- Default value: `100`
- Range: `[0, 2147483647]`
- This variable is used to push down the Limit and TopN operators to the threshold in TiKV.
- If the value of Limit or TopN is less than or equal to this threshold, then the Limit and TopN operators are forcibly pushed down to TiKV. This variable provides a solution when Limit or TopN cannot be pushed down due to estimation errors. 
- Scope: SESSION | GLOBAL
- Default value:  `ON`
- This variable is used for the optimizer whether to enable the method that estimates the number of rows based on column order correlation
By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves …
=> Introduced 2 new variables

scale-tidb-using-tiup.md
Add a notice about scaling PD nodes, this is the same as in "scale tidb cluster with Ansible" document.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6514
=> add notice about scaling in pd node

sql-statements/sql-statement-create-index.md
add example for expression index
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6901
=> add example for expression index

system-variables.md, tiflash/use-tiflash.md, tikv-configuration-file.md
=> Revert "System variables: update `broadcast_join_threshold_count` and `broadc…"

best-practices/java-app-best-practices.md
added timeout options for Java best practices
- This PR is translated from: [#6710](https://github.com/pingcap/docs-cn/pull/6710)
=> best practices: add timeout options for Java best practices

quick-start-with-tidb.md
updated version to 5.2.0 and the TiUP playground that supports M1 silicon
- This PR is translated from: [#6791](https://github.com/pingcap/docs-cn/pull/6791)
=> Quick start: update version and TiUP playground supports M1 silicon

releases/release-5.2.0.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7010
=> release note: update feature description

production-deployment-using-tiup.md
add instructions for offline mirror 
- This PR is translated from: [#6633](https://github.com/pingcap/docs-cn/pull/6633)
=> TiUP: add instructions for offline mirror

tune-tikv-memory-performance.md
removed description for sync-log in "tune-tikv-memory-performance.md".
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6922
=> tune tikv memory performance: remove description for sync-log

dashboard/dashboard-statement-list.md
add a note to explain the blue bar and yellow line in the document "SQL Statements Page of TiDB Dashboard" (dashboard-statement-list.md)
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6872
=> dashboard statement list: add a note to explain the blue bar and yellow line

releases/release-5.1.0.md
added compatibility change for `tidb_enable_noop_functions` in "release-5.1.0.md"
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6870
=> release 5.1.0: add compatibility change for `tidb_enable_noop_functions`

dynamic-config.md
removed  the unsupported parameter `raftstore.sync-log` (from v 5.0) in "dynamic-config.md".
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6965
=> modify configuration online: remove unsupported parameters

migrate-from-aurora-using-lightning.md
updated a Aurora MySQL dumpling command in "migrate-from-aurora-using-lightning.md" file.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6847
=> Migrate from Aurora: update Aurora MySQL dumpling command

tidb-binlog/tidb-binlog-configuration-file.md
updated the information about "syncer.to.checkpoint" in "tidb-binlog/tidb-binlog-configuration-file.md" file.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6830
=> TiDB Binlog config: update "syncer.to.checkpoint" info

tikv-configuration-file.md
Complement the descriptions of wal-recovery-mode and use-direct-io-for-flush-and-compaction.
Previous descriptions are vague.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6860
=> update doc on wal-recovery-mode and use-direct-io-for-flush-and-compaction

system-variables.md, tidb-configuration-file.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6928
=> change expressions related to statement summary tables

system-variables.md
updated the scope and description about `tidb_opt_prefer_range_scan`
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6859
=> system variables: update description about `tidb_opt_prefer_range_scan`

.circleci/config.yml
chore: use py scripts in docs/master
- Other reference link(s): https://github.com/pingcap/docs/pull/6338
=> chore: use py scripts in docs/master

grafana-tikv-dashboard.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6989
=> Add description for TiKV Ready handled panel

tikv-configuration-file.md
Fixed the wrong description about `compaction-readahead-size` in "tikv-configuration-file.md" referred to "[Tune TiKV Memory Parameter Performance](https://docs.pingcap.com/tidb/stable/tune-tikv-memory-performance)"
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7039
=> TiKV config: fix wrong description about `compaction-readahead-size`

optimistic-transaction.md, transaction-isolation-levels.md
Signed-off-by: you06 <you1474600@gmail.com>
Issues pingcap/docs-cn#6392, pingcap/docs-cn#6756
The transaction and isolation doc are updated.
- Other reference link(s): pingcap/docs-cn#6858
=> update transaction doc

br/backup-and-restore-faq.md, br/use-br-command-line-tool.md
added a warning about using multiple BR command-lines at a single time in the "backup-and-restore-faq.md" and "use-br-command-line-tool.md" files.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6890 https://github.com/pingcap/docs-cn/pull/7072
=> BR FAQ: add a warning about multi br importing

command-line-flags-for-tidb-configuration.md
Removed two deprecated flags `--binlog-socket` and `--tmp-storage-path` in "command-line-flags-for-tidb-configuration.md".
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6757
=> Configuration Options: remove two TiDB's command options

system-variables.md
The feature 'noop functions' is actually very unsafe. Several internal users I have spoken to recently have misunderstood it.
This changes it from a 'note' to a 'warning' and provides an example for more context of what it does.
The example will need to be changed slightly for TiDB 5.1 and below because transaction read only is not affected by noop funcs yet.
For details, see [tips for choosing the affected versions](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md#guideline-for-choosing-the- …
=> system-variables: improve noop functions warning

scripts/check-conflicts.py, scripts/check-control-char.py, scripts/check-file-encoding.py, scripts/check-manual-line-breaks.py, scripts/check-tags.py
=> chore: fix byte encode

dashboard/dashboard-access.md, post-installation-check.md
Enhance TiDB login description to EN docs to make them in line with CN version. 
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6371 
@ran-huang
=> Enhance TiDB login descriptions - EN

releases/release-5.0.0.md, releases/release-5.1.0.md
Add a check item for feedback-probability in release 5.0.0 and release 5.1.0
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6887
=> release note: add a check item for feedback-probability

basic-features.md
It looks a bit strange on https://docs.pingcap.com/tidb/dev/basic-features because you have to scroll for quite a while until there is something different between versions. This will probably always be the case given the very quick release-cycle.
As a partial fix, this collapses charset and collations to take up less screen realestate.
- …
=> basic-features: collapse charset and collations

sql-statements/sql-statement-create-index.md
Update the related variable description for CREATE INDEX
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6588
=> Update the related variable description for CREATE INDEX

tikv-configuration-file.md
- Added the configurations `log-level`, `log-file`, `log-format`, `log-rotation-timespan`, `log-rotation-size`, `slow-log-file`, `slow-log-threshold`
- Updated the description of `end-point-slow-log-threshold`
- Revise some formats of configurations for consistency
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6996 …
=> TiKV config: add 7 log-related congifurations

releases/release-5.2.0.md
Mention `caching_sha2_password` in the release notes
- https://github.com/pingcap/parser/pull/1232
=> release-5.2.0: Add info about caching_sha2

tidb-configuration-file.md
tidb-configuration-file: correct the default value of committer-concurrency
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7142
=> tidb-configuration-file: correct the default value of committer-concurrency

tune-tikv-thread-performance.md
Changed the default value of `grpc-concurrency` from 4 to 5 in "tune-tikv-thread-performance.md".
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7139
=> Tune TiKV: change the default value of `grpc-concurrency`

tune-tikv-thread-performance.md
removed a note about `raftstore.sync-log`
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7183
=> remove a note about `raftstore.sync-log`

tiflash/monitor-tiflash.md
Signed-off-by: JaySon-Huang <tshent@qq.com>
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/7161
=> Add desc of "Storage Write Stall" row in the TiFlash grafana

tidb-configuration-file.md
Fix default value of performance.committer concurrency
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7116
=> tidb: fix default value of performance.committer-concurrency

functions-and-operators/aggregate-group-by-functions.md, functions-and-operators/date-and-time-functions.md, functions-and-operators/encryption-and-compression-functions.md, system-variables.md
Document *some* of the system variables that were missing from the docs
Related: #3155
=> Document missing sysvars

system-variables.md
Adds documentation for the PR https://github.com/pingcap/tidb/pull/25464
This is a minor feature.
master, 5.2.
https://github.com/pingcap/tidb/pull/25464
=> system-variables: add skip-name-resolve

system-variables.md
```
MySQL  127.0.0.1:4000 ssl  test  SQL > SHOW VARIABLES LIKE 'version\_compile\_%';
+-------------------------+-------+
| Variable_name           | Value |
+-------------------------+-------+
| version_compile_machine | amd64 |
| version_compile_os      | linux |
+-------------------------+-------+
2 rows in set, 1 warning (0.0028 sec)
```
Related PR: https://github.com/pingcap/tidb/pull/28958
=> Add docs for version_compile_* variables

system-variables.md
This relates to https://github.com/pingcap/docs/pull/6622 -- since it gives advice based on units.
=> system-variables: add configuration tip based on units

security-compatibility-with-mysql.md
Add Socket Authentication info.
Note that this doesn't update `default_authentication_plugin` as setting that to `auth_socket` doesn't make sense and isn't supported.
Also adding info about [FIDO](https://dev.mysql.com/doc/refman/8.0/en/fido-pluggable-authentication.html) authentication that was [released in MySQL 8.0.27](https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-27.html) this week.
Related PR: https://github.com/pingcap/tidb/pull/27561
=> Add auth_socket support

tidb-lightning/tidb-lightning-configuration.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7346
=> Lightning: add character set conversion configuration instructions

basic-features.md
+ Refine the layout of basic-features.md
+ Correct the support status for TiDB Binlog
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/7365 https://github.com/pingcap/docs/pull/6130
=> Refine the layout of basic-features.md

system-variables.md
`tmp_table_size` is a noop variable and not used.
The `tidb_tmp_table_max_size` is documented in another PR.
- Other reference link(s): this variable is introduced by https://github.com/pingcap/docs/pull/6492
=> system-variable.md: remove tmp_table_size

tikv-configuration-file.md
Updated the description of `reserve-space` in "tikv-configuration-file.md".
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7407
=> TiKV config: update the description of `reserve-space`

system-variables.md
Add TSO related variables `tidb_enable_tso_follower_proxy` and `tidb_tso_client_batch_max_wait_time`.
1. For the description of newly added variables, please refer to https://github.com/pingcap/docs-cn/pull/7364.
2. For the order of newly added variables in the document, please refer to …
=> system variables: add two TSO related variables

dynamic-config.md, tikv-configuration-file.md
raft-reject-transfer-leader-duration is ignored since v5.0.0.
https://github.com/tikv/tikv/pull/11249
=> remove stale configuration

temporary-tables.md
fix the declaration about INNODB_TEMP_TABLE_INFO
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7562
=> fix the declaration about INNODB_TEMP_TABLE_INFO

tidb-lightning/tidb-lightning-configuration.md
Add description for --log-file parameter, --log-file="-" use to print log to stdout
the --log-file="-" used by DBaaS, however, no doc described what it means.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/7549
=> Add description for --log-file parameter

sync-diff-inspector/sync-diff-inspector-overview.md
=> sync-diff-inspector: add annontation for option configuration items

download-ecosystem-tools.md, ticdc/manage-ticdc.md, tiup/tiup-component-dm-import.md
Bump version for v5.3.0, including only ecosystem tools. This PR change must be fully tested.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7521
=>  Bump version for v5.3.0 - ecosystem tools

tidb-monitoring-api.md
Fix a typo in tidb-monitoring-api.md
=> Fix a typo in tidb-monitoring-api.md

configure-memory-usage.md, sql-plan-replayer.md, tidb-configuration-file.md
Align 3 PR from docs-cn
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7322 https://github.com/pingcap/docs-cn/pull/6664 https://github.com/pingcap/docs-cn/pull/7664
=> Align 3 PRs from docs-cn

tikv-configuration-file.md, tune-tikv-thread-performance.md
- Added new configuration items `store-io-pool-size`, `raft-write-size-limit`, `raft-msg-flush-interval`.
- Updated the configuration item `store-pool-size`.
- Updated the contents related to the StoreWriter thread pool in "tune-tikv-thread-performance.md".
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7628
- Other …
=> Add doc for raftstore asynchronous write IO

experimental-features.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7763
=> experimental-features: add OpenAPI feature #7763

mysql-compatibility.md, sql-statements/sql-statement-select.md
Fix https://github.com/pingcap/docs/issues/7048
We should describe the `SELECT` incompatibilities on both mysql compatibility and SELECT statement reference. To reduce duplication, I have edited the description on mysql compatibility to be just the facts. There is slightly more detail on the SELECT page.
This should be the standard we use for documenting compatibility, since otherwise the MySQL compatibilty page gets too long as we improve it. …
=> Move part of SELECT incompatibility to detailed page

configure-placement-rules.md
I have updated version info about default enabled Placement Rules in "configure-placement-rules.md" because this feature is enabled by default since TiDB v 5.0.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7339
=> Update version info about default enabled Placement Rules

mysql-compatibility.md
Remove `LIST` from the explicitly unsupported partition types. Support for this is experimental as noted on https://docs.pingcap.com/tidb/stable/partitioned-table#list-partitioning . I've added a link to this doc.
In v5.3.0 the warning text changed slightly from:
```
sql> CREATE TABLE t2 (id int primary key) partition by key(id) partitions 3;
Query OK, 0 rows affected, 1 warning (0.0902 sec)
Warning (code 8200): Unsupported partition type, treat as normal table
```
to
```
sql> CREATE TABLE t2 (id int primary key) partition by key(id) partitions 3;
Query OK, 0 rows affected, 1 warning (0.0989 sec)
Warning (code 8200): Unsupported partition type KEY, treat as normal table
```
This is useful as it now indicates the problematic partition type. This also means this PR only applies to v5.3.0 or …
=> mysql-compatibility: Update details on partitioning

tidb-binlog/deploy-tidb-binlog.md, tidb-binlog/tidb-binlog-configuration-file.md
tidb-binlog: update kafka-max-message-size configuration
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7445
=> tidb-binlog: update kafka-max-message-size configuration

mysql-compatibility.md, sql-statements/sql-statement-explain.md
TiDB does not support `EXPLAIN FORMAT=tree`. It comes from MySQL 8.0, so it had not previously been documented (our official claim  = 5.7), but users might not know this. So it helps to include it here.
**Note:** I've updated this to cover optimizer switch compatibility as well. In https://github.com/pingcap/tidb/issues/29040 we determined that optimizer_switch should be read_only for now.
For details, see [tips for choosing the affected versions](https://github.com/pingcap/docs/blob/master/CONTRIBUTING …
=> sql-statements: update claims on optimizer/explain compatibility

tiup/tiup-playground.md
Fixed wrong command-line flags `----db.host host` and `----db.port int` according to the Chinese docs.
=> TiUP playground: fix wrong command-line flags

system-variables.md
Signed-off-by: you06 <you1474600@gmail.com>
Add a new environment variable which controls coprocessor paging for `IndexLookUp` executor, ref pingcap/tidb#30578.
=> system-variables: add tidb_enable_paging

tikv-control.md
Required changes:
* Replace `--db` with `--data-dir`
* Remove `/db` from the path
```
[dvaneeden@dve-carbon tikv-0]$ tiup ctl:v5.2.2 tikv --db /home/dvaneeden/.tiup/data/SqRmWep/tikv-0/data/db size -r 2
Starting component `ctl`: /home/dvaneeden/.tiup/components/ctl/v5.2.2/ctl tikv --db /home/dvaneeden/.tiup/data/SqRmWep/tikv-0/data/db size -r 2
error: Invalid value for '--db <db>': DEPRECATED!!! Use --data-dir and --config instead
Error: exit status 1
Error: run `/home/dvaneeden/.tiup/components/ctl/v5.2.2/ctl` (wd:/home/dvaneeden/.tiup/data/SqWYNWa) failed: exit status 1
```
I used this:
```
sed -i -E 's/tikv-ctl (.*)--db ([^ ]*)\/db\/?/tikv-ctl \1--data-dir \2/g' tikv-control.md
```
See also https://github.com/tikv/website/pull/307
=> tikv-control: Replace `--db` with `--data-dir`

command-line-flags-for-pd-configuration.md, command-line-flags-for-tidb-configuration.md, pd-configuration-file.md
Fix the optional and default values of some log-related configurations of PD and TiDB.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8110
=> PD configs: fix the log-related configs

dm/dm-task-configuration-guide.md, dm/task-configuration-file-full.md
dm: add dm task timezone config
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8159
=> dm: add dm task timezone config

tiflash/tiflash-configuration.md
1. Add description of tiflash-proxy apply-pool-size and store-pool-size configuration. These two configurations have existed since TiDB 4.0 version, this PR is just to supplement the description of the configuration. 
2. TiFlash has [changed default values of some configurations](https://github.com/pingcap/tics/pull/3414), so the doc need to be updated.
For details, see [tips for choosing the affected versions](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md#guideline-for-choosing-the-affect …
=> Change the default values of multiple tiflash configs

TOC.md, br/backup-and-restore-tool.md, character-set-and-collation.md, character-set-gbk.md, dm/dm-overview.md, mysql-compatibility.md, tidb-lightning/tidb-lightning-overview.md
Add a new doc for the GBK character set and update some relevant sections.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8101, https://github.com/pingcap/docs-cn/pull/8173
=> Add GBK charset description #8101

best-practices/pd-scheduling-best-practices.md
Signed-off-by: JmPotato <ghzpotato@gmail.com>
`disable-replace-offline-replica` and `disable-location-replacement` had been changed to `enable-replace-offline-replica` and `enable-location-replacement` since v3.1.0.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8543
=> pd-ctl: update the deprecated scheduler config names

explain-subqueries.md
The result in the Semi join section in "Explain Statements That Use Subqueries" in English version was different from the Chinese version. In this PR, the English version is revised to the same content of the Chinese version.
- Other reference link(s): https://github.com/pingcap/docs/issues/7710
=> Revise the result in the Semi join section in "Explain Statements That Use Subqueries"

placement-rules-in-sql.md, sql-statements/sql-statement-alter-placement-policy.md, sql-statements/sql-statement-create-placement-policy.md, sql-statements/sql-statement-show-placement-for.md, sql-statements/sql-statement-show-placement.md
This updates the docs for a removed feature in master (direct placement)
Closes https://github.com/pingcap/tidb/issues/31486
Closes https://github.com/pingcap/tidb/issues/31559
Closes https://github.com/pingcap/tidb/issues/31487
- Other reference link(s): https://github.com/pingcap/tidb/issues/31486
=> remove direct placement
