tune-operating-system.md

Added aliases to files that are newly added since Jun 25

add a v2.1 alias to 1 file to avoid 404 urls in Google

---

configure-store-limit.md
releases/release-3.0.16.md
tune-operating-system.md

Added aliases to files that are newly added since Jun 25

add v3.0 aliases to 3 files to avoid 404 urls in Google

---

faq/tidb-faq.md

Updates out of date FAQs
Fixes #2325
Fixes #2325

faq/tidb-faq: update out of date faqs

---

troubleshoot-hot-spot-issues.md

Removed spurious backslash
Removed spurious backslash from troubleshoot-hot-spot-issues.md

Removed spurious backslash from troubleshoot-hot-spot-issues.md

---

TOC.md
tidb-scheduling.md

Signed-off-by: qupeng <qupeng@pingcap.com>
Add tidb-scheduling sector.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3180 

translate tidb-scheduling

---

TOC.md
tidb-scheduling.md

4.0 has been updated in https://github.com/pingcap/docs/pull/3342
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3180/
- Other reference link(s): #3102

port #3102: add tidb scheduling to master branch

---

information-schema/information-schema-metrics-summary.md

Remove backtick ``` ` ``` and extra quote characters `'` in metadata.

Remove backtick and extra quote characters in metadata

---

TOC.md

Add "Read Historical Data" in TOC
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3820

TOC: Add "Read Historical Data"

---

faq/tidb-faq.md

Fix three links introduced in #3240
- Other reference link(s): #3240

Fix three deployment links in FAQ

---

TOC.md

TOC: Fix typo in STATS META

---

mysql-compatibility.md
quick-start-with-tidb.md
tidb-architecture.md

Add an alias in TiDB Architecture doc

Add aliases to fix dead links

---

tidb-binlog/tidb-binlog-kafka-deployment.md

Add an alias for dev in v3.0

---

tiflash/use-tiflash.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3780/

Update tiflash expr pushdown list

---

tikv-configuration-file.md

Document the new TiKV configuration `backup.num-threads`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4057

tikv: update backup.num-threads configuration

---

information-schema/information-schema-tikv-region-status.md
information-schema/information-schema-tikv-store-status.md

Add column description for system tables TIKV_REGION_STATUS and TIKV_STORE_STATUS.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3503, https://github.com/pingcap/docs-cn/pull/4076/files#diff-345ad3d131a6268bda0656454cd78346R946

Add column description for system tables

---

TOC.md
_index.md
faq/deploy-and-maintain-faq.md
faq/migration-tidb-faq.md

- Add more FAQ topics to `_index.md`
- Update wording to keep consistency
- Add deployment in K8s link to `TOC.md`

Add more topics to the index file

---

sql-statements/sql-statement-load-data.md

Load data has a confusing note about a variable, when it means a feature.
Fixes https://github.com/pingcap/tidb/issues/17800

sql-statements: improve load data

---

mysql-compatibility.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/2527

Remove alter PK from unsupported features

---

_index.md
overview.md

- Update wording about features in `overview.md`
- Add the pronunciation of TiDB

overview, index: update wording and add pronunciation

---

grafana-pd-dashboard.md
support.md
upgrade-tidb-using-ansible.md

Add 4 aliases to fix 4 broken links.

Add 4 aliases to fix 4 dead links

---

releases/release-3.0.17.md

Add a description for query-feedback-limit
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4169

add a description for configuration item query-feedback-limit

---

tidb-configuration-file.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3982

tidb-config: remove useless note of oom action

---

tidb-lightning/tidb-lightning-tidb-backend.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4025

tidb-lightning: modify the description of routes label

---

faq/high-reliability-faq.md

Update an faq.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3652

faq: update the tiup way of modifying version number

---

tidb-lightning/tidb-lightning-tidb-backend.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4025

tidb-lightning: fix a typo

---

faq/tidb-faq.md

Delete duplicate content in `sql-faq.md` doc to align a part of https://github.com/pingcap/docs-cn/pull/3262.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3262

tidb-faq: delete repetition in sql-faq 

---

tispark-overview.md

Remove word 'slave' in tispark document
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4171

tispark: remove evil word 'slave'

---

benchmark/benchmark-tidb-using-sysbench.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3419 https://github.com/pingcap/docs-cn/pull/4137

benchmark: clarify some expressions in sysbench report

---

benchmark/benchmark-tidb-using-sysbench.md
mysql-compatibility.md

Update the description and link of auto-increment.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3480

auto-increment: update doc

---

TOC.md

Remove a link in the toggle title in TOC.

TOC: remove a link in the toggle title

---

tiflash/troubleshoot-tiflash.md

After [placement rules](/configure-placement-rules.md) are enabled, the previously configured `max-replicas` and `location-labels` no longer take effect. To adjust the replica policy, use the interface related to placement rules.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3418 https://github.com/pingcap/docs-cn/pull/4194

Update related description in troubleshoot-tiflash

---

mydumper-overview.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3428

Mydumper: add faq about tz

---

TOC.md
adopters.md

adopters: update the TiDB adopters list

---

constraints.md
sql-statements/sql-statement-create-table.md

The statement reference for `CREATE TABLE` is a little bit weird:
* As well as having a `synopsis` sub heading, it also had a `syntax` sub heading.
* Many of the items under the `syntax` subheading describe options that are not actually supported, but parsed and ignored. As such, it feels weird to document these.
* Some non-critical info such as "doesn't include check constraints" and "supports some foreign key constraints" are also under `syntax` - these are best suited for the "MySQL compatibility" subheading. The point about foreign keys was also incorrect - it is not supported in syntax only, since this meta data was always stored, and relationships were validated. It is not yet enforced by DML is all.
* LIKE is documented, but it also explicitly says that there is a separate docs …

constraints, create table: improve clarity and update out of date info

---

TOC.md
auto-random.md
experimental-features-4.0.md
whats-new-in-tidb-4.0.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3943

Add experimental-features.md

---

sql-statements/sql-statement-explain-analyze.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4059

sql-statement-explain-analyze: add note for explain analyze with DML

---

tikv-configuration-file.md

Update default value for RocksDB max-subcompactions

---

experimental-features-4.0.md

Add auto-scaling doc link in 4.0 experimental feature
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4239

Add auto-scaling doc link in 4.0 experimental feature

---

mysql-compatibility.md

add auto_id_cache table option explanation.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3046

Add auto_id_cache table option explanation

---

dashboard/dashboard-faq.md
dashboard/dashboard-ops-deploy.md
dashboard/dashboard-ops-reverse-proxy.md
dashboard/dashboard-ops-security.md

Add instructions to deploy TiDB Dashboard behind HAProxy, as well as reorg some contents behind a collapse panel.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3828

Add HAProxy instructions for TiDB Dashboard

---

benchmark/v4.0-performance-benchmarking-with-tpch.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3585

benchmark: change a parameter level from global to session

---

identify-slow-queries.md
statement-summary-tables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3923

Update identify-slow-queries.md & statement-summary-tables.md

---

br/backup-and-restore-use-cases.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3906

br: update version

---

br/backup-and-restore-tool.md
br/backup-and-restore-use-cases.md

replace 'usage scenario' and 'scenario' with 'use case'.
- Other reference link(s): [BR Use Cases](https://docs.pingcap.com/tidb/stable/backup-and-restore-use-cases); [Use BR to Back up and Restore Data](https://docs.pingcap.com/tidb/stable/backup-and-restore-tool)

br: replace 'usage scenario' and  'scenario'

---

tiflash/tiflash-configuration.md

add tiflash store limit config version change note
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3941

add tiflash store limit config version change note

---

dashboard/dashboard-ops-security.md

The `<details></details>` has to be paired inside blockquote

chore: make details tag closed

---

sql-statements/sql-statement-drop-column.md

For new features, `DROP COLUMN` can drop single-value indices related columns. So update the document.
- This PR is translated from:  https://github.com/pingcap/docs-cn/pull/4255
- Other reference link(s): https://github.com/pingcap/tidb/pull/18852

Update documents fix drop column support features

---

upgrade-tidb-using-tiup.md

Add a note for tiflash `data_dir`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3998

add a note for tiflash data_dir

---

tiup/tiup-cluster.md

Customize the editing method of 'tiup cluster edit-config'.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4000

Customize the editing method of 'tiup cluster edit-config'

---

tikv-control.md

This PR update the usage of tikv-ctl modify-tikv-config
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4132

update the usage of tikv-ctl modify-tikv-config

---

adopters.md

add PayPay's English case study link

adopters: add PayPay's English case study link

---

adopters.md

add PayPay's English case study

adopters: add PayPay's English case study

---

sync-diff-inspector/sync-diff-inspector-overview.md
tidb-binlog/tidb-binlog-faq.md

update some description about tidb-binlog and sync-diff-inspector.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4040

tools: update some description about tidb-binlog and sync-diff-inspector

---

_index.md

Add three existing files to `_index.md`

Add what's new in TiDB 4.0, adopters, credits to index

---

grafana-pd-dashboard.md
grafana-tikv-dashboard.md
tiflash/monitor-tiflash.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4145

Align the description of TiFlash Grafana dashboard with other components

---

TOC.md

The current file order of BR in TOC is not logical.

toc: update the file order of br

---

best-practices/pd-scheduling-best-practices.md

The syntax shows the argument separate from the command by a hyphen, but that is not legal. It should be separated instead by a space.
```
root@tidb-tools:~# pd-ctl -u my-cluster-pd.poc.svc:2379 scheduler add evict-leader-scheduler-1
add a scheduler
Usage:
add [command]
Available Commands:
balance-adjacent-region-scheduler add a scheduler to disperse adjacent regions on each store
balance-hot-region-scheduler      add a scheduler to balance hot regions between stores
balance-leader-scheduler          add a scheduler to balance leaders between stores
balance-region-scheduler          add a scheduler to balance regions between stores
evict-leader-scheduler            add a scheduler to evict leader from a store
grant-leader-scheduler            add a scheduler to grant leader to a store …
```

Fixed evict-leader-scheduler syntax

---

tidb-configuration-file.md

add the config item `[security]spilled-file-encryption-method`
- This PR is translated from: https://github.com/pingcap/tidb/pull/19070 https://github.com/pingcap/docs-cn/pull/4302

add a config item [security]spilled-file-encryption-method in tidb-configuration-file.md

---

tiup/tiup-cluster.md

Add migrate control node in tiup-cluster
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4272

Add migrate control node in tiup-cluster

---

tidb-limitations.md

tidb limitations: fix MB bytes

---

sql-statements/sql-statement-show-create-sequence.md

fix an error in example sql statement.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4301

fix an error in `create sequence`

---

optimistic-transaction.md
pessimistic-transaction.md
system-variables.md
transaction-overview.md

This improves the clarity of when you would use optimistic transactions, autocommit, atomic statement rollback etc.

transactions: improve clarity of transactions

---

adopters.md

adopters: add the VIPKid case

---

character-set-and-collation.md

Fixes https://github.com/pingcap/tidb/issues/17801

character set: include useful warning

---

experimental-features-4.0.md
scale-tidb-using-tiup.md
ticdc/manage-ticdc.md
tiflash/tiflash-overview.md
tiflash/troubleshoot-tiflash.md
tiup/tiup-cluster.md
troubleshoot-high-disk-io.md

Fix an incorrect wording "scale out/in a node".
+ scale out a node --> add a node/scale out a cluster
+ scale in a node --> remove a node/take a node offline/scale in a cluster

Fix an incorrect wording "scale out or in a node"

---

tispark-deployment-topology.md

Change two yaml file links to absolute links starting with `https`
- Other reference link(s): https://github.com/pingcap/docs/pull/3611/commits/92900af7dec25c60c38ec67089db4912a4890395 in https://github.com/pingcap/docs/pull/3611

Fix two yaml file links

---

production-deployment-using-tiup.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4279

Add doc for tiup cluster env init

---

br/backup-and-restore-tool.md

This PR is manually cherry-picked from https://github.com/pingcap/docs-cn/pull/4339.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4339, https://github.com/pingcap/docs-cn/pull/4346

Clarify wording in BR tool doc 

---

upgrade-tidb-using-tiup-offline.md

Change the way of config offline mirror package.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4238

Change the way of config offline mirror package

---

ticdc/troubleshoot-ticdc.md

Refine the docs about the status in TiCDC.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3993

ticdc: refine the docs about the status in cdc

---

identify-slow-queries.md
tidb-binlog/tidb-binlog-faq.md
tidb-binlog/tidb-binlog-overview.md

Add 3 aliases to fix dead links.

Add 3 aliases to fix dead links

---

sql-statements/sql-statement-explain-analyze.md

Fix a typo in the `EXPLAIN ANALYZE` statement.

sql-statement-explain-analyze: fix a typo

---

br/backup-and-restore-tool.md

Update BR restrictions.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3750 https://github.com/pingcap/docs-cn/pull/4265

Update BR restrictions

---

configure-placement-rules.md
pd-control.md

Add description about configuring rule groups.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4270

pd: add rule group configuration

---

ticdc/manage-ticdc.md
ticdc/troubleshoot-ticdc.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4399

ticdc: command sample fix and add one more faq

---

ticdc/manage-ticdc.md
ticdc/ticdc-open-protocol.md
ticdc/ticdc-overview.md

+ Add the old value feature and bit flags of columns https://github.com/pingcap/docs-cn/pull/4209
+ Update open protocol tables https://github.com/pingcap/docs-cn/pull/4355
+ Update the note about a bug https://github.com/pingcap/docs-cn/pull/4234
The TiCDC architecture image is updated in https://github.com/pingcap/docs/pull/3779.
The reviewer of this PR can directly refer to the latest upstream version.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4209 https://github.com/pingcap/docs-cn/pull/4355 https://github.com/pingcap/docs-cn/pull/4234 https://github.com/pingcap/docs-cn/pull/4413

ticdc: add old value feature and column bit flag feature

---

faq/tidb-faq.md

Cherry-picked from https://github.com/pingcap/docs/pull/3851

faq: add faq for the inconsistent order of a SELECT statement without ORDER BY

---

ticdc/ticdc-open-protocol.md
tidb-binlog/maintain-tidb-binlog-cluster.md

Add 2 aliases to fix dead links

Add 2 aliases to fix dead links

---

experimental-features-4.0.md
ticdc-deployment-topology.md
ticdc/ticdc-overview.md
whats-new-in-tidb-4.0.md

ticdc: cdc is GA since v4.0.6
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4472

ticdc: cdc is GA since v4.0.6

---

ticdc/manage-ticdc.md
ticdc/troubleshoot-ticdc.md

ticdc: update some usage restrictions and configs
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4474

ticdc: update some usage restrictions and configs

---

mysql-compatibility.md

Add a missing item in mysql-compatibility.md.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4485

Add a missing item in mysql-compatibility.md

---

system-variables.md

This PR updates the documentation for https://github.com/pingcap/tidb/pull/19816
It only affects master.

sysvars: update tidb_dml_batch_size

---

br/backup-and-restore-faq.md

Correct a description.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4454

br: correct description

---

basic-features.md
character-set-and-collation.md

collation: add utf8_unicode_ci/utf8mb4_unicode_ci support

---

sync-diff-inspector/sync-diff-inspector-overview.md

update download link for sync-diff-inspector.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4428

tools: update download link for sync-diff-inspector

---

functions-and-operators/aggregate-group-by-functions.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4504

functions-and-operators: function STDDEV is supported

---

explain-views.md

This is a followup PR to https://github.com/pingcap/docs/pull/3858 - but they can be reviewed independently, and merge out of order.
This PR does not add this page to the TOC. I will only do that once all PRs are merged (this is one ~3-4 followup PRs).

sql tuning: add EXPLAIN views

---

explain-index-merge.md

This is a followup PR to #3858 - but they can be reviewed independently, and merge out of order.
This PR does not add this page to the TOC. I will only do that once all PRs are merged (this is one ~3-4 followup PRs).
The content here is taken directly from [query-execution-plan#indexmerge-example](https://docs.pingcap.com/tidb/stable/query-execution-plan#indexmerge-example). **I have not made any changes**, it LGTM already.

explain: add index merge

---

tikv-configuration-file.md

Remove sync-log config in TiKV config template

---

functions-and-operators/aggregate-group-by-functions.md

function VAR_SAMP()/STDDEV_SAMP() is supported.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4539 https://github.com/pingcap/docs-cn/pull/4533

functions-and-operators: function VAR_SAMP()/STDDEV_SAMP() is supported

---

storage-engine/titan-configuration.md

Fix titan blob-run-mode options' name.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4541; https://github.com/pingcap/docs-cn/pull/4541

Fix titan blob-run-mode options

---

benchmark/v4.0-performance-benchmarking-with-tpcc.md

benchmarking with tpcc should use TPC-C in the configuration instead of Sysbench
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4562; https://github.com/pingcap/docs-cn/pull/4562

Fix typo in benchmark result

---

TOC.md
roadmap.md
ticdc/manage-ticdc.md

Update TiDB roadmap.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4245

update TiDB roadmap

---

tiup/tiup-cluster.md

Add monitor components local config description.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4390

Add monitor config

---

benchmark/benchmark-sysbench-v2.md
functions-and-operators/encryption-and-compression-functions.md
sql-statements/sql-statement-create-database.md
tidb-binlog/deploy-tidb-binlog.md
transaction-overview.md

Add 5 aliases to fix dead links

Add 5 aliases to fix dead links

---

hardware-and-software-requirements.md

Add a link to TiUP Documentation Guide.
(The link was removed in https://github.com/pingcap/docs/pull/2658#issuecomment-637449058)
- Other reference link(s): https://github.com/pingcap/docs/pull/2658#issuecomment-637449058

Add a link to tiup in hardware and software requirements

---

TOC.md

Fix a TOC typo

---

tidb-binlog/binlog-consumer-client.md

Add one alias to fix dead link

Add one alias to fix dead link

---

explain-overview.md

Resolve a conflict that causes web page build failure.

Resolve a concflict

---

system-variables.md

Add system variable: tidb_union_concurrency
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4558

system_variables: add tidb_union_concurrency

---

ticdc/manage-ticdc.md

ticdc: add HTTP API for adjusting log level
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4560

ticdc: add HTTP API for adjusting log level

---

adopters.md

add Zhuan Zhuan, Xiaohongshu, and BOB

adopters: add Zhuan Zhuan, Xiaohongshu and BOB

---

TOC.md

TOC: update the adopters.md URL

---

TOC.md

Revert the change in #4007 because it would be easier to maintain future versions with the previous way

Revert the adopters link

---

auto-increment.md

The previous section name is Uniqueness, a noun, while the section name being updated in this PR was Monotonic, an adjective.
N/A

Update section name Monotonic to Monotonicity in auto-increment.md

---

faq/tidb-faq.md

This documents the pending change in https://github.com/pingcap/tidb/pull/19459
It has not merged to master or tidb-4.0 yet, but can be reviewed (and translated) now, since some users will no doubt hit it after it has merged.
https://github.com/pingcap/tidb/pull/19459

faq: add multistatement faq

---

pd-configuration-file.md

The default value of quota-backend-bytes is not right, change it.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4671

Update the default value of quota-backend-bytes

---

tiflash/maintain-tiflash.md

- Other reference link(s): https://github.com/pingcap/docs-cn/issues/4681

Fix TiFlash critical logs

---

tiflash/use-tiflash.md

add some annotation to broadcast join.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4636 https://github.com/pingcap/docs-cn/pull/4692

add doc for broadcast join 

---

ticdc/manage-ticdc.md

Correct cyclic-sync-ddl usage.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4697

ticdc: correct cyclic-sync-ddl usage

---

adopters.md

adopters: add ZTO Express

---

coprocessor-cache.md

Add how to use `EXPLAIN ANALYZE` and view Grafana panel to `coprocessor-cache.md`
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4659

Add using EXPLAIN ANALYZE and Grafana to coprocessor cache

---

certificate-authentication.md
information-schema/information-schema-sql-diagnostics.md
optimistic-transaction.md
releases/release-2.1.8.md
sync-diff-inspector/sync-diff-inspector-overview.md
tidb-binlog/bidirectional-replication-between-tidb-clusters.md

Add 6 aliases to fix dead links

Add 6 aliases to fix dead links

---

command-line-flags-for-tikv-configuration.md

Remove unneccssary escape \ from `--advertise-status-addr`
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4748

Remove unneccssary escape \ from `--advertise-status-addr`

---

adopters.md

Add U-Next case study in adopters.md

adopters: add U-Next case studies

---

dashboard/dashboard-diagnostics-access.md
dashboard/dashboard-intro.md

Signed-off-by: Breezewish <me@breeswish.org>
Remove Dashboard experimental flag.
Add experimental flag for Dashboard diagnostics.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4755

Remove the experimental flag for TiDB Dashboard

---

functions-and-operators/aggregate-group-by-functions.md

Add documentation about APPROX_PERCENTILE.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4760

Add documentation about APPROX_PERCENTILE

---

tikv-configuration-file.md

This config is added by tikv/tikv#8863. Update document to reflect the change.

Update config to include max-background-flushes

---

get-started-with-tispark.md

Fix a typo in get-started-with-tispark.md

---

.github/workflows/stale.yaml

Add an action to check stale issues.

.github: add an action to check stale issues

---

roadmap.md

Update roadmap for tidb-operator
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4800

update roadmap for tidb-operator

---

tiflash/monitor-tiflash.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4743

Add metric of TiFlash Coprocessor

---

pd-configuration-file.md

Fix a typo in pd-configuration-file.md

---

.github/workflows/link-check.yaml
adopters.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4828

filter several external links to pass ci check

---

pessimistic-transaction.md
tikv-configuration-file.md

change the value of `info-log-roll-time` into `0s`.  https://github.com/tikv/tikv/pull/8283
- Other reference link(s):  https://github.com/tikv/tikv/pull/8283

Update a value in tikv-configuration-file.md

---

quick-start-with-tidb.md

Remove TiDB-Wasm from `quick-start-with-tidb.md`.

quick-start-with-tidb: remove Wasm-related content

---

sql-statements/sql-statement-admin-cancel-ddl.md
sql-statements/sql-statement-admin-show-ddl.md

- Other reference link(s): https://github.com/pingcap/docs/pull/3587

Fix a typo in the `admin` statement

---

sql-statements/sql-statement-admin.md

Fix 2 display errors by adding the escape characters.

sql: fix display errors

---

TOC.md
br/backup-and-restore-storages.md

Reorder two BR documents in TOC:
+ BR Use Cases
+ Use BR Tool
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4886

toc: reorder br docs

---

tidb-binlog/tidb-binlog-relay-log.md

Refine the relay log description.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4867

tidb binlog: refine relay log description

---

adopters.md

Add PalFish and its case studies in adopters.

adopters: add palfish

---

sync-diff-inspector/sync-diff-inspector-overview.md

Add a command for downloading the Docker image of tidb-enterprise-tools (containing sync-diff-inspector).
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4897

sync-diff-inspector: add a command to download docker image

---

br/backup-and-restore-use-cases.md

Specify NIC
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4894

br: update backup-and-restore-use-cases.md

---

sync-diff-inspector/sync-diff-inspector-overview.md

Add some description of log and check result for sync-diff-inspector.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4887

tools: add some description of log and check result for diff

---

character-set-and-collation.md
sql-statements/sql-statement-show-collation.md

Add 2 anchor links in collation-related docs.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4925

Add 2 links in collation-related docs

---

analyze-slow-queries.md

Fix a typo in analyze-slow-queries.md:
`there` -> `where`
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4940

Fix a typo in analyze-slow-queries.md

---

quick-start-with-tidb.md

Add instruction on how to connect to MySQL.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4943

Add instruction on how to connect to mysql

---

ticdc/integrate-confluent-using-ticdc.md

Add "Apache" before "Kafka" (only for the first appearance of "Kafka").

ticdc: add "apache" before "kafka"

---

tidb-binlog/binlog-control.md

Remove useless download info for binlogctl
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4960

Remove useless download info for binlogctl

---

ticdc/manage-ticdc.md

add a description for uri with special characters.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4982

ticdc: add a description for uri with special characters

---

upgrade-tidb-using-tiup.md

use absolute path
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4946

tiup: use absolute path

---

tidb-configuration-file.md

`level`
- 指定日志输出级别, 可选项为 [debug, info, warn, error, fatal]
- 默认值: "info"
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4991

Add log.level description

---

dumpling-overview.md

add system database detail description.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4983

dumpling: add system database detail

---

tidb-control.md

Modify the description of `--port` from service port to status port.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5017

tidb-control: modify service port to status port

---

sql-statements/sql-statement-backup.md

Add some parameters in the backup sql example.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5028

statements: put access-key & secret-key in backup example

---

tidb-binlog/tidb-binlog-configuration-file.md

add an example for `ignore-txn-commit-ts`
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5042

binlog: add an example for `ignore-txn-commit-ts`

---

TOC.md

Remove `synchronous replication` from TOC because the feature name does not accurately reflect what the feature truly can do. @BusyJay will think of a new feature name and update the docs. Before he does so, it will be better to remove the doc from the TOC menu in case it misleads readers.

toc: remove synchronous replication

---

dynamic-config.md

Signed-off-by: Ryan Leung <rleungx@gmail.com>
This PR makes the dynamic config of TiKV more clear.
- Other reference link(s): https://github.com/pingcap/docs/issues/4326

Make the dynamic config of TiKV more clear

---

download-ecosystem-tools.md

Update some example versions in `download-ecosystem-tools.md`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5027

update example versions in download-ecosystem-tools.md

---

pd-control.md

Add scheduler config evict-leader-scheduler and its description.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4992

pd-ctl: add scheduler config evict-leader-scheduler

---

br/backup-and-restore-faq.md

Update the description of "permission denied" error.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4880

Update the description of "permission denied" error

---

tikv-control.md

- Remove unnecessary description：「TiUP 是晚于 tidb-ansible 推出的部署工具，使用方式更加简化」
- Add tiup ctl tikv detailed parameter output
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5024

tikv-control: update description

---

data-type-numeric.md

add a warning for a float compatibility problem
Related to https://github.com/pingcap/tidb/issues/11328
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5052

update document for adding a float compatibility problem's warning

---

ticdc/troubleshoot-ticdc.md

Add two troubleshoot QAs for TiCDC.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5047 https://github.com/pingcap/docs-cn/pull/5083

ticdc: add two troubleshoot QAs

---

tidb-configuration-file.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5003

add more comment for mem-quota-query

---

production-offline-deployment-using-tiup.md

Add command description about switching to online environment.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5023

Update online environment switch

---

tidb-configuration-file.md

see https://github.com/pingcap/tidb/blob/master/config/config.toml.example#L244

fix the default value of tcp-keep-alive

---

tikv-configuration-file.md

Fix wrong description and default value for enable-statistics.
default enabled since [release-1.0](https://github.com/tikv/tikv/blob/release-1.0/etc/config-template.toml)

tikv: fix wrong description and default value for enable-statistics

---

best-practices/massive-regions-best-practices.md

Fix a broken link in `massive-regions-best-practices.md`
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5111

Fix a broken link

---

.github/workflows/link-check.yaml
adopters.md

adopters: add NetEase Games

---

system-variables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5099
- Other reference link(s):pingcap/tidb#21777

system-variables: disable clustered index by default 

---

data-type-numeric.md
tikv-configuration-file.md

update tikv-server config options.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5123

update tikv-server-config file with bottommost-level-compression

---

releases/release-3.0.20.md

releases: remove an extra note

releases: remove an extra note

---

quick-start-with-tidb.md

There are only two methods on that page now.
fix https://github.com/pingcap/docs/issues/4496

fix a number in quick-start-with-tidb.md

---

.github/pull_request_template.md

Add a v5.0 tick box in the PR template.

Update PR template for v5.0

---

TOC.md

Remove test docs from TOC. These two docs are outdated and will be rewritten later. This removal is accepted by @scsldb and @shuke987.
- This PR is translated from: Remove test docs from TOC

Remove test docs from TOC

---

pd-configuration-file.md

Add description for `enable-joint-consensus`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5188

add enable-joint-consensus

---

.circleci/config.yml

update PDF generation
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5215

chore: update PDF

---

statement-summary-tables.md

Fix a typo in doc

---

pd-configuration-file.md
system-variables.md
tidb-configuration-file.md
tikv-configuration-file.md

Comment out v5.0 version marks before it is officially released.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5222

Comment out v5.0 version marks

---

system-variables.md

Update description of the variable `tidb_opt_agg_push_down`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5196

update description of the variable `tidb_opt_agg_push_down`

---

tidb-limitations.md

Update max column count in tidb-limitations.md.

Update max column count in tidb-limitations.md

---

post-installation-check.md

Remove TiDB Dashboard's outdated experimental note.

Remove TiDB Dashboard's outdated experimental note

---

releases/release-4.0.9.md

Update the compressed backup for dumpling in the release note.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5160

Add a note to release-4.0.9.md

---

partitioned-table.md
system-variables.md

+ Fix wrong descriptions.
+ remove list partition doc since it doesn't release in 5.0-rc
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5293

Remove list partition and list columns partition

---

.github/workflows/dispatch.yml

chore: update dispatch branch

---

adopters.md

Add chehaoduo in adopters

---

releases/release-5.0.0-rc.md

Fix typos in release notes

---

releases/release-4.0.9.md
tikv-configuration-file.md

according to tikv config-template.toml, merge grpc section to new server section
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5234

Refine sections in tikv-configuration-file.md

---

ecosystem-tool-user-guide.md

close https://github.com/pingcap/docs/issues/4606
mydumper note is misleading and inaccurate

refine ecosystem tool guide document

---

releases/release-4.0.10.md

Fix format issue

---

releases/release-5.0.0-rc.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5310

Fix a typo in 5.0 RC release notes

---

pd-control.md

In the case of the default 100ms, the 10ms adjustment is more radical, and in some scenarios may bring a greater burden to the pd-leader.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5249

update patrol-region-interval 10ms -> 50ms

---

sql-statements/sql-statement-kill.md
tidb-configuration-file.md

add SQL & config docs for global kill
- Other reference link(s): https://github.com/pingcap/tidb/pull/17649

tidb: add doc for global kill

---

adopters.md

Adpters: add 58.com

---

grafana-pd-dashboard.md

Fix display error

---

upgrade-tidb-using-tiup.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5220

Update upgrade-tidb-using-tiup.md 

---

hybrid-deployment-topology.md

The configuration is not consistent with the description text.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5328

Fix an inconsistency between description and config

---

.github/workflows/stale.yaml

Use the latest version.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5326, https://github.com/pingcap/docs-cn/pull/5320

.github: update stale action

---

production-deployment-from-binary-tarball.md

Update 5.0 download links in production-deployment-from-binary-tarball.md

---

ticdc/manage-ticdc.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5357

Update `kafka-version` description

---

production-deployment-from-binary-tarball.md

Update nightly download links in production-deployment-from-binary-tarball.md 

---

deploy-test-cluster-using-docker-compose.md
download-ecosystem-tools.md
pd-configuration-file.md
sql-statements/sql-statement-add-index.md
sql-statements/sql-statement-show-columns-from.md
upgrade-tidb-using-ansible.md

Add 5 aliases to fix broken links

Add 5 aliases to fix broken links

---

.github/workflows/media.yml

Refresh CDN cache when modify existing images.
Refresh CDN cache when modify existing images.

chore: update CDN refresh

---

sql-statements/sql-statement-kill.md
tidb-configuration-file.md

A follow-up of https://github.com/pingcap/docs-cn/pull/5386
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/5386

tidb: Refine the doc for global kill

---

comment-syntax.md

comment-syntanx: move a misplaced sentence

comment-syntanx: move a misplaced sentence

---

best-practices/massive-regions-best-practices.md
ticdc/ticdc-overview.md

Changed
https://docs.pingcap.com/zh/tidb/stable/massive-regions-best-practices#%E6%96%B9%E6%B3%95%E5%9B%9B%E5%BC%80%E5%90%AF-hibernate-region-%E5%8A%9F%E8%83%BD
https://docs.pingcap.com/zh/tidb/stable/ticdc-overview
this is the link of stable version and dev has the same problem

Fix hibernate region config link error

---

error-codes.md
faq/tidb-faq.md

Add 2 aliases to fix broken links.

Add 2 aliases to fix broken links

---

tiflash/use-tiflash.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5434

Rename `Duration` to `Time`

---

ticdc/manage-ticdc.md

TiCDC supports Kafka up to 2.7.0
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5443

ticdc: update max support kafka version 

---

adopters.md

add case study links for Shopee, Zhihu, and Xiaomi

adopters: add case study links

---

tiup/tiup-overview.md

In TiUP v1.3.1, execute tiup doc will throw error exit status 3.
If it is based on the return result of tiup list, I think it should be deleted?
https://tiup.io
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5315

tiup: delete doc from tiup list

---

check-before-deployment.md

Add tuned profile, udev script and cpu governor systemd service configurations.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5303

add optimal parameter configurations

---

sql-plan-management.md

Fix a typo in a statement example 
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5468

Fix a typo in a statement example 

---

TOC.md

toc: remove confusing "recommended"

toc: remove confusing "recommended"

---

system-variables.md

Signed-off-by: ailinkid <314806019@qq.com>

doc: fix ddl reorg priority scope problem

---

ticdc/manage-ticdc.md
ticdc/troubleshoot-ticdc.md

The default value of old value is true
https://github.com/pingcap/ticdc/blob/master/pkg/config/config.go#L29
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5456

ticdc: the default value of old value is true

---

tiflash/use-tiflash.md

Update TiFlash pushdown whitelist.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5543

update tiflash pushdown whitelist 

---

scale-tidb-using-tiup.md

- Swap lines to stress the `Note` part.
- Use `tiup ctl pd` instead of `pd-ctl` in tiup page.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5475

Add `tiup ctl pd` command in tiup page

---

scale-tidb-using-tiup.md

Update TiDB info v4.0->v5.0.0-rc
- Other reference link(s): https://github.com/pingcap/docs/pull/4877

tiup: update version info in scale-tidb-using-tiup.md

---

adopters.md

Add Meituan case study #2;
Change Meitun link from Wikipedia to Crunchbase;
Change industry to `E-commerce`;
Move Meituan upward.

adopters: add meituan case study #2

---

dumpling-overview.md

`--consistency auto` description change
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5034

`--consistency auto` description change

---

tidb-configuration-file.md

Add the time unit after the time value in the description of 'stats-lease'
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5323

Update parameter type description

---

choose-index.md
command-line-flags-for-pd-configuration.md
dashboard/dashboard-diagnostics-report.md
download-ecosystem-tools.md
literal-values.md
privilege-management.md
releases/release-2.0.6.md
releases/release-3.0.0-rc.3.md
releases/release-4.0.5.md
sql-statements/sql-statement-recover-table.md
ticdc/manage-ticdc.md
ticdc/ticdc-open-protocol.md
tidb-troubleshooting-map.md

Fix some typos detected by Vale.

fix some typos detected by Vale

---

TOC.md
glossary.md
ticdc/ticdc-glossary.md
upgrade-tidb-using-tiup.md

+ Add TiCDC glossary
+ Add more information in upgrade-tidb-using-tiup.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5471 https://github.com/pingcap/docs-cn/pull/5312

Add TiCDC glossary and update upgrade-tidb-using-tiup

---

maintain-tidb-using-tiup.md
production-deployment-using-tiup.md
production-offline-deployment-using-tiup.md
tiup/tiup-cluster.md
upgrade-tidb-using-tiup.md

Fix a broken link of TiUP configuration parameter template.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5625

tiup: fix a broken link

---

releases/release-4.0.11.md

Fix a typo in TiDB 4.0.11 release notes.

Fix a typo in 4.0.11 release notes

---

tispark-overview.md

add a description in tispark overview.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5460

tispark: add a description in tispark overview

---

pd-recover.md

Fix the typo bootsrap in pd-recover.md.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5654

fix typo `bootsrap` in pd-recover.md

---

benchmark/benchmark-sysbench-v4-vs-v3.md
benchmark/v4.0-performance-benchmarking-with-tpcc.md

To close https://github.com/pingcap/docs/issues/4950.

Remove a config that does not exists

---

maintain-tidb-using-ansible.md
offline-deployment-using-ansible.md
online-deployment-using-ansible.md
scale-tidb-using-ansible.md
upgrade-tidb-using-ansible.md

+ Add dev Ansible aliases (removed in https://github.com/pingcap/docs/pull/4946 from dev) to v4.0 Ansible docs (access to dev Ansible docs will be redirected to v4.0 Ansible docs)
+ Add warnings against using TiDB Ansible for upgrade, maintenance, and scaling.

Add dev Ansible aliases to v4.0 Ansible docs

---

ticdc/ticdc-overview.md

Update ticdc mysql sink description.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5644

ticdc: Update ticdc mysql sink description

---

credits.md
tidb-configuration-file.md

+ Add configuration item description `committer-concurrency`
+ Replace `tools` with `migrate` in credits.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5612 https://github.com/pingcap/docs-cn/pull/5629

Add configuration item description 'committer-concurrency'

---

TOC.md
alert-rules.md
migrate-from-aurora-mysql-database.md
migrate-from-mysql-dumpling-files.md
tidb-lightning/tidb-lightning-faq.md

+ Add a table to describe severity levels and remove duplicated descriptions in alert-rules.md.
+ Refine titles for some migration-related documents.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5640 https://github.com/pingcap/docs-cn/pull/5560

*: refine alert-rules.md and the titles of several migration docs

---

adopters.md

adopters: add kunlun case study

---

tidb-configuration-file.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5699

docs: remove some config fields for copr cache

---

dashboard/dashboard-key-visualizer.md

Update the title level of "Concentrated reads or writes" from the 2nd to the 3rd, because its parent title "Common heatmap types" is in the 2nd level.
- This PR is translated from: pingcap/docs-cn#5730

Correct the title level of Concentrated reads or writes

---

adopters.md

adopters: add Ninja Van

---

sql-statements/sql-statement-create-table.md

Update compatibility for temporary tables for dev and v5.0.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5758

Update compatibility for temporary tables

---

tiup/tiup-component-cluster-clean.md
tiup/tiup-component-cluster-deploy.md
tiup/tiup-component-cluster-edit-config.md

Add:
+ tiup-component-cluster-clean.md
+ tiup-component-cluster-deploy.md
+ tiup-component-cluster-edit-config.md
**Follow-up: Some broken links are commented out for now. Once these docs are merged, I'll create a separate PR to uncomment the links.**

tiup: add 3 docs

---

garbage-collection-configuration.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5755

enable compaction filter by default 

---

system-variables.md

As title.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5792
- Other reference link(s): https://github.com/pingcap/tidb/pull/18193, the introduction of this variable

sysvars: add tidb_skip_ascii_check

---

.circleci/config.yml
.github/workflows/dispatch.yml

Stop triggering website build.

chore: stop building v5 temporary

---

.github/workflows/dispatch.yml

chore: trigger preview build

---

pd-configuration-file.md

Update the default value of enable-joint-consensus from false to true for 5.0GA according to the confirmation from Jay
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5790

Update the default value of joint consensus

---

system-variables.md

sysvars: add docs for tidb_enable_strict_double_type_check

---

tiup/tiup-bench.md
tiup/tiup-cluster.md

Remove private info in TiUP document 
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5788

Remove private info in TiUP document

---

character-set-and-collation.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5833

doc: fix doc typo

---

tikv-configuration-file.md

Add TTL related configurations in `tikv-configuration-file.md`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5756

tikv: add ttl configuration

---

get-started-with-tidb-lightning.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5816

lightning: update config in get started 

---

partitioned-table.md
system-variables.md

- revert https://github.com/pingcap/docs-cn/pull/5293
- update doc for the related session variable. (`tidb_enable_list_partition` )
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5653

update doc for list partition table

---

system-variables.md
tiflash/use-tiflash.md

Added the support information of MPP to the TiFlash introduction and System variables
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5702

write document for mpp #5702

---

ticdc/manage-ticdc.md

Add more description about Unified Sorter.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5749

cdc: add more description about Unified Sorter

---

ticdc/troubleshoot-ticdc.md

Added information on how to handle DDL failures after 4.0.11
Follow-up: This PR needs to be cp to release-5.0 after TiDB 5.0 GA is released.
4.0.11 or above，5.0.0-rc excluded.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5449

TiCDC: add trouble shooting info about DDL failures

---

quick-start-with-tidb.md

update use tiup client access database

update use tiup client access database

---

tidb-configuration-file.md

Documentation for https://github.com/pingcap/tidb/pull/21552
https://github.com/pingcap/tidb/pull/21552

Add docs for enable-tcp4-only

---

grafana-tikv-dashboard.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5744

Update grafana-tikv-dashboard.md 

---

tiflash/tiflash-configuration.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5739

tiflash: add more explanation for parameter `bg_task_io_rate_limit`

---

TOC.md
releases/release-notes.md

Revert 4.0.12 release notes (only deletes TOC and release-notes.md)
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5944

revert 4.0.12 release notes

---

quick-start-with-tidb.md
releases/release-4.0.12.md

correct the order of 4.0.12 release notes
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5948

releases: correct the order of notes

---

system-variables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5892

add apply-cache

---

error-codes.md
faq/sql-faq.md
faq/tidb-faq.md
garbage-collection-configuration.md
garbage-collection-overview.md
log-redaction.md
partitioned-table.md
pd-configuration-file.md
read-historical-data.md
releases/release-5.0.0-rc.md
sql-plan-management.md
sql-statements/sql-statement-flashback-table.md
system-variables.md
ticdc/manage-ticdc.md
ticdc/ticdc-overview.md
tidb-binlog/tidb-binlog-overview.md
tidb-configuration-file.md
tidb-limitations.md
tidb-troubleshooting-map.md
tiflash/tiflash-configuration.md
tiflash/use-tiflash.md
tikv-configuration-file.md
tiup/tiup-playground.md
transaction-overview.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5911

*: update all 5.0-rc descriptions to v5.0

---

tikv-configuration-file.md

Signed-off-by: gengliqi <gengliqiii@gmail.com>
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5893

tikv: change default store/apply max-batch-size

---

configure-memory-usage.md

update default `oom-action`
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5915

update default oom action of TiDB

---

check-before-deployment.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5823

add the rsa generating command in check-before-deployment.md

---

tikv-configuration-file.md

Match TiKV docs's config default value with TiKV codebase.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5669

update doc to match config default value with TiKV codebase.

---

tidb-configuration-file.md

Added the description for a new configuration entry for the 'tidb-configuration-file'.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5937

update configuration page for enable-enum-length-limit

---

.github/workflows/link-check.yaml

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5964

link-check.yaml: disables external link check

---

clustered-indexes.md
system-variables.md

Fix two grammar mistakes in `clustered-indexes.md` and `system-variables.md`.

fix grammar mistakes

---

tiflash/tiflash-configuration.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5931

update tiflash config: add proxy log level 

---

tikv-configuration-file.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5961

tikv: update CDC config

---

tiflash/tiflash-configuration.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5941

Update the way of configlocation-labels if tiflash enable

---

clustered-indexes.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5971

fix a typo in clustered-indexes.md

---

pd-configuration-file.md

pd: remove the experimental flag for the enable-joint-consensus config
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5974

pd: remove the experimental flag for the enable-joint-consensus config

---

.circleci/config.yml
.github/workflows/dispatch.yml

Update 5.0 PDF version tag. Leave this pr until the version of documents updated.

chore: update PDF version tag

---

upgrade-tidb-using-tiup.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5989

Add a note in upgrade-tidb-using-tiup.md

---

information-schema/client-errors-summary-by-host.md
information-schema/client-errors-summary-by-user.md
information-schema/client-errors-summary-global.md

Fix typos in information-schemas introduced in https://github.com/pingcap/docs/pull/5062.

Fix typos in information-schemas

---

backup-and-restore-using-mydumper-lightning.md
experimental-features-4.0.md
loader-overview.md
maintain-tidb-using-ansible.md
mydumper-overview.md
offline-deployment-using-ansible.md
online-deployment-using-ansible.md
production-offline-deployment-using-tiup.md
scale-tidb-using-ansible.md
syncer-overview.md
upgrade-tidb-using-ansible.md
upgrade-tidb-using-tiup-offline.md

Add stable and dev aliases to docs removed in dev.

add stable aliases for deleted docs in dev

---

TOC.md
sql-statements/sql-statement-table.md

Add initial documentation for the `TABLE` statement.
- This statement also works in PostgreSQL (tested on 13.2) and it may conform to the ISO SQL standards. Should we document that as well?
- I don't think the EBNF is complete yet ( test on https://kennytm.github.io/website-docs/dist/ if you make any changes)

Document the TABLE statement

---

tiup/tiup-mirror-reference.md

Fixed typo "mirrir" -> "mirror"

mirrir -> mirror

---

statistics.md

Fix a typo in statistics.md.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5762

Fix a typo in statistics.md

---

tikv-configuration-file.md
tune-tikv-performance.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5886

Update the default value of grpc-raft-conn-num

---

system-variables.md
tikv-configuration-file.md

+ Fix statements:
- hibernate region is disabled on release branch.
- unified thread pool is no longer experimental long time ago.
+ Add value ranges for some system variables
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5952 https://github.com/pingcap/docs-cn/pull/5918

update system-variable for statements-summary and fixes statements

---

faq/migration-tidb-faq.md

update a dumpling faq
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5757

update a dumpling faq

---

alert-rules.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6005

update the rule for gc can't work alert 

---

grafana-tikv-dashboard.md

Signed-off-by: qupeng <qupeng@pingcap.com>

update grafana panels for TiKV GC

---

error-codes.md

Refine a sentence in error-codes.md according to https://github.com/pingcap/docs/pull/5346/files#r614265174.

error-codes: refine a sentence

---

dumpling-overview.md

This is because lightning is [suggesting this](https://github.com/pingcap/tidb-lightning/blob/39dac927300b350f939da529f5328160d34d7727/lightning/mydump/region.go#L279-L284)
for non-CSV files.

dumpling-overview: Suggest 256 MB or less as file size

---

tiup/tiup-component-dm-patch.md
tiup/tiup-component-dm-restart.md
tiup/tiup-component-dm.md

Add 3 docs:
- tiup/tiup-component-dm.md
- tiup/tiup-component-dm-restart.md
- tiup/tiup-component-dm-patch.md

tiup: add TiUP DM introduction and docs for command `dm-restart` and `dm-patch`

---

adopters.md

Remove PayPay case-study articles due to compliance issues.

adopters: rm 2 case study articles

---

tidb-configuration-file.md

Add the value range for `token-limit` in the TiDB Configuration File document.
- Other reference link(s): https://github.com/pingcap/tidb/issues/24226

tidb-config: add value range for token-limit

---

character-set-and-collation.md

Fix a typo in Update character-set-and-collation.md

Fix a typo in Update character-set-and-collation.md

---

releases/release-5.0.1.md

releases: add a lighting note to br in 5.0.1
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6135

releases: add a lighting note to br in 5.0.1

---

command-line-flags-for-pd-configuration.md

Some command-line flag items in [PD Configuration Flags | PingCAP Docs](https://docs.pingcap.com/tidb/dev/command-line-flags-for-pd-configuration) are neither clear enough nor consistent with similar config items in [PD Configuration File | PingCAP Docs](https://docs.pingcap.com/tidb/dev/pd-configuration-file). This PR corrects a few PD command-line flags to make it consistent. In the Chinese version, these modified items are consistent and do not need an update.
- Other reference link(s): [PD 配置参数 | PingCAP Docs](https://docs.pingcap.com/zh/tidb/dev/command-line-flags-for-pd-configuration), [PD Configuration Flags | PingCAP Docs](https://docs.pingcap.com/tidb/dev/command-line-flags-for-pd-configuration)

pd: align the language of similar items between docs

---

statement-summary-tables.md

The statement summary doc is not very clear: users are always confused why the data of the history table is becoming less.
Add tips for it to clarify why it may become less and how to solve this problem.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5854

Add tips for the limitation of statements summary history table

---

statistics.md

Move the position of a title to make it more logical.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6150
- Other reference link(s):https://github.com/pingcap/docs-cn/issues/5906

Move the position of a note 

---

literal-values.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5620

Add details for Hexadecimal Literals

---

br/backup-and-restore-faq.md
br/backup-and-restore-use-cases.md

Update some br docs and add some faq.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5663

br: update some faq from oncall

---

ticdc/manage-ticdc.md

The sample of Pulsar sink url auth param config is wrong.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/6026

Correct the sample of Pulsar sink url auth param config.md

---

quick-start-with-tidb.md

Add a note that TiUP Playground doesn't support M1
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6121

Add a note that TiUP Playground doesn't support M1

---

best-practices/pd-scheduling-best-practices.md

Refine a description for PD scheduling best practices.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5515

Refine a description for PD scheduling best practices

---

pd-configuration-file.md

Add the value range and type for `store-balance-rate` in the PD Configuration File document.
- Other reference link(s): https://github.com/pingcap/tidb/issues/24316

pd-config: add value range and type for store-balance-rate

---

dumpling-overview.md

Move the part of parameter description in dumpling-overview.md
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/6053

Move the part of parameter description in dumpling-overview.md

---

tikv-configuration-file.md

Signed-off-by: gengliqi <gengliqiii@gmail.com>
update tikv 2 config default value `leader-transfer-max-log-lag`(https://github.com/tikv/tikv/pull/9592) and `merge-check-tick-interval`(https://github.com/tikv/tikv/pull/9675)

update tikv config default value

---

alert-rules.md
tidb-configuration-file.md
tiflash/tiflash-configuration.md

Fix typos in the document

---

README.md
download-ecosystem-tools.md
maintain-tidb-using-tiup.md
pd-control.md
pd-recover.md
post-installation-check.md
quick-start-with-tidb.md
scale-tidb-using-tiup.md
tiup/tiup-cluster.md
tiup/tiup-component-management.md

Update the code examples and links after 5.0 GA, so we guide users to try a newer version of TiDB.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5773

master/5.0: bump version and links to v5.0.0

---

ticdc/manage-ticdc.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/5896

ticdc: update caveats of cyclic replication

---

sql-mode.md

Remove the description of --sql-mode
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6196

Remove the description of --sql-mode

---

tiup/tiup-mirror.md

Adding info about how to use the mirror created with `tiup mirror clone`.

tiup-mirror: Add a hint about how to use a tiup mirror

---

config-templates/geo-redundancy-deployment.yaml
geo-distributed-deployment-topology.md

This should help the reader to better understand the example
and by also linking to the document about labels this provide further
information if needed.
/label version-specific-changes-required

geo-distributed-deployment-topology: Explain dc and zone names

---

system-variables.md

Add documentation for https://github.com/pingcap/tidb/pull/23818
This affects master only.

Add read only to noop functions

---

explain-mpp.md

Fix wrong table name
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6204

Fix wrong table name

---

dumpling-overview.md

Currently we point users to: https://docs.pingcap.com/tidb/stable/download-ecosystem-tools#dumpling
However for this the user needs to:
- Figure out what version he/she wants to download
- Then based on that construct the URL
- Download the file
- Extract/install dumpling
TiUP is making this easier, so best to use that instead. This is also
more consistent with other tools.

dumpling-overview: Add info about how to install with TiUP

---

mysql-compatibility.md
sql-statements/sql-statement-load-data.md

Added information about `LOAD DATA...REPLACE` compatibility.
- Other reference link(s): https://github.com/pingcap/tidb/issues/24515

mysql-compatibility: Document LOAD DATA compatibility

---

sql-statements/sql-statement-add-index.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6259

Remove the legacy unsupported info for VISIBLE/INVISIBLE index

---

tikv-control.md

Add more information for compact and remove-fail-stores command
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/6065
- Other reference link(s):https://github.com/tikv/tikv/issues/10040

tikv-ctl: Add more information for compact and remove-fail-stores

---

dashboard/dashboard-ops-deploy.md
quick-start-with-tidb.md

Most of the content is not changed.
Follow-up: Follow up on @dveeden's comments.
Main change:
- I used [shortcodes for tab panels](https://github.com/pingcap/website-docs#shortcodes-for-tab-panels) to create two panels "Mac" and "Linux" to reorganize the page structure. Tabs are shown like this:
- I bumped version to v5.0.1, the latest stable version of v5.0. And in future releases, we'll bump the version in this page to the latest stable one. This will be written in our docs release checklist. FYI @morgo 
- I rewrote the beginning according to Morgan's suggestions: 1) removed the warning on the top 2) introduce what TiUP is 
https://github.com/pingcap/docs/pull/5613#discussion_r631681358 …

Add tab panels to TiDB Quick Start page and optimize content and structure

---

tidb-computing.md

fix Error DDL
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6273

Fix a typo in tidb-computing.md

---

ticdc/deploy-ticdc.md

Add a link to the CDC configurable field.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6272

Add a link to the CDC configurable field

---

certificate-authentication.md

Fix a display failure of copyable snippt
- Other reference link(s): https://github.com/pingcap/docs/issues/5633

Fix a display failure of copyable snippt

---

enable-tls-between-components.md

Fix a display error of code snippit

Fix a display error of code snippit

---

br/backup-and-restore-faq.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6269

br: add br faq NotFound description

---

br/backup-and-restore-use-cases.md

Add a notice about TiFlash on BR user case.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/6174

br: update tiflash related docs on nfs

---

tidb-lightning/tidb-lightning-backends.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6284

Update status-port description

---

dumpling-overview.md

Update dumpling document about threads and some other stuff.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6285

dumpling: update dumpling doc

---

system-variables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6264

Add some more docs about async commit not used

---

sql-statements/sql-statement-explain.md

update doc for explain for connection.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6260

*: update doc for explain for connection 

---

config-templates/complex-cdc.yaml

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6312

cdc: fix config typo

---

read-historical-data.md

Add practical advise to the read-historical-data page and link to the related dumpling docs

read-historical-data: Add practical advise about how to use this feature

---

command-line-flags-for-tikv-configuration.md
scale-tidb-using-tiup.md

- To update the confusing tiup ctl pd usage.
- To add PD information for the command.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6227

tiup: clarify the pd-ctl command usage

---

tiflash/use-tiflash.md

explain how to check if mpp takes effect.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6262

add detailes about whether mpp takes effect

---

tikv-configuration-file.md

Add the value range and type for stack-size in the TiKV Configuration File document.
- Other reference link(s): https://github.com/pingcap/tidb/issues/24314

tikv-config: add value range and type for stack-size

---

tikv-configuration-file.md

fix a typo in tikv-config: add value range and type for stack-size #5681
- Other reference link(s): https://github.com/pingcap/docs/pull/5681

tikv-config: fix a typo for stack-size

---

tidb-binlog/upgrade-tidb-binlog.md

fix typo
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6320

binlog: fix typo

---

ticdc/manage-ticdc.md

add the default value for  --sort-engine.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6279

add --sort-engine default values

---

ticdc/troubleshoot-ticdc.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6331

ticdc: update troubleshoot for ddl skip

---

config-templates/complex-tidb-binlog.yaml

Fix typos in complex-tidb-binlog.yaml.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6340

Fix typos in complex-tidb-binlog.yaml

---

ticdc/deploy-ticdc.md
ticdc/manage-ticdc.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6258

ticdc: add more docs about unified sorter

---

tispark-overview.md

- [x ] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs) that's required for repo owners to accept my contribution.
add a missing '.' in tispark-overview.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6386

Fix typo: tispark-overview.md

---

tikv-configuration-file.md

Doc change for tikv/tikv#10272.

Update default value for RocksDB soft-pending-compaction-bytes-limit

---

system-variables.md
tidb-configuration-file.md

Improve wording in SEM docs.
- Other reference link(s): https://github.com/pingcap/docs/pull/5647

minor wording changes on sem docs

---

tikv-configuration-file.md

Add corresponding docs change to tikv/tikv#9197.
No.

tikv: add configuration docs for I/O rate limiter

---

system-variables.md

This adds basic docs for a mysql-compatible feature. It has been present in TiDB for a long time.

system-variables: add warning count

---

sql-statements/sql-statement-split-region.md

Enhance descriptions of the Split Region section according to the feedbacks from the user support issues
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6318

Enhance descriptions of the Split Region section

---

tiflash/use-tiflash.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6427

mpp support new ops

---

telemetry.md

add new telemetry feature.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6406

Add new telemetry feature

---

system-variables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6265

system variables: add system variable cte_max_recursion_depth

---

TOC.md
sql-statements/sql-statement-with.md

Close https://github.com/pingcap/docs-cn/issues/6216
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6220 https://github.com/pingcap/docs-cn/pull/6265

Add document for CTE

---

tiflash/use-tiflash.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6428

Update tiflash supported pushdown expression list

---

system-variables.md

This is a minor feature that is MySQL compatible.
The TiDB PR is: https://github.com/pingcap/tidb/pull/23713
https://github.com/pingcap/tidb/pull/23713

system-variables: add init connect

---

tiflash/use-tiflash.md

update tiflash documents about cartesian join
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6429

update tiflash documents about cartesian join support

---

clustered-indexes.md
tidb-binlog/tidb-binlog-overview.md
upgrade-tidb-using-tiup.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6405
- https://github.com/pingcap/tidb/issues/24133
- https://github.com/pingcap/tidb/pull/24135
- https://github.com/pingcap/tidb-binlog/pull/1040

tidb-binlog: support binlog for clustered index

---

tiflash/use-tiflash.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6430

fix system table replica doc

---

mysql-compatibility.md
sql-statements/sql-statement-change-column.md
sql-statements/sql-statement-modify-column.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6413

modify the column type change doc

---

tikv-configuration-file.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6449

resolevd-ts: add resolved-ts related config doc

---

tikv-configuration-file.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6399

TiKV config: add abort-on-panic

---

br/backup-and-restore-faq.md
br/backup-and-restore-tool.md

add a document for backup restore system tables.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6403

br: add a document for backup restore systables

---

roadmap.md

update tidb roadmap
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6401

Update the tools part in roadmap.md

---

pd-configuration-file.md
pd-control.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6452

*: update PD configuration

---

sql-statements/sql-statement-show-table-regions.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6467

Correct the region IDs in the show table example #6480

---

sql-statements/sql-statement-with.md

Fix ebnf display
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6515

Fix ebnf display

---

migrate-from-aurora-using-lightning.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6484

lightning: fix a lightning config bug

---

upgrade-tidb-using-tiup.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6474

Update content about upgrade

---

benchmark/v5.0-performance-benchmarking-with-tpch.md

Add alias for `/benchmark/v5.0-performance-benchmarking-with-tpch.md` deleted in https://github.com/pingcap/docs/pull/5844
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6511

Add alias for 5.0 mpp test report in dev

---

as-of-timestamp.md
experimental-features.md
stale-read.md

Add note about stale read
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6518, https://github.com/pingcap/docs-cn/pull/6525

Add note about stale read

---

download-ecosystem-tools.md
pd-control.md
pd-recover.md
production-deployment-using-tiup.md
quick-start-with-tidb.md
scale-tidb-using-tiup.md
ticdc/manage-ticdc.md
tiup/tiup-bench.md
tiup/tiup-command-mirror-rotate.md
tiup/tiup-component-cluster-deploy.md
tiup/tiup-component-management.md
tiup/tiup-mirror.md
tiup/tiup-playground.md

Bump version for v5.1.0
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6517

Bump version for v5.1.0

---

releases/release-5.1.0.md

fix a display issue in dev

---

TOC.md

Add 5.1 to the release notes TOC

Add 5.1 to the release notes TOC

---

roadmap.md

https://github.com/pingcap/tidb/issues/17526 is finished, so update the roadmap.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6555

*: upadate roadmap

---

partitioned-table.md

fix partition table doc error
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6558

fix partition table doc error

---

as-of-timestamp.md

Add workaround about using Stale Read with TiFlash.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6541

Add workaround about using Stale Read with TiFlash

---

releases/release-5.1.0.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6531

release-5.1.0: update CTE description

---

ticdc/troubleshoot-ticdc.md

- This PR is translated from: None
- Other reference link(s): None

Fix ticdc canal-json related doc

---

pd-configuration-file.md
tiflash/tiflash-configuration.md

Signed-off-by: Ryan Leung <rleungx@gmail.com>
This PR removes some useless configurations of PD. 

remove some useless configurations

---

hybrid-deployment-topology.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6635

“location_labels” Spelling mistake

---

sql-statements/sql-statement-with.md

Remove a blank line that causes display failure
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6575

Remove a blank line that causes display failure

---

tikv-configuration-file.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6557

TiKV configuration: update max-peer-down-duration default value

---

configure-memory-usage.md

from the source code, the default is 1G
https://github.com/pingcap/tidb/blob/78f33e692a2888a8b167ff06ca91055372455198/config/config.go#L563
and the change is introduced from https://github.com/pingcap/tidb/pull/14951
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6503
- Other reference link(s): https://github.com/pingcap/tidb/pull/14951

configure-memory-usage: update default value

---

quick-start-with-tidb.md

Add a note to clarify the example IP in quick-start-with-tidb.md.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6375
- Other reference link(s): https://github.com/pingcap/docs-cn/issues/6374

quick-start-with-tidb: add a note to clarify the example ip

---

partitioned-table.md

adding the correction to incorrect examples. it's helpful for reader to understand it.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6560

partitioned-table: adding the correction to incorrect examples

---

dumpling-overview.md

added config example for s3.region
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6539

added config example for s3.region

---

experimental-features.md
quick-start-with-tidb.md
ticdc/ticdc-open-protocol.md

+ Add a note to clarify the purpose of the quick start guide
+ remove a experimental feature of ticdc
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6442 https://github.com/pingcap/docs-cn/pull/6404

Add a note to clarify the purpose of the quick start guide

---

tikv-configuration-file.md

Overhauling TiKV RocksDB configuration file (#5746)

---

functions-and-operators/aggregate-group-by-functions.md
functions-and-operators/expressions-pushed-down.md
functions-and-operators/json-functions.md

- fixed some broken external links
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/6626

fix-broken-external-links

---

tikv-configuration-file.md

Fix some default configurations for RocksDB

---

tikv-configuration-file.md

Added a note about grpc-compression-type
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6475

Added a note about grpc-compression-type

---

hardware-and-software-requirements.md

Updated TiUP version
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/6546

Updated TiUP version

---

check-before-deployment.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6377

Remove the swappiness parameter

---

faq/migration-tidb-faq.md

added the FAQ links of the migration-related tools in the Migration FAQs document
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6663

Migration FAQs: added the FAQ links of the migration related tools

---

sql-statements/sql-statement-show-variables.md
statement-summary-tables.md
system-variables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6718

Update the default value of tidb_stmt_summary_max_stmt_count

---

.github/workflows/dispatch.yml

Trigger  branch `refactor-migration-docs` build on pr push.

chore: trigger refactor docs build

---

download-ecosystem-tools.md
pd-recover.md
production-deployment-using-tiup.md
production-offline-deployment-using-tiup.md
quick-start-with-tidb.md
scale-tidb-using-tiup.md
ticdc/manage-ticdc.md
tiup/tiup-component-cluster-deploy.md
upgrade-tidb-using-tiup.md

Bump version for v4.0.14

---

sync-diff-inspector/sync-diff-inspector-overview.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6749

fix a typo for sync_diff_inspector

---

.circleci/config.yml
.github/workflows/dispatch.yml

refactor-migration-docs: Update CI config

---

migration-overview.md

It's juts a demo for discussion, I would translate it into enlish after refinement

update migration overview demo in chinese

---

data-migration/aurora/increment-aurora.md
data-migration/cloud/aws-tidb.md
data-migration/cloud/google-tidb.md
data-migration/cloud/migrate-cloud-overview.md
data-migration/file/csv-tidb.md
data-migration/file/file-migration-overview.md
data-migration/file/sql-tidb.md
data-migration/mysql/huge-data.md
data-migration/mysql/increment-mysql.md
data-migration/mysql/small-data.md
data-migration/tidb-tidb.md

fix blank title

---

benchmark/v5.1-performance-benchmarking-with-tpch.md

This variable is deprecated and useless when mpp is enabled, but may confuse users, so I remove it.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6703

remove useless variable

---

grafana-tidb-dashboard.md

removed a line in the "TiDB Monitoring Metrics" document
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5753

TiDB Monitoring Metrics: remove a line

---

tidb-configuration-file.md

Added a security option `require-secure-transport` in TiDB configuration file
- This PR is translated from: [#6696](https://github.com/pingcap/docs-cn/pull/6696)

TiDB configuration: add a security option `require-secure-transport`

---

scripts/verify-link-anchors.sh

Fix Lint by locking plugin versions

chore: lock plugin versions

---

benchmark/v5.0-performance-benchmarking-with-tpch.md

Deleted a line set @@tidb_opt_broadcast_join=0;
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6704

Delete a line set @@tidb_opt_broadcast_join=0;

---

config-templates/complex-cdc.yaml

Added # gc-ttl: 86400 
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6465

Add gc ttl

---

ticdc/ticdc-open-protocol.md

Updated golang demo link
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6755

TiCDC: update a golang demo link

---

br/use-br-command-line-tool.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6296

br/use-br-command-line-tool: supplement br note

---

.github/pull_request_template.md
CONTRIBUTING.md

pr_template: Provides tips for cherry-pick
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6702

pr_template: Provides tips for cherry-pick

---

tidb-configuration-file.md

Add documentation for `auto-tls` that was introduced in https://github.com/pingcap/tidb/pull/24141

Add docs for auto-tls setting

---

tidb-scheduling.md

tidb-scheduling: fix typo

---

tiup/tiup-cluster-topology-reference.md

This pull request updates the `log_dir` description, which should be the log directory, not data one.

The `log_dir` should be the log directory

---

functions-and-operators/aggregate-group-by-functions.md

add detail version support for APPROX_PERCENTILE function in aggregate-group-by-functions.md
added
customer use tidb:v4.0.1 and try to use APPROX_PERCENTILE function but got error: FUNCTION does not exist.
release-4.0
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6878

add detail version support for APPROX_PERCENTILE function in aggregate-group-by-functions.md

---

error-codes.md
support.md

Fix a broken link
Alternative targets:
- https://dev.mysql.com/doc/mysql-errors/5.7/en/server-error-reference.html
- https://dev.mysql.com/doc/mysql-errors/8.0/en/
Closes #6194

Fix broken link in error codes doc and support doc

---

scale-tidb-using-tiup.md

docs: fix format for TiKV and PD configuration file template invalid.

---

basic-sql-operations.md

separate query statement and result in two text boxes.
- Other reference link(s): #6204

docs: separate query statement and result in two text boxes. (#6204)

---

adopters.md

404 links caused by Chinese site refactor.

adopters: remove 404 links

---

TOC.md
ticdc/manage-ticdc.md
ticdc/ticdc-open-api.md
ticdc/ticdc-overview.md
tidb-configuration-file.md

ticdc: fix wording
Open API --> OpenAPI

ticdc: fix wording

---

ticdc/ticdc-open-api.md

ticdc-open-api: correct some error
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6932 https://github.com/pingcap/docs-cn/pull/6936

ticdc-open-api: correct some error

---

.github/pull_request_template.md
CONTRIBUTING.md
README.md

update PR template for v5.2
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6865

update PR template for v5.2

---

.github/workflows/dispatch.yml

chore: stop building temporary

---

sql-plan-management.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6943

fix typo for sql-plan-management.md

---

alert-rules.md

updated descriptions about `TiKV_coprocessor_request_error` and `TiKV_coprocessor_request_lock_error` in "alert-rules.md" file.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6930

alert rules: update some descriptions

---

ticdc/manage-ticdc.md
tiup/tiup-component-dm-edit-config.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6931

fix typo: relaod -> reload

---

releases/release-5.2.0.md

Fix title typo

---

adopters.md

adopters: add xiaomi

---

tidb-configuration-file.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7021

correct a default value

---

tidb-configuration-file.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7020

add release notes information

---

.circleci/config.yml
scripts/check-conflicts.py
scripts/check-control-char.py
scripts/check-file-encoding.py
scripts/check-manual-line-breaks.py
scripts/check-tags.py
scripts/check-zh-punctuation.py
scripts/file-format-lint.py
scripts/get-issue-number.py

Migrate scripts previously hosted in [CharLotteiu/pingcap-docs-checks](https://github.com/CharLotteiu/pingcap-docs-checks) to pingcap/docs.
> **NOTE:**
>
> Corresponding config changes should be made to all repos that have referenced these py files, including docs-cn, docs-tidb-operator, docs-dm, blogs.
- …

chore: migrate scripts to docs

---

credits.md

updated links to the full list of code and docs contributors
closes #6193
- This PR is translated from:[#5901](https://github.com/pingcap/docs-cn/pull/5901)

credits: update links to the full list of code and docs contributors

---

dynamic-config.md

changed a link's name and a time in "dynamic-config.md".
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6964

modify configuration online: change a name for consistency

---

pd-configuration-file.md

added log level related configuration "`level`" in "pd-configuration-file.md".
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6963

PD configuration file: add log level

---

production-offline-deployment-using-tiup.md
upgrade-tidb-using-tiup.md

Fix 2 broken links of tiup config files
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7042

Fix 2 broken links of tiup config files

---

TOC.md

Fix a TOC display error introduced in https://github.com/pingcap/docs/pull/6138.

Fix TOC display error

---

sql-statements/sql-statement-kill.md

Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>
fix the correctness problem about kill

sql: fix the correctness problem about kill

---

alert-rules.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6978

Update alert rule for low space

---

releases/release-2.1.17.md

- [ ×] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs) that's required for repo owners to accept my contribution.
Modified a typo.
- [× ] v3.0 (TiDB 3.0 versions)
- [× ] v2.1 (TiDB 2.1 versions)

Modify a typo  

---

.github/workflows/dispatch.yml

Trigger website build when pr merged.

chore: add dispatch back

---

releases/release-2.1.17.md

Modify a typo. close https://github.com/pingcap/docs/issues/2218 
@ran-huang  Please help review my PR. Thank you.

modify a typo-2

---

overview.md

Add a few links to overview.md to make docs in line with its Chinese version. 
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6306
- Other reference link(s): 
@ran-huang

add doc links to overview.md

---

statement-summary-tables.md

This page mistakenly claimed that statements_summary was in performance_schema rather than information_schema. I also added additional clarification about the difference.

performance_schema -> information_schema

---

scripts/check-file-encoding.py

binary mode doesn't take an encoding argument, so remove encoding.

chore: update ci scripts

---

TOC.md
_index.md
download-ecosystem-tools.md
pd-control.md
pd-recover.md
production-deployment-using-tiup.md
quick-start-with-tidb.md
releases/release-5.2.0.md
releases/release-5.2.1.md
releases/release-notes.md
scale-tidb-using-tiup.md
ticdc/manage-ticdc.md
tiup/tiup-component-cluster-deploy.md
tiup/tiup-component-management.md
tiup/tiup-mirror.md
tiup/tiup-playground.md
upgrade-tidb-using-tiup.md

release-notes: add 5.2.1 release notes
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7086

release-notes: add 5.2.1 release notes

---

tikv-configuration-file.md

The enable-compaction-filter in tikv-configuration-file.md is default false now , but actually it is default true.
I have used 'tiup playground' to test v5.0.0,v5.0.1,v5.0.2,v5.0.3,v5.1.0,v5.1.1 ,  and enable-compaction-filter is default true in all versions.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7084
- …

fix-enable-compaction-filter-in-tikv-configuration-file

---

configure-placement-rules.md

Fixed two wrong placement commands in "configure-placement-rules.md".
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7073

Configure placement rules: fix placement doc

---

adopters.md

adopters: add Pinterest

---

faq/sql-faq.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7043

faq: add info for schema is changed error

---

adopters.md

adopters: remove Pinterest

---

mysql-compatibility.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7153

Fix wrong wording in mysql-compatibility.md

---

adopters.md

adopters: add Huya Live

---

dynamic-config.md

add dynamic online change cdc configuration docs.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7148

For 4.0.15: tikv(cdc): dynamic online change cdc configuration

---

dumpling-overview.md
scripts/verify-link-anchors.sh

Test dumpling video

---

download-ecosystem-tools.md
pd-recover.md
production-deployment-using-tiup.md
production-offline-deployment-using-tiup.md
quick-start-with-tidb.md
scale-tidb-using-tiup.md
ticdc/manage-ticdc.md
tiup/tiup-component-cluster-deploy.md
upgrade-tidb-using-tiup.md

Change version number to v4.0.15
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7199

bump version for v4.0.15

---

download-ecosystem-tools.md
pd-recover.md
production-deployment-using-tiup.md
quick-start-with-tidb.md
ticdc/manage-ticdc.md
tiup/tiup-component-cluster-deploy.md
upgrade-tidb-using-tiup.md

Change the version number to 5.0.4
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7200

bump version for 5.0.4

---

download-ecosystem-tools.md
pd-control.md
pd-recover.md
production-deployment-using-tiup.md
quick-start-with-tidb.md
ticdc/manage-ticdc.md
tiup/tiup-component-management.md
tiup/tiup-mirror.md
tiup/tiup-playground.md
upgrade-tidb-using-tiup.md

Change version number to 5.1.2
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7201

Bump version for 5.1.2

---

system-variables.md

Signed-off-by: unconsolable <chenzhipeng2012@gmail.com>
Document `tidb_enable_noop_functions` controls system variable `sql_auto_is_null`, which is introduced by pingcap/tidb#28247
- This PR is translated from: pingcap/docs-cn#7162
- Other reference link(s): pingcap/tidb#28247

system variables: update tidb_enable_noop_functions behavior

---

pd-configuration-file.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6884

docs: update pd-configuration about upgrade

---

sql-statements/sql-statement-create-index.md

fix example for expression index
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7127

fix example for expression index

---

system-variables.md

This is auto generated from the server code.
It updates the permitted ranges of values following the merge of https://github.com/pingcap/tidb/pull/28842

system-variables: update permitted ranges

---

basic-features.md

There is no series of GA tests for `add columns`. I think it is better to update the document.
- Other reference link(s): https://github.com/pingcap/tidb/issues/29150

*: update add columns features

---

download-ecosystem-tools.md
pd-control.md
pd-recover.md
production-deployment-using-tiup.md
quick-start-with-tidb.md
scale-tidb-using-tiup.md
ticdc/manage-ticdc.md
tiup/tiup-component-cluster-deploy.md
tiup/tiup-component-management.md
tiup/tiup-mirror.md
tiup/tiup-playground.md
upgrade-tidb-using-tiup.md

Bump-version-for-5.2.2
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7358

Bump-version-for-5.2.2

---

get-started-with-tidb-lightning.md
tidb-lightning/tidb-lightning-backends.md
tidb-lightning/tidb-lightning-checkpoints.md
tidb-lightning/tidb-lightning-configuration.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7285 & https://github.com/pingcap/docs-cn/pull/7340

lightning: add description for tidb backend

---

tidb-lightning/tidb-lightning-configuration.md

In https://github.com/pingcap/docs/pull/6669, I've modified some expressions on `strict-format`. This PR is to make sure that the related docs are consistent
- Other reference link(s): https://github.com/pingcap/docs/pull/6669

Update tidb-lightning-configuration.md to make sure consistency

---

tidb-lightning/tidb-lightning-configuration.md

Corrected the default values of checksum and analyze in Lightning.
checksum should be "required" by default
analyze should be "optional" by default
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7388

Corrected the default values of checksum and analyze in Lightning.

---

tiflash/use-tiflash.md

update functions supported by TiFlash
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7379

update functions supported by TiFlash

---

.github/pull_request_template.md
CONTRIBUTING.md
README.md

chore: update pr template for v5.3
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7419

chore: update pr template for v5.3

---

generated-columns.md

Fix a broken link format

---

adopters.md

Update SHAREit Group into the TiDB Adopters.

Update SHAREit into Adopters

---

best-practices/pd-scheduling-best-practices.md
pd-configuration-file.md
pd-control.md

Updated default values and version info of the following configurations：
- `patrol-region-interval`, `max-days`, `max-backups`, `max-snapshot-count`, `max-pending-peer-count`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7406

PD config: update some default values of PD configurations

---

pd-control.md

Changed the value of "enable-placement-rules" in some examples and removed the store limit scene.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7429

PD control: remove store limit scene

---

.github/workflows/ci.yaml
.github/workflows/link-check.yaml

- Add link anchor checks GitHub action, because these checks are too buggy in Jenkins and affect merge.
- Add back external link check action
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7467

chore: add link check ci

---

ticdc/manage-ticdc.md

add SASL config item for ticdc
https://github.com/pingcap/ticdc/pull/1789

ticdc: add SASL config item

---

TOC.md
tidb-lightning/tidb-lightning-configuration.md
tidb-lightning/tidb-lightning-error-resolution.md

Document the error resolution features, introduced in pingcap/tidb#27181 and pingcap/tidb#28464.

tidb-lightning: document max-error and duplicate-resolution

---

pd-recover.md

The default comparison principle for sort is dictionary order, not number size
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7331

pd-recover: fix inappropriate commands

---

br/use-br-command-line-tool.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7404 and https://github.com/pingcap/docs-cn/pull/7428

 br: update doc for encrypt

---

tidb-lightning/tidb-lightning-configuration.md
tidb-lightning/tidb-lightning-error-resolution.md

- Other reference link(s): https://github.com/pingcap/docs-cn/pull/7430

fix the default value of duplicate-resolution

---

placement-rules-in-sql.md

placement rules: fix bad wording

---

TOC.md
experimental-features.md
online-unsafe-recovery.md
pd-control.md

- Added the document "Online Unsafe Recovery".
- Added `unsafe remove-failed-stores [store-ids | show | history]` command in "PD Control".
1. https://github.com/pingcap/docs-cn/pull/7381
2. https://github.com/pingcap/docs-cn/pull/7509

Add online unsafe recovery related documents

---

system-variables.md

system-variables: add tidb_enable_pseudo_for_outdated_stats
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7351

system-variables: add tidb_enable_pseudo_for_outdated_stats

---

TOC.md
sql-plan-replayer.md

sql-plan-replayer: add sql-plan-replayer doc
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7380

sql-plan-replayer: add sql-plan-replayer doc

---

sql-statements/sql-statement-analyze-table.md
statistics.md

statistics: add the updates of the new grammar
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7391

statistics: add the updates of the new grammar

---

troubleshoot-write-conflicts.md

fix a typo in the SQL example for troubleshoot-write-conflicts.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7485

fix a typo in the SQL example for troubleshoot-write-conflicts.md

---

ticdc/manage-ticdc.md

Deleted "Configure sink URI with cdclog"

Deleted "Configure sink URI with cdclog"

---

br/use-br-command-line-tool.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7528

br: Add the tag of experimental-feature into encrypt-br

---

TOC.md
mysql-compatibility.md
system-variables.md
temporary-tables.md
ticdc/ticdc-overview.md

Change file name from temporary table to temp tables

Change file name from temporary table to temp tables

---

statistics.md

- Add example, which makes it easier to see how one would run this, including the default `tidb-server-status-port`.
- Add a note about using `--local-infile=1` on the client.
- Add a link to https://docs.pingcap.com/tidb/stable/sql-statement-load-stats
This is what happens without `--local-infile=1`:
```
mysql> LOAD STATS '/tmp/t1.json';
ERROR 2068 (HY000): LOAD DATA LOCAL INFILE file request rejected due to restrictions on access.
mysql> SELECT tidb_version()\G
tidb_version(): Release Version: v5.4.0-alpha-49-g49d995d57
Edition: Community
Git Commit Hash: 49d995d577f64b79168a145cb5be45151ebb557a
Git Branch: master
UTC Build Time: 2021-11-08 10:12:15
GoVersion: go1.16.4
TiKV Min Version: …
```

statistics: Add example and note about local infile

---

ticdc/manage-ticdc.md

Corrected the default value of max-batch-size to 16.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7478

ticdc: update max-batch-size

---

TOC.md
alert-rules.md
ticdc/ticdc-alert-rules.md

Add description of TiCDC alert rules.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7354 

Added TiCDC Alert Rules

---

benchmark/v5.1-performance-benchmarking-with-tpcc.md

\
Fix typos in v5.1-performance-benchmarking-with-tpcc.md

Fix typos in v5.1-performance-benchmarking-with-tpcc.md

---

benchmark/v5.2-performance-benchmarking-with-tpcc.md

Fix a typo in v5.2-performance-benchmarking-with-tpcc.md

---

system-variables.md

Closes https://github.com/pingcap/docs/issues/6844
This is **not new to TiDB 5.3**. It has been around since at least TiDB 5.0. But I don't think we need to cherry pick it to earlier releases.
Also improves the wording of "not supported in production environments". The previous wording implies that there can only be one production envionment, but often customers can have more than one environment. …

system-variables: document tidb-enable-alter-placement

---

tikv-control.md

Updated the description and warning notes for unsafe recovery in "tikv-control.md".
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7519

Update the description and warning notes for unsafe recovery

---

scale-tidb-using-tiup.md

Added some warnings about the use of the Tombstone API in "scale-tidb-using-tiup.md".
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7518

Add some warnings about the use of the Tombstone API

---

TOC.md
tidb-lightning/tidb-lightning-distributed-import.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7580

add version information

---

sync-diff-inspector/sync-diff-inspector-overview.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7585

change the download link for sync-diff-inspector

---

scale-tidb-using-tiup.md
tiup/tiup-cluster-topology-reference.md

1. Deleted gc-ttl and tz from the list.
2. Added gt-ttl and data_dir in the yaml example.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7269

ticdc: add data_dir to examples

---

ticdc/ticdc-open-api.md

Delete the warning note that open api is an experimental feature.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/7541

ticdc: GA TiCDC open API

---

benchmark/v5.2-performance-benchmarking-with-tpch.md

Add aliases to v5.2 TPCH report
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7542

Add aliases to v5.2 TPCH report

---

tidb-configuration-file.md

Update the value of txn-local-latches from enable to enabled
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7486
- Other reference link(s): https://github.com/pingcap/docs-cn/issues/7468

Update the value of txn-local-latches from enable to enabled

---

releases/release-4.0.15.md
system-variables.md

make some correction for tidb_opt_insubq_to_join_and_agg
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7378 https://github.com/pingcap/docs-cn/pull/7203

make some correction for tidb_opt_insubq_to_join_and_agg

---

system-variables.md

Corrected the description of `tidb_allow_fallback_to_tikv` in "system-variables.md".
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7238

system variables: correct the description of `tidb_allow_fallback_to_tikv`

---

ticdc/manage-ticdc.md

Changed cdc-test to topic-name.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/7204

optimization config desc

---

tikv-configuration-file.md

Added `max-grpc-send-msg-len` configuration in "tikv-configuration-file.md".
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7298

add `max-grpc-send-msg-len` configuration

---

sync-diff-inspector/sync-diff-inspector-overview.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7608

update the download link for sync-diff-inspector

---

enable-tls-between-components.md
pd-control.md
troubleshoot-lock-conflicts.md
troubleshoot-write-conflicts.md

Use tiup for commands in the docs. Replacing `./pd-ctl` with `tiup ctl pd`.

replace `./pd-ctl` with `tiup ctl pd`

---

sync-diff-inspector/sync-diff-inspector-overview.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7660

sync-diff-inspector: update docker link

---

hardware-and-software-requirements.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7498

update ticdc recommended disk size

---

ticdc/ticdc-open-protocol.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7597

ticdc: update java example link

---

system-variables.md

Fix a mistaken link
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7342

Fix a mistaken link

---

dynamic-config.md

add dynamic online change cdc configuration docs.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/7241

tikv(cdc): dynamic online change cdc configuration

---

optimizer-hints.md
sql-statements/sql-statement-create-sequence.md

Align 2 prs from docs-cn (sql and planner)
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7417 https://github.com/pingcap/docs-cn/pull/7202

Align 2 prs from docs-cn (sql and planner)

---

faq/sql-faq.md

Correct description about DELETE space release
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7165

Correct description about DELETE space release

---

placement-rules-in-sql.md

Signed-off-by: xhe <xw897002528@gmail.com>
- Other reference link(s): pingcap/tidb#29908

tidb: warn about the limitations of placement rules dict syntax

---

table-attributes.md

Small fixes for the table attributes document
This PR is in line with https://github.com/pingcap/docs-cn/pull/7627.

table-attributes: minor fixes

---

alert-rules.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7409

update some alert rules

---

tidb-lightning/tidb-lightning-distributed-import.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7710

lightning: fix lightning distribute import config

---

releases/release-4.0.9.md

Added an entry #21290 in the release notes.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/7717

Add a missing note to v4.0.9 release notes

---

experimental-features.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7593

Update experimental features for v5.3

---

production-deployment-using-tiup.md
quick-start-with-tidb.md
scale-tidb-using-tiup.md
tiup/tiup-component-cluster-deploy.md
tiup/tiup-component-management.md
tiup/tiup-mirror.md
tiup/tiup-playground.md
upgrade-tidb-using-tiup.md

Bump versions for tiup related content for 5.3.0
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7561

 Bump versions for tiup related content for 5.3.0

---

dashboard/dashboard-user.md

fix the expression about creating sql user when enabling sem
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7605

fix the expression about creating sql user when enabling sem

---

quick-start-with-tidb.md
tiup/tiup-playground.md

change-tiup-related-content
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7685

change-tiup-related-content

---

explain-indexes.md
releases/release-4.0.9.md

Deleted the following duplicated line in the example:
EXPLAIN SELECT * FROM t1 WHERE intkey BETWEEN 300 AND 310;
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/7731

Delete a duplicated line in the example in explain-indexes.md 

---

best-practices/haproxy-best-practices.md

1、移除systemd方式启动、停止haproxy；
2、修改haproxy安装方式；
1、原来使用yum安装haproxy的方式，会导致haproxy版本过旧；
1、当前haproxy2.5.0版本使用在tidb 5.3.0版本上；

Update haproxy best practices using haproxy2.5.0

---

quick-start-with-tidb.md

test simpletab

---

.github/workflows/dispatch.yml

chore: update dispatch in release-5.3
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7551

chore: update dispatch in release-5.3

---

.github/workflows/dispatch.yml
releases/release-5.3.0.md

Fix a rendering failure caused by wrong format
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7759

Fix a rendering failure caused by wrong format

---

TOC.md

Update release notes info in TOC

update release notes info in TOC

---

releases/release-5.3.0.md

It currently looks like 'Telemetry' is a subheading of 'Removed feature', which is not the case and can lead to incorrect conclusions.

release-5.3.0: Fix level for 'Telemetry'

---

tikv-configuration-file.md

Added: documentation for existing configuration parameter [`cert-allowed-cn`](https://github.com/tikv/tikv/blob/36a32504806411b3d620d3abff06166cc7296484/components/security/src/lib.rs#L31) in TiKV configuration
This configuration parameter is implemented (and works as expected), but is missing from the documentation.
- This PR is …

tikv: Documentation for `cert-allowed-cn` configuration directive

---

best-practices/haproxy-best-practices.md

Remove a redundant space in a command in haproxy-best-practices.md.
- Other reference link(s): https://github.com/pingcap/docs/pull/7046

Remove a redundant space in a command

---

releases/release-5.3.0.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7764

release note 5.3.0: fix RPO and RTO wrong description #7764

---

releases/release-5.3.0.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7767

fix RPO and RTO in v5.3.0 release note

---

ticdc/manage-ticdc.md

Corrected description about RTO and RPO.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/7768

Corrected RTO and RPO in manage-ticdc.md

---

TOC.md
releases/release-5.2.3.md
releases/release-notes.md
releases/release-timeline.md

releases: add tidb 5.2.3 release note
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7715

releases: add tidb 5.2.3 release note

---

TOC.md
releases/release-5.0.5.md
releases/release-notes.md
releases/release-timeline.md

releases: add tidb 5.0.5 release notes
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7714

releases: add tidb 5.0.5 release notes

---

information-schema/information-schema-data-lock-waits.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7377/files

Add warning about data_lock_waits table won't record optimistic transaction blocked by pessimistic transaction

---

tidb-lightning/tidb-lightning-configuration.md

lightning: update config description of checksum and analyze
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7408

lightning: update config description of checksum and analyze

---

benchmark/benchmark-tidb-using-sysbench.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7248/files

Correct the description about the default transaction mode

---

grafana-tidb-dashboard.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7398

Update transaction types panel name

---

ticdc/manage-ticdc.md

Updated descriptions about partition-num and max-message-bytes parameters.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/7570

cdc: add advice for how to use kafka sink in ticdc

---

.github/workflows/bot.yaml
scripts/pr_reminder.py

Run a script in GitHub Actions, which sends scheduled PR reports to a Lark group.

Add a lark bot for PR reminder

---

.github/workflows/bot.yaml

Use an env var for lark bot webhook.

.github: add env for lark bot

---

data-type-date-and-time.md

Fix error on conversion between date and time types
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7692

Fix error on conversion between date and time types

---

alert-rules.md

Fix TiDB alert rule

---

tiup/tiup-component-cluster-scale-in.md

add a warning note
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7572

Update tiup component cluster scale-in

---

tidb-computing.md

Optimize wording for tidb-computing
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7701

Optimize wording for tidb-computing

---

upgrade-tidb-using-tiup.md

Fix a typo in upgrade-tidb-using-tiup

Fix a typo in upgrade-tidb-using-tiup

---

tidb-configuration-file.md

TiDB: remove invalid log format
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7963

TiDB: remove invalid log format

---

tidb-configuration-file.md

https://github.com/pingcap/docs-cn/pull/7929
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7929

Update the description for Prepare Plan Cache

---

statistics.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7359

statistics: Add a note about the solution of a potential OOM issue

---

releases/release-5.0.5.md

Remove a note in release-5.0.5.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8001

Remove a note in release-5.0.5.md

---

TOC.md
download-ecosystem-tools.md
ecosystem-tool-user-case.md
ecosystem-tool-user-guide.md
tidb-operator-overview.md

1. Rename **TiDB Ecosystem Tools** to **TiDB Tools** to avoid confusion of external ecosystem tools.
2. Move TiUP docs to **TiDB Tools**. 
3. In TiDB Tools, add an entry for TiDB Operator. 
4. Add TiUP and TiDB Operator to TiDB Tools overview, user case, and download documents. 
The changes for TiUP are only applicable to 4.0 and later releases, so this PR needs modification after being applied to other branches.  …

Move TiUP docs to TiDB Tools and add entry for TiDB Operator

---

maintain-tidb-using-tiup.md

Update the order of starting and stopping components by using tiup
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7403, https://github.com/pingcap/docs-cn/pull/7904

Update the order of starting and stopping components by using tiup

---

auto-increment.md

Document a scenario where TiDB does not produce the same results as MySQL yet this is considered legal.

auto_increment: improve description of monotonic

---

br/backup-and-restore-faq.md
releases/release-4.0-ga.md
releases/release-4.0.0-rc.1.md
releases/release-4.0.0-rc.2.md
releases/release-4.0.0-rc.md
releases/release-4.0.10.md
releases/release-4.0.11.md
releases/release-4.0.12.md
releases/release-4.0.13.md
releases/release-4.0.14.md
releases/release-4.0.15.md
releases/release-4.0.2.md
releases/release-4.0.3.md
releases/release-4.0.5.md
releases/release-4.0.6.md
releases/release-4.0.7.md
releases/release-4.0.8.md
releases/release-4.0.9.md
ticdc/ticdc-open-protocol.md
ticdc/ticdc-overview.md

changed github.com/pingcap/ticdc to github.com/pingcap/tiflow

changed github.com/pingcap/ticdc to github.com/pingcap/tiflow

---

overview.md

Added two intro videos to "Overview"

Add two intro videos to "Overview"

---

scripts/pr_reminder.py

chore: fix typos in pr_reminder

---

overview.md

Revised the video place in "Overview"

Revise the video place in "Overview"

---

glossary.md

Added the explanation of TSO in "glossary.md".
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7258

Add the explanation of TSO

---

download-ecosystem-tools.md
pd-recover.md
production-deployment-using-tiup.md
production-offline-deployment-using-tiup.md
quick-start-with-tidb.md
scale-tidb-using-tiup.md
ticdc/manage-ticdc.md
tiup/tiup-component-cluster-deploy.md
upgrade-tidb-using-tiup.md

Bump version for v4.0.16
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8025

Bump version for v4.0.16

---

scripts/pr_reminder.py

chore: Fix typo in script

---

tiup/tiup-playground.md

Added two missed blanks in "tiup/tiup-playground.md".
- Other reference link(s): #7328

TiUP playground: add missed blanks

---

ticdc/ticdc-overview.md

Updated the code repo link of TiCDC
from https://github.com/pingcap/tiflow
to https://github.com/pingcap/tiflow/tree/master/cdc
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/8062

Updated the code repo link of TiCDC

---

.github/pull_request_template.md

chore: add v5.4 to pr template

---

scripts/pr_reminder.py

chore: add area dm to pr reminder

chore: add area dm to pr reminder

---

adopters.md
data-migration/migrate-mysql-tidb-above-tb.md

Add the doc for `Migrate Data above Terabytes from MySQL to TiDB`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7480

data-migration: add doc for migrate from mysql to tidb above tb

---

data-migration/migrate-with-binlog-sql-expression-filter.md

Add how to filter binlog events using SQL expressions
- This PR is translated from: data-migration/migrate-with-binlog-sql-expression-filter.md in https://github.com/pingcap/docs-cn/pull/7480

Add how to filter binlog events using SQL expressions

---

scripts/pr_reminder_basedon_assignee.py

chore: fix typos in py

---

dm/dm-source-configuration-file.md
dm/relay-log.md

update description of relay log
- This PR is translated from: https://github.com/pingcap/docs-dm/pull/863

update description of relay log

---

download-ecosystem-tools.md
pd-recover.md
production-deployment-using-tiup.md
quick-start-with-tidb.md
scale-tidb-using-tiup.md
ticdc/manage-ticdc.md
tiup/tiup-component-cluster-deploy.md
upgrade-tidb-using-tiup.md

bump version for 5.0.6

---

.github/workflows/dispatch.yml

Disable build for master

---

dm/task-configuration-file-full.md

Add DM `collation_compatible ` config description.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8094
- Other reference link(s): https://github.com/pingcap/tiflow/pull/4121

Update the description about DM collation_compatible config

---

migrate-from-csv-files-to-tidb.md

escape cr lf to fix pdf build

---

tikv-configuration-file.md

TiKV config: add docs for raft engine configurations

---

basic-features.md

Remove wrong line in basic feature

Remove wrong line in basic feature

---

releases/release-5.3.0.md

Two bugs were left out of the release notes by mistake
- https://github.com/pingcap/tidb/pull/28528
- https://github.com/pingcap/tidb/pull/27216

Add references to fixed bugs

---

faq/upgrade-faq.md
sql-statements/sql-statement-add-index.md
upgrade-tidb-using-tiup.md

Update warning for DDL execution before cluster upgrade
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8141

Update warning for DDL execution before cluster upgrade

---

dm/maintain-dm-using-tiup.md
dm/quick-create-migration-task.md
dm/quick-start-create-source.md
migrate-small-mysql-shards-to-tidb.md

fix chinese periods

---

tikv-configuration-file.md

Refer to https://github.com/tikv/tikv/pull/10599

update raft log gc related tikv configurations

---

tiup/tiup-mirror.md

Update `tiup mirror` documentation
Closes #7362
Closes https://github.com/pingcap/tiup/issues/1304

tiup-mirror: Extend and update

---

tikv-configuration-file.md

Add a line to explain one configuration item.

add some details for raft engine docs

---

tiflash/tiflash-command-line-flags.md
tiflash/tiflash-configuration.md
tiflash/use-tiflash.md

Add doc for tiflash data validation and dttool.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8077

tiflash: add dttool docs

---

dm/dm-open-api.md
dm/dm-worker-configuration-file.md
dm/relay-log.md

align relay log behaviour in v5.4.0
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8165 https://github.com/pingcap/docs-cn/pull/8113 https://github.com/pingcap/docs-cn/pull/8107

align relay log behaviour in v5.4.0

---

command-line-flags-for-tikv-configuration.md
tikv-configuration-file.md

Add log-related configuration items:
- `level`
- `format`
- `enable-timestamp`
- `filename`
- `max-size`
- `max-days`
- `max-backups`
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8102

TiKV config: Add log-related configuration items

---

benchmark/v5.3-performance-benchmarking-with-tpch.md

Add aliases to v5.3 TPCH report
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8183

Add aliases to v5.3 TPCH report

---

tikv-configuration-file.md

Reverts https://github.com/pingcap/docs/pull/7431 and https://github.com/pingcap/docs/pull/7354
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8206

Revert "TiKV config: add docs for raft engine configurations"

---

sql-statements/sql-statement-show-create-placement-policy.md
sql-statements/sql-statement-with.md

Fix ebnf errors
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8174

Fix ebnf errors

---

system-variables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8157

planner: introduce a new variable tidb_regard_null_as_point #8157

---

tidb-lightning/tidb-lightning-faq.md

Added description about how to clean up metadata schema.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/8160

lightning: clean up metadata schema 

---

dm/dm-open-api.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8189
- Other reference link(s):  https://github.com/pingcap/docs-cn/issues/8188

fix dm openapi http method

---

tikv-configuration-file.md

Revert "Revert "TiKV config: add docs for raft engine configurations""

---

tidb-lightning/tidb-lightning-error-resolution.md

Changed syntax_error_v1 to comment

Changed syntax_error_v1 to comment

---

best-practices/high-concurrency-best-practices.md

Fix blog links in docs

---

download-ecosystem-tools.md
ticdc/manage-ticdc.md

Bump version for v5.4.0, including only ecosystem tools. This PR change must be fully tested.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/8216

Bump version for v5.4.0 - ecosystem tools

---

dm/deploy-a-dm-cluster-using-tiup-offline.md
dm/deploy-a-dm-cluster-using-tiup.md
dm/dm-precheck.md
dm/dmctl-introduction.md
dm/maintain-dm-using-tiup.md

change the determine version to ${version}

dm: update version description

---

tiflash/tiflash-configuration.md

update doc for MPP utilization optimization
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8112

update doc for MPP utilization optimization

---

br/backup-and-restore-faq.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7515

BR: only update 5.4 parts of BR FAQ

---

best-practices/tidb-best-practices.md
dashboard/dashboard-key-visualizer.md
faq/migration-tidb-faq.md
faq/sql-faq.md
faq/tidb-faq.md
tiflash/tiflash-overview.md

Fix more blog links in docs
- Other reference link(s): https://github.com/pingcap/docs/issues/7477

Fix more blog links in docs

---

dashboard/dashboard-access.md
production-deployment-using-tiup.md

5.4.0-tiup-deployment-change
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8158

5.4.0-tiup-deployment-change

---

tidb-troubleshooting-map.md

Fix improper "or" between item lists
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8220

Fix improper "or" between item lists

---

tispark-overview.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8111

ADD: authentication and authorization user doc #8111

---

quick-start-with-tidb.md

Fix the format of note for quick start with TiDB

---

releases/release-4.0.0-rc.md

Fixed a typo in 4.0 RC Release Notes
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8162

Fix a typo in 4.0 RC Release Notes

---

explain-indexes.md

Revised a number in "explain-indexes.md".
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8161

revise a number in "EXPLAIN indexes"

---

production-deployment-using-tiup.md
quick-start-with-tidb.md
scale-tidb-using-tiup.md
tiup/tiup-component-cluster-deploy.md
tiup/tiup-component-management.md
tiup/tiup-mirror.md
tiup/tiup-playground.md
upgrade-tidb-using-tiup.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8214

5.4.0 tiup bump version

---

tidb-limitations.md

Correct the partition number supported by a table
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8238

Correct the partition number supported by a table

---

.github/workflows/bot.yaml

Disable pr reminder bot for v5.4

chore: disable pr reminder bot for v5.4

---

best-practices/java-app-best-practices.md
configure-memory-usage.md
data-type-date-and-time.md
data-type-numeric.md
sql-statements/sql-statement-create-table.md
system-variables.md

Align 4 PRs
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8059 https://github.com/pingcap/docs-cn/pull/8104 https://github.com/pingcap/docs-cn/pull/8219 https://github.com/pingcap/docs-cn/pull/7393

Align 4 PRs

---

br/backup-and-restore-faq.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8294

Fix unclear description and typos in br docs

---

transaction-overview.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7427

Update transaction-overview.md #7427

---

query-execution-plan.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7451

Add a note in v3.0 pointing to a later doc version

---

tidb-configuration-file.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8138

update txn-total-size-limit upper limit #8138

---

keywords.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8299

chore: use TabsPanel

---

br/use-br-command-line-tool.md
ticdc/ticdc-overview.md

- Other reference link(s): https://github.com/pingcap/docs/pull/5879, https://github.com/pingcap/docs/pull/6190

Remove PITR from BR and Pulsar from Lightning
