pingcap/docs

quick-start-with-htap.md, tiflash/use-tiflash.md
Add HTAP tutorial link and extra explanations
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7774
=> Add HTAP tutorial link and extra explanations

config-templates/complex-tiflash.yaml
Signed-off-by: JaySon-Huang <tshent@qq.com>
Fix typos in complex-tiflash.yaml
* Should use ":" instead of "="
* The array-size in `storage.main.capacity` should be the same as `storage.main.dir`
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8320
=> Fix typo in complex-tiflash.yaml

dm/dm-overview.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8351
=> Add v5.4 to the DM overview documentation 

alert-rules.md
Fix a GC alert rules about `TiKV_GC_can_not_work` in v3.0.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8217
=> Fix GC alert expression

tidb-lightning/tidb-lightning-distributed-import.md
Add usage restrictions.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/8249
=> lightning: add usage restriction for tidb-lightning

releases/release-timeline.md
Fix a typo in release-timeline
=> Fix a typo in release-timeline

.github/workflows/dispatch.yml
=> enable build for master

TOC.md, releases/release-5.4.0.md, releases/release-notes.md
Fix a few redudant spaces
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8372
=> Fix a few redudant spaces

br/backup-and-restore-faq.md
Only remained the parts related to v5.3 or earlier versions in 
-Edited (only 5.3) version： https://github.com/pingcap/docs-cn/pull/8205
-Full version: https://github.com/pingcap/docs-cn/pull/7515
=> BR FAQ: only remain 5.3 parts

experimental-features.md
Fix markdown to link to /placement-rules-in-sql.md by removing the space.
=> Fix markdown to link to /placement-rules-in-sql.md

alert-rules.md
Fixed some alert items in "alert-rules.md".
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7275
=> alert rules: fix alert items

configure-placement-rules.md
Updated the description about placement rules
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8050
=> Update the description about placement rules

tikv-configuration-file.md
Updated `max-peer-down-duration` in "tikv-configuration-file.md".
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7902
=> TiKV config: update `max-peer-down-duration`

tidb-binlog/bidirectional-replication-between-tidb-clusters.md
binlog: warn cyclic replication
=> binlog: warn Bidirectional Replication

alert-rules.md
Removed `TiKV_coprocessor_request_error` and `TiKV_coprocessor_request_lock_error` in "alert-rules.md".
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7907
- Other reference link(s): https://github.com/tikv/tikv/pull/11614/files
=> alert-rules: remove 'meet_lock' related alters

benchmark/v5.1-performance-benchmarking-with-tpcc.md, benchmark/v5.2-performance-benchmarking-with-tpcc.md, benchmark/v5.3-performance-benchmarking-with-tpcc.md, two-data-centers-in-one-city-deployment.md
- Fixed a wrong command `tiup bench tpcc prepare --warehouses 5000 --db tpcc -H 127.0.0.1 -p 4000` in docs.
- Updated a sentence in "two-data-centers-in-one-city-deployment.md" for clarification.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7860
=> Fix a wrong commands in docs and update a sentence for clarification

tiflash/tiflash-configuration.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8381
=> Delete a description in tiflash-configuration.md

best-practices/java-app-best-practices.md
- This PR is translated from: https://github.com/pingcap/docs-cn/issues/8401
=> fix a typo in java best practices

br/use-br-command-line-tool.md
correct BR feature description
=> correct BR document

br/use-br-command-line-tool.md
- Other reference link(s): https://github.com/pingcap/docs/pull/7343
=> Update description about backing up system tables

production-deployment-using-tiup.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8402
=> fix a number in tiup prod deployment

TOC.md
=> Fix a TOC issue for PDF generation

tiup/tiup-playground.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8455
=> Remove use of v5.4.0 in dev version

follower-read.md
Signed-off-by: tier-cap <zhengxiaojin@pingcap.com>
tidb replica read support global set.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8422
- Other reference link(s): 
https://github.com/pingcap/docs/pull/6451/files
https://github.com/pingcap/tidb/pull/27622
=> tidb replica read support global set.

.github/pull_request_template.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8477
=> add 6.0 option in pr template 

tiup/tiup-playground.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8462
=> Remove version from tiup playground and add two examples

TOC.md, tidb-in-kubernetes.md, tidb-operator-overview.md
Update TiDB Operator overview to include v1.3.
- This PR is translated from:  https://github.com/pingcap/docs-cn/pull/8398, https://github.com/pingcap/docs-cn/pull/8436
=> update tidb operator version descripiton

download-ecosystem-tools.md, pd-control.md, pd-recover.md, production-deployment-using-tiup.md, quick-start-with-tidb.md, scale-tidb-using-tiup.md, ticdc/manage-ticdc.md, tiup/tiup-component-management.md, tiup/tiup-mirror.md, tiup/tiup-playground.md
Bump version for 5.1.4
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/8453
=> Bump version for 5.1.4

scripts/get-duplicated-notes.py, scripts/internal-deduplicate.py
Add 2 scripts fot release note preparation
=> chore: add 2 scripts for release note preparation

basic-features.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8452
=> Fix wrong feature name for index merge

tiflash/tiflash-configuration.md
Signed-off-by: JaySon-Huang <tshent@qq.com>
The configuration "tmp_path" in TiFlash config file is required if the user deploy a tiflash instance other than tiup/tidb-operator
master/6.0 are not affected.
5.4/5.3/5.2/5.1/5.0/4.0 are affected.
Note that this PR is base on release-5.4 …
=> tmp_path is required if user deploy tiflash instance other than tiup/tidb-operator

releases/release-5.4.0.md, scripts/get-duplicated-notes.py
This PR updates the script to add sort info for each duplicate note according to already published release notes. 
=> release notes: Add sort info for the duplicated notes

tikv-configuration-file.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8185/files
=> Fix name of config item wake-up-delay-duration in TiKV config file #8185

tiup/tiup-cluster.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8500, https://github.com/pingcap/docs-cn/pull/8537
=> update version for 5.2

tiup/tiup-cluster.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8501, https://github.com/pingcap/docs-cn/pull/8536
=> update version for 5.1

tiup/tiup-cluster.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8502, https://github.com/pingcap/docs-cn/pull/8535
=> update version for 5.0

scripts/pr_reminder.py
chore: add a label description in py reminder
=> chore: add a label description in py reminder

br/use-br-command-line-tool.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8504
=> Fix BR link version

br/use-br-command-line-tool.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8531
=> Recover description about system tables

alert-rules.md
Fix ping latency alert solution
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8361
=> fix ping latency alert solution

download-ecosystem-tools.md, pd-control.md, pd-recover.md, production-deployment-using-tiup.md, quick-start-with-tidb.md, scale-tidb-using-tiup.md, ticdc/manage-ticdc.md, tiup/tiup-component-management.md, tiup/tiup-mirror.md, tiup/tiup-playground.md
Bump version for 5.3.1
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/8559
=> Bump version for 5.3.1

releases/release-5.1.4.md, releases/release-5.3.1.md
Change Feature enhancements to Improvements
=> Change Feature enhancements to Improvements

scripts/pr_reminder.py, scripts/pr_reminder_basedon_assignee.py
refine py_reminder_by_assignee to make the 0 value invisible.
=> chore: refine py_reminder_by_assignee

benchmark/v5.4-performance-benchmarking-with-tpcc.md
Fix a typo in v5.4-performance-benchmarking-with-tpcc
=> Fix a typo in v5.4-performance-benchmarking-with-tpcc

tiup/tiup-cluster-topology-reference.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8584
=> Fix tiup storage retention

tidb-lightning/tidb-lightning-configuration.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8235
=>  Add some configs in tidb-lightning-configuration.md

TOC.md, migrate-large-mysql-shards-to-tidb.md, tidb-lightning/deploy-tidb-lightning.md, tidb-lightning/tidb-lightning-backends.md, tidb-lightning/tidb-lightning-faq.md, tidb-lightning/tidb-lightning-requirements.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8228, https://github.com/pingcap/docs-cn/pull/8439
=> Update lightning requirements and add memory info

releases/release-5.4.0.md
Add doc links to rn-5.4 to improve usability.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8414
=> rn: add links to rn-5.4

two-data-centers-in-one-city-deployment.md
Add descriptions about using configurations in `rule.json`.
Note: the change in "releases/release-3.0.3.md" is made to fix a Jenkins error, and this error only occurred in the Chinese doc. So this English PR did not fix that problem.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8365
=> 2dc: add config descriptions

experimental-features.md, sql-prepare-plan-cache.md
SQL prepare execution plan cache: add the experimental feature warning
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7804
=> SQL prepare execution plan cache: add the experimental feature warning

system-variables.md
Update description to tidb_scatter_region
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7466 https://github.com/pingcap/docs-cn/pull/7622
=> Update description to tidb_scatter_region

mysql-compatibility.md
Clarified a description about auto-incremental ID 
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/8604
=> Clarified a description about auto-incremental ID 

tikv-configuration-file.md
Refer to https://github.com/tikv/tikv/issues/11028
=> Fix compaction style in tikv configuration file

tidb-lightning/tidb-lightning-backends.md, tidb-lightning/tidb-lightning-distributed-import.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8333
=>  Add description of can't mix multiple backends

best-practices/high-concurrency-best-practices.md
Revise an expression in "Highly Concurrent Write Best Practices"
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8140
=> revise an expression in "Highly Concurrent Write Best Practices"

tikv-configuration-file.md
Added raftstore.capacity configuration (`capacity`) in the "tikv-configuration-file.md".
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8201
=> TiKV config: add `capacity`

config-templates/complex-tidb-binlog.yaml
Change `tidb-binlog` to `tidb_binlog` in deploy meta.yaml because the former way will make drainer fails.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8615
- Other reference link(s): https://github.com/pingcap/tidb-binlog/issues/1139#event-6215887302
=> update config template

.github/workflows/rebase.yml
chore: update rebase secret key
=> chore: update rebase secret key

auto-increment.md, grafana-pd-dashboard.md, system-variables.md
auto-increment: correct the description in 'limit' part
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7964
=> auto-increment: correct the description in 'limit' part

migrate-small-mysql-shards-to-tidb.md
=> Change auto-incremental to auto-increment

tune-tikv-memory-performance.md
Added parameter specifications about coprocessor in "tune-tikv-memory-performance.md".
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8352
=> tune TiKV memory: revised the performance documentation

tidb-lightning/tidb-lightning-requirements.md
Fix a build failure caused by wrong `<table>` tag
=> fix table attribute error

dm/quick-create-migration-task.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8660
=> Remove migration from files

.github/workflows/dispatch.yml
=> disable trigger website building from docs master

dm/dm-create-task.md
add doc for start-task --start-time
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8640
=> add doc for start-task --start-time

tidb-lightning/tidb-lightning-error-resolution.md
Delete experimental warning in error resolution.
1. https://github.com/pingcap/docs-cn/pull/8641 
2. https://github.com/pingcap/docs-cn/pull/8642
=> lightning: delete experimental warning in error resolution

dm/task-configuration-file-full.md
add a config description about dump files to s3
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8681
=> add a config description about dump files to s3

mysql-compatibility.md, sql-statements/sql-statement-load-data.md
With https://github.com/pingcap/tidb/pull/31303 merged we now support `LOAD DATA...REPLACE`.
- Other reference link(s): ttps://github.com/pingcap/tidb/pull/31303
=> update LOAD DATA ... REPLACE compatibility

tiflash/monitor-tiflash.md
Signed-off-by: bestwoody <bestwoody@163.com>
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8712
=> threads_monitor_of_tiflash

tiflash/monitor-tiflash.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8707
=> Add metrics for min-tso scheduler

tiflash/tiflash-configuration.md
Update tiflash-configuration.md, update default value of dt_enable_logical_split
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/8717/files
=> Update tiflash-configuration.md, update default value of dt_enable_logical_split 

sync-diff-inspector/shard-diff.md
Fix a typo in sync diff
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/7928
=> Fix a typo in sync diff

tidb-lightning/tidb-lightning-faq.md
corrrected tidb-lightning-ctl
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/7946
=> corrrected tidb-lightning-ctl

dm/dm-open-api.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8612
=> DM: update openapi spec

tidb-configuration-file.md
Change the default value of new_collations_enabled_on_first_bootstrap
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8464
=> Change the default value of new_collations_enabled_on_first_bootstrap

explain-mpp.md
tiflash: remove tidb_opt_broadcast_join 
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8740
=> tiflash: remove tidb_opt_broadcast_join

tiflash/tiflash-configuration.md, tiflash/use-tiflash.md
update doc for default checksum strategy.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8711
=> tiflash: update doc for default checksum strategy

sql-statements/sql-statement-create-sequence.md
Fix a typo in create sequence
Close https://github.com/pingcap/docs-cn/issues/8762
=> Fix a typo in create sequence

ticdc/manage-ticdc.md
clarify rowid HandleKey meaning
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/8156
=> ticdc: clarify rowid HandleKey meaning

tidb-binlog/tidb-binlog-reparo.md
update description of start-tso
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/7933
=> update description of start-tso

ticdc/ticdc-canal-json.md
"old" field in "delete" event changed since v5.4.0
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/8653
=> "old" field in "delete" event changed since v5.4.0

tiflash/tiflash-configuration.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8768
=> Thread pool function GA

dm/task-configuration-file-full.md
fixed a typo
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/8774
=> fixed a typo

tikv-configuration-file.md
TiKV configuration change 6.0
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8736
=> TiKV configuration change 6.0

faq/sql-faq.md, privilege-management.md
Update docs to indicate LOAD DATA...REPLACE INTO support
- https://github.com/pingcap/docs/pull/7426
- https://github.com/pingcap/tidb/pull/31303
=> Update docs to indicate LOAD DATA...REPLACE INTO support

pd-control.md
Add pd-ctl  `balance-leader-scheduler` configuration command
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8677
=> Add pd-ctl  `balance-leader-scheduler` config command

functions-and-operators/expressions-pushed-down.md, system-variables.md
Update the expressions and data types that TiDB supports to push down.
① https://github.com/pingcap/docs-cn/pull/8684
② https://github.com/pingcap/docs-cn/pull/8761 (minor updates)
=> Revise the expressions that can be pushed down

dashboard/continuous-profiling.md, experimental-features.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8777
=> Continuous-profiling GA in TiDB 6.0.md

scale-tidb-using-tiup.md, ticdc/manage-ticdc.md, tiflash/use-tiflash.md
- https://github.com/pingcap/docs-cn/pull/8732
- https://github.com/pingcap/docs-cn/pull/8697
- https://github.com/pingcap/docs-cn/pull/8696
- https://github.com/pingcap/docs-cn/pull/8540
=> Align four 6.0 PRs

pd-control.md
Added descriptions about `balance-leader batch`
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8806
=> PD Control: add descriptions about `balance-leader batch`

tikv-configuration-file.md
Revised two notes about Raft Engine
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8787
=> Revise notes about Raft Engine

dashboard/top-sql.md, experimental-features.md, glossary.md, system-variables.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8701, https://github.com/pingcap/docs-cn/pull/8773, https://github.com/pingcap/docs-cn/pull/8755
=> Updates for Top SQL GA

tidb-configuration-file.md
ref: add doc for pessimistic auto-commit
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8396
=> ref: add doc for pessimistic auto-commit

tiflash/tiflash-overview.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8811
=> Add tiflash repo link to overview

tiflash/use-tiflash.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8807
=> Add more warnings about running mpp on partition table

placement-rules-in-sql.md
=> fix typo in placement rules

placement-rules-in-sql.md, telemetry.md
=> Update the link of privacy policy

statistics.md, tidb-lightning/tidb-lightning-configuration.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8624, https://github.com/pingcap/docs-cn/pull/8699, 
=> Update docs for base64 encoding of password and kill auto analyze

production-deployment-using-tiup.md, quick-start-with-tidb.md, scale-tidb-using-tiup.md, tiup/tiup-bench.md, tiup/tiup-cluster.md, tiup/tiup-component-cluster-deploy.md, tiup/tiup-component-management.md, tiup/tiup-mirror.md, tiup/tiup-playground.md, upgrade-tidb-using-tiup.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8816
=> tiup bump version for 6.0

download-ecosystem-tools.md, pd-control.md, pd-recover.md, ticdc/manage-ticdc.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8817
=> bump version for v6.0-ecosystem tools and PD

TOC.md, data-inconsistency-errors.md, error-codes.md, system-variables.md, troubleshoot-data-inconsistency-errors.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7880, https://github.com/pingcap/docs-cn/pull/8767,  https://github.com/pingcap/docs-cn/pull/8792
=> New docs: reduce-data-inconsistency #7880

basic-features.md, experimental-features.md
Update experimental features and basic features in 6.0 
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8783
=> Update experimental features and basic features

blocklist-control-plan.md, explain-overview.md
Unify the title in blocklist-control-plan.md and explain-overview.md from `EXPLAIN Overview` to `TiDB Query Execution Plan Overview`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8857
=> Unify title for explain overview 

credits.md
Add TiFlash to the credits.md because now TiFlash repository https://github.com/pingcap/tiflash is public.
=> Add TiFlash to the credits.md

tikv-configuration-file.md
- Modify configuration description for disable-auto-compactions
- Change value `"true"` to `true`
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/8793
=> Modify configuration description for disable-auto-compactions and fix typo

.github/workflows/dispatch.yml
This reverts commit 60c22fa82b89d49ca48d7413c5dc8d549a11a975.
=> Revert "disable trigger website building from docs master (#7878)"

releases/release-6.0.0-dmr.md
change the order of new features and compatibility changes
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/8904
=> releases: change the order of new features and compatibility changes

.github/workflows/bot.yaml
chore: stop pr bot for v6.0 docs
=> chore: stop pr bot for v6.0 docs

releases/release-6.0.0-dmr.md
Add a missing note.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8917
=> update 6.0 release notes dm compatibility

tiflash/use-tiflash.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7064, https://github.com/pingcap/docs-cn/pull/8863
=> tiflash: Add label schedule for TiFlash

sql-statements/sql-statement-show-stats-meta.md
Update column header description  from `Syntax element` to `Column name`
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/8242
=> Update column header description

config-templates/simple-file-binlog.yaml
There are 3 directories in TiUP configuration, drainer's data_dir (generated by global config), drainer's config.data-dir, and drainer's config.syncer.to.dir.
The priority of this is drainer_servers.config.syncer.to.dir > drainer_servers.data_dir > drainer.config.data-dir, so the data-dir is adjusted to the higher priority version here.
- …
=> Update binlog deploy configuration

sql-statements/sql-statement-commit.md
This is a behavior difference from MySQL that could be impactful to users.
=> Add common scenario for commit failure

tidb-configuration-file.md
Add `grpc-compression-type` to tidb-configuration-file.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/8742
=> Add `grpc-compression-type`to tidb-configuration

sql-statements/sql-statement-modify-column.md
This pull request adds another example that modify column signed int to unsigned int also raises ERROR 8200
```sql
mysql> select tidb_version()\G
tidb_version(): Release Version: v5.4.0
Edition: Community
Git Commit Hash: 55f3b24c1c9f506bd652ef1d162283541e428872
Git Branch: heads/refs/tags/v5.4.0
UTC Build Time: 2022-01-25 08:41:05
GoVersion: go1.16.4
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
mysql> CREATE TABLE t (a int primary key);
Query OK, 0 rows affected (0.07 sec)
mysql> ALTER TABLE t MODIFY COLUMN a INT(10) UNSIGNED;
ERROR 8200 (HY000): Unsupported modify column: this column has primary key flag
mysql>
```
**Tips for …
=> Modify column signed int to unsigned int also raises ERROR 8200

releases/release-5.3.0.md, sql-plan-replayer.md, upgrade-tidb-using-tiup.md
- Translate Prometheus change desc from [#8154](https://github.com/pingcap/docs-cn/pull/8154) to `releases/release-5.3.0.md` and `upgrade-tidb-using-tiup.md`
- Fix typo and format in `releases/release-5.3.0.md`
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8154
=> Add Prometheus change desc, fix typo and format

tiup/tiup-cluster.md
Add a description about daemon process.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/8769
=> Add a description about daemon process

dm/deploy-a-dm-cluster-using-tiup-offline.md
Remove experimental label and warning for DM offline deployment
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/8237/
=> Remove experimental label for DM offline deployment

telemetry.md
Add the description of pseudonymization of IP address.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/8818
=> Update TiDB usage details of telemetry

tiup/tiup-bench.md
Add link for TPC-C and TPC-H.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/8277
=> Add link for TPC-C and TPC-H

releases/release-5.3.0.md
Add asynchronous write IO in store thread for 5.3.0 release note.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8721
=> Add asynchronous write IO in store thread

sync-diff-inspector/sync-diff-inspector-overview.md
fix the download link in v5.1
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/8955
=> fix the download link in v5.1

sync-diff-inspector/sync-diff-inspector-overview.md
fix the download link in v4.0
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/8954
=> fix the download link in v4.0

dynamic-config.md
Set config `tikv log-level` to tikv `log-level`
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/8808
=> Fix config tikv `log-level`

explain-subqueries.md
Fix typo error and refine the description of the plan.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7856
=> Fix description error in explain-subqueries.md

statistics.md, system-variables.md
Update default value of `tidb_analyze_version` in v5.1.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/8411
=> Update default value of `tidb_analyze_version` in v5.1 and v5.2

upgrade-tidb-using-tiup.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8968
=> Update description about the --force parameter

functions-and-operators/date-and-time-functions.md
Fixes https://github.com/pingcap/docs/issues/7455
=> Add notes on datetime

TOC.md, develop/developer-guide-overview.md
=> Add developer-guide-overview.md

.github/pull_request_template.md, README.md
Add v6.1 in pr template
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8984
=> chore: add v6.1 in pr template

tikv-configuration-file.md
Add warnings about `enable-ttl` in "tikv-configuration-file.md".
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8043, https://github.com/pingcap/docs-cn/pull/8856
=> TiKV config: add warnings about `enable-ttl`

upgrade-tidb-using-tiup.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8961
=> Add a warning about upgrading tiflash using tiup

ticdc/ticdc-overview.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8950
=> Update ticdc overview

tidb-limitations.md
Corrected the default value of columns, from 1071 to 1017
- Other reference link(s):https://github.com/pingcap/docs/issues/8251, https://github.com/pingcap/docs-cn/pull/5542
=> Corrected the default value of columns

dm/feature-expression-filter.md, keywords.md, migrate-aurora-to-tidb.md
Fix aliases typo from 'tidb/dev' to '/tidb/dev'.
=> Fix aliases typo

faq/manage-cluster-faq.md
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/8997
=> add how to estimate the size of a table

br/use-br-command-line-tool.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8970
=> Modify the filename that appears in the br command

tikv-configuration-file.md
Fix the value for `compression-per-level`
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7843
=> TiKV Config: Fix the value for `compression-per-level`

placement-rules-in-sql.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9078
=> Fix example errors in placement-rules-in-sql.md

TOC.md, br/backup-and-restore-tool.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8958
=> Add backup-and-restore-using-dumpling-lightning.md to TOC

quick-start-with-tidb.md
- Change the description of Shell profile
- Add parameter -i to specify the key file used to connect to the target machine
- Modify Mac to macOS
- Fix format
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9015
https://github.com/pingcap/docs-cn/pull/9019
=> Change the description of shell profile and add parameter -i in quick-start-with-tidb.md

tispark-overview.md
- Delete the description of installing and deploying Spark.
- Fix format to align with docs-cn version
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/8985
=> Delete the description of installing and deploying Spark

pd-recover.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8526
=> Update two parts in "pd-recover.md"

alert-rules.md
Fix the rule of TiKV_GC_can_not_work
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/9122
=> Fix the rule of TiKV_GC_can_not_work

.github/workflows/rebase.yml
- Update cirrus-actions from v1.4 to [v1.6](https://github.com/cirrus-actions/rebase/releases/tag/1.6) to fix the unsafe repository problem when `/rebase`.
- Since the rebase is running on a Docker container, add `git config --global --add safe.directory /github/workspace` in `rebase.yml` is fail.
- Other …
=> Actions: Fix "fatal: unsafe repository" in rebase.yml

tikv-configuration-file.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9114
=> v5.2.4: TiKV configuration changes

exporting-grafana-snapshots.md
Add a warning in "exporting-grafana-snapshots.md"
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8927, https://github.com/pingcap/docs-cn/pull/9006
=> Add a warning in exporting-grafana-snapshots.md

benchmark/v5.4-performance-benchmarking-with-tpch.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9141
=> Add hardware configurations and aliases to 5.4 tpch

tiup/tiup-reference.md
Modify `help` command to `--help` command.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9197
=> Fix typo in tiup-reference.md

br/backup-and-restore-storages.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8739
=> add aliyun oss example

table-attributes.md
Add a notice for table attributes on 6.0.0
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9016
=> Add a notice for table attributes on 6.0.0

table-attributes.md
Add a notice for table attributes on 5.4.0
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9017
=> Add a notice for table attributes on 5.4.0

table-attributes.md
Add a notice for table attributes on 5.3
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9018
=> Add a notice for table attributes on 5.3.0

encryption-at-rest.md
=> fix an anchor link

faq/manage-cluster-faq.md
Update an FAQ according to discussion
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9230
=> Update an FAQ according to discussion

tidb-configuration-file.md
add config description for opentracing
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7345
=> add config description for opentracing

mysql-compatibility.md
- Other reference link(s): https://github.com/pingcap/docs/issues/7226
=> Document four unsupported mysql syntax and statements

develop/connect-to-tidb.md
- This PR is translated from: [connect-to-tidb.md](https://github.com/pingcap/docs-cn/blob/develop/develop/connect-to-tidb.md)
=> [Translate] connect-to-tidb

develop/connection-parameters.md
- This PR is translated from: [connection-parameters.md](https://github.com/pingcap/docs-cn/blob/develop/develop/connection-parameters.md)
=> [Translate] connection-parameters

develop/create-database.md
- This PR is translated from: [create-database.md](https://github.com/pingcap/docs-cn/blob/develop/develop/create-database.md)
=> [Translate] create-database

develop/developer-guide-overview.md
- This PR is translated from: [developer-guide-overview.md](https://github.com/pingcap/docs-cn/blob/develop/develop/developer-guide-overview.md)
=> [Translate] feat-developer-guide-overview

develop/build-cluster-in-cloud.md, develop/developer-guide-overview.md, develop/sample-application-java.md
- This PR is translated from: [sample-application-java.md](https://github.com/pingcap/docs-cn/blob/develop/develop/sample-application-java.md)
=> [Translate] sample-application-java

develop/schema-design-overview.md
- This PR is translated from: [schema-design-overview.md](https://github.com/pingcap/docs-cn/blob/develop/develop/schema-design-overview.md)
=> [Translate] schema-design-overview

develop/tidb-crud-sql.md
- This PR is translated from: [tidb-crud-sql.md](https://github.com/pingcap/docs-cn/blob/develop/develop/tidb-crud-sql.md)
=> [Translate] tidb-crud-sql

troubleshoot-hot-spot-issues.md
Add two hotspot scenarios in "troubleshoot-hot-spot-issues.md".
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9025
=> Troubleshoot hotspot issues: add hotspot scenarios

tikv-configuration-file.md
Added override information about some configuration items.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9115
=> TiKV Config: add override information about some configuration items

two-data-centers-in-one-city-deployment.md
Refine the format of JSON and add methods to change PD configuration in Placement Rules
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9099
=> Refine the format of JSON and add methods to change PD configuration

CONTRIBUTING.md, README.md, dm/dm-overview.md, ticdc/troubleshoot-ticdc.md
=> Updata the contact info from slack to internals

develop/create-secondary-indexes.md
- This PR is translated from: [create-secondary-indexes.md](https://github.com/pingcap/docs-cn/blob/develop/develop/create-secondary-indexes.md)
=> [Translate] create-secondary-indexes

develop/insert-data.md
- This PR is translated from: [insert-data.md](https://github.com/pingcap/docs-cn/blob/develop/develop/insert-data.md)
=> [Translate] insert-data

develop/sample-application-java.md, develop/sample-application-spring-boot.md
=> [Debug] remove chinese

tispark-overview.md
add aliases for a tispark file deleted in https://github.com/pingcap/docs/pull/6459
=> add aliases for a deleted tispark file

dm/dm-precheck.md, dm/task-configuration-file-full.md
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/8790
=> add description of ignore-checking-items

develop/prepared-statement.md
=> [Translate] prepared-statement

develop/delete-data.md
=> [Translate] delete-data

develop/update-data.md
=> [Translate] update-data

develop/transaction-restraints.md
=> [Translate] transaction-restraints

develop/object-naming-guidelines.md
=> [Translate] object-naming-guidelines

ticdc/manage-ticdc.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9301
=> ticdc: fix sinkURI typo

develop/implicit-type-conversion.md
=> [Translate] implicit-type-conversion

develop/timeouts-in-tidb.md
=> [Translate] timeouts-in-tidb

develop/unstable-result-set.md
=> [Translate] unstable-result-set

develop/object-naming-guidelines.md, develop/sql-development-specification.md
=> Trans sql development specification

develop/optimistic-and-pessimistic-transaction.md
- This PR is translated from: https://github.com/pingcap/docs-cn/blob/develop/develop/optimistic-and-pessimistic-transaction.md
=> [Translate] optimistic-and-pessimistic-transaction

develop/transaction-overview.md
- This PR is translated from: https://github.com/pingcap/docs-cn/blob/develop/develop/transaction-overview.md
=> [Translate] transaction overview

benchmark/v5.4-performance-benchmarking-with-tpch.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9339
=> tpch: Correct aliases

benchmark/v5.4-performance-benchmarking-with-tpch.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9337
=> Add back 5.4 tpch report

develop/use-temporary-tables.md
dev: update temporary table dev doc
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9338
=> dev: update temporary table dev doc

whats-new-in-tidb-4.0.md
add missing alias to fix broken link
=> add missing alias to fix broken link

config-templates/complex-tiflash.yaml
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9351
=> tiflash: update some topoloy

develop/sample-application-java.md
=> [Update] hide real url

download-ecosystem-tools.md, pd-control.md, pd-recover.md, production-deployment-using-tiup.md, quick-start-with-tidb.md, scale-tidb-using-tiup.md, sync-diff-inspector/sync-diff-inspector-overview.md, ticdc/manage-ticdc.md, tiup/tiup-cluster.md, tiup/tiup-component-cluster-deploy.md, tiup/tiup-component-management.md, tiup/tiup-mirror.md, tiup/tiup-playground.md, upgrade-tidb-using-tiup.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9181
=> v5.2.4: Bump version for v5.2 docs 

migrate-from-tidb-to-tidb.md, replicate-betwwen-primary-and-secondary-clusters.md, replicate-data-to-kafka.md
=> fix typo and unify the description

dm/dm-hardware-and-software-requirements.md, faq/deploy-and-maintain-faq.md, hardware-and-software-requirements.md
Remove `platform` from `Linux OS Platform`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9346
=> Remove `platform` from `Linux OS Platform`

develop/paginate-results.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9359
=> develop: use users table as the NONCLUSTERED paginate example

develop/use-common-table-expression.md, develop/use-temporary-tables.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9314
=> develop: refine read data codes

develop/transaction-troubleshoot.md, develop/troubleshoot-overview.md
Signed-off-by: crazycs520 <crazycs520@gmail.com>
- This PR is translated from: https://github.com/pingcap-inc/tidb-developer-guide/pull/26
=> [Translate]: troubleshoot

develop/implicit-type-conversion.md, develop/transaction-restraints.md
=> [Delete] rest chinese

TOC.md
Move Glossary after Release Notes.
=> Move Glossary after Release Notes

best-practices/haproxy-best-practices.md
Update HAProxy deploy operating system introduction.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8956
=> Update HAProxy deploy operating system introduction

ticdc/manage-ticdc.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9300
=> ticdc: remove unsupported kafka auth type

enable-tls-between-clients-and-servers.md
- Other reference link(s): https://github.com/pingcap/docs/pull/7899
=> tidb-configuration-file: fix typo

tidb-lightning/tidb-lightning-configuration.md
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/8977
=> lightning: update config description of web interface and server mode

.github/pull_request_template.md
Update PR template.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/9239
=> remove legacy versions from pr template

tikv-configuration-file.md
=> tikv: fix a format in tikv config

tiup/tiup-cluster-topology-reference.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8836
=> tiup: update how to config initial-commit-ts on tiup v1.9.2

tiflash/tiflash-overview.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9427
=> Update tiflash architecture image

releases/release-5.3.0.md
=> Follow-up for #7077

pd-control.md
Signed-off-by: IcePigZDB <icepigzdb@gmail.com>
Support endKey in http interface `regions/key` and adjust the pdctl region command `region startKey` to `region keys`accordingly. This is originally proposed as a precondition of the push down optimisation of `infomation_schema.tikv_region_status`. …
=> tools: update the usage of region startkey to region keys

statement-summary-tables.md
Some system variables are changed to global after 5.4.
Note: some changes from the Chinese PR are covered in https://github.com/pingcap/docs/pull/7737
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8186
=> update statement summary variables scope

clinic/clinic-user-guide-for-tiup.md
Add log redaction info into `clinic/clinic-user-guide-for-tiup.md`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9070
=> Add log redaction info into clinic doc

basic-features.md
Fix typo by replacing `Exection` with `Execution`
=> Fix typo by replacing `Exection` with `Execution`

ticdc/manage-ticdc.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9472
=> Add missing protocol argument and experimental warning for Pulsar URI

download-ecosystem-tools.md, pd-control.md, pd-recover.md, production-deployment-using-tiup.md, quick-start-with-tidb.md, scale-tidb-using-tiup.md, sync-diff-inspector/sync-diff-inspector-overview.md, ticdc/manage-ticdc.md, tiup/tiup-cluster.md, tiup/tiup-component-cluster-deploy.md, tiup/tiup-component-management.md, tiup/tiup-mirror.md, tiup/tiup-playground.md, upgrade-tidb-using-tiup.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9446
=> v5.4.1: Bump version for v5.4 docs

system-variables.md
This pull request adds `GROUP BY <expr> ASC|DESC` syntax as controlled by tidb_enable_noop_functions 
Follow up https://github.com/pingcap/tidb/pull/21120
```sql
mysql> SELECT tidb_version()\G
tidb_version(): Release Version: v6.0.0
Edition: Community
Git Commit Hash: 36a9810441ca0e496cbd22064af274b3be771081
Git Branch: heads/refs/tags/v6.0.0
UTC Build Time: 2022-03-31 10:27:25
GoVersion: go1.18
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```
```sql
mysql> desc t1;
+-------+---------+------+------+---------+-------+
| Field | Type    | Null | Key  | Default | Extra |
+-------+---------+------+------+---------+-------+
| id    | …
```
=> Add `GROUP BY <expr> ASC|DESC` syntax as controlled by tidb_enable_noop_functions

statement-summary-tables.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9480
=> statement-summary-tables: fix a broken link 

mysql-compatibility.md
Refine table partition description from https://github.com/pingcap/docs/pull/7163
=> Refine table partition description

TOC.md, releases/versioning.md
Add the doc for TiDB versioning system. 
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/9238 https://github.com/pingcap/docs-cn/pull/9361
=> add tidb versioning doc

tikv-configuration-file.md
=> tikv: fix some error for tikv config

.github/workflows/dispatch.yml
Pause website build for master branch.
=> ci: pause master build

dynamic-config.md, tikv-configuration-file.md, tikv-control.md
Add warnings for consistency check
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9526
=> Add warnings for consistency check

tiflash/tiflash-configuration.md
- changed `format_version`  default value to 4
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9507
=> Changed format_version default value to 4

.github/workflows/bot.yaml, scripts/pr_reminder_basedon_assignee.py
=> chore: enable v6.1 pr bot

develop/dev-guide-implicit-type-conversion.md, develop/dev-guide-optimize-sql-best-practices.md, develop/dev-guide-optimize-sql-overview.md, develop/dev-guide-optimize-sql.md
=> develop: 4 docs for optimizing sql

dm/shard-merge-best-practices.md
The section [上游 RDS 封装分库分表的处理](https://docs.pingcap.com/zh/tidb/stable/shard-merge-best-practices#%E4%B8%8A%E6%B8%B8-rds-%E5%B0%81%E8%A3%85%E5%88%86%E5%BA%93%E5%88%86%E8%A1%A8%E7%9A%84%E5%A4%84%E7%90%86) is missing in the English version.
- Other reference link(s): https://github.com/pingcap/docs-dm/pull/900
=> dm: add a missing section

dm/dm-source-configuration-file.md, dm/relay-log.md, dm/task-configuration-file-full.md
deprecate useless configs.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9370
=> dm: deprecate useless config

develop/dev-guide-timeouts-in-tidb.md, develop/dev-guide-troubleshoot-overview.md, develop/dev-guide-unstable-result-set.md
Polish dev troubleshooting docs
=> Review dev troubleshooting docs

migrate-from-csv-files-to-tidb.md, migrate-large-mysql-to-tidb.md
=> TiDB Lightning: Fix a typo

exporting-grafana-snapshots.md
Add a warning for MetricsTool 
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9509
=> Add a warning for MetricsTool 

tiflash/use-tiflash.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9577
=> TiFlash: Fix incorrect values of isolation_read_engines

develop/dev-guide-create-table.md, develop/dev-guide-index-best-practice.md, develop/dev-guide-object-naming-guidelines.md
develop guide: review reference
=> Dev guide: review reference

develop/dev-guide-create-database.md, develop/dev-guide-create-secondary-indexes.md, develop/dev-guide-schema-design-overview.md
=> Dev guide: database schema design

develop/dev-guide-choose-driver-or-orm.md, develop/dev-guide-connect-to-tidb.md, develop/dev-guide-connection-parameters.md
=> develop-guide: Connect to TiDB

develop/dev-guide-build-cluster-in-cloud.md, develop/dev-guide-sample-application-java.md, develop/dev-guide-tidb-crud-sql.md
=> Dev guide: review quick start

develop/dev-guide-get-data-from-single-table.md, develop/dev-guide-hybrid-oltp-and-olap-queries.md, develop/dev-guide-paginate-results.md, develop/dev-guide-use-common-table-expression.md, develop/dev-guide-use-follower-read.md, develop/dev-guide-use-stale-read.md, develop/dev-guide-use-subqueries.md, develop/dev-guide-use-temporary-tables.md, develop/dev-guide-use-views.md
=> Dev guide: review read data

tiflash/use-tiflash.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9543
=> tiflash: update function list supported by TiFlash

tikv-configuration-file.md
=> add doc for raft engine memory limit

TOC.md, develop/dev-guide-overview.md, develop/dev-guide-troubleshoot-overview.md
=> [Debug] typo

basic-features.md, experimental-features.md, partitioned-table.md, placement-rules-in-sql.md, system-variables.md
List partitioning is now considered GA and the EXPERIMENTAL warnings should be removed from the documentation.
=> Make list partitioning GA (remove Experimental)

TOC.md
=> [Update] update TOC

system-variables.md, tidb-configuration-file.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9585
=> add parameters for tidb_stats_cache_mem_quota

TOC.md
=> [Update] add dev-guide-index-best-practice.md

character-set-gbk.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9503
=> ticdc: Add support for GBK charset in TiCDC

tiflash/use-tiflash.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9541
=> tiflash: add docs about window function push down to tiflash

tidb-cloud/backup-and-restore.md, tidb-cloud/delete-tidb-cluster.md
=> cloud: add info about backup files for cluster deletion 

tidb-cloud/tidb-cloud-auditing.md
=> auditing: enhance the example of audit log filename

.github/workflows/ci.yaml, .gitignore, package-lock.json, package.json, scripts/filterCloudDoc.js, scripts/generate_cloud_pdf.sh, scripts/merge_by_toc.py, scripts/verify-duplicated-file-name.sh
=> Add cloud scripts

system-variables.md
This adds Type information to system variables. Float typed values also did not previously show their range. They now do.
The meta data is generated from the tidb source code against master.
=> system-variables: Add type information, range info for float

ticdc/ticdc-canal-json.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9647
=> remove obsolete condition for `enable-tidb-extension`

TOC-cloud.md, basic-sql-operations.md
=> chore: test doc filtering

tidb-cloud/create-tidb-cluster.md, tidb-cloud/manage-user-access.md, tidb-cloud/monitor-built-in-alerting.md, tidb-cloud/monitor-datadog-integration.md, tidb-cloud/monitor-prometheus-and-grafana-integration.md, tidb-cloud/monitor-tidb-cluster.md, tidb-cloud/set-up-vpc-peering-connections.md
=> cloud: update docs for project setting changes 

dynamic-config.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9513
=> tikv: add some new online configs

ticdc/manage-ticdc.md
Add description for Kafka multi-topic feature
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/9471
=> Add description for Kafka multi-topic feature

join-reorder.md, system-variables.md
system variable: add the switch control for outer join reorder
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9558
=> system variable: add the switch control for outer join reorder

ticdc/manage-ticdc.md
Add Kafka authentication and authorization description about sasl-gssapi.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/9633
=> Add Kafka authentication and authorization description in TiCDC

dm/feature-shard-merge-optimistic.md
as title
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/9317
=> dm: update doc for optimistic shard ddl

alert-rules.md
Change rockdb.defaultcf to rocksdb.defaultcf
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/9662
=> fix a typo: change rockdb.defaultcf to rocksdb.defaultcf 

system-variables.md
=> Modify the default value of `tidb_enable_list_partition` to `ON` in v6.1.0

tiflash/use-tiflash.md
translated from https://github.com/pingcap/docs-cn/pull/9686
=> tiflash: correct window desc name.

online-unsafe-recovery.md, pd-control.md, tikv-control.md
Update online unsafe recovery doc
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9634 https://github.com/pingcap/docs-cn/pull/9495 https://github.com/pingcap/docs-cn/pull/9685
=> Update online unsafe recovery doc

tikv-configuration-file.md, tikv-control.md
tikv: add a new config item `background-error-recovery-window`
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9448 https://github.com/pingcap/docs-cn/pull/8702
=> tikv: add a new config item `background-error-recovery-window`

TOC-tidb-cloud.md
=> cloud: make FAQs as an independent chapter

tidb-cloud/manage-user-access.md, tidb-cloud/tidb-cloud-billing.md
=> cloud: Add password policy

tidb-cloud/release-notes-2022.md, tidb-cloud/tidb-cloud-poc.md, tidb-cloud/tidb-cloud-quickstart.md
=> cloud: update PoC entries 

.github/workflows/dispatch.yml
=> disable dispatch 6.1 for now

tidb-configuration-file.md
add back a missing default value
- Other reference link(s):  https://github.com/pingcap/docs/pull/7868
=> add back a missing default value

statistics.md, system-variables.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9562 https://github.com/pingcap/docs-cn/pull/9690
=> docs: analyze memory quota

tidb-cloud/release-notes-2021.md, tidb-cloud/select-cluster-tier.md
=> cloud: Update storage size for dev tier

system-variables.md, tidb-configuration-file.md
v6.1: add experimental warning
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9712
=> v6.1: add experimental warning

_index.md
as title.
- Other reference link(s):https://github.com/pingcap/docs/pull/8736
=> fix 404 caused by deleting adopters.md

TOC-tidb-cloud.md, basic-sql-operations.md
=> cloud: Update basic-sql-operations.md

tikv-configuration-file.md, tune-region-performance.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9744
=> Add experimental warning for customized region size

production-deployment-using-tiup.md, quick-start-with-tidb.md, scale-tidb-using-tiup.md, tiup/tiup-cluster.md, tiup/tiup-component-cluster-deploy.md, tiup/tiup-component-management.md, tiup/tiup-mirror.md, tiup/tiup-playground.md, upgrade-tidb-using-tiup.md
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/9735
=> tiup: bump version to v6.1

clinic/clinic-user-guide-for-tiup.md
This PR replaces the data downloading link with a description because this link cannot be accessed by most users and might cause 404.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9482
=> clinic: update the data downloading link with description

develop/dev-guide-bookshop-schema-design.md, develop/dev-guide-create-table.md, develop/dev-guide-delete-data.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9766
=> [Debug] outdated code and table name

tune-tikv-memory-performance.md
add description of how to modify TiKV configuration.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9606
=> add description of how to modify TiKV configuration

glossary.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9672
=> add glossary for v6.1

system-variables.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9790
=> 6.1: modify the value of a non-txn dml variable

releases/release-6.1.0.md, releases/release-timeline.md
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/9776
=> fix release notes and update release date

ticdc/manage-ticdc.md, ticdc/ticdc-avro-protocol.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9787
=> ticdc: make kafka topic rule clear for avro codec

develop/dev-guide-build-cluster-in-cloud.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9796
=> dev-guide: update Cloud signup URL

tidb-cloud/manage-user-access.md, tidb-cloud/release-notes-2022.md
=> cloud: update password reset policy

basic-features.md, experimental-features.md
Update basic features and experimental features for v6.1.0. The changes are listed as follows:
- List 分区: experimental -> GA
- List COLUMNS 分区: experimental -> GA
- dynamic pruning: experimental -> GA
- Global Kill: experimental -> GA
- SET CONFIG（dynamic config）: experimental -> GA
- Raft Engine： experimental -> GA
- Online unsafe recovery： experimental -> GA
- Buckets are used as the unit of concurrent query: experimental
- TiKV API v2: experimental
- Control the memory quota for collecting statistics: experimental
- ALTER TABLE ... COMPACT: experimental
- User level lock: GA
- Batch: GA
- Statistics for dynamic pruning: Experimental -> GA
By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor …
=> Update experimental features for v6.1

tidb-in-kubernetes.md
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/9800
=> trigger pdf

.github/workflows/dispatch.yml
=> trigger dispatch

partitioned-table.md
=> Remove experimental of List COLUMNS partitioning

tidb-cloud/tidb-cloud-auditing.md
=> cloud: add auditing fields

grafana-performance-overview-dashboard.md
=> performance: add link to tuning methods

explore-htap.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9819
=> tispark: remove description of not supporting Spark 3.x

dashboard/dashboard-faq.md
Signed-off-by: Wish <breezewish@outlook.com>
Add a help for ngm not started error when deployed using TiUP Playground.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9795
=> TiDB Dashboard: Add help for ngm using TiUP Playground

migrate-aurora-to-tidb.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9813
=> DM: fix 404 caused by removing a dm doc without aliases to stable

tidb-cloud/connect-to-tidb-cluster.md, tidb-cloud/manage-user-access.md, tidb-cloud/monitor-built-in-alerting.md, tidb-cloud/monitor-datadog-integration.md, tidb-cloud/monitor-prometheus-and-grafana-integration.md, tidb-cloud/monitor-tidb-cluster.md, tidb-cloud/release-notes-2022.md, tidb-cloud/set-up-vpc-peering-connections.md, tidb-cloud/tidb-cloud-poc.md
=> cloud: modifying project settings

backup-and-restore-using-dumpling-lightning.md
This PR is to fix 404 caused by removing backup-and-restore-using-dumpling-lightning from branches 5.0, 5.1, 5.2, 5.3, 5.4, stable, and dev without adding aliases properly: https://github.com/pingcap/docs/pull/8308
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9812
=> br: fix 404 caused by removing a doc without adding aliases

releases/release-6.1.0.md
Use 'Rails' not 'RoR' to talk about Ruby on Rails. Usually when I call "Ruby on Rails" for short,  "Rails" is an appropriate term. 
=> Use 'Rails' not 'RoR' to talk about Ruby on Rails

.github/workflows/link.yaml, .lycheeignore
- Remove `--exclude github.com` because `https://github.com/.*/pull/.*` and `https://github.com/.*/issues/.*` are added in `.lycheeignore`.
- Close https://github.com/pingcap/docs-tidb-operator/issues/1864
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/9768
=> ci: remove exclude github.com and add excluded links

partitioned-table.md
=> Fix format in partitioned-table.md

TOC.md, clinic/quick-start-with-clinic.md
- Add clinic/quick-start-with-clinic.md
- Add log redaction
- Update the data download link with description
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8733 https://github.com/pingcap/docs-cn/pull/9482 https://github.com/pingcap/docs-cn/pull/9070 …
=> Clinic: add quick-start-with-clinic 

develop/dev-guide-outdated-for-django.md, develop/dev-guide-outdated-for-go-sql-driver-mysql.md, develop/dev-guide-outdated-for-gorm.md, develop/dev-guide-outdated-for-hibernate-orm.md, develop/dev-guide-outdated-for-laravel.md, develop/dev-guide-outdated-for-python-mysql-connector.md, develop/dev-guide-outdated-for-sqlalchemy.md, develop/dev-guide-overview.md
these aliases are added in https://github.com/pingcap/docs/pull/8977
=> Remove aliases from master 

develop/dev-guide-outdated-for-django.md, develop/dev-guide-outdated-for-go-sql-driver-mysql.md, develop/dev-guide-outdated-for-gorm.md, develop/dev-guide-outdated-for-hibernate-orm.md, develop/dev-guide-outdated-for-laravel.md, develop/dev-guide-outdated-for-python-mysql-connector.md, develop/dev-guide-outdated-for-sqlalchemy.md, develop/dev-guide-overview.md
=> add aliases for v6.1

.github/pull_request_template.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9853
=> chore: add 6.2 to and remove 6.0 and 4.0 from pr template

.github/workflows/bot.yaml
=> chore: disable 6.1 bot

TOC.md
Fix a TOC display issue
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9882
=> Fix a TOC display issue

sync-diff-inspector/upstream-downstream-diff.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9642
=> sync-diff/ update sync-diff upstream-downstream-diff.md document

tiup/tiup-component-cluster-check.md, upgrade-tidb-using-tiup.md
…sing tiup
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9851
=> tiup: describe how to merge two offline mirrors when upgrading tidb using tiup

transaction-overview.md
update the maximum size of transaction.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/9369
=> update the maximum size of transaction

migrate-from-tidb-to-tidb.md
=> ticdc: add aliases for incremental replication in 6.1

tiup/tiup-bench.md
=> tiup bench: Add clean up instruction for tpcc

tidb-cloud/tidb-cloud-billing-tcu.md
=> tidbcloud: update TCU billing for gcp/asia-east1

tidb-cloud/import-csv-files.md, tidb-cloud/import-parquet-files.md, tidb-cloud/import-sample-data.md, tidb-cloud/migrate-from-aurora-bulk-import.md, tidb-cloud/tidb-cloud-quickstart.md
=> cloud: remove the bucket region field from the import interface

TOC-tidb-cloud.md, tidb-cloud/backup-and-restore.md, tidb-cloud/connect-to-tidb-cluster.md, tidb-cloud/create-tidb-cluster.md, tidb-cloud/manage-user-access.md, tidb-cloud/release-notes-2022.md, tidb-cloud/tidb-cloud-billing.md, tidb-cloud/tidb-cloud-quickstart.md, tune-tikv-memory-performance.md
=> cloud: manage user profiles

tidb-cloud/connect-to-tidb-cluster.md
=> cloud: Update current ip

TOC-tidb-cloud.md, tidb-cloud/_index.md
=> cloud: update TOC-tidb-cloud for data migration and backup/restore scenarios 

releases/release-6.1.0.md, sql-statements/sql-statement-show-variables.md, system-variables.md
6.1: delete tidb_enable_batch_dml
- This PR is translated from:  https://github.com/pingcap/docs-cn/pull/9829
=> 6.1: delete tidb_enable_batch_dml

releases/release-6.1.0.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9983
=> Fix a wrong issue numer in 6.1 rn

releases/release-5.4.0.md, tiflash/tiflash-configuration.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9979
=> release and tiflash: remove description about downgrade

data-type-string.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8574
=> fix length limitations of longtext and longblob

tidb-cloud/tidb-cloud-faq.md
=> cloud: update the faq for migration path

faq/migration-tidb-faq.md
We now have `LOAD DATA ... REPLACE INTO ...` support.
- https://github.com/pingcap/docs/pull/7976
- https://github.com/pingcap/docs/pull/7426
- https://github.com/pingcap/tidb/pull/31303
=> migration-tidb-faq: update now there is support for `load data ... replace into`

tidb-configuration-file.md
Correct the default value of enable-timestamp
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9614
=> Correct the default value of enable-timestamp

.lycheeignore
Close https://github.com/pingcap/docs-tidb-operator/issues/1879, https://github.com/pingcap/docs-tidb-operator/issues/1899
=> ci: update exclude link pattern in .lycheeignore

.github/workflows/ci.yaml, scripts/filterCloudDoc.js, scripts/filterNonCloudDoc.js, scripts/utils.js
rm custom content under different type
refine ci
=> Refine ci of internal link checks

tikv-configuration-file.md
Add a note to some tikv configs
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8293
=> Add a note to some tikv configs

troubleshoot-lock-conflicts.md
sync base backoff time for troubleshoot-lock-conflicts.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9332
=> sync base backoff time for troubleshoot-lock-conflicts.md

data-type-numeric.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7837
=> Update data-type-numeric.md 

alert-rules.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9457
=> Update an outdated TiKV alert in v5.3

releases/release-6.0.0-dmr.md, sql-statements/sql-statement-show-collation.md
Fix a typo in 6.0 release notes
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9326
=> Fix a typo in 6.0 release notes

character-set-and-collation.md
fix description about no collation framework
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9069
=> fix description about no collation framework

tikv-configuration-file.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10080
=> tikv-configuration-file: add unit for raftstore.capacity

tidb-cloud/release-notes-2022.md
=> cloud: update release-notes-2022

best-practices/haproxy-best-practices.md, character-set-and-collation.md, system-variables.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9847 https://github.com/pingcap/docs-cn/pull/9968
=> add warning for system variable tidb_skip_utf8_check

develop/dev-guide-build-cluster-in-cloud.md, develop/dev-guide-sample-application-java.md, develop/dev-guide-sample-application-spring-boot.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10096
=> [Debug] hide real url

releases/release-timeline.md
=> fix release timeline

download-ecosystem-tools.md, pd-control.md, pd-recover.md, production-deployment-using-tiup.md, quick-start-with-tidb.md, scale-tidb-using-tiup.md, ticdc/manage-ticdc.md, tidb-lightning/tidb-lightning-configuration.md, tiup/tiup-component-management.md, tiup/tiup-mirror.md, tiup/tiup-playground.md
bump versions to v5.3.2
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/10287
=> bump versions to v5.3.2

sql-statements/sql-statement-add-index.md, sql-statements/sql-statement-alter-index.md, sql-statements/sql-statement-change-column.md, sql-statements/sql-statement-drop-column.md, sql-statements/sql-statement-drop-index.md, sql-statements/sql-statement-modify-column.md, sql-statements/sql-statement-rename-index.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9639
=> sql-statement: refine the sqlgram for alter table

pd-configuration-file.md
Modify the default value of `max-days` and `max-backups` to `0` from v4.0 to v5.2.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9557
=> Fix the default value of the log config of PD

br/rawkv-backup-and-restore.md
Close https://github.com/pingcap/docs/issues/9427
=> fix docs-merge-pipeline error

tidb-cloud/import-sample-data.md, tidb-cloud/tidb-cloud-glossary.md
=> cloud: replace vague words with clear descriptions

br/backup-and-restore-overview.md, br/backup-storage-azblob.md
=> br: fix aliases

tikv-configuration-file.md
Add `report-region-buckets-tick-interval` in tikv-configuration-file.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9899
=> Add description about report-region-buckets-tick-interval

statistics.md
=> statistics: fix typo

tidb-cloud/size-your-cluster.md
=> cloud: Determine cluster size

releases/release-3.0.0-beta.1.md
Close https://github.com/pingcap/docs/issues/9455
=> fix broken link in release-3.0.0-beta.1

br/backup-and-restore-overview.md, br/backup-storage-azblob.md
Fix https://github.com/pingcap/docs-tidb-operator/issues/1925
- Other reference link(s): https://github.com/pingcap/docs/pull/8628
=> Add stable aliases in two new BR docs

configure-placement-rules.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10315
=> Fix typos in placement rules command

dashboard/continuous-profiling.md
Signed-off-by: mornyx <mornyx.z@gmail.com>
=> dashboard: update status of continuous profiling

configure-placement-rules.md, placement-rules-in-sql.md
Change the placement policy example where HDD and SSD is used to use SSD and NVMe as running TiKV is not a recommended setup.
=> We should never recommend slow storage for TiKV

tiflash/tiflash-command-line-flags.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10361
=> tiflash: update command-line-flags.md

dashboard/dashboard-diagnostics-report.md, system-variables.md
[System Variables](https://docs.pingcap.com/tidb/dev/system-variables) and [TiDB Dashboard Diagnostic Report](https://docs.pingcap.com/tidb/dev/dashboard-diagnostics-report) are not build in 5.0.
=> v5.0: trigger website build

TOC.md
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/10065
=> move dm architecture in toc

br/br-deployment.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10392
=> fix typo in SHOW BACKUPS|RESTORES command 

table-filter.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10400
=> table filter: remove unfriendly special symbols

dumpling-overview.md
=> trigger pdf build

tidb-cloud/use-htap-cluster.md
=> cloud: update TiFlash replica number description 

tidb-cloud/tidb-cloud-auditing.md
Adjust the description of Audit logging for Database, modify the warning information, and delete  “It is not recommended that you use it for production environments.”
=> Adjust the description of Audit logging for Database

system-variables.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10442
=> system variable: remove unnecessary examples

tidb-cloud/import-csv-files.md, tidb-cloud/import-parquet-files.md, tidb-cloud/import-sample-data.md, tidb-cloud/migrate-from-aurora-bulk-import.md, tidb-cloud/tidb-cloud-quickstart.md
=> cloud: add validation before data import

tidb-cloud/release-notes-2022.md, tidb-cloud/size-your-cluster.md, tidb-cloud/tidb-cloud-billing.md
=> cloud: add billing profile

tidb-cloud/tidb-cloud-faq.md
=> cloud: add TiFlash FAQ

quick-start-with-tidb.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10494
=> tiup: fix incorrect relationship between x86_64 and arm

TOC-tidb-cloud.md
=> cloud: update TOC for troubleshooting data access errors

develop/dev-guide-optimize-sql-best-practices.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10490
=> [Update] add CREATE INDEX statement in add index optmize doc

br/backup-and-restore-overview.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10537
=> br: remove an unclear usage tip about checksum

tidb-lightning/monitor-tidb-lightning.md
Close https://github.com/pingcap/docs/issues/9585
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10528
=> tidb lightning: fix old download location for lightning.json

dynamic-config.md, pd-configuration-file.md, pd-control.md
=> add unit of schedule.max-merge-region-size

tidb-cloud/tidb-cloud-auditing.md, tidb-cloud/tidb-cloud-quickstart.md
=> cloud: fix simpletab issues

experimental-features.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10559
=> Remove GA features from experimental doc

tidb-cloud/import-csv-files.md, tidb-cloud/import-parquet-files.md, tidb-cloud/import-sample-data.md, tidb-cloud/migrate-from-amazon-s3-or-gcs.md, tidb-cloud/migrate-from-aurora-bulk-import.md, tidb-cloud/tidb-cloud-quickstart.md, tidb-cloud/troubleshoot-import-access-denied-error.md
=> cloud:  update validation steps

sync-diff-inspector/sync-diff-inspector-overview.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10586
=> sync-diff-inspector: fix typos

develop/dev-guide-sql-development-specification.md
Close https://github.com/pingcap/docs-cn/issues/10595
=> [Debug] specification typo

TOC.md
=> [Update] add golang example to TOC

TOC.md, replicate-between-primary-and-secondary-clusters.md
=> betwwen → between

.github/workflows/dispatch.yml
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10614
=> disable trigger website building from master

develop/dev-guide-bookshop-schema-design.md, develop/dev-guide-build-cluster-in-cloud.md, develop/dev-guide-delete-data.md, develop/dev-guide-get-data-from-single-table.md, develop/dev-guide-hybrid-oltp-and-olap-queries.md, develop/dev-guide-join-tables.md, develop/dev-guide-optimistic-and-pessimistic-transaction.md, develop/dev-guide-optimize-sql.md, develop/dev-guide-paginate-results.md, develop/dev-guide-prepared-statement.md, develop/dev-guide-sample-application-golang.md, develop/dev-guide-sample-application-java.md, develop/dev-guide-transaction-restraints.md, develop/dev-guide-update-data.md, develop/dev-guide-use-stale-read.md, develop/dev-guide-use-temporary-tables.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10556
=> develop: fix simpletab

tidb-cloud/backup-and-restore.md
=> Delete a running backup job

tidb-cloud/scale-tidb-cluster.md
=> cloud: refine the scaling a cluster doc

develop/dev-guide-delete-data.md
=> [Debug] bulk-delete description error

tidb-cloud/scale-tidb-cluster.md
=> cloud: add a note for storage size changes

TOC-tidb-cloud.md
fix an erorr in cloud toc
- Other reference link(s):https://github.com/pingcap/docs/pull/9679
=> cloud: fix an erorr in cloud toc

tiup/tiup-component-cluster-scale-in.md
Signed-off-by: Jack Yu <jackysp@gmail.com>
=> tiup: modify the scale-in --force warning

tispark-overview.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10646
=> add TiSpark 3.0

br/backup-and-restore-tool.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10639
=> br: synchronize the usage tips of the latest version to 5.4

TOC.md, tidb-lightning/tidb-lightning-physical-import-mode-usage.md, tidb-lightning/tidb-lightning-physical-import-mode.md
Translate part of the docs from the TiDB Lightning refactoring plan (https://github.com/pingcap/docs-cn/pull/9653), including two docs:
- `tidb-lightning/tidb-lightning-physical-import-mode-usage.md`
- `tidb-lightning/tidb-lightning-physical-import-mode.md`
Some paragraphs are taken from https://github.com/pingcap/docs/blob/master/tidb-lightning/tidb-lightning-backends.md
**Note: Some v6.2 features rely on these two docs, so we need to merge them ASAP.** …
=> tidb-lightning: add lightning physical import mode usage

tidb-cloud/set-up-vpc-peering-connections.md
=> cloud: Update set-up-vpc-peering-connections.md

tidb-cloud/tidb-cloud-auditing.md, tidb-cloud/tidb-cloud-console-auditing.md
Web Console Audit logging function introduction.
=> Console Audit logging feature introduction

TOC-tidb-cloud.md, tidb-cloud/release-notes-2022.md
=> cloud: remove api docs

tidb-cloud/release-notes-2022.md, tidb-cloud/select-cluster-tier.md
=> cloud: update hibernation condition

experimental-features.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10682
=> remote the avro support from experimental feature list

TOC-tidb-cloud.md
=> cloud: add  limitations-and-quotas.md to TOC

tidb-cloud/limitations-and-quotas.md
=> cloud: update limitations-and-quotas.md

develop/dev-guide-choose-driver-or-orm.md
=> [Debug] jdbc version 5.1.49

br/rawkv-backup-and-restore.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10686
=> br: deprecate rawkv backup and restore

tidb-cloud/connect-to-tidb-cluster.md, tidb-cloud/release-notes-2022.md, tidb-cloud/select-cluster-tier.md, tidb-cloud/tidb-cloud-quickstart.md
=> cloud: add username prefix

tiflash/tiflash-configuration.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10603
=> tiflash: Change format_version default value to 4

TOC-tidb-cloud.md, tidb-cloud/config-s3-and-gcs-access.md, tidb-cloud/import-csv-files.md, tidb-cloud/import-parquet-files.md, tidb-cloud/migrate-data-into-tidb.md, tidb-cloud/migrate-from-amazon-s3-or-gcs.md, tidb-cloud/migrate-from-aurora-bulk-import.md
Create a new article about S3 and GCS access configuration, and updated related links.
=> cloud: add aws s3 and gcs config

tikv-configuration-file.md
Signed-off-by: pingyu <yuping@pingcap.com>
Introduce CDC for API v2. Related Chinese PR https://github.com/pingcap/docs-cn/pull/10599.
Please note that the related link (https://github.com/tikv/migration/tree/main/cdc) is still under development, and will be finished soon.
=> tikv,v6.2: Introduce CDC for API v2

tidb-cloud/config-s3-and-gcs-access.md
=> cloud: fix titile spelling

tidb-cloud/configure-security-settings.md, tidb-cloud/release-notes-2022.md
=> cloud: add a release note for security setting updates

tiflash/tiflash-configuration.md
Added a new configuration dt_enable_read_thread
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/10524
=> tiflash: add a new configuration dt_enable_read_thread

releases/versioning.md
Add a description that links to the TiDB support policy at the PingCAP website
- Other reference link(s): #8486
=> releases: add a link to release support policy

tikv-configuration-file.md
https://github.com/tikv/tikv/pull/12798
=> deprecate gc-merge-rewrite

tidb-limitations.md
v6.2: add TiKV minimal version limit
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10568
=> v6.2: add TiKV minimal version limit

develop/dev-guide-build-cluster-in-cloud.md, tidb-cloud/backup-and-restore.md, tidb-cloud/config-s3-and-gcs-access.md, tidb-cloud/configure-security-settings.md, tidb-cloud/connect-to-tidb-cluster.md, tidb-cloud/create-tidb-cluster.md, tidb-cloud/delete-tidb-cluster.md, tidb-cloud/import-csv-files.md, tidb-cloud/import-parquet-files.md, tidb-cloud/import-sample-data.md, tidb-cloud/migrate-data-into-tidb.md, tidb-cloud/migrate-from-amazon-s3-or-gcs.md, tidb-cloud/migrate-from-aurora-bulk-import.md, tidb-cloud/scale-tidb-cluster.md, tidb-cloud/select-cluster-tier.md, tidb-cloud/set-up-vpc-peering-connections.md, tidb-cloud/tidb-cloud-quickstart.md
cloud: update for the cluster creation UI
=> cloud: update for the cluster creation UI

tidb-cloud/tidb-cloud-support.md
cloud: update support doc for support plans
=> cloud: update support doc for support plans

tidb-cloud/import-csv-files.md, tidb-cloud/import-parquet-files.md, tidb-cloud/import-sample-data.md, tidb-cloud/migrate-from-aurora-bulk-import.md, tidb-cloud/tidb-cloud-quickstart.md
=> cloud: update steps of importing CSV and Parquet files

TOC.md, develop/dev-guide-build-cluster-in-cloud.md, develop/dev-guide-create-database.md, develop/dev-guide-create-secondary-indexes.md, develop/dev-guide-create-table.md, develop/dev-guide-delete-data.md, develop/dev-guide-get-data-from-single-table.md, develop/dev-guide-insert-data.md, develop/dev-guide-optimistic-and-pessimistic-transaction.md, develop/dev-guide-optimize-sql-overview.md, develop/dev-guide-overview.md, develop/dev-guide-sql-development-specification.md, develop/dev-guide-tidb-crud-sql.md, develop/dev-guide-update-data.md
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/10714
=> develop: update DevTier to Developer Tier

sql-statements/sql-statement-alter-table-compact.md
Manual Compact GA. Delete description about experimental feature for ALTER TABLE ... COMPACT
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/10605
=> sql: manual compact GA

basic-features.md, experimental-features.md, placement-rules-in-sql.md, statistics.md
Some experimental information in the documentation is not correct. This PR corrects the information.
- Statistics V2 has been GA is v5.4.
- Cascading Placement Rules has been GA in v5.0.
- View has been GA in v3.0.
- SHOW CONFIG has been GA in v4.0.
=> correct experimental information in docs

TOC.md
Add docs home link in toc
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/10761
=> *: add docs home link in toc

tidb-cloud/_index.md
Add TiDB Cloud learning path for v6.1
=> cloud: add tidb cloud learning path for 6.1

tidb-cloud/_index.md
=> tidb: add tidb learnig path

tidb-cloud/_index.md
Corrected content in tidb cloud learning path
- Other reference link(s):https://github.com/pingcap/docs/pull/9828
=> Corrected content in tidb cloud learning path

dynamic-config.md
Support modifying the TiKV configuration item `log.level` online.
=> tikv: add a new dynamic config

TOC-tidb-cloud.md
=> cloud: update TOC for backup and restore

TOC.md, _index.md
Updated TiDB learning path, and added docs home in toc
=> tidb learning path: updated TiDB learning path, and added docs home in toc

TOC-tidb-cloud.md, TOC.md
add docs home in tidb toc and tidb cloud toc
=> toc: add docs home in tidb toc and tidb cloud toc

system-variables.md
=> Add note for tidb_restricted_read_only

basic-features.md, develop/dev-guide-use-common-table-expression.md, optimizer-hints.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10373
=> planner: update the doc for merge hint

tikv-configuration-file.md
Add a description of `raftstore.report-min-resolved-ts-interval`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10669
=> config: add description of report-min-resolved-ts-interval

TOC.md, best-practices/java-app-best-practices.md, develop/dev-guide-choose-driver-or-orm.md, develop/dev-guide-transaction-restraints.md, mysql-compatibility.md, sql-statements/sql-statement-rollback.md, sql-statements/sql-statement-savepoint.md
add doc for savepoint
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9700
=> add doc for savepoint

dynamic-config.md, system-variables.md, tikv-configuration-file.md
v6.2: add a few sysvars
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10665 https://github.com/pingcap/docs-cn/pull/10679 https://github.com/pingcap/docs-cn/pull/10685 https://github.com/pingcap/docs-cn/pull/10668
=> v6.2: add a few sysvars

_index.md
learning path: fix broken links
=> learning path: fix broken links

TOC-tidb-cloud.md, develop/dev-guide-build-cluster-in-cloud.md, tidb-cloud/_index.md
=> cloud: add develop doc links to the  learning path

tidb-cloud/release-notes-2022.md
=> cloud: improve release notes by adding reference links

tidb-cloud/select-cluster-tier.md
=> cloud: Update select-cluster-tier.md

system-variables.md
system variable: add tidb_opt_skew_distinct_agg
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10564 https://github.com/pingcap/docs-cn/pull/10797
=> system variable: add tidb_opt_skew_distinct_agg

TOC.md, develop/dev-guide-read-in-fast-mode.md, information-schema/information-schema-tiflash-replica.md, sql-statements/sql-statement-set-tiflash-mode.md
Add fast mode
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/10560
=> sql: add fast mode

_docHome.md
=> cloud: add tidb cloud dve guide

mysql-compatibility.md, sql-statements/sql-statement-alter-table.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10772
=> update the limitations of multi-schema change

system-variables.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10755
=> system-veriables: add @@tidb_min_paging_size and @@tidb_max_paging_size

experimental-features.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10704
=> add multi-schema change to experimental feature page

system-variables.md
delete experimental for tidb_analyze_version. This should have been done in https://github.com/pingcap/docs/pull/9803.
=> delete experimental for tidb_analyze_version

system-variables.md
add doc for tidb_track_aggregate_memory_usage
=> add doc for tidb_track_aggregate_memory_usage

tikv-configuration-file.md
=> Revert "config: add description of report-min-resolved-ts-interval"

tidb-cloud/configure-security-settings.md, tidb-cloud/tidb-cloud-billing.md
cloud: change the position of Security Settings button
=> cloud: change the position of Security Settings button

tidb-cloud/backup-and-restore.md, tidb-cloud/release-notes-2022.md, tidb-cloud/tidb-cloud-billing-tcu.md
=> cloud: support GCP region Osaka

TOC-tidb-cloud.md, tidb-cloud/migrate-data-into-tidb.md, tidb-cloud/migrate-incremental-data-from-mysql.md
Added a new article about incremental data migration from MySQL to TiDB Cloud.
=> cloud: Create migrate-incremental-data-from-mysql.md

sql-statements/sql-statement-explain.md
sql-statements: add explanation for explain format = "brief"
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10759
=> sql-statements: add explanation for explain format = "brief"

br/backup-and-restore-faq.md, br/backup-and-restore-overview.md, br/br-usage-restore.md
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/10429, https://github.com/pingcap/docs-cn/pull/10671
=> br: add doc for restoring sys privilege tables

br/backup-and-restore-storages.md, br/backup-storage-S3.md, dm/task-configuration-file-full.md, dumpling-overview.md, encryption-at-rest.md, migrate-aurora-to-tidb.md, migrate-from-csv-files-to-tidb.md, migrate-from-sql-files-to-tidb.md, migrate-large-mysql-to-tidb.md, sql-statements/sql-statement-backup.md, sql-statements/sql-statement-restore.md, sql-statements/sql-statement-show-backups.md, tidb-cloud/migrate-from-aurora-bulk-import.md
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/10561, https://github.com/pingcap/docs-cn/pull/10684
=> remove s3.region parameter

br/backup-and-restore-use-cases.md, dm/quick-start-create-task.md, download-ecosystem-tools.md, quick-start-with-tidb.md, ticdc/manage-ticdc.md, tidb-binlog/get-started-with-tidb-binlog.md
v6.2: bump version for tools
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10830
=> v6.2: bump version for tools

ticdc/manage-ticdc.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10557
=> ticdc: add doc for row filter config

tidb-binlog/binlog-consumer-client.md
Close https://github.com/pingcap/docs/issues/9867
=> fix broken link in binlog-consumer-client.md

overview.md
=> tidb overview: updated video links

tiflash/tiflash-configuration.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10844
=> tiflash: add some config item for PageStorage V3

identify-slow-queries.md, information-schema/information-schema-slow-query.md, statement-summary-tables.md, system-variables.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10585
=> *: add description about the binary plan

overview.md
Refined the size of the intro video
=> overview: refine the size of the intro video

tidb-cloud/scale-tidb-cluster.md
=> cloud: add a note for scaling 4C cluster

alert-rules.md
Add the PD_cluster_slow_tikv_nums alert rule
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10352
=> Add alert rules for PD_cluster_slow_tikv_nums

system-variables.md
Although the current document has a clear description of INSTANCE scope variables at the beginning, users may still get confused when they reach the specified item by searching the document.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10845
=> sysvar: add description in INSTANCE sysvars

tikv-configuration-file.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10757
=> br: update tikv config for pitr

.github/workflows/dispatch.yml
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10879
=> chore: disable release-6.2

system-variables.md
Add desc for variable `tidb_batch_pending_tiflash_count`
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10811
=> Add desc for variable `tidb_batch_pending_tiflash_count`

clinic/clinic-user-guide-for-tiup.md, clinic/quick-start-with-clinic.md, develop/dev-guide-delete-data.md, develop/dev-guide-get-data-from-single-table.md, develop/dev-guide-join-tables.md, develop/dev-guide-optimistic-and-pessimistic-transaction.md, develop/dev-guide-paginate-results.md, develop/dev-guide-prepared-statement.md, develop/dev-guide-sample-application-golang.md, develop/dev-guide-sample-application-java.md, develop/dev-guide-transaction-restraints.md, develop/dev-guide-update-data.md, develop/dev-guide-use-common-table-expression.md, develop/dev-guide-use-follower-read.md, develop/dev-guide-use-stale-read.md, develop/dev-guide-use-temporary-tables.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10878
=> Syncing tab choices using groupId

system-variables.md
=> add document for system variable tidb_read_consistency

develop/dev-guide-overview.md
=> [Update] add PE link

clinic/clinic-user-guide-for-tiup.md
=> revert several lines that caused build failure

clinic/clinic-user-guide-for-tiup.md, develop/dev-guide-sample-application-java.md
=> fix simpletab

clinic/clinic-user-guide-for-tiup.md
https://github.com/pingcap/docs/pull/9963
=> clinic/clinic-user-guide-for-tiup: add groupid

tidb-cloud/tidb-cloud-faq.md
=> cloud: remove a customer name

dm/dm-overview.md
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/10314
=> dm: fix a 404 link

system-variables.md
Fix description for tidb_opt_mpp_outer_join_fixed_build_side
=> Fix description for tidb_opt_mpp_outer_join_fixed_build_side

stale-read.md
=> Fix typo in stale-read.md

tidb-configuration-file.md, tikv-configuration-file.md
add missing doc for enable-forwarding
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10810
=> add missing doc for enable-forwarding

develop/dev-guide-proxysql-integration.md
=> develop/dev-guide-proxysql-integration.md: fix groupid

tikv-control.md
Signed-off-by: qupeng <qupeng@pingcap.com>
=> update tikv control doc

sync-diff-inspector/sync-diff-inspector-overview.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10630
=> sync_diff_inspector: update unsupport types

pd-control.md
- This PR is translated from: https://github.com/pingcap/docs-cn/blob/master/pd-control.md
=> *: align description about pd-control with Chinese

TOC.md, backup-and-restore-use-cases-for-maintain.md, br-usage-backup-for-maintain.md, br-usage-restore-for-maintain.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10943
=> br: rename three br docs under maintain for better search experience

production-deployment-using-tiup.md, scale-tidb-using-tiup.md, tiup/tiup-cluster.md, tiup/tiup-component-cluster-deploy.md, tiup/tiup-component-management.md, tiup/tiup-mirror.md, tiup/tiup-playground.md, upgrade-tidb-using-tiup.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10910
=> tiup: bump version for 6.2

TOC.md, binary-package.md, download-ecosystem-tools.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10401 https://github.com/pingcap/docs-cn/pull/10900
=> *: add a doc for binary package and update download tools page

system-variables.md
=> sysvar: debug expressions

error-codes.md, faq/deploy-and-maintain-faq.md, faq/manage-cluster-faq.md, faq/monitor-faq.md, faq/tidb-faq.md, sql-statements/sql-statement-load-data.md
faq: remove error codes content from tidb faq
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10931
=> faq: remove error codes content from tidb faq

tidb-cloud/tidb-cloud-intro.md
=> Add TiDB Cloud intro video

_index.md
v6.2: bump version for learning path
=> v6.2: bump version for learning path

pd-recover.md
Update the Go version of PD Recover from v1.13 to v1.16. Since the change was merged into https://github.com/tikv/pd/pull/3711 on May 27, 2021, this PR needs cherry pick from v4.0 to v6.2
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10983
=> PD Recover: update Go version from v1.13 to v1.16

system-variables.md
Document a new sys var `tidb_txn_commit_batch_size`.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/9610
=> add tidb_txn_commit_batch_size

integration-overview.md
- Other reference link(s): https://github.com/pingcap/docs/pull/10075
=> ticdc: emphasize integrating with snowflake

migrate-from-tidb-to-mysql.md, migrate-from-tidb-to-tidb.md
Update inappropriate descriptions in https://github.com/pingcap/docs/pull/9692
- Other reference link(s): https://github.com/pingcap/docs/pull/9692
=> migrate: update descriptions

tidb-lightning/tidb-lightning-distributed-import.md
Delete contents about diagrams in lightning
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/11029
=> lightning: delete contents about diagrams in lightning

br/pitr-known-issues.md
Add known issues for PITR
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/11021
=> br: add pitr known issues

.github/workflows/dispatch.yml
=> chore: enable build of release 6.2

.github/workflows/dispatch.yml
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11040
=> chore: enable build of the master branch

TOC-tidb-cloud.md, tidb-cloud/api-overview.md
Add API overview.
- Other reference link(s): https://github.com/pingcap/docs/pull/9559
=> cloud: add api overview

TOC.md, releases/release-6.2.0.md, releases/release-notes.md, releases/release-timeline.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11051
=> refine 6.2.0 release docs

tidb-cloud/tidb-cloud-support.md
=> cloud: update tidb-cloud-support.md

tidb-cloud/_index.md
=> cloud: update _index.md

tidb-cloud/connect-to-tidb-cluster.md
=> cloud: use internal link

br/br-log-command-line.md, br/pitr-usage.md
add doc for enabling log backup
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/11047
=> pitr: add doc for enabling log backup

deploy-monitoring-services.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11053
=> update version of monitoring components

TOC-tidb-cloud.md, develop/dev-guide-proxysql-integration.md
Add a document about how to integrate TiDB Cloud with ProxySQL. [preview](https://add-develop-proxysql.website-docs.pages.dev/tidbcloud/dev-guide-proxysql-integration)
=> develop: add proxysql integration

TOC-tidb-cloud.md, tidb-cloud/_index.md, tidb-cloud/changefeed-overview.md, tidb-cloud/monitor-tidb-cluster.md, tidb-cloud/pause-or-resume-tidb-cluster.md, tidb-cloud/release-notes-2022.md, tidb-cloud/select-cluster-tier.md
=> Revert "Revert "cloud: pause or resume a cluster""

releases/release-5.3.1.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11066
=> release 5.3.1: move dm bug fixes from the ticdc module to the dm module

tidb-cloud/release-notes-2022.md
=> Cloud: Update release notes

configure-placement-rules.md
=> fix a typo in configure-placement-rules

tidb-cloud/config-s3-and-gcs-access.md, tidb-cloud/configure-security-settings.md, tidb-cloud/connect-to-tidb-cluster.md, tidb-cloud/delete-tidb-cluster.md, tidb-cloud/import-csv-files.md, tidb-cloud/import-parquet-files.md, tidb-cloud/import-sample-data.md, tidb-cloud/migrate-from-aurora-bulk-import.md, tidb-cloud/scale-tidb-cluster.md, tidb-cloud/select-cluster-tier.md, tidb-cloud/set-up-vpc-peering-connections.md
=> cloud: update the description to find your cluster

releases/release-5.0.5.md
=> fix a typo in 5.0.5 RN

releases/release-5.2.3.md
=> fix a typo in 5.2.3 RN

releases/release-5.1.3.md
=> fix a typo in 5.1.3 RN

tidb-cloud/tidb-cloud-faq.md
cloud: add 2 FAQs
- Other reference link(s): https://github.com/pingcap/docs/pull/10061
=> cloud: add 2 FAQs

releases/release-6.1.0.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11065
=> emphasize a ticdc improvement in 6.1 release notes

.github/workflows/prevent-deletion.yaml
Change the workflow trigger in `prevent-deletion.yaml` from `pull_request` to `pull_request_target`. Otherwise the workflow will not have write access to base repository's Checks.
=> Fix permission issue in Prevent Deletion workflow

tidb-cloud/migrate-incremental-data-from-mysql.md, tidb-cloud/tidb-cloud-faq.md, tidb-cloud/tidb-cloud-support.md
=> cloud: categorize FAQs

ticdc/ticdc-open-api.md
Fix a typo on ticdc open api field description
=> fix: typo on ticdc open api field description

ticdc/ticdc-faq.md
Add upstream to clarify the TiCDC stall scenario when using TiDB Lightning and BR.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11002
=> TiCDC FAQ: clarify the scenario of using TiDB Lightning and BR

faq/migration-tidb-faq.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11099
=> fix incorrect description in migration faq

faq/migration-tidb-faq.md
=> remove Chinese reference in migration faq

best-practices/haproxy-best-practices.md
Revert "Update a path in haproxy guide"
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11092
=> Revert "Update a path in haproxy guide"

.github/pull_request_template.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11116
=> chore: add v6.3 to PR template

tidb-cloud/backup-and-restore.md
remove useless default backup UTC time table
=> remove useless default backup UTC time table

TOC-tidb-cloud.md, develop/dev-guide-proxysql-integration.md
=> Revert "develop: add proxysql integration"

releases/release-5.1.4.md
Add a new entry in release notes 5.1.4
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/11127
=> tidb: add a new entry in release notes 5.1.4

tidb-cloud/tidb-cloud-faq.md
Add one FAQ item about VPC peering between different clouds
=> tidb-cloud: add one FAQ about VPC peering between clouds

br/backup-and-restore-design.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10622
=> br: add backup file layout description

ticdc/manage-ticdc.md, ticdc/ticdc-faq.md, ticdc/ticdc-overview.md
add transaction-atomicity parameter to TiCDC
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10313
=> add transaction-atomicity parameter to TiCDC

tidb-cloud/tidb-cloud-performance-reference.md
…lease-6.1
add test scale memory.
Add memory info for the test scales.
=> TiDBCloud: Add Memory Info to testScale in Performance-Reference page

.github/workflows/prevent-deletion.yaml
Fix a bug that the prevent-deletion workflow cannot find head
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11103
=> CI: fix the bug that prevent-deletion cannot find head commit

tikv-configuration-file.md
- Other reference link(s): https://github.com/tikv/tikv/issues/12355
=> add tikv configuration item `simplify-metrics`

br/br-deployment.md, hardware-and-software-requirements.md
v6.1: add multi-level os support doc
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11134
=> v6.1: add multi-level os support doc

ticdc/manage-ticdc.md
=> Revert "ticdc: add a warning for the eventually consistent replication feature"

faq/sql-faq.md
faq: delete a word in a title to be more "inclusive"
- Other reference link(s): https://github.com/pingcap/docs/pull/10271#issuecomment-1235194532
=> faq: delete a word in a title to be more inclusive

tidb-cloud/changefeed-sink-to-apache-kafka.md
=> cloud: update kafka changefeed doc based on docs usability testing

TOC.md
=> remove a duplicated Dumpling entry from TOC.md

ticdc/manage-ticdc.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11182
=> ticdc: update the warning for using redo log

_index.md
Fix aliases that were mistakenly changed in https://github.com/pingcap/docs/pull/9839
=> index: fix index aliases for v4.0

_index.md
Fix aliases that were mistakenly changed in https://github.com/pingcap/docs/pull/9845
=> index: fix index aliases for v6.0

_index.md
Fix aliases that were mistakenly changed in https://github.com/pingcap/docs/pull/9843
=> index: fix index aliases for v5.3

_index.md
Fix aliases that were mistakenly changed in https://github.com/pingcap/docs/pull/9842
=> index: fix index aliases for v5.2

_index.md
Fix aliases that were mistakenly changed in https://github.com/pingcap/docs/pull/9841
=> index: fix index aliases for v5.1

_index.md
Fix aliases that were mistakenly changed in #9844
- Other reference link(s): #9844
=> index: fix index aliases for v5.4

_index.md
Fix aliases that were mistakenly changed in https://github.com/pingcap/docs/pull/9846
=> index: fix index aliases for v6.1

_index.md
Fix aliases that were mistakenly changed in https://github.com/pingcap/docs/pull/9840
=> index: fix index aliases for v5.0

character-set-and-collation.md
=> Add missing collations and unify code block style

sql-statements/sql-statement-alter-user.md, sql-statements/sql-statement-create-user.md
As title.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/11104
=> support account lock/unlock in create/alter user

tidb-cloud/tidb-cloud-poc.md
cloud: add an option to access apply for poc
=> cloud: add an option to access apply for poc

tidb-cloud/set-up-private-endpoint-connections.md
=> cloud: fix image display in set-up-private-endpoint-connections.md

tidb-cloud/changefeed-sink-to-apache-kafka.md
=> cloud: update changefeed-sink-to-apache-kafka.md according to UI changes 

character-set-and-collation.md
=> move comment from code block to the normal text

schedule-replicas-by-topology-labels.md
placement rules: remove experimental note
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11231
=> placement rules: remove experimental note

tidb-cloud/_index.md, tidb-cloud/api-overview.md
=> cloud: update api overview

best-practices/pd-scheduling-best-practices.md
best-practices: fix a wrong description
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11243
=> best-practices: fix a wrong description

TOC.md, develop/dev-guide-third-party-support.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11125
=> [Update] supported third lib

binary-package.md, download-ecosystem-tools.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11113
=> support downloading server and toolkit packages under arm

tidb-cloud/tidb-cloud-performance-reference.md
Only modify latency to Avg Latency, more accurate to users who read this document page.
=> cloud: modify latency to Avg Latency in Performance Reference Page

develop/dev-guide-proxysql-integration.md
Signed-off-by: aolin <aolin.zhang@pingcap.com>
Redirect https://docs.pingcap.com/tidbcloud/dev-guide-proxysql-integration to  https://docs.pingcap.com/tidb/stable/dev-guide-proxysql-integration.
- Other reference link(s): https://github.com/pingcap/docs/pull/10254
=> Redirect `tidbcloud/dev-guide-proxysql-integration` to `tidb/dev-guide-proxysql-integration`

TOC.md, tidb-lightning/tidb-lightning-faq.md, tidb-lightning/tidb-lightning-glossary.md, tidb-lightning/troubleshoot-tidb-lightning.md, tidb-troubleshooting-map.md
Split troubleshoot from faq.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/9653
=> lightning: split troubleshoot from faq

TOC.md, releases/release-5.3.3.md, releases/release-notes.md, releases/release-timeline.md
release: add TiDB 5.3.3 release note
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11265
=> release: add TiDB 5.3.3 release note

tidb-cloud/configure-security-settings.md, tidb-cloud/create-tidb-cluster.md, tidb-cloud/select-cluster-tier.md, tidb-cloud/tidb-cloud-glossary.md, tidb-cloud/tidb-cloud-quickstart.md
cloud: add docs for playground
=> cloud: add docs for playground and cluster overview

tidb-cloud/release-notes-2022.md
cloud: update release notes for 914
=> cloud: update release notes for 914

releases/release-5.3.2.md, releases/release-5.3.3.md, releases/release-5.4.2.md
releases: refine 5.3.3 release note
=> releases: refine 5.3.3 release note

tidb-cloud/monitor-tidb-cluster.md
=> cloud: Update monitor-tidb-cluster.md

ticdc/deploy-ticdc.md, ticdc/manage-ticdc.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11119
=> ticdc: update cdc server/cli params

basic-features.md, functions-and-operators/encryption-and-compression-functions.md, security-compatibility-with-mysql.md, sql-statements/sql-statement-show-builtins.md, system-variables.md
Add the description about `tidb_sm3_password` authentication and `SM3()` function.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10578
- Other reference link(s): https://github.com/pingcap/tidb/pull/36193
=> v6.3: Add description about SM3 encryption authentication

config-templates/complex-cdc.yaml, tiup/tiup-cluster-topology-reference.md
as title.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11295
=> tiup: update doc for cdc_server_id

placement-rules-in-sql.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11093
- Other reference link(s): https://github.com/pingcap/tidb/pull/37252
=> remove tiflash and placement in sql incompatible descrption

partitioned-table.md
Add description about `EXCHANGE PARTITION`.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/11017
=> table partition: exchange partition feature

br/backup-storage-S3.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11292
=> backup: support object lock in s3

command-line-flags-for-tidb-configuration.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10806
=> Update command line parameter documents

partitioned-table.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11270
=> update dynamic prune mode requirements

br/br-log-command-line.md, br/pitr-troubleshoot.md, br/point-in-time-recovery.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11133
=> pitr: support exchange partition, gcs, and azblob

tiflash/tiflash-supported-pushdown-calculations.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11191
=> tiflash: add docs about lead/lag push down to tiflash

ticdc/manage-ticdc.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11111
=> ticdc: deprecated mem sorter

br/pitr-known-issues.md, tikv-configuration-file.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11184
=> br: update pitr docs about small files

partitioned-table.md
Document the new feature INTERVAL Partitioning
https://github.com/pingcap/tidb/pull/35662
=> table partition: add INTERVAL partitioning

sync-diff-inspector/upstream-downstream-diff.md, ticdc/manage-ticdc.md
ticdc: add sync point config
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11273
=> ticdc: add sync point config

system-variables.md
set default value of tidb_enable_pseudo_for_outdated_stats to OFF
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11238
=> set default value of tidb_enable_pseudo_for_outdated_stats to OFF

br/br-log-command-line.md, br/pitr-usage.md, br/point-in-time-recovery.md, tikv-configuration-file.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11294, https://github.com/pingcap/docs-cn/pull/11315
=> log-backup: update version check for pitr

security-compatibility-with-mysql.md, system-variables.md
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/11322
=> security: add tidb-jdbc to sm3 docs

system-variables.md
Added new variable `tidb_opt_three_stage_distinct_agg`.
=> Add new variable tidb_opt_three_stage_distinct_agg

dm/task-configuration-file-full.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10555/files
=> dm: add a config safe-mode-duration

TOC.md, benchmark/benchmark-tidb-using-ch.md, releases/release-3.0-ga.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10762
=> add ch benchmark #10762

partitioned-table.md
Refined a description about ranges.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/11314
- Other reference link(s):https://github.com/pingcap/docs/pull/10385
=> table partition: update RANGE COLUMNS partitioning 

develop/dev-guide-build-cluster-in-cloud.md
- Other reference link(s): v6.1: https://github.com/pingcap/docs/pull/10111
=> dev-guide: rename active clusters

auto-random.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10364
=> auto-random.md: rewrite the document

tidb-cloud/monitor-tidb-cluster.md, tidb-cloud/pause-or-resume-tidb-cluster.md, tidb-cloud/scale-tidb-cluster.md, tidb-cloud/select-cluster-tier.md
=> update cluster status

tidb-cloud/scale-tidb-cluster.md
=> cloud: update the entrance name of scaling a cluster

tidb-cloud/manage-user-access.md
=> cloud: update user profile tab

TOC-tidb-cloud.md, tidb-cloud/api-overview.md
- api becomes public beta. No application required.
- move api doc position
=> cloud: api public beta

tidb-cloud/tidb-cloud-billing.md
cloud: update quota-based invoice doc
=> cloud: update quota-based invoice doc

tidb-cloud/size-your-cluster.md
modify the part of size TiKV node quantity, add tikv storage usage, which is actually used.
=> Modify size tikv node quantity

tidb-cloud/release-notes-2022.md
cloud: update release notes for 0920
=> cloud: update release notes for 0920

tidb-cloud/import-sample-data.md
=> cloud: fix indent

tidb-cloud/tidb-cloud-glossary.md, tidb-cloud/tidb-cloud-intro.md
=> cloud: add Playground to TiDB Cloud Intro

functions-and-operators/string-functions.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11344
=> update regexp docs

storage-engine/titan-configuration.md
titan: update the step of disabling titan
=> titan: update the step of disabling titan

tidb-cloud/import-sample-data.md, tidb-cloud/tidb-cloud-htap-quickstart.md
cloud: refine htap and import sample data docs
=> cloud: refine htap and import sample data docs

troubleshoot-data-inconsistency-errors.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9336
=> fix explanation of error 8134 

tidb-cloud/tidb-cloud-roadmap.md
=> cloud: rm roadmap dates

sql-statements/sql-statement-create-index.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11376
=> sql: update sql-statement-create-index.md

tidb-cloud/tidb-cloud-roadmap.md
=> cloud: add disclaimer for roadmap

ticdc/deploy-ticdc.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11397
=> update deploy cdc docs

tidb-cloud/migrate-sql-shards.md
Changed the password to a placeholder.
=> tidb cloud: change pw to placeholder

migrate-from-tidb-to-tidb.md, tidb-lightning/tidb-lightning-overview.md
Close https://github.com/pingcap/docs-tidb-operator/issues/2013
=> Fix broken links in docs-tidb-operator

br/pitr-known-issues.md, system-variables.md
Add a compatible description when using index acceleration and PITR.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11385
=> Edit pitr compatible description with add index lightning feature

tikv-configuration-file.md
Add sm4 to tikv-configuration-file.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11412
=> Add sm4 to tikv-configuration-file.md

tikv-configuration-file.md
Signed-off-by: Lucasliang <nkcs_lykx@hotmail.com>
Supplement the doc on how to degrade TiKV - v6.3.0 with  `format-version: 2` to previous version, such as v6.1.0.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11398
- Other reference link(s): N/A
=> Supplement the doc on how to degrade v6.3.0 with `format-version: 2`.

follower-read.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11417
=> TiDB Operator v1.4 supports setting labels for TiDB

sql-plan-replayer.md, system-variables.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11317
=> support plan replayer for multi sqls

binary-package.md, br/br-deployment.md, comment-syntax.md, develop/dev-guide-paginate-results.md, download-ecosystem-tools.md, system-variables.md, tiflash/tiflash-configuration.md, tiflash/use-tispark-to-read-tiflash.md, tikv-control.md
Only `> **Note:**`, `> **Warning:**`, `> **Tip:**`, and `> **Important:**` can be rendered probably.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11428
=> Fix admonition format

system-variables.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11426
=> Add experimental warning for tidb_ddl_enable_fast_reorg

tidb-cloud/manage-user-access.md
=> cloud: update password policy
