tikv-configuration-file.md

Using string literals was supported in https://github.com/tikv/tikv/pull/11068.
This configuration change will **not** break backward compatibility. Old settings are still accepted.

Update tikv rocksdb enum type configurations

---

functions-and-operators/miscellaneous-functions.md

The current linked issue https://github.com/pingcap/tidb/issues/10929 has been closed because it asks to show errors when non-supported `GET_LOCK()` and `RELEASE_LOCK()` are executed. If someone click this link and they may misunderstand this issue has been resolved, like these functions are available in TiDB.
This commit updates the linked issue number to show the current status of `GET_LOCK()` and `RELEASE_LOCK()` functions, which is not supported yet. …

Update issue number to show `GET_LOCK()` and `RELEASE_LOCK()` status

---

hardware-and-software-requirements.md

List Amazon Linux 2 (CentOS 7 based) as supported. This is common OS when deploying on ARM64 (AWS Graviton 2)
- https://github.com/pingcap/tiup/pull/1740

List Amazon Linux 2 as supported

---

information-schema/information-schema-placement-rules.md
placement-rules-in-sql.md

Signed-off-by: xhe <xw897002528@gmail.com>
A follow up from pingcap/docs-cn#8230:
1. add descriptions on `placement rules` and `placement policies`
2. remove one more direct placement in `information-schema-placement-rules.md`
3. refine one example
- This PR is translated from: pingcap/docs-cn#8230

*: clarify rules and policies

---

configure-placement-rules.md

Fix the format of `"count"`'s value from `"5"` to `5`, because the count field is an integer, and the former value causes errors.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8678

fix a format of count‘s value

---

tiflash/tiflash-command-line-flags.md
tiflash/tiflash-configuration.md

Add `dt_compression_method` and `dt_compression_level` config in TiFlash doc.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8611

update tiflash doc add dt_compression_method and dt_compression_level config

---

dynamic-config.md
grafana-tikv-dashboard.md
pessimistic-transaction.md
tikv-configuration-file.md
transaction-isolation-levels.md

tikv: update docs about in-memory pessimistic locks
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8645

tikv: update docs about in-memory pessimistic locks

---

system-variables.md
transaction-isolation-levels.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8617

txn: update the document about read-consistency read check ts variable

---

tiflash/use-tiflash.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8698

add docs for mpp partition table support

---

dynamic-config.md
tikv-configuration-file.md

- Added new TiKV configurations that can be configured dynamically: `raftstore.raft-max-inflight-msgs`, `readpool.unified.max-thread-count`
- Updated value ranges for some TiKV configurations: `max-thread-count`, `num-threads`
- Updated descriptions of some TiKV configurations: `raft-max-inflight-msgs`, `apply-pool-size`(the changes for this configuration's description are the same as changes in PR #7963, line 738). …

TiKV config: Add new online configurations and update value ranges

---

tikv-configuration-file.md

- Disable Raft Engine by default
- Add a note to remind users that this feature is an experimental feature
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8810

Disable Raft Engine by default

---

sql-prepare-plan-cache.md
system-variables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8623

update documents related to Plan Cache

---

sql-statements/sql-statement-alter-placement-policy.md

close https://github.com/pingcap/docs/issues/8030
- Other reference link(s): https://github.com/pingcap/docs-cn/blob/master/sql-statements/sql-statement-alter-placement-policy.md

Add missing example in ALTER PLACEMENT POLICY

---

tidb-scheduling.md

Revised the format of a newly updated part in [#6949](#https://github.com/pingcap/docs/pull/6949).
The formats in cherry-pick PRs #6949 have been revised, so I only revised the format in the master in this PR.

TiDB Scheduling: Revise the format of status description parts

---

br/backup-and-restore-tool.md

Add comments for 6.0 br compatibility because of the default changing of the config  `new_collations_enabled_on_first_bootstrap` from `false` to `true`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8809

add doc for new-collation-enable in br

---

placement-rules-in-sql.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8853

placement-rules-in-sql: add some lightning descriptions 

---

placement-rules-in-sql.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8858

Add alter partition demo in placement in sql

---

mysql-compatibility.md

Update SQL keywords in mysql-compatibility.md.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/6421

Update SQL keywords format in mysql-compatibility

---

releases/release-6.0.0-dmr.md
releases/release-timeline.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/8871/files

fix 6.0 release notes

---

enable-tls-between-clients-and-servers.md
tidb-configuration-file.md

Add docs for the `tls-version` configuration in the TiDB configuration.
- Other reference link(s): https://github.com/pingcap/tidb/pull/26937

tidb-configuration-file: add tls-version

---

statistics.md
system-variables.md

Update description for analyze version
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8412

Update description for analyze version

---

system-variables.md

tidb_dml_batch_size is only effective when another variable is turned on 'tidb_batch_insert', 
however it is not documented causing some confusion for customer
added
'tidb_batch_insert' parameter is required to turn on in order for 'tidb_dml_batch_size' to work, but information is currently missing in the doc 
No reference link, internal …

Update tidb_dml_batch_size section

---

auto-increment.md

Add mention of the `FORCE` keyword that can be used like `ALTER TABLE t FORCE AUTO_INCREMENT=100` to reset the auto increment value of a table.
- https://github.com/pingcap/tidb/issues/25400

auto-increment: Mention `FORCE`

---

tispark-overview.md

- Fix format: white space, spark-sql code format, link of http://spark-master-hostname:8080
- Remove note and config in statistics information
- Change firewalld description to a note
- Other reference link(s): https://github.com/pingcap/tispark/pull/2300

Remove statistics information and change firewalld description in TiSpark Overview

---

dm/quick-start-with-dm.md
dm/task-configuration-file-full.md

Update quick start guide and task configuration file full.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8454 https://github.com/pingcap/docs-cn/pull/8969/files
- Other reference link(s): part 1 (https://github.com/pingcap/docs/pull/7977)

dm: refactor dm docs - part 2

---

mysql-compatibility.md

This pull request adds the national character sets behavior difference between TiDB and MySQL explained at https://github.com/pingcap/tidb/issues/33346#issue-1177725325
- This PR is translated from: https://github.com/pingcap/tidb/issues/33346

Add the national character sets behavior difference between TiDB and MySQL

---

auto-random.md

- Make it more clear that only `bigint` is supported for `auto_random` in recent versions
- Make it clear that you can modify a column to change it from `auto_increment` to `auto_random` ( https://github.com/pingcap/tidb/pull/20512 )
- Document the limitations for the `auto_increment` to `auto_random` change.

Update auto_random docs

---

certificate-authentication.md

According to the community feedback OPENSSL X509 command description error, this PR to improve the OPENSSL X509 command line parameters
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/9026

fix openssl x509 command line parameter

---

migrate-large-mysql-shards-to-tidb.md
tidb-lightning/tidb-lightning-configuration.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8925

Replace route with mydumper.files due to route feature not GA yet

---

privilege-management.md
system-variables.md

Added the description of following configurations:
- `RESTRICTED_REPLICA_WRITER_ADMIN` in the "privilege-management.md"
- `tidb_restricted_read_only` in the "system-variables.md"
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/6716

system variable: add `tidb_restricted_read_only`

---

functions-and-operators/miscellaneous-functions.md

Add `UUID_TO_BIN()` and `BIN_TO_UUID()` to the list of supported miscellaneous functions.
Note that the links go the MySQL 8.0 reference manual as these are not available in MySQL 5.7.
I'm not closing #5920 yet as this doesn't yet explain how to deal with UUID and hotspots, that will be another PR.
- #5920
- https://github.com/pingcap/tidb/pull/20140

functions-and-operators: Add UUID_TO_BIN and BIN_TO_UUID

---

system-variables.md

The docs for `tidb_restricted_read_only` are inconsistent:
The type for this variable is a boolean, which in `SHOW VARIABLES` context will show `ON` or `OFF`. In `SELECT @@varname` context it will return `0` or `1`, so for docs context we have to chose one format. 
It looks like the original PR author chose `0`/`1`, but in the rest of the page we use `ON`/`OFF`, which is also consistent with the mysql docs: https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html
For details, see [tips for …

system-variables: improve restricted-read-only docs

---

deploy-monitoring-services.md
dm/deploy-a-dm-cluster-using-binary.md
dm/quick-start-create-task.md
get-started-with-tidb-lightning.md
sync-diff-inspector/sync-diff-inspector-overview.md
tidb-binlog/deploy-tidb-binlog.md
tidb-binlog/get-started-with-tidb-binlog.md
tidb-binlog/tidb-binlog-reparo.md
tidb-lightning/deploy-tidb-lightning.md

Remove `/bin` from some toolkit commands: `dm-master`, `dm-worker`, `dmctl`, `dumpling`, `sync_diff_inspector`, `binlogctl`, `pump`, `drainer`.

Remove `/bin` from toolkit commands

---

two-data-centers-in-one-city-deployment.md

Added a rollback step to "two-data-centers-in-one-city-deployment.md".
- This PR is translated from:  https://github.com/pingcap/docs-cn/pull/9174, https://github.com/pingcap/docs-cn/pull/9307

add a rollback step

---

faq/tidb-faq.md

Update a TiDB FAQ about supported storage engine
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9490

Update a TiDB FAQ about supported storage engine

---

pessimistic-transaction.md
transaction-overview.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8095, https://github.com/pingcap/docs-cn/pull/8316

Update the memory usage size of a transaction #8316

---

ticdc/manage-ticdc.md
ticdc/troubleshoot-ticdc.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/7151

ticdc: synchronize data in the new collations

---

configure-memory-usage.md

Fix a ref found in https://github.com/pingcap/docs/pull/8689/files#r884377227
- Other reference link(s): https://github.com/pingcap/docs/pull/8689/files#r884377227

fix a wrong ref in memory control

---

dashboard/top-sql.md

we fix a bug so we can ignore the limitation, cn-doc pr: https://github.com/pingcap/docs-cn/pull/9651
fix pr: pingcap/tidb#33861
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9651

Delete a limitation description

---

dashboard/dashboard-faq.md
grafana-tidb-dashboard.md
optimizer-hints.md
sql-prepared-plan-cache.md
system-variables.md

As title. Some contents are updated in https://github.com/pingcap/docs/pull/8689. 
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9553

update doc for memory management of prepared plan cache

---

pd-configuration-file.md
pd-control.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9502 https://github.com/pingcap/docs-cn/pull/9604 https://github.com/pingcap/docs-cn/pull/9637

Add max-store-preparing-time in pd-ctl

---

garbage-collection-configuration.md
system-variables.md

add system variable `tidb_gc_max_wait_time` 
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9496
https://github.com/pingcap/docs-cn/pull/9670

system-variables: add system variable tidb_gc_max_wait_time 

---

optimizer-hints.md

docs: add the usage for the join order hint
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9392

docs: add the usage for the join order hint

---

releases/release-6.0.0-dmr.md

Add optimized batch update of hotspot indexes to `release-6.0.0-dmr`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9511

Add optimized batch update of hotspot indexes to release-6.0.0-dmr

---

functions-and-operators/json-functions.md

Update the status of JSON functions in TiDB
```
mysql> CREATE TABLE t3 (id int primary key auto_increment, o_id int, attribute varchar(255), value varchar(255));
Query OK, 0 rows affected (0.12 sec)
mysql> INSERT INTO t3(o_id, attribute, value) VALUES(2,'color','red'),(2,'fabric','silk'),(3,'color','green'),(3,'shape','square');
Query OK, 4 rows affected (0.02 sec)
Records: 4  Duplicates: 0  Warnings: 0
mysql> SELECT o_id, attribute, value FROM t3;
+------+-----------+--------+
| o_id | attribute | value  |
+------+-----------+--------+
|    2 | color     | red    |
|    2 | fabric    | silk   |
|    3 | color     | green  |
|    3 | shape     | square |
+------+-----------+--------+
4 rows in set (0.00 sec)
mysql> SELECT o_id, JSON_ARRAYAGG(attribute) AS attributes
-> FROM t3 GROUP BY …
```

json-functions: Update status and links

---

tiflash/tiflash-configuration.md

Reverts pingcap/docs#8662
TiFlash v6.1 by default use `format_version = 3`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9705

Revert "Changed format_version default value to 4"

---

tikv-configuration-file.md

Signed-off-by: pingyu <yuping@pingcap.com>
Fix configuration item storage.api-version to right position.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/9718

tikv: Fix storage.api-version position

---

best-practices/high-concurrency-best-practices.md
deploy-monitoring-services.md
tidb-troubleshooting-map.md

close https://github.com/pingcap/docs/issues/8816

remove links to tidb-ansible

---

functions-and-operators/locking-functions.md

add description for locking function when timeout = -1
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9742

add description for locking function when timeout = -1

---

releases/release-6.1.0.md

This pull request adds link to `tidb_max_auto_analyze_time` system variables in the TiDB 6.1.0 release notes.

Add link to `tidb_max_auto_analyze_time` system variables

---

check-before-deployment.md

- Add deploy` tidb-test` step before `tiup cluster exec tidb-test`.
- Fix format.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9512

Add deploy `tidb-test` step before `tiup cluster exec tidb-test`

---

placement-rules-in-sql.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8967

Fix typos in placement-rules-in-sql.md

---

auto-increment.md
explain-subqueries.md
functions-and-operators/aggregate-group-by-functions.md
functions-and-operators/window-functions.md
grafana-tidb-dashboard.md
mysql-compatibility.md
placement-rules-in-sql.md
schedule-replicas-by-topology-labels.md
sql-statements/sql-statement-add-column.md
statistics.md
tiflash-deployment-topology.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9663 https://github.com/pingcap/docs-cn/pull/9481 https://github.com/pingcap/docs-cn/pull/9416 https://github.com/pingcap/docs-cn/pull/9183 https://github.com/pingcap/docs-cn/pull/8971 https://github.com/pingcap/docs-cn/pull/8722 …

Align 8 PRs

---

develop/dev-guide-object-naming-guidelines.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9709

[Update] v6.1 removed lower-case-table-name option

---

releases/release-5.4.0.md

releases: add compatibility-breaker label PRs to release notes
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8757

releases: add compatibility-breaker label PRs to release notes

---

best-practices/massive-regions-best-practices.md
pd-control.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10307

fix format: remove >> in code block

---

clinic/clinic-introduction.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/9732
- Other reference link(s): https://github.com/pingcap/docs-tidb-operator/pull/1890 https://github.com/pingcap/docs-tidb-operator/pull/1889

Add Operator links in clinic-introduction.md

---

TOC.md
clinic/clinic-data-instruction-for-tiup.md
clinic/clinic-introduction.md
clinic/clinic-user-guide-for-tiup.md
clinic/quick-start-with-clinic.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10362

add content for clinic us server

---

data-type-numeric.md

close https://github.com/pingcap/docs/issues/9547

Replace "bit" with "digit"

---

production-deployment-using-tiup.md

remove SimpleTab tag

---

develop/dev-guide-transaction-troubleshoot.md

- This PR is translated from: https://github.com/pingcap/docs/issues/9825

develop: dev-guide-transaction-troubleshoot-typo.md fix typo

---

configure-load-base-split.md
dynamic-config.md

Update the description of load base split:
- Add `split.region-cpu-overload-threshold-ratio`
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10519

tikv: update the Load Base Split introduction

---

command-line-flags-for-tikv-configuration.md

Add the description of `--config-info`, which lists available configuration values.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10615

tikv: add command line flag --config-info

---

information-schema/information-schema-data-lock-waits.md

[Chinese Version of this PR](https://github.com/pingcap/docs-cn/pull/10438)

Update doc for DATA_LOCK_WAITS

---

dynamic-config.md
sql-statements/sql-statement-show-config.md
tikv-configuration-file.md

v6.2: add doc for auto analyze auto tune support
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10360 https://github.com/pingcap/docs-cn/pull/10753 https://github.com/pingcap/docs-cn/pull/10786

v6.2: add doc for auto analyze auto tune support

---

system-variables.md

add doc for @@tidb_enable_noop_variables
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10711

add doc for @@tidb_enable_noop_variables

---

optimizer-hints.md
subquery-optimization.md

planner: add the doc for the SEMI_JOIN_REWRITE hint
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10607

planner: add the doc for the SEMI_JOIN_REWRITE hint

---

TOC.md
information-schema/information-schema-variables-info.md
information-schema/information-schema.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/10712

add doc for information_schema.variable_info

---

ticdc/manage-ticdc.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/10623

Add description of --overwrite-checkpoint-ts for changefeed resume

---

experimental-features.md

Add fast analyze to experimental document

Add fast analyze to experimental document

---

pd-configuration-file.md

This pull request adds `max-days` and `max-backups` default value 0 means for PD configuration guide. There is a similar document for TiKV's `max-days` and `max-backups` via https://github.com/pingcap/docs/pull/7425 There is no PD one.
Here are the technical backgrounds for these documentation changes.
1. max-days at PD configuration
https://github.com/tikv/pd/blob/b5e113436c85f81d0e6ca2b5b592271114089db2/conf/config.toml#L97
```
```
https://github.com/tikv/pd/blob/b5e113436c85f81d0e6ca2b5b592271114089db2/pkg/logutil/log.go#L33-L34
```
// Max log keep days, default is never deleting.
MaxDays int `toml:"max-days" json:"max-days"`
```
It says "default is never deleting."
2. max-backups at PD configuration
https://github.com/tikv/pd/blob/b5e113436c85f81d0e6ca2b5b592271114089db2/conf/config.to …

Add `max-days` and `max-backups` default value 0 means for PD

---

tiflash/tiflash-configuration.md

Signed-off-by: JaySon-Huang <tshent@qq.com>
According to https://github.com/pingcap/tiflash/issues/5576, if user deploys tiflash with explicit setting `profiles.default.dt_enable_logical_split = 1`.
After several logical split, PageStorage V3 will throw an exception for the third time logical split and make TiFlash crash.
Here we declare the config item to be deprecated
For details, see [tips for choosing the affected versions](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md#guideline-for-ch …

Not recommend setting tiflash logical split since 6.2

---

system-variables.md

These two variables could be applied to all the release versions below.

add descriptions for two system variables

---

scale-tidb-using-tiup.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10846

use scale-in to manually remove a TiFlash node

---

tiup/tiup-bench.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10942

tiup bench: modify command from --output to --output-dir

---

TOC.md
system-variables.md
ticdc/integrate-confluent-using-ticdc.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10997

ticdc: highlight integrate with snowflake

---

migration-overview.md

Added ticdc in migration overview
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/11020

migration: add ticdc in migration overview

---

join-reorder.md
system-variables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11034

Compatibility update for outer join reorder

---

tidb-lightning/tidb-lightning-requirements.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10941

lightning: fix format

---

faq/high-reliability-faq.md
faq/manage-cluster-faq.md
faq/sql-faq.md
faq/tidb-faq.md

- Add some FAQs to documentation
- Update an outdated FAQ

faq: add some faqs to documentation

---

tikv-configuration-file.md

This pull request fixes typo `Unite:` should be `Unit:` for `reserve-space` .

Fix typo `Unite:` should be `Unit:` for `reserve-space`

---

faq/sql-faq.md

FAQ: add a faq (blacklist a sql execution)

FAQ: add a faq (blacklist a sql execution)

---

clustered-indexes.md
system-variables.md

Since TiDB v6.3.0, the default value of `tidb_enable_clustered_index` is modified from `INT_ONLY` to `ON`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11177
- Other reference link(s): https://github.com/pingcap/tidb/pull/37384

clustered-indexes.md: change the system variable default value to `ON`

---

tikv-configuration-file.md

Signed-off-by: Lucasliang <nkcs_lykx@hotmail.com>
Add necessary docs for the new feature `log recycling` in raft-engine, released in v6.3.0.
None.

Add docs for raft-engine log recycling feature.

---

functions-and-operators/string-functions.md

Support regexp functions since TiDB v6.3
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11219

Add docs for regexp functions

---

develop/dev-guide-connect-to-tidb.md
develop/dev-guide-third-party-support.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11260

[Update] third party tools update

---

experimental-features.md
storage-engine/titan-configuration.md
tikv-configuration-file.md

update tikv docs for titan fallback

---

optimizer-hints.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11276

doc: update the doc for hash_join_build and hash_join_probe hints

---

tiflash/tiflash-configuration.md

dt_enable_read_thread is deprecated. Enabled by default and cannot be changed. 
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/11203

tiflash: dt_enable_read_thread deprecated

---

TOC.md
error-codes.md
metadata-lock.md
sql-statements/sql-statement-commit.md
system-variables.md

Since v6.3.0, TiDB introduces metadata lock to avoid the ``Information schema is changed`` error.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11138

support metadata lock

---

system-variables.md

Add tidb_opt_inline_cte system vars usage description in docs
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11216

docs:Add tidb_opt_force_inline_cte system vars usage description in docs.

---

system-variables.md
transaction-isolation-levels.md

system-variables: add a variable tidb_rc_write_check_ts
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11275 https://github.com/pingcap/docs-cn/pull/11313

system-variables: add a variable tidb_rc_write_check_ts

---

dynamic-config.md
tikv-configuration-file.md
tune-tikv-thread-performance.md

Since v6.3.0, TiKV introduces the `readpool.unified.auto-adjust-pool-size` configuration item to control whether to automatically adjust the thread pool size.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11320

tikv: add new config for auto adjust read pool thread count

---

explain-subqueries.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11208

doc: add naaj doc

---

system-variables.md

Documenting the sysvar added in [this PR](https://github.com/pingcap/tidb/pull/36146)
https://github.com/pingcap/tidb/pull/36146

Document require_primary_key system variable

---

faq/tidb-faq.md
tidb-architecture.md
user-account-management.md

- Refine and update descriptions in `tidb-faq.md`, such as wording, missing info or links
- Update two related documents
> Note: The changes in this PR don't affect technical correctness.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11433

*: refine TiDB product basic FAQs descriptions

---

_index.md

Added reference in TiDB learning path.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/11491

learning path: add reference in TiDB learning path

---

system-variables.md

As stated in the title, add missing documents for 2 sys vars. I also would like to add some more descriptions for `ssl_cert`, `ssl_key` and `ssl_ca`.

system-variables: add documents for `error_count` and `max_connections`

---

_index.md

learning path: fix a format erorr

---

tidb-troubleshooting-map.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8564

clarify the meaning of small transaction for TTL

---

config-templates/complex-multi-instance.yaml

Fix the data dir of monitored instance from "/tidb-data-monitored-9100" to "/tidb-data/monitored-9100"
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/3279

Fix the data dir of monitored instance

---

system-variables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11328 https://github.com/pingcap/docs-cn/pull/11375 https://github.com/pingcap/docs-cn/pull/11431 https://github.com/pingcap/docs-cn/pull/11505

sysvar: add 2 sysvars

---

system-variables.md

system-variable: add document for tx_isolation_one_shot

---

best-practices/pd-scheduling-best-practices.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11282

Add a link to explain how to change weight

---

system-variables.md

sysvar: fix wrong variables names

sysvar: fix wrong variables names

---

system-variables.md

sysvar: add 1 var
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11269

sysvar: add 1 var

---

non-transactional-dml.md
system-variables.md

Signed-off-by: ekexium <eke@fastmail.com>

add the variables of batch-dml

---

develop/dev-guide-connect-to-tidb.md

There are two official commandline clients for MySQL, both opensource and released by the Oracle MySQL team.
1. MySQL Client (`mysql`), which is part of the MySQL Server code base, but can be installed separately via `yum install mysql` on most YUM based linux distributions. With [the offical YUM repo](https://dev.mysql.com/doc/refman/8.0/en/linux-installation-yum-repo.html) this becomes `yum install mysql-community-client`. This client is written in C and has existed for as long as MySQL does.
2. MySQL Shell (`mysqlsh`), which is a separate code base and can be installed separately. This is a newer tool and supports SQL, but also JS and Python. It has a more modern code base and is more extendable than the 'old' client.
It looks like these two were mixed up into a single section of the …

Correct MySQL Shell/Client section

---

statistics.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11717

Add white space after ANALYZE TABLE

---

TOC.md
releases/release-6.1.2.md
releases/release-notes.md
releases/release-timeline.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11678

add v6.1.2 release notes

---

develop/dev-guide-paginate-results.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11341

develop: fix paging sql with multiple columns for cluster index table

---

tidb-configuration-file.md
tidb-limitations.md

Growing the `txn-entry-size-limit` to the maximum size needs adjustments in other settings as well. 
When `txn-entry-size-limit` is too small:
```
sql> INSERT INTO t1(t) VALUES(REPEAT('x',6*1024*1024));
ERROR: 8025 (HY000): entry too large, the max entry size is 6291456, the size of data is 6291489
```
When `raft-entry-max-size` is too small:
```
sql> INSERT INTO t1(t) VALUES(REPEAT('x',15*1024*1024));
ERROR: 1105 (HY000): message:"raft entry is too large, region 2, entry size 15728790" raft_entry_too_large:<region_id:2 entry_size:15728790 > 
```
When `max_allowed_packet` is too small:
```
sql> INSERT INTO t1(t) VALUES(REPEAT('x',100*1024*1024));
ERROR: 1301 (HY000): Result of repeat() was larger than max_allowed_packet (67108864) - truncated
```
When `txn-total-size-limit` is too small: …

tidb-configuration-file: add more notes to txn-entry-size-limit

---

dm/dm-webui-guide.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/11163

dm: update prerequisites for webui

---

experimental-features.md
tidb-configuration-file.md

Since TiDB v4.0.0, LOCK TABLE is introduced as an experimental feature and you can use the `LOCK TABLE` or `UNLOCK TABLE` when setting the `enable-table-lock` to `true`.
Fix https://github.com/pingcap/docs/issues/6831
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11808

add description for enable-table-lock

---

dm/task-configuration-file-full.md
migrate-aurora-to-tidb.md
migrate-large-mysql-shards-to-tidb.md
migrate-large-mysql-to-tidb.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11790

dm: add description about mysql-instance.meta

---

command-line-flags-for-tidb-configuration.md

Add missing flags for `tidb-server`.
```
$ diff <(path/to/tidb/bin/tidb-server -h 2>&1 | awk '/^  -/ { print $1 }' | sort) <(awk '/^##/ { print $2 }' command-line-flags-for-tidb-configuration.md | cut -d\` -f2 | sed -e 's/--/-/g' | sort)
3d2
< -alsologtostderr
9d7
< -help
11,12d8
< -initialize-insecure
< -initialize-secure
15,16d10
< -log_backtrace_at
< -log_dir
19d12
< -logtostderr
35d27
< -stderrthreshold
37d28
< -temp-dir
39d29
< -v
41d30
< -vmodule
```
- https://github.com/pingcap/tidb/pull/28482
- https://github.com/pingcap/tidb/pull/28487
- https://github.com/pingcap/tidb/pull/36088

command-line-flags-for-tidb-configuration: Add missing flags

---

character-set-and-collation.md
constraints.md
log-redaction.md
system-variables.md
transaction-overview.md

Signed-off-by: ekexium <eke@fastmail.com>
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11690

complement errors relating to lazy uniqueness check

---

faq/high-reliability-faq.md
tidb-configuration-file.md

collation: remove a redundant sentence
Close https://github.com/pingcap/docs/issues/7078 https://github.com/pingcap/docs/issues/6539

collation: remove a redundant sentence

---

keywords.md
security-compatibility-with-mysql.md
system-variables.md
tidb-configuration-file.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11824

Add description about tidb_auth_token authentication

---

data-type-string.md

- Add remark about default row/column sizes for types that are over the default 6 MiB.
- Correct the text for `TEXT(M)`
From [the mysql docs on string data types](https://dev.mysql.com/doc/refman/8.0/en/string-type-syntax.html):
> An optional length M can be given for this type. If this is done, MySQL creates the column as the smallest TEXT type large enough to hold values M characters long. 
```
sql> CREATE TABLE t1 (id int primary key, c1 TEXT(60), c2 TEXT(70), c3 TEXT(70) CHARSET ASCII);
Query OK, 0 rows affected (0.1513 sec)
sql> SHOW CREATE TABLE t1\G
Table: t1
Create Table: CREATE TABLE `t1` (
`id` int(11) NOT NULL,
`c1` tinytext DEFAULT NULL,
`c2` text DEFAULT NULL,
`c3` tinytext CHARACTER SET ascii COLLATE ascii_bin …
```

data-type-string: Corrections

---

TOC.md
_index.md
br/backup-and-restore-faq.md
clinic/clinic-introduction.md
clinic/clinic-user-guide-for-tiup.md
clinic/quick-start-with-clinic.md
ecosystem-tool-user-case.md
ecosystem-tool-user-guide.md
faq/faq-overview.md
faq/manage-cluster-faq.md
faq/upgrade-faq.md
quick-start-with-tidb.md
telemetry.md
tidb-in-kubernetes.md
tidb-operator-overview.md
tiflash-620-upgrade-guide.md

k8s: in k8s -> on k8s

---

tikv-configuration-file.md

Signed-off-by: pingyu <yuping@pingcap.com>
- English translation of https://github.com/pingcap/docs-cn/pull/11959
See [rendered](https://github.com/pingyu/docs/blob/tikv-api-v2-fix-en/tikv-configuration-file.md#api-version-new-in-v610).
Please also note that some links to tikv.org is under developing, and will be finished in several days. …

tikv: Fix some words for TiKV API v2

---

clinic/clinic-data-instruction-for-tiup.md
clinic/clinic-introduction.md
clinic/clinic-user-guide-for-tiup.md
clinic/quick-start-with-clinic.md

update server name

---

tiflash/create-tiflash-replicas.md

Add some instructions about how to sync TiFlash replica faster.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/11405 https://github.com/pingcap/docs-cn/pull/12081

tiflash: Add instructions to improve replica sync performance

---

TOC.md
releases/release-5.3.4.md
releases/release-notes.md
releases/release-timeline.md

add 5.3.4 release notes

---

experimental-features.md
metadata-lock.md
sql-statements/sql-statement-commit.md
system-variables.md

Since TiDB v6.5.0, metadata lock is GA and enabled by default
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12002

enable metadata lock by default

---

configure-memory-usage.md
experimental-features.md
system-variables.md
tidb-configuration-file.md
troubleshoot-tidb-oom.md

Add docs for global memory control GA
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12085

Add docs for global memory control GA

---

sql-statements/sql-statement-explain.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12102

sql: update doc for json format explain

---

.github/pull_request_template.md

chore: add v6.6 checkbox in pr template
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12238

chore: add v6.6 checkbox in pr template

---

sql-statements/sql-statement-create-user.md

sql: fix statement bug

---

system-variables.md

Signed-off-by: you06 <you1474600@gmail.com>
ref: pingcap/tidb#39361
Document the experimental feature `tidb_store_batch_size`.
- This PR is translated from: pingcap/docs-cn#12252

 add doc for experimental variable tidb_store_batch_size

---

br/br-batch-create-table.md

correct description of br batch create table

br: incorrect description of batch create table

---

TOC-tidb-cloud.md
develop/dev-guide-choose-driver-or-orm.md
develop/dev-guide-third-party-tools-compatibility.md

Fix CustomContent format in note

---

sql-statements/sql-statement-alter-table-compact.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10470

Add observability for ALTER TABLE ... COMPACT

---

configure-placement-rules.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12484

placement rules: add a role "voter"

---

functions-and-operators/set-operators.md
sql-statements/sql-statement-admin-checksum-table.md
sql-statements/sql-statement-create-role.md
sql-statements/sql-statement-drop-role.md
sql-statements/sql-statement-grant-role.md
sql-statements/sql-statement-revoke-role.md
sql-statements/sql-statement-set-default-role.md
sql-statements/sql-statement-table.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12268

Update the command and output in SQL statements

---

tidb-troubleshooting-map.md

troubleshooting: add a few links to map
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12543

troubleshooting: add a few links to map

---

best-practices/java-app-best-practices.md
develop/dev-guide-choose-driver-or-orm.md
develop/dev-guide-connection-parameters.md
faq/tidb-faq.md
tispark-overview.md

- Update URLs to use Connector/J 8.0 docs instead of 5.1
- Correct naming to "MySQL Connector/J" in a few places.
- Update the status of the EOF bug ( see https://bugs.mysql.com/bug.php?id=106252 )

Update JDBC information

---

hybrid-deployment-topology.md
tikv-configuration-file.md
tune-tikv-memory-performance.md

- Remove `storage.block-cache.shared` in v6.6
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12241

*: always enable block cache

---

metadata-lock.md

Add link to `CHANGE COLUMN` from `Metadata Lock`. 
Because while investigating https://github.com/pingcap/tidb/issues/40838 , I've found the link to `CHANGE COLUMN` from `Metadata Lock` is missing. 

ALTER TABLE .. CHANGE COLUMS is affected by metadata lock

---

system-variables.md

Correct the wrong sysvar default value (tidb_row_format_version = 1) from 1 to 2.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12898

sysvar: correct a wrong sysvar default value

---

command-line-flags-for-tidb-configuration.md
tidb-configuration-file.md

Add the description about --initialize-sql-file option and the related configuration, which is introduced in v6.6.0.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12681

Add description about --initialize-sql-file option

---

sync-diff-inspector/sync-diff-inspector-overview.md

Add a description for the new parameter `skip-non-existing-table`, which is used to skip validation for tables that do not exist upstream or downstream.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12776

sync-diff: add description for the new parameter skip-non-existing-table

---

identify-slow-queries.md
information-schema/information-schema-slow-query.md

Translate from https://github.com/pingcap/docs-cn/pull/12638
Starting from TiDB v6.6.0, the Warnings field is added in slow query log
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12638

slow-query: add Warnings field to slow log and the slow query table

---

optimizer-hints.md

add the doc for (no_)keep_order hint for v6.6 release
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12630

docc: add the doc for (no_)keep_order hint

---

tiflash/tiflash-configuration.md

Starting from v6.6, the default value of `max_memory_usage_for_all_queries` changes to 0.8.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12663

tiflash: update config description of max_memory_usage_for_all_queries

---

tikv-configuration-file.md

There are two default values for `lock-cf-compact-interval` and line 793 `+ Default value: "256MB"` should be removed.
This PR applies to v3.0 and later versions

lock-cf-compact-interval: fix the default value to 10m

---

tidb-lightning/tidb-lightning-configuration.md

Introduced a new parameter `header-schema-match`.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/12963

lightning: introduce a new parameter `header-schema-match`

---

faq/backup-and-restore-faq.md

Add a section describing how to quickly recovering data in the case of misoperations.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12635

add backup faq for flashback

---

system-variables.md

add a sys var: `tidb_ddl_distribute_reorg`
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/12885 https://github.com/pingcap/docs-cn/pull/13033

ddl: add tidb_ddl_distribute_reorg to sys var

---

system-variables.md

This is an addition to https://github.com/pingcap/docs/pull/12069
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13032

stmtsummary: add system vars description

---

tikv-configuration-file.md

Remove the note "TiDB Dashboard will have a display error" from the description of `grpc-compression-type`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13034

tikv config: remove note of grpc-compression-type

---

dm/maintain-dm-using-tiup.md
quick-start-with-tidb.md
ticdc/deploy-ticdc.md
tiflash-620-upgrade-guide.md
tiup/tiup-cluster.md
tiup/tiup-component-cluster-upgrade.md
tiup/tiup-component-dm-upgrade.md
upgrade-tidb-using-tiup.md

It's not clear whether `v` is included in the `<version>` placeholder. This PR adds examples when describing `tiup ... <version>` and uses `<version>` as placeholder to keep it consistent with tiup cli.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12999

tiup: add examples for tiup version placehoder

---

TOC.md
alert-rules.md
clinic/clinic-introduction.md
clinic/clinic-user-guide-for-tiup.md
dashboard/dashboard-faq.md
dm/dm-error-handling.md
error-codes.md
faq/migration-tidb-faq.md
non-transactional-dml.md
pessimistic-transaction.md
sql-plan-management.md
support.md
tidb-binlog/monitor-tidb-binlog-cluster.md
tidb-cloud/limitations-and-quotas.md
tidb-cloud/tidb-cloud-poc.md
tiflash/tiflash-alert-rules.md
tiflash/troubleshoot-tiflash.md
troubleshoot-data-inconsistency-errors.md
two-data-centers-in-one-city-deployment.md

Add info for getting support.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/12897

*: update info on support resources

---

sql-statements/sql-statement-admin-show-ddl.md

close https://github.com/pingcap/docs/issues/9698
Add syntax 'ADMIN SHOW DDL JOB QUERIES LIMIT m OFFSET n', which can retrieve DDL commands' content within a certain range (n+1, n+m).
A new syntax is added.
Add description for syntax 'ADMIN SHOW DDL JOB QUERIES LIMIT m OFFSET n', which can retrieve DDL commands' content within a certain range (n+1, n+m).
I added a new syntax 'ADMIN SHOW DDL JOB QUERIES LIMIT m OFFSET n', and the details can refer to:
https://github.com/pingcap/tidb/pull/36285
https://github.com/pingcap/tidb/pull/36480
By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED …

Add new syntax 'ADMIN SHOW DDL JOB QUERIES LIMIT m OFFSET n'

---

br/backup-and-restore-overview.md

Update BR compatibility info for v6.6.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13031

br: change the compatibility table

---

faq/sql-faq.md
privilege-management.md

Add missing dynamic privileges and update the version that supports optimistic locking to v3.0.8.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13050, https://github.com/pingcap/docs-cn/pull/12492

sql: add missing dynamic privileges and update optm lock version

---

tidb-lightning/tidb-lightning-physical-import-mode.md

Add a limitation that users do not perform read/writer operations during data migration.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/13071

lightning: add a limitation during data migration

---

system-variables.md

Starting from TiDB v6.3, the index acceleration feature is not fully compatible with adding unique indexes.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/12673

index acceleration: not compatible with unique index

---

TOC.md
releases/release-6.1.5.md
releases/release-notes.md
releases/release-timeline.md

Add release notes for v6.1.5.
- [x v6.6 (TiDB 6.6 versions)
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13130

add v6.1.5 release notes

---

explain-mpp.md

Replace the version`v6.6.6` with `v6.6.0` to follow-up https://github.com/pingcap/docs/pull/12387 .
The Chinese version one looks correct https://github.com/pingcap/docs-cn/pull/12921

Replace `v6.6.6` with `v6.6.0`

---

faq/sql-faq.md

Add the missing `DELAYED` priority
```
sql> SELECT HIGH_PRIORITY 1;
+---+
| 1 |
+---+
| 1 |
+---+
1 row in set (0.0014 sec)
sql> SELECT LOW_PRIORITY 1;
+---+
| 1 |
+---+
| 1 |
+---+
1 row in set (0.0004 sec)
sql> SELECT DELAYED 1;
+---+
| 1 |
+---+
| 1 |
+---+
1 row in set (0.0004 sec)
```
see also: https://github.com/pingcap/tidb/blob/1e0956d5ba41182e603295e02ae8f767d62979e4/distsql/request_builder.go#L257-L267 

sql-faq: add missing DELAYED priority

---

tidb-lightning/tidb-lightning-logical-import-mode.md
tidb-lightning/tidb-lightning-overview.md
tidb-lightning/tidb-lightning-physical-import-mode-usage.md
tidb-lightning/tidb-lightning-physical-import-mode.md

Clarify the relationship between backends and import modes.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/10645

lightning: clarify backends and import modes

---

pd-control.md

Resolve #10970 
Updated the jq options for the `region check` command in the pd-control.md file.

Update jq usage on region check command

---

command-line-flags-for-tidb-configuration.md

`proxy-protocol-fallbackable` is introduced in TiDB v6.5.1
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13337

tidb: add --proxy-protocol-fallbackable

---

tikv-configuration-file.md

Enable log recycling by default.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13381

[TiKV] Enable log recycling by default.

---

sql-prepared-plan-cache.md
system-variables.md

Starting from v7.0.0, prepared plan cache supports subquery.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13228

planner: plan cache support subquery

---

system-variables.md

Add a new variable `tidb_enable_inl_join_inner_multi_pattern` to control whether the inner table of Index Join supports `Selection` or `Projection` operators.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13451

planner: add variable tidb_enable_inl_join_inner_multi_pattern

---

optimizer-hints.md
system-variables.md

add doc for more hints.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/13313

planner: add the doc for hint

---

tikv-configuration-file.md

Add a new configuration `raft-engine.prefill-for-recycle` in TiKV for supporting to make log recycling effective when starting in cold state.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13339

[TiKV] Introduce `raft-engine.prefill-for-recycle` configuration.

---

develop/dev-guide-use-stale-read.md

I fixed the typo where it should be "stale read" but was "steal read"

develop: fix typo for stale

---

alert-rules.md

This pull request adds link how to address TiKV_pending_task alert because it is not clear what to do now. Also it rewrites the statement so that it is clear that `apply worker` is noun. the current statement may cause misunderstanding that `apply` is verb.

Add link how to address TiKV_pending_task alert

---

tidb-cloud/monitor-prometheus-and-grafana-integration.md

Fix Grafana Json Link

---

tidb-cloud/serverless-tier-limitations.md

- [ x ] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs) that's required for repo owners to accept my contribution.
Add `max sleep seconds` limitation for serverless tidb
Serverless TiDB 6.6.0

add max sleep second limitation for serverless

---

privilege-management.md
sql-statements/sql-statement-calibrate-resource.md

as tittle
- https://github.com/pingcap/docs-cn/pull/13709  
- https://github.com/pingcap/docs-cn/pull/13714

sql-statement: calibrate resource support workload

---

releases/release-7.0.0.md

release notes: fix a version error

---

scale-tidb-using-tiup.md
ticdc/deploy-ticdc.md
tidb-cloud/migrate-from-op-tidb.md
tiup/tiup-component-cluster-check.md

The scale-out.yml example is inaccurate. This PR updates some examples:
- Modify the file name from `scale-out.yaml` to `scale-out.yml`
- Modify the deploy_dir from `/data/deploy/install/deploy/...` to `/tidb-deploy/...`
- Modify the data_dir from `/data/deploy/install/data/...` to `/tidb-data/...`
- Modify the log_dir from `/data/deploy/install/log/...` to `/tidb-deploy/.../log`
For details, see [tips for choosing the affected versions (in Chinese)](https://github.com/pingcap/docs-cn/blob/master/CONTRI …

tiup: fix the scale-out yaml example

---

system-variables.md

as tittle
- Other reference link(s):https://github.com/pingcap/docs/pull/13303

system-variables: update the default value of datadir

---

ddl-introduction.md

as title
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/13731

ddl: add admin pause/resume commands

---

basic-features.md
partitioned-table.md

Removed the warning that INTERVAL partitioning is experimental, effectively making it GA.

Make INTERVAL Partitioning GA

---

ticdc/ticdc-changefeed-config.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13763

v7.1: modify default value descriptions for enable-partition-separator 

---

ticdc/ticdc-faq.md

Fix an inconsistency issue in the TiCDC FAQ by updating the description from **if I set `enable-old-value` to `true`** to **if I set `safe-mode` to `true`**. The following content of this FAQ is focused on the `safe-mode` feature rather than `enable-old-value`.
```
TiCDC guarantees that all data is replicated at least once. When there is duplicate data in the downstream, write conflicts occur. To avoid this problem, TiCDC converts `INSERT` and `UPDATE` statements into `REPLACE INTO` statements. This behavior is controlled by the `safe-mode` parameter.
```
By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, …

ticdc: fix the description of safe-mode

---

dm/maintain-dm-using-tiup.md
maintain-tidb-using-tiup.md
tiup/tiup-cluster.md
tiup/tiup-component-cluster-patch.md
tiup/tiup-component-cluster-reload.md
tiup/tiup-component-cluster-scale-in.md
tiup/tiup-component-cluster-upgrade.md

The default value of transfer-timeout is 600.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13808

tiup: update the default value of transfer-timeout from 300 to 600

---

sql-non-prepared-plan-cache.md
sql-prepared-plan-cache.md
system-variables.md

In v7.1.0, TiDB introduces a new system variable tidb_plan_cache_max_plan_size.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13807

planner: add doc for the new variable tidb_plan_cache_max_plan_size

---

releases/release-6.5.2.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/13819

add a note on max_prepared_stmt_count for 6.5.2

---

tidb-lightning/tidb-lightning-distributed-import.md

Update the suggested handling method for the data inaccuracy error
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13823
- Other reference link(s): https://github.com/pingcap/docs/pull/13338

Update Lightning import error handling

---

auto-increment.md

This pull request describes `auto_id_cache = 0` behavior. That works as default cache size `30000` but not documented.
- Other reference link(s): Fix #12876

Describe `auto_id_cache = 0` behavior

---

releases/release-7.1.0.md
tidb-configuration-file.md

Add configuration `performance.force-init-stats`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13840
- Other reference link(s): https://github.com/pingcap/tidb/pull/43381

add configuration performance.force-init-stats

---

ticdc/ticdc-changefeed-config.md

This PR adds a suggestion for users to set enable-partition-separator to true
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13762

v7.0: revert default value changes for enable-partition-separator

---

develop/dev-guide-use-stale-read.md

Add a note about the precision of NOW when using stale read.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13738

add notice for now usage in stale read

---

statistics.md

Add description about `force-init-stats` in Introduction to Statistics.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13948
- Other reference link(s): https://github.com/pingcap/tidb/pull/43381

add description about force-init-stats in introduction to statistics

---

data-type-date-and-time.md

Fix the precision of DATETIME and TIMESTAMP values from milliseconds to microseconds.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13969

update precision of DATETIME and TIMESTAMP values

---

sql-non-prepared-plan-cache.md
system-variables.md

non-prepared plan cache is disabled by default in v7.1 (revert https://github.com/pingcap/docs/pull/13284)
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13947
- Other reference link(s): https://github.com/pingcap/docs/pull/13284

disable non-prep plan cache by default

---

hardware-and-software-requirements.md
pd-control.md
pd-recover.md
tidb-control.md

Starting from v7.0.0, the Golang version required for compiling and running TiDB is **1.20 or later**.
This PR updates the Golang version from 1.18.5 to 1.20 and applies to v7.0 and master.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14029
- Other reference link(s): https://github.com/pingcap/tidb/pull/41604

update Golang version to 1.20

---

basic-features.md
security-compatibility-with-mysql.md
system-variables.md

Add some basic description about the LDAP authentication feature on 7.1.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13899

auth, variables: add description about ldap authentication

---

predicate-push-down.md

Fix doc wrong related with `substring` which can be pushed down now

---

best-practices/java-app-best-practices.md
develop/dev-guide-connect-to-tidb.md
dm/dm-glossary.md
tidb-configuration-file.md

The old internals manual has been replaced with a generic redirect. This replaces the links with new links in the new source code documentation of MySQL

Fix pages linking to the old MySQL Internals Manual

---

tidb-cloud/tidb-cloud-release-notes.md

add release notes for 20230530

cloud: add release notes for 20230530

---

basic-features.md
ddl-introduction.md
releases/release-7.1.0.md
smooth-upgrade-tidb.md

Reverts pingcap/docs#13294
Remove `ADMIN PAUSE DDL JOBS job_id [, job_id]` and `ADMIN RESUME DDL JOBS job_id [, job_id]` in TiDB v7.1.0
Translate from https://github.com/pingcap/docs-cn/pull/14078

Revert "ddl: add admin pause/resume commands"

---

tidb-cloud/data-service-manage-github-connection.md

Added a step to refresh the UI

cloud: update  Data App update import steps

---

ticdc/ticdc-changefeed-config.md

TiDB v7.1.0 introduces only-output-updated-columns. This PR removes only-output-updated-columns from v7.0 and earlier versions.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14174

ticdc: remove only-output-updated-columns from v7.0 and earlier versions

---

basic-sql-operations.md

This PR add the link of TiDB Playground to one more document that is not included in https://github.com/pingcap/docs/pull/13744
- Other reference link(s): https://github.com/pingcap/docs/pull/13744

Add TiDB Playground link to try SQL on cloud

---

temp.md
tiflash/use-tiflash-mpp-mode.md

Add a known issue for TiFlash mpp.
> **Due to the file structure changes in v6.1, I'll cherry-pick to v5.3~v5.0 after I resolve conflicts in v5.4 cp PR.**
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14086

Add a known issue for TiFlash mpp.

---

tidb-cloud/tidb-cloud-release-notes.md

Update Cloud release notes, add General changes for June 6, 2023 and June 5, 2023

cloud release notes: add General changes

---

tidb-cloud/migrate-sql-shards.md

cloud dm: remove inaccurate description

---

develop/dev-guide-timeouts-in-tidb.md
system-variables.md
temp.md

我们已经修改了 max_execution_time 的作用范围，也在文档中做相应的修改。
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14282 https://github.com/pingcap/tidb/pull/38671

Change the description for max_execution_time.

---

system-variables.md

TiDB v7.2.0 changes the default value of `tidb_remove_orderby_in_subquery` from `OFF` to `ON`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14045
- Other reference link(s): https://github.com/pingcap/tidb/issues/44163

system variable: change default value of tidb_remove_orderby_in_subquery from off to on

---

br/backup-and-restore-storages.md

support access blob by [SAS (shared access signatures)](https://learn.microsoft.com/en-us/rest/api/storageservices/delegate-access-with-shared-access-signature).
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14234

br: support access by azure sas token

---

tidb-cloud/explore-data-with-chat2query.md

TiDB Cloud no longer imports a built-in sample dataset upon creation.

cloud: remove the built-in sample dataset

---

constraints.md
system-variables.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/14320
- Other reference link(s): https://github.com/pingcap/tidb/issues/41711

sql: add switch for check constraint

---

system-variables.md

Align with https://github.com/pingcap/docs-cn/pull/14318
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14318

system variable: add the description for mpp cte shared scan

---

tikv-configuration-file.md

rocksdb.*cf: supply descriptions on `ttl` and `periodic-compaction-seconds`.

---

system-variables.md

link: pingcap/tidb#7275
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14328

add runtime filter session variable

---

scripts/release_notes_update_pr_author_info_add_dup.py

chore for release notes table script: fix two matching issues for repo name and PR number

---

ticdc/ticdc-changefeed-config.md

add kafka oauth configurations
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14198

ticdc:  add kafka oauth configurations

---

tidb-control.md

Include warning messages to notify customers.  We don't recommend to use tidb-ctl in application design. 
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/14361

include warning in tidb control

---

sql-statements/sql-statement-show-indexes.md

The `SHOW INDEX` statement is compatible with MySQL starting from v7.1.0
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14273

sql-statements: update the compability comment for SHOW INDEX

---

TOC.md
releases/release-6.1.7.md
releases/release-7.2.0.md
releases/release-notes.md
releases/release-timeline.md

release: add v6.1.7 release notes
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14404

release: add v6.1.7 release notes

---

system-variables.md

add a system variable tidb_lock_unchanged_keys

system variable: add tidb_lock_unchanged_keys

---

dashboard/dashboard-ops-reverse-proxy.md
dashboard/dashboard-session-sso.md
develop/dev-guide-unstable-result-set.md
dm/feature-online-ddl.md
enable-tls-between-components.md
quick-start-with-htap.md
schedule-replicas-by-topology-labels.md
sql-plan-management.md
statistics.md
ticdc/deploy-ticdc.md
ticdc/integrate-confluent-using-ticdc.md
tidb-cloud/integrate-tidbcloud-with-dbt.md
tidb-cloud/integrate-tidbcloud-with-zapier.md
tidb-cloud/terraform-get-tidbcloud-provider.md
tidb-cloud/terraform-use-cluster-resource.md
tiflash/create-tiflash-replicas.md
tiflash/troubleshoot-tiflash.md
tiup/tiup-bench.md

fix: correct whitespace usage
The code blocks in the PDF are displayed incorrectly due to wrong whitespace usage:
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14665

fix: correct whitespace usage

---

sql-statements/sql-statement-explain-analyze.md
tidb-resource-control.md

RU was included in `explain analyze` since v7.0.0. This information is missing in user doc.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14519

resource_control: RU info in explain analyze

---

temp.md
ticdc/ticdc-sink-to-kafka.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14657

cdc add docs about handle-key only

---

sql-statements/sql-statement-analyze-table.md

This pull request fixes typo `AnlyzeOption` that should be `AnalyzeOption`

Fix typo `AnlyzeOption` should be `AnalyzeOption`

---

tidb-lightning/tidb-lightning-configuration.md

- add enable-diagnose-logs param
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/14599

lightning: add enable-diagnose-logs param

---

optimizer-hints.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14664

planner: add document about some new introduced hints

---

tikv-configuration-file.md

TiDB v7.3 changes the default value of compaction-guard-min-output-file-size from 1MB to 8MB.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14641 

v7.3: update compaction-guard-min-output-file-size

---

tikv-configuration-file.md

https://github.com/tikv/tikv/pull/15055
https://github.com/tikv/tikv/pull/15115
https://github.com/tikv/tikv/pull/15174

update default values for RocksDB config

---

tidb-lightning/tidb-lightning-configuration.md
tidb-lightning/tidb-lightning-error-resolution.md
tidb-lightning/tidb-lightning-logical-import-mode-usage.md
tidb-lightning/tidb-lightning-physical-import-mode-usage.md

lightning: update docs for duplicate detection

---

statistics.md
system-variables.md
temp.md

Introduce the system variable `tidb_skip_missing_partition_stats`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14647
- Other reference link(s): https://github.com/pingcap/tidb/pull/41176

add system variable tidb_skip_missing_partition_stats

---

sql-plan-replayer.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14524

 sql-plan-replayer: add doc for historical stats integration into the plan replayer

---

temp.md
tidb-configuration-file.md
upgrade-tidb-using-tiup.md

增加关于在升级过程中，对于 server-version 配置参数的说明。
updates for TiDB in K8s is included in https://github.com/pingcap/docs-tidb-operator/pull/2431
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14569

Remove server version upgrade

---

tidb-lightning/tidb-lightning-physical-import-mode-usage.md

Delete record in conflict detection.
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/14811
- Other reference link(s):https://github.com/pingcap/docs/pull/14343

tidb-lightning: delete record option in conflict detection 

---

sql-statements/sql-statement-create-user.md

Improve the description of password policy management.
In TiDB v6.5, the password policy management mechanism for CREATE USER has been resolved. For detailed description, please see [TiDB Password Management](/password-management.md)
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14955

Improve the description of password policy management

---

CONTRIBUTING.md
best-practices/tidb-best-practices.md
dashboard/continuous-profiling.md
dashboard/dashboard-access.md
dashboard/dashboard-cluster-info.md
dashboard/dashboard-key-visualizer.md
dashboard/dashboard-ops-security.md
dashboard/dashboard-profiling.md
dashboard/dashboard-resource-manager.md
dashboard/dashboard-slow-query.md
dashboard/dashboard-statement-list.md
dashboard/top-sql.md
develop/dev-guide-playground-gitpod.md
develop/dev-guide-sample-application-java-spring-boot.md
dm/dm-daily-check.md
dm/migrate-data-using-dm.md
exporting-grafana-snapshots.md
quick-start-with-tidb.md
scale-tidb-using-tiup.md
tidb-binlog/monitor-tidb-binlog-cluster.md
tidb-cloud/config-s3-and-gcs-access.md
tidb-cloud/data-service-oas-with-nextjs.md
tidb-cloud/integrate-tidbcloud-with-airbyte.md
tidb-cloud/integrate-tidbcloud-with-dbt.md
tidb-cloud/monitor-datadog-integration.md
tidb-cloud/set-up-private-endpoint-connections-serverless.md
tidb-cloud/set-up-private-endpoint-connections.md
tidb-troubleshooting-map.md

Autolinks cause machine translation failure.

replace autolinks in release-7.1

---

dm/dm-binlog-event-filter.md
dm/dm-block-allow-table-lists.md
dm/dm-table-routing.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/14949

dm: update contents about wildcards

---

tidb-configuration-file.md

Added docs for the undocumented `deprecate-integer-display-length` option.
See also: https://github.com/pingcap/tidb/blob/302786ffb91400f30d0be90abaca852a73ffa41c/config/config.toml.example#L102-L104
Note that I also filed a bug that is related to this issue: https://github.com/pingcap/tidb/issues/46650
Also related: https://github.com/pingcap/tidb/pull/18775
For details, see [tips for choosing the affected versions](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md#guideline-for-choosing-the- …

Add deprecate-integer-display-length to TIDB Config

---

explain-index-merge.md

Change IndexRangeScan_13 to IndexRangeScan_5
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/15060

sql: fix a typo

---

TOC.md
releases/release-6.5.4.md
releases/release-6.5.5.md
releases/release-notes.md
releases/release-timeline.md

Add release notes for v6.5.5
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/15040

add release notes for v6.5.5

---

functions-and-operators/tidb-functions.md

Add documentation for the new `TIDB_PARSE_TSO_LOGICAL()` function.
* https://github.com/pingcap/docs/pull/14630
* https://github.com/pingcap/tidb/pull/46452
* https://github.com/pingcap/tidb/issues/46451

Add TIDB_PARSE_TSO_LOGICAL()

---

explain-joins.md

Keep the description of TableReader ID to be consistent with the output.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15103
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/11624

explain joins: fix the TableReader operator

---

TOC-tidb-cloud.md
TOC.md
information-schema/information-schema-check-constraints.md

This is for `information_schema.CHECK_CONSTRAINTS` as implemented in https://github.com/pingcap/tidb/pull/46428

Add docs for information_schema.CHECK_CONSTRAINTS

---

optimizer-hints.md
system-variables.md

sysvar: add system variable `tidb_opt_enable_hash_join`

---

sql-statements/sql-statement-explain-analyze.md

Added details on how RUs are calculated to the `EXPLAIN ANALZYE` documentation. See https://github.com/pingcap/tidb/issues/47269

Add RU calcuation to explain docs

---

best-practices/java-app-best-practices.md
develop/dev-guide-choose-driver-or-orm.md
develop/dev-guide-connect-to-tidb.md
develop/dev-guide-connection-parameters.md
develop/dev-guide-third-party-tools-compatibility.md
system-variables.md
tidb-cloud/secure-connections-to-serverless-clusters.md
tidb-cloud/tidb-cloud-tls-connect-to-dedicated.md
tispark-overview.md

Starting from Connector/J 8.1, the documentation website is changed from `https://dev.mysql.com/doc/connector-j/8.0/en` to `https://dev.mysql.com/doc/connector-j/en`. ref: https://github.com/mysql/mysql-connector-j/commit/9529cbc1f2089e8575824106dd10bbb7959e9860
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15301 …

Connector/J: fix broken links

---

releases/release-7.4.0.md

Add experimental note for global sort in release-7.4.0.md
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15359

global sort is experimental in v7.4

---

tidb-roadmap.md

update tidb roadmap

---

correlated-subquery-optimization.md
explain-subqueries.md

Fix the operator IDs to match the explain results
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/11624

fix the operator info

---

information-schema/information-schema.md

Fix https://github.com/pingcap/docs-cn/issues/15376
- Other reference link(s): https://github.com/pingcap/docs/pull/14780

information-schema.md: add `CHECK_CONSTRAINTS`

---

temp.md
ticdc/ticdc-changefeed-config.md
ticdc/ticdc-ddl.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15361

add ticdc sql mode config

---

dumpling-overview.md
ecosystem-tool-user-guide.md
mydumper-overview.md

Mydumper is deprecated in v7.5.0. This PR updates the note in v4.0-v7.4 to refeact that Mydumper is deprecated.

deprecate Mydumper

---

tidb-cloud/config-s3-and-gcs-access.md

cloud: add description about SSE-KMS

---

tidb-cloud/tidb-cloud-org-sso-authentication.md

cloud: support configuring SCIM

---

tidb-cloud/backup-and-restore.md
tidb-cloud/connect-via-standard-connection.md
tidb-cloud/migrate-from-mysql-using-aws-dms.md
tidb-cloud/tidb-cloud-tls-connect-to-dedicated.md

Some descriptions were inaccurate and did not align with the current state of TiDB Cloud products. These inaccuracies caused inconvenience to users. To address this issue, adjustments have been made to ensure that the document aligns as closely as possible with the current status of TiDB Cloud products.
- …

Modify the inaccuracies in the TLS description

---

character-set-and-collation.md
character-set-gbk.md

There's a limitation when LIKE 'prefix%' works with non-binary collation. This could cause performance regression.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15443

include limitation of LIKE when it works with non-binary collation

---

sql-statements/sql-statement-show-master-status.md

Add info about `SHOW BINARY LOG STATUS` being a new alias for `SHOW MASTER STATUS`.
Related to https://github.com/pingcap/tidb/issues/48673

statements: Add SHOW BINARY LOG STATUS info

---

tidb-binlog/bidirectional-replication-between-tidb-clusters.md
tidb-binlog/tidb-binlog-overview.md
tidb-binlog/upgrade-tidb-binlog.md

In v7.5.0, the data replication feature of TiDB Binlog is deprecated.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15342

tidb-binlog: deprecate binlog as a data sync tool

---

develop/dev-guide-sample-application-java-jdbc.md

Fix broken link to Connector/J docs

---

tidb-cloud/changefeed-sink-to-apache-kafka.md
tidb-cloud/tidb-cloud-billing-dm.md

cloud: refine the steps for configuring the changefeed target

---

tidb-cloud/data-service-manage-endpoint.md
tidb-cloud/data-service-postman-integration.md

dataservice: update batch endpoint request body format

---

sql-statements/sql-statement-select.md

add more explains and examples for `SELECT ... INTO OUTFILE` statements

---

tiflash/use-tiflash-mpp-mode.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15293

update task type for mpp

---

smooth-upgrade-tidb.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/15079

*: add more contents about supported versions and upgrade methods

---

TOC-tidb-cloud.md
TOC.md
sql-statements/sql-statement-flush-status.md
sql-statements/sql-statement-show-status.md
status-variables.md
system-variables.md

Update the docs for `SHOW STATUS`
This is mostly for https://github.com/pingcap/tidb/pull/48152 but it looks like we never properly documented the existing status variables.
https://github.com/pingcap/tidb/pull/48152

Update SHOW STATUS docs

---

system-variables.md
temp.md

require_secure_transport is forbidden to be set to on when SEM is enabled.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15582

update doc of `require_secure_transport`

---

sync-diff-inspector/route-diff.md

sync-diff-inspector: add descriptions and examples of table routers

---

temp.md
troubleshoot-tidb-oom.md

This PR updates the outdated OOM message in the docs.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15627

update the error message of OOM

---

foreign-key.md

Replaced the following ambiguous sentence:
The foreign key feature is usually used for providing integrity and consistency constraint checks for data in small or medium volumes

update the foreign key feature description

---

mysql-schema.md
tidb-distributed-execution-framework.md

DXF: add a limitation that adding indexes to columns of `TIMESTAMP` data type via the DXF is not supported

---

system-variables.md

This pull request explains `tidb_max_tiflash_threads` default value `-1` means in the `system-variables.md`. The current one just says `indicating that this system variable is invalid`. Here the invalid is not clear for me.
This commit is based on this line https://github.com/pingcap/docs/blame/e1a67bfe2d66860fa435c8bc851a38451bbd7772/dynamic-config.md#L350
For details, see [tips for choosing the affected versions](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md#guideline-for-choosing-the-af …

Explain `tidb_max_tiflash_threads` default value `-1` means

---

dashboard/dashboard-slow-query.md
information-schema/information-schema-slow-query.md
system-variables.md

It is not obvious why some SQL statements in the `SLOW_QUERY` table and on the TiDB Dashboard are limited and how to change this. This helps to improve that.

Add/clarify SQL length limits

---

statistics.md

Clarify configuration persistence of analyze statement. Add the way to check the config and give some examples of how to overwrite the config.

stats: clarify configuration persistence of analyze statement

---

sql-statements/sql-statement-explain.md

Explain formats are defined [here](https://github.com/pingcap/tidb/blob/master/pkg/types/explain_format.go) in TiDB. However the list of formats in the documentation was a lot shorter. Note that the `verbose` and `plan_cache` formats were already listed elsewhere in the docs.
This only adds `verbose` and `plan_cache`. Maybe others like `cost_trace` etc. should also be added?
For details, see [tips for choosing the affected versions](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md#guideline-f …

Add missing explain formats

---

develop/dev-guide-choose-driver-or-orm.md

MySQL Connector/J 8.0 has compatibility issues with TiDB v7.5. Earlier versions of TiDB are fine as they announce themselves as MySQL v5.7. Later versions are fine as they implement the `information_schema.KEYWORD` table.

Add info about compatibility issues with Connector/J 8.0 with TiDB v7.5

---

tidb-resource-control.md

Explicitly declare the scope of runway queries.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15904

explicitly declare the scope of runway queries

---

external-storage-uri.md
sql-statements/sql-statement-import-into.md
tidb-lightning/tidb-lightning-overview.md
tidb-lightning/tidb-lightning-physical-import-mode.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/15881

Removed unsupported Azure Blob storage via import into

---

functions-and-operators/string-functions.md
temp.md

Fix https://github.com/pingcap/docs/issues/15418
This PR adds instructions for the ASCII() function.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15481

 string-functions: add instructions for using ASCII()

---

dynamic-config.md
tikv-configuration-file.md

tikv: document periodic full compaction.

---

TOC-tidb-cloud.md
TOC.md
information-schema/information-schema-keywords.md
information-schema/information-schema.md
keywords.md

Add documentation related to https://github.com/pingcap/tidb/pull/48807

Add docs for the I_S keyword table

---

tikv-configuration-file.md

`enable-forwarding` belongs to `pd` but not `log.file`
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16102
- Other reference link(s): https://github.com/tikv/tikv/blob/7f708a1c5a4188c67e18ef082099928881e587ed/components/pd_client/src/config.rs#L40

move tikv configure item `pd.enable-forwarding` to correct place

---

tidb-cloud/connect-via-standard-connection-serverless.md

add disable public endpoint

---

TOC-tidb-cloud.md
tidb-cloud/api-overview.md
tidb-cloud/tidb-cloud-release-notes.md

use IAM instead of api key for api references

cloud: small fix for iam and msp

---

TOC.md
error-codes.md
keywords.md
sql-statements/sql-statement-admin-bdr-role.md
statement-summary-tables.md
ticdc/ticdc-bidirectional-replication.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/15865

Update bdr mode && add description related bdr sql

---

system-variables.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/15626

*: add a new system variable `tidb_enable_global_index`

---

tidb-cloud/data-service-get-started.md

Fix https://github.com/pingcap/docs/issues/15743

Update data-service-get-started.md 

---

br/br-pitr-manual.md

fix #15438 
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15438

pitr: update limitation of first time restore

---

character-set-and-collation.md
character-set-gbk.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15814
- Other reference link(s): https://github.com/pingcap/tidb/issues/48181

*: remove the restriction for building range scan for `LIKE` on new collation columns

---

develop/dev-guide-gui-navicat.md

fix typo
- Other reference link(s): https://github.com/pingcap/docs/pull/15347

develop: Update dev-guide-gui-navicat.md

---

br/br-snapshot-guide.md
releases/release-7.6.0.md

Remove the ` --tikv-max-restore-concurrency` parameter from v7.6.0.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16353 and https://github.com/pingcap/docs-cn/pull/16348

br: remove --tikv-max-restore-concurrency

---

functions-and-operators/string-functions.md

Fix https://github.com/pingcap/docs/issues/15491
This PR adds instructions for the LEFT() and LENGTH function. (one of the [doc dash issues](https://github.com/orgs/pingcap/projects/51/views/3?pane=issue&itemId=45777998))

string-functions: add instrunctions for LEFT() and LENGTH()

---

character-set-and-collation.md

Add instructions about the connection collation, which is decided by the client. It may cause behavior change between TiDB v7.3 and v7.4 after TiDB supports `utf8mb4_0900_ai_ci`.

add instructions about connection collation

---

migrate-from-tidb-to-mysql.md

I was reading the guide to migrate from TiDB to MySQL.
The guide advised to disable the GC before Dumpling is run.
However, I read in the Dumpling overview that this is now only necessary in certain conditions in the latest TiDB version.
If this section was potentially not up to date with that, I thought it will be nicer to note on that. …

Note that GC Disabling is a must despite Dumpling's auto extend feature

---

functions-and-operators/string-functions.md
temp.md

Fix https://github.com/pingcap/docs-cn/issues/15950
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16112, https://github.com/pingcap/docs-cn/pull/16514

add detail desc for String Function SUBSTRING_INDEX () and TO_BASE64

---

sql-statements/sql-statement-analyze-table.md

Follow up: https://github.com/pingcap/docs-cn/pull/15270
We should drop this syntax on the docs. This feature was removed by this PR: https://github.com/pingcap/tidb/pull/47544/files
Right now, if you try it on TiDB you will get
```console
mysql> analyze incremental table t index idx;
ERROR 1105 (HY000): the incremental analyze feature has already been removed in TiDB v7.5.0, so this will have no effect
```
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16647
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/15270

tidb: remove INCREMENTAL syntax of analyze table statement

---

develop/dev-guide-choose-driver-or-orm.md

Update the compatibility issue between Connector/J 8.0 and TiDB v7.5.
- Other reference link(s): https://github.com/pingcap/docs/pull/15794

update the compatibility issue between Connector/J 8.0 and TiDB v7.5

---

tidb-cloud/changefeed-sink-to-apache-kafka.md

changefeed: add constraint to Replication Factor and Partition Number

---

functions-and-operators/string-functions.md
temp.md

Update the introduction of UPPER and WEIGHT_STRING, fix https://github.com/pingcap/docs-cn/issues/15953
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16161
- Other reference link(s): https://docs.pingcap.com/zh/tidb/dev/string-functions

Update the introduction to UPPER() and WEIGHT_STRING()

---

functions-and-operators/string-functions.md
temp.md

Update the introduction of UCASE() and UNHEX(), fix https://github.com/pingcap/docs-cn/issues/15952
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16168
- Other reference link(s): https://docs.pingcap.com/zh/tidb/dev/string-functions

Update the introduction to UCASE() and UNHEX()

---

placement-rules-in-sql.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16670

Update placement-rules-in-sql.md to fix the incorrect part

---

enable-tls-between-clients-and-servers.md
tidb-configuration-file.md

Remove the support for tls 1.1 and 1.0 in v8.0.

remove support for tls 1.1 and 1.0

---

templates/template.tex

Update the LaTex template to implement automatic underscore wrapping in PDF table cells
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16173 https://github.com/pingcap/docs-cn/pull/16389

pdf: implement automatic underscore wrapping table cells

---

develop/dev-guide-sample-application-nodejs-prisma.md
develop/dev-guide-sample-application-ruby-rails.md
tidb-cloud/serverless-driver-kysely-example.md
tidb-cloud/serverless-driver-prisma-example.md

Update the `.env` code examples in `develop/` to keep the style consistent with other files.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16135

develop: update env file code examples

---

status-variables.md

When running TiDB with tiup playground, tiup cluster, tidb-operator or other situations where it runs with at least PD, TiKV and TiDB there are more status variables available than when running with only TiDB (`./bin/tidb-server`, unistore). This adds the missing variables.
See also https://github.com/pingcap/tidb/pull/22286
- This PR is …

status-variables: Add conditional status that are not available with unistore

---

smooth-upgrade-tidb.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16673

*: add a restriction for smooth-upgrade-tidb

---

CONTRIBUTING.md

- Removed the Docs Dash information
- Added the guideline for contributing to TiDB Cloud documentation
- Added the guideline for previewing EBNF diagrams

contribution guide: add EBNF preview and CustomContent instructions

---

ticdc/ticdc-alert-rules.md

Fix the alert rule of `tikv_cdc_min_resolved_ts_no_change_for_1m` and add ticdc_changefeed_failed alert rule.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16430

ticdc: add ticdc_changefeed_failed alert rule

---

error-codes.md

According to these TiDB server error messages, "PD server timeout" should be the correct error message.
S and T are both lowercase.
https://github.com/pingcap/tidb/blob/60aa838790e36e33b4105d22e191dfa827fe3663/errors.toml#L3101
https://github.com/pingcap/tidb/blob/60aa838790e36e33b4105d22e191dfa827fe3663/pkg/errno/errname.go#L1151
- This …

tidb: "PD server timeout" error message as lowercase

---

hardware-and-software-requirements.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16707

update hardware requirement for disaggregated tiflash

---

tiflash/tiflash-supported-pushdown-calculations.md

TiFlash v8.0 supports pushing down power 
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16502

update tiflash function pushdown list to add power

---

TOC-tidb-cloud.md
TOC.md
information-schema/information-schema-tidb-index-usage.md
information-schema/information-schema.md
sys-schema.md
system-variables.md
tidb-configuration-file.md

Add the document for index usage related system tables and databases.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16511

Add documents for `information_schema.tidb_index_usage` and `sys.schema_unused_index`.

---

system-variables.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/16813

Add div_precision_increment system variable doc

---

command-line-flags-for-tidb-configuration.md
tidb-configuration-file.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/16719

tidb: add `general-log-file` and `compression`

---

TOC.md
temp.md
ticdc/ticdc-changefeed-config.md
ticdc/ticdc-debezium.md
ticdc/ticdc-overview.md

Add a new doc "TiDB Debezium Protocol"
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16513
- Other reference link(s): https://github.com/pingcap/tiflow/pull/10197, https://github.com/pingcap/tiflow/pull/10307

Add TiCDC Debezium Protocol docs

---

system-variables.md

Related to https://github.com/pingcap/docs-cn/pull/16757
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16757

*: add `tidb_low_resolution_tso_update_interval`

---

optimizer-hints.md
sql-plan-management.md
system-variables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16770

planner: update SPM doc 

---

tikv-configuration-file.md

Update minimum value for initial-scan-rate-limit.
https://github.com/tikv/tikv/pull/16485

Update minimum value for initial-scan-rate-limit

---

configure-memory-usage.md
system-variables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15789

Spill of parallel aggregation in TiDB

---

system-variables.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/16830

sys-var: add `tidb_schema_cache_size`

---

tidb-configuration-file.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/16854

add doc for tikv-client.enable-replica-selector-v2

---

tiproxy/tiproxy-overview.md

Fix the issue that the images of TiProxy are not displayed:
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16870

TiProxy: update images

---

TOC.md
pd-microservices.md
temp.md
tiup/tiup-playground.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/15975
- Other reference link(s):https://github.com/pingcap/docs-tidb-operator/pull/2478

pd: support pd microservices

---

sql-plan-replayer.md

Added the recommendation to disable auto_analyze when using plan_replayer. Otherwise, analyze will overwrite the imported statistics information.
This resolves issue: #16363

docs: Disable auto_analyze for plan_replayer

---

tidb-lightning/tidb-lightning-configuration.md

Document the Lightning configuration `tikv-importer.logical-import-batch-size` and `-rows`.
- Other reference link(s): pingcap/tidb#46997

lightning: document logical-import-batch-{size,rows}

---

sql-statements/sql-statement-explain.md

Update sql-statement-explain.md - typo

---

choose-index.md

https://github.com/pingcap/docs-cn/pull/16855
https://github.com/pingcap/tidb/issues/51778

choose-index: update the docs for supporting more patterns for mv index

---

tidb-lightning/tidb-lightning-configuration.md
tidb-lightning/tidb-lightning-error-resolution.md
tidb-lightning/tidb-lightning-physical-import-mode-usage.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16896

Revise conflict data resolution enhancement during data import

---

TOC-tidb-cloud.md
tidb-cloud/notification-2024-04-11-dm-feature-maintenance.md
tidb-cloud/notification-2024-04-18-dm-feature-maintenance.md

Add TiDB Cloud Dedicated Data Migration maintenance notification

cloud: add TiDB Cloud Dedicated Data Migration maintenance notification

---

sql-prepared-plan-cache.md

One critical issue 51407 was found which could causes severe issue when prepared plan cache is enabled. The doc of prepared plan cache was update with the description and workarounds.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16878

include the description of critical issue 51407 in doc

---

pd-microservices.md
releases/release-8.0.0.md
tiup/tiup-playground.md

Remove PD playground from PD microservices
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16970

pdms: remove pd playground

---

character-set-and-collation.md

TiDB docs website docs.pingcap.com does not support "#" as a comment. It shows as SQL code, which confuses readers:

fix comment syntax for correct website rendering

---

functions-and-operators/string-functions.md

Add LPAD() example

---

tidb-cloud/serverless-driver-prisma-example.md

see https://github.com/pingcap/docs/pull/16774 for review details

cloud: support edge in prisma

---

br/backup-and-restore-storages.md

- Other reference link(s):https://github.com/pingcap/docs/pull/15165  https://github.com/pingcap/docs-cn/pull/15289

dumpling: add URI formats

---

sql-statements/sql-statement-show-collation.md

ebnf show collation

---

functions-and-operators/string-functions.md

Add example for OCT()

---

sql-statements/sql-statement-trace.md

Closes #16995
Also add `FORMAT='log'`

ebnf trace

---

sql-statements/sql-statement-show-plugins.md

ebnf show plugins

---

sql-statements/sql-statement-show-engines.md

ebnf show engines

---

temp.md
tikv-configuration-file.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17032

RocksDB: Add track-and-verify-wals-in-manifest desc

---

sql-statements/sql-statement-show-privileges.md

ebnf show privileges

---

functions-and-operators/string-functions.md

Add example for QUOTE()

---

data-type-default-values.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/17054

*: default value tiny update

---

sql-statements/sql-statement-show-tables.md

ebnf show tables

---

sql-statements/sql-statement-show-table-status.md

ebnf show table status

---

sql-statements/sql-statement-set-role.md

ebnf set role

---

sql-statements/sql-statement-set-variable.md
user-defined-variables.md

ebnf user variable

---

sql-statements/sql-statement-show-placement-for.md
sql-statements/sql-statement-show-placement-labels.md
sql-statements/sql-statement-show-placement.md

Correct SHOW PLACEMENT ebnf

---

functions-and-operators/string-functions.md

Add example for multi argument CHAR()

---

functions-and-operators/string-functions.md

Closes #16943
Closes #16944
Closes #16945

Add examples for regexp functions

---

tiproxy/tiproxy-configuration.md
tiproxy/tiproxy-overview.md
tiup/tiup-component-cluster-upgrade.md

- TiUP Cluster supports specifying versions of specific components:
```
Flags:
--alertmanager-version string        Fix the version of alertmanager and no longer follows the cluster version.
--blackbox-exporter-version string   Fix the version of blackbox-exporter and no longer follows the cluster version.
--cdc-version string                 Fix the version of cdc and no longer follows the cluster version.
--force                              Force upgrade without transferring PD leader
-h, --help                               help for upgrade
--ignore-config-check                Ignore the config check result
--ignore-version-check               Ignore checking if target version is bigger than current version
--node-exporter-version string       Fix the version of node-exporter and no …
```

tiup, tiproxy: add version flags to tiup cluster upgrade

---

functions-and-operators/string-functions.md

string-functions: update reference manual

---

sql-statements/sql-statement-show-profiles.md

ebnf show profiles

---

functions-and-operators/encryption-and-compression-functions.md

encryption-and-compression-functions: Update for MySQL 8.0

---

functions-and-operators/bit-functions-and-operators.md

Closes #16823 
This doesn't yet:

bit-functions-and-operators: Update reference manual links

---

sql-statements/sql-statement-update.md

ebnf update

---

sql-statements/sql-statement-show-table-regions.md

ebnf show table regions

---

sql-statements/sql-statement-show-table-next-rowid.md

ebnf show table next rowid

---

sql-statements/sql-statement-show-indexes.md

ebnf show indexes

---

functions-and-operators/string-functions.md

Add examples for ORD()

---

functions-and-operators/string-functions.md

Add MID() and NOT LIKE examples

---

functions-and-operators/control-flow-functions.md

control-flow-functions: Update reference manual links

---

functions-and-operators/numeric-functions-and-operators.md

numeric-functions-and-operators: Update reference manual

---

functions-and-operators/tidb-functions.md

Fix typo: retuns to returns at functions-and-operators/tidb-functions.md

Fix typo: retuns to returns at functions-and-operators/tidb-functions.md

---

enable-tls-between-components.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/17259

fix pd cert allowed cn description

---

hardware-and-software-requirements.md

Starting from v8.0.0, the Rust version for compiling and running TiDB is updated to nightly-2023-12-28.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17266

v8.0: update Rust version for compiling and running TiDB to nightly-2023-12-28

---

hardware-and-software-requirements.md

Starting from v7.6.0, the Rust version for compiling and running TiDB is updated to nightly-2023-12-10

v7.6: update Rust version for compiling and running TiDB to nightly-2023-12-10

---

information-schema/information-schema-ddl-jobs.md
sql-statements/sql-statement-admin-show-ddl.md

- Remove EBNF that's not part of `ADMIN SHOW DDL...`
- Add column descriptions for `ADMIN SHOW DDL` output
- Change `ADMIN SHOW DDL` output to vertical to make it more readable
- Add some common `JOB_TYPE`'s
- Add description for `CREATE_TIME` and `END_TIME` for the `ADMIN SHOW DDL JOBS` output.
- Add more links to the `See also`
- Fix EBNF to add `LIMIT n,m` in addition to `LIMIT n OFFSET m`. (Thanks @kennytm ) …

Extend ADMIN SHOW DDL docs

---

sql-statements/sql-statement-select.md

ebnf select

---

ticdc/ticdc-changefeed-config.md
ticdc/ticdc-open-api-v2.md

Add sink.open.output-old-value and sink.debezium.output-old-value to control whether to output the value before the row data changes.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17140

ticdc add output old value config

---

TOC.md
ticdc/ticdc-client-authentication.md
ticdc/ticdc-server-config.md

v8.1.0 supports TiCDC client authentication.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16692

Add client authentication support for ticdc

---

ticdc/ticdc-sink-to-cloud-storage.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/16731

ticdc: enhance storage sink uri config

---

tidb-cloud/import-sample-data.md

tidb cloud: refine importing sample table doc

---

TOC-tidb-cloud.md
TOC.md
basic-sql-operations.md
develop/dev-guide-create-table.md
develop/dev-guide-tidb-crud-sql.md
expression-syntax.md
mysql-compatibility.md
sql-statements/sql-statement-overview.md

Replace sqlgram links

---

functions-and-operators/tidb-functions.md
system-variables.md

1. The statement in the example had syntax errors
2. The variable docs didn't link to the function
- #13258 
- https://github.com/pingcap/tidb/pull/43479

tidb_row_checksum(): Update docs

---

faq/manage-cluster-faq.md

Describe in what condition TiDB & RawKV can be used together.
Since `v6.1.0` TiDB & RawKV can be used together if [API V2](https://docs.pingcap.com/tidb/stable/tikv-configuration-file#api-version-new-in-v610)  is enabled:
> Data is scoped according to different usage and API V2 supports co-existence of TiDB, Transactional KV, and RawKV applications in a single cluster.
But the relevant FAQ has not been changed accordingly yet. …

faq: Describe in what condition TiDB and RawKV can be used together

---

sql-statements/sql-statement-add-index.md
sql-statements/sql-statement-alter-table.md
sql-statements/sql-statement-create-index.md
sql-statements/sql-statement-create-table.md
sql-statements/sql-statement-show-indexes.md

sql: add a note about `FULLTEXT`

---

best-practices/grafana-monitor-best-practices.md

fix the default port of TiKV servers from 20181 to 20180
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17732

tikv: fix default port from 20181 to 20180

---

metadata-lock.md

fix error message of 8028 in metadata lock from "Error 8028: Information schema is changed" to "ERROR 8028 (HY000): public column a has changed"

fix error message of 8028 in metadata lock

---

extended-statistics.md

- Adds a warning and update wording, to align with the refined Chinese version https://github.com/pingcap/docs-cn/pull/17339
- The word "create" is more commonly used together with "extended statistics objects". So I also updated the word usage. …

Add warning and update wording for extended statistics

---

sql-statements/sql-statement-create-user.md

For reviewers: Preview ebnf on https://kennytm.github.io/website-docs/dist/
The `PASSWORD REQUIRE CURRENT DEFAULT` syntax is accepted to be able to parse the output of `SHOW CREATE USER`  from MySQL.  Especially as this is added by default by MySQL even if not specified when creating the user.
In MySQL `PASSWORD REQUIRE CURRENT` and `PASSWORD REQUIRE CURRENT OPTIONAL` are also accepted, but TiDB doesn't and the parser won't accept this.
As there is no `password_require_current` system variable in TiDB and no other options are accepted this syntax is meaningless / ignored.
See also: https://dev.mysql.com/doc/refman/8.4/en/password-management.html#password-reverification-policy
Note that the docs suggested that `CREATE USER 'foo3'@'%' IDENTIFIED BY 'abc' DEFAULT ROLE 'myrole'` should be …

Update EBNF for password options

---

releases/release-8.0.0.md
releases/release-8.1.0.md
system-variables.md
temp.md

Update inaccurate descriptions for the `tidb_schema_cache_size` system variable
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17847

Update descriptions for tidb_schema_cache_size

---

ticdc/ticdc-sink-to-pulsar.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17914

ticdc: adjust pulsar sink doc

---

sql-statements/sql-statement-admin-show-ddl.md

The EBNF didn't correctly indicate that `ADMIN SHOW DDL` is a valid statement

admin show ddl: Fix EBNF

---

extended-statistics.md
sql-statements/sql-statement-show-column-stats-usage.md
sql-statements/sql-statement-show-stats-histograms.md
statistics.md

When I was creating https://github.com/pingcap/docs-cn/pull/17827, I found some issues in the English version. So I created this PR to:
- Fix some typos and format
- Update wording and links

stats, sql: fix format and update wording

---

privilege-management.md
sql-statements/sql-statement-alter-user.md
user-account-management.md

- Add links where appropriate 
- Minor corrections

Add more links and corrections to user account management

---

tidb-cloud/serverless-limitations.md
time-to-live.md

add serverless ttl job interval desc

---

functions-and-operators/tidb-functions.md

Fix SQL statements and command output:
```
mysql> CREATE RESOURCE GROUP 'rg1' RU_PER_SEC = 1000;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 27 near "'rg1' RU_PER_SEC = 1000"
``` …

TiDB functions: update command output

---

temp.md
upgrade-tidb-using-tiup.md

Updates DDL descriptions when using smooth upgrade. This PR is a follow-up to https://github.com/pingcap/docs/pull/18332.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18239
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/18076

Update DDL descriptions in cluster upgrade

---

releases/release-7.5.3.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/18279

tidb: add a bugfix about issue https://github.com/pingcap/tidb/issues/54652

---

partitioned-table.md
sql-statements/sql-statement-create-table.md

partitioned tables: add some restrictions 

---

sql-statements/sql-statement-show-stats-buckets.md
system-variables.md

Signed-off-by: hi-rustin <rustin.liu@gmail.com>
1. I updated the description for the NDV field from the histogram bucket.
2. I corrected some variable's scopes.

statistics: mark NDV as deprecated and update variable scopes

---

best-practices-on-public-cloud.md

add Titan for TiDB Best Practices on Public Cloud

---

sql-statements/sql-statement-admin-bdr-role.md
ticdc/ticdc-bidirectional-replication.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/18345

make bdr ddl replicate GA en

---

best-practices/java-app-best-practices.md
develop/dev-guide-connection-parameters.md
dm/dm-worker-intro.md
system-variables.md

Add  a new variable `tidb_enable_lazy_cursor_fetch`.

variable: add document about lazy cursor fetch and its variable

---

partitioned-table.md
placement-rules-in-sql.md
sql-statements/sql-statement-add-column.md
sql-statements/sql-statement-add-index.md
sql-statements/sql-statement-create-index.md
sql-statements/sql-statement-create-table.md
system-variables.md

Update to #17979 for https://github.com/pingcap/tidb/pull/55264 addition that GLOBAL is explicitly required for Global Indexes, and will also be in the output of SHOW CREATE TABLE. Hopefully it will be included in 8.3
- Other reference link(s):https://github.com/pingcap/docs-cn/pull/18217

partition: add doc for global index, also with GLOBAL IndexOption/ColumnOption

---

system-variables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18226

system-variables: add tiflash_hashagg_preaggregation_mode

---

config-templates/simple-tiproxy.yaml
tiproxy/tiproxy-configuration.md
tiproxy/tiproxy-deployment-topology.md
tiproxy/tiproxy-grafana.md
tiproxy/tiproxy-load-balance.md
tiproxy/tiproxy-overview.md

1. Add virtual IP-related doc.
2. Remove Prometheus-related limitations in load balance. If Prometheus is unavailable, TiProxy will query TiDB directly.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18079

tiproxy: add vip configurations

---

br/br-pitr-manual.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18202

br: add issue for pitr usage

---

tidb-configuration-file.md

Add description of newly added config `batch-policy`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18231

tidb: add doc for `batch-policy` config

---

grafana-tikv-dashboard.md

Add a bunch of descriptions for restore based on metrics in `TiKV#tikv_details.dashboard.py`

br: add metrics description for snapshot restore and PITR

---

identify-expensive-queries.md
information-schema/information-schema-processlist.md
releases/release-8.2.0.md
temp.md

Update the columns in information_schema.processlist.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18164
- Other reference link(s): https://github.com/pingcap/tidb/issues/54486
This PR is for v8.3 and later releases. For v8.2, there is another PR https://github.com/pingcap/docs-cn/pull/18181.

doc: session_alias and rows_affected in information_schema.processlist

---

system-variables.md
temp.md
tidb-configuration-file.md

Refine slow log description to make it more clear and complete
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18127
- related issue: https://github.com/pingcap/tidb/issues/31466

Refine slow log description

---

system-variables.md

Modify the scope of system variable `tidb_gc_concurrency`.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18117

doc: concurrency of gc delete-range

---

temp.md
ticdc/ticdc-split-update-behavior.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18333

dev, v8.2, and v8.3: add v8.1.1 to ticdc split behavior for update events

---

temp.md
ticdc/ticdc-split-update-behavior.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18332

v8.1.1: update ticdc split behavior for update events

---

releases/release-8.0.0.md
temp.md
ticdc/ticdc-changefeed-config.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/16873

Add debezium disable schema doc for ticdc

---

temp.md
ticdc/ticdc-sink-to-mysql.md

Adds a note about data initialization.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18140

Add a note to ticdc-sink-to-mysql.md

---

generated-columns.md

- This PR is translated from:https://github.com/pingcap/docs/pull/18677

*: add a limitation about not supporting `NULLIF()` and supporting `CASE`

---

TOC-tidb-cloud.md
tidb-cloud/_index.md
tidb-cloud/backup-and-restore.md
tidb-cloud/configure-ip-access-list.md
tidb-cloud/configure-security-settings.md
tidb-cloud/connect-to-tidb-cluster.md
tidb-cloud/connect-via-sql-shell.md
tidb-cloud/connect-via-standard-connection-serverless.md
tidb-cloud/connect-via-standard-connection.md
tidb-cloud/create-tidb-cluster.md
tidb-cloud/import-with-mysql-cli.md
tidb-cloud/migrate-from-mysql-using-data-migration.md
tidb-cloud/migrate-from-op-tidb.md
tidb-cloud/set-up-private-endpoint-connections-on-google-cloud.md
tidb-cloud/set-up-private-endpoint-connections.md
tidb-cloud/set-up-vpc-peering-connections.md
tidb-cloud/tidb-cloud-tls-connect-to-dedicated.md

cloud: update connection page for TiDB Dedicated clusters

---

glossary.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/18536

glossary: fix descrption about isolation

---

ticdc/ticdc-sink-to-kafka.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/18545

ticdc: add a note about schema

---

tidb-cloud/vector-search-index.md

Reported in https://discord.com/channels/1083300679386406923/1285336626213421157/1285619831978197147 

Simple typo fix

---

TOC-tidb-cloud.md
TOC.md
information-schema/information-schema-check-constraints.md
information-schema/information-schema-tidb-check-constraints.md

Add description about `TIDB_CHECK_CONSTRAINTS`
- Other reference link(s): https://github.com/pingcap/tidb/pull/48313

tidb: add description about `TIDB_CHECK_CONSTRAINTS`

---

system-variables.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18693

system-variables: optimize the persist info

---

sql-statements/sql-statement-explain.md
temp.md

As the title says.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18727

sql-statement-explain: add explanation related to scalar subquery

---

tidb-cloud/config-s3-and-gcs-access.md

Optimize usage of External ID

---

basic-features.md
develop/dev-guide-transaction-restraints.md
tidb-configuration-file.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/18805

txn: fix the maximum value of a transaction from 10GB to 1 TiB

---

system-variables.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/18649

sysvars: add `tidb_shard_row_id_bits` and `tidb_pre_split_regions`

---

partitioned-table.md
placement-rules-in-sql.md
system-variables.md

Deprecate tidb_enable_table_partition, tidb_enable_list_partition and tidb_enable_global_index,
These were experimental flags and are no-longer needed,
Keeping them as always ON to avoid breaking existing usage.
All three requires explicit PARTITION BY, PARTITION BY LIST or GLOBAL IndexOption to be used, which should be enough.
- This PR …

Deprecated `tidb_enable_table_partition`, `tidb_enable_list_partition` and `tidb_enable_global_index`

---

system-variables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18557
- Other reference link(s): https://github.com/pingcap/tidb/issues/54057

planner: add variables for instance plan cache

---

br/backup-and-restore-storages.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/18640

br: support imdsv2 to retrive IAM Role

---

time-to-live.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18457

update TTL doc to allow split tasks for utf8 column

---

information-schema/information-schema-processlist.md
information-schema/information-schema-slow-query.md

Update processlist and slow_query tables' desc, both add two new columns.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18527

Update two informtion_schema tables desc

---

br/br-pitr-manual.md
br/use-br-command-line-tool.md

br: add doc for log backup encryption

---

system-variables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18651
https://github.com/pingcap/docs-cn/pull/18651

*: add tidb_auto_analyze_concurrency

---

sql-statements/sql-statement-alter-resource-group.md
sql-statements/sql-statement-create-resource-group.md
sql-statements/sql-statement-query-watch.md
tidb-resource-control.md

Add the newly added `SWITCH_GROUP(<name>)` syntax document by https://github.com/pingcap/tidb/pull/54804.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18501

Add new resource control action SWITCH_GROUP

---

tikv-configuration-file.md

Release `raft-engine.spill-dir` configurations for users who wanna uses multi disks for storing raft logs.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18690

raft-engine: add the `spill-dir` config parameter

---

system-variables.md

https://github.com/pingcap/tidb/pull/56316
https://github.com/pingcap/docs-cn/pull/18716

sys-variables: update `tidb_schema_cache_size` default value

---

system-variables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18706

system variables: change default value for var `tidb_enable_inl_join_inner_multi_pattern`

---

TOC.md
schema-cache.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/18646
- Other reference link(s):https://github.com/pingcap/docs/pull/19007

add document for info schema cache 

---

ticdc/ticdc-integrity-check.md
ticdc/ticdc-sink-to-kafka.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18273

cdc: add description about the checksum v2

---

ticdc/ticdc-sink-to-kafka.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18184

cdc: add claim check raw value format doc

---

dynamic-config.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18540

tikv: add new dynamic configure for flow-control

---

enable-tls-between-components.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18755

pd: support multi cn after 8.4

---

dynamic-config.md
pessimistic-transaction.md
tikv-configuration-file.md

Ref: https://github.com/pingcap/docs-cn/pull/18648
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18648

tikv config: add in memory pessismitic lock size limit config

---

glossary.md

glossary: link TSO to the TSO doc

---

information-schema/information-schema-slow-query.md
system-variables.md

- https://github.com/pingcap/tidb/pull/20200
- https://github.com/pingcap/tidb/issues/56707

Update docs around slow_query tables

---

auto-increment.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18543

auto-increment.md: add invalidate cache descriptions

---

ddl-introduction.md

ddl-introduction: switch the tab of pre-v6.2 info and post-v6.2 info

---

migrate-from-csv-files-to-tidb.md
temp.md

Add a description to step 1.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18935

Improve migration from from CSV files

---

system-variables.md
tidb-configuration-file.md

https://github.com/pingcap/docs-cn/pull/18817

*: add tidb_enable_stats_owner

---

temp.md
ticdc/ticdc-changefeed-config.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18865

cdc: add warn for event filter

---

information-schema/information-schema-data-lock-waits.md
mysql-schema/mysql-schema.md
troubleshoot-lock-conflicts.md

Update docs related to locking

---

tiup/tiup-cluster-topology-reference.md

topology config supports TiCDC server and TiKV-CDC, they are different.
https://asktug.com/t/topic/1034131

tiup: add kvcdc server topylogy example

---

tiproxy/tiproxy-performance-test.md
tiproxy/tiproxy-traffic-replay.md

- Some community users gave feedback that they wanted the performance effect of traffic capture, so I did a performance test.
- Meanwhile, a colleague wanted to see the sample of `fail`, so I added a sample.
- Added more warnings as the PM required.
- Fix wrong name of db `tiproxy_traffic_replay`.  …

tiproxy: add performance report of traffic capture

---

tidb-cloud/integrate-tidbcloud-with-airbyte.md

clarify more about airbyte TiDB connector sync mode

---

schema-cache.md

Updated the Schema Cache limitations
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/19039

Updated the Schema Cache limitations

---

tidb-cloud/pause-or-resume-tidb-cluster.md

cloud: update pause operation behavior for TiDB Cloud Dedicated clusters

---

tiflash/tiflash-configuration.md
tiflash/tiflash-mintso-scheduler.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18997

Add mintso config parameters

---

partitioned-table.md

- Other reference link(s): https://github.com/pingcap/tidb/pull/56868

partitioned-table: remove some restrictions on global index

---

schema-cache.md
system-variables.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/19063

schema cache ga

---

system-variables.md

Fix incorrect messages for set_var()
- `tidb_read_consistency` is supported conditionally
- `tidb_read_staleness` is not support
Translated from https://github.com/pingcap/docs-cn/pull/19119
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19119

fix incorrect message for set_var()

---

br/br-pitr-manual.md
br/br-snapshot-manual.md

br: remove experimental feature notice for encryption to GA in v8.5

---

data-type-numeric.md
data-type-overview.md
tidb-configuration-file.md

Update the docs to follow the change in default value for `deprecate-integer-display-length`. 
This follows the behavior in MySQL.
Integer types can be defined like `int(10)` or `int(8)` or `int`. People often misunderstand the meaning of the number that is specified here (e.g. the 10 and the 8 here). This does not change the capacity of the value that can be stored it only changes how it might be displayed.
See also https://dev.mysql.com/doc/refman/8.0/en/numeric-type-attributes.html and https://github.com/pingcap/tidb/pull/56529
**Important**: This changes the documentation for the variable and updates the page describing numeric types. However this does _NOT_ update the output that might have changed. 
Output that changes based on this variable:
- `SHOW CREATE TABLE`
- `DESCRIBE …

Update docs for deprecate-integer-display-length=true

---

system-variables.md

add description for var `tidb_ddl_reorg_max_write_speed`
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19071
- Other reference link(s): https://github.com/pingcap/tidb/pull/57145

tidb: add description for var `tidb_ddl_reorg_max_write_speed`

---

tidb-cloud/tidb-cloud-release-notes.md

cloud: add release notes 2024-11-26

cloud: add release notes 2024-11-26

---

TOC-tidb-cloud.md
tidb-cloud/tidb-cloud-org-sso-authentication.md
tidb-cloud/tidb-cloud-sso-authentication.md

Replace “Basic SSO” with “Standard SSO” to better reflect its functionality and importance.
- [] master (the latest development version)

cloud: replace “Basic SSO” with “Standard SSO”

---

pd-control.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19023

Add service-middleware config for pd-ctl

---

TOC.md
sql-statements/sql-statement-admin-alter-ddl.md
sql-statements/sql-statement-admin-show-ddl.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19085

docs: add documentation for ADMIN ALTER DDL JOBS command

---

sql-statements/sql-statement-change-drainer.md
sql-statements/sql-statement-change-pump.md
sql-statements/sql-statement-show-drainer-status.md
sql-statements/sql-statement-show-pump-status.md
temp.md
tidb-binlog/bidirectional-replication-between-tidb-clusters.md
tidb-binlog/binlog-consumer-client.md
tidb-binlog/binlog-control.md
tidb-binlog/deploy-tidb-binlog.md
tidb-binlog/get-started-with-tidb-binlog.md
tidb-binlog/handle-tidb-binlog-errors.md
tidb-binlog/maintain-tidb-binlog-cluster.md
tidb-binlog/monitor-tidb-binlog-cluster.md
tidb-binlog/tidb-binlog-configuration-file.md
tidb-binlog/tidb-binlog-faq.md
tidb-binlog/tidb-binlog-glossary.md
tidb-binlog/tidb-binlog-overview.md
tidb-binlog/tidb-binlog-relay-log.md
tidb-binlog/tidb-binlog-reparo.md
tidb-binlog/troubleshoot-tidb-binlog.md
tidb-binlog/upgrade-tidb-binlog.md

TiDB ends the support of Binlog starting from v8.4.0. This PR adds aliases for Binlog docs for stable doc links.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19191

add aliases for Binlog docs

---

releases/release-7.4.0.md

[tidb_stats_cache_mem_quota](/system-variables.md#tidb_stats_cache_mem_quota-从-v610-版本开始引入) was generally available on v7.4.0. Include missing announcement in release notes.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19226

Announce GA of memory control on stats cache

---

tidb-cloud/backup-and-restore.md

br: add doc for latest backup protection

---

optimizer-fix-controls.md

Before v8.5.0, the default value of 46177 is OFF
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19301

planner: fix the default value of 46177 to OFF for versions earlier than 8.5

---

sql-statements/sql-statement-flashback-cluster.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18903

flashback: add limitation with stale read/snapshot

---

tikv-configuration-file.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19315

fix version-mark format for shared-blob-cache

---

optimizer-fix-controls.md

cloud: fix control add 56318

---

TOC.md
best-practices/tidb-best-practices.md
check-before-deployment.md
faq/deploy-and-maintain-faq.md
faq/sql-faq.md
hardware-and-software-requirements.md
production-deployment-using-tiup.md
quick-start-with-tidb.md

- Improves some description and cross-references in [Deploy a TiDB Cluster Using TiUP | TiDB Docs](https://docs.pingcap.com/tidb/dev/production-deployment-using-tiup)
- Adds link of [Scale a TiDB Cluster Using TiUP | TiDB Docs](https://docs.pingcap.com/tidb/dev/scale-tidb-using-tiup) to the bottom section 
- Adds link of [Best Practices for TiDB Security Configuration | TiDB Docs](https://docs.pingcap.com/tidb/dev/best-practices-for-security-configuration) to the beginning section
- Updates wording in `TOC.md` to make it consistent with the actual `title` in `.md` files
By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a …

*: improve deployment doc and toc

---

tidb-cloud/backup-and-restore-serverless.md
tidb-cloud/delete-tidb-cluster.md
tidb-cloud/tidb-cloud-poc.md

serverless BR 

---

tidb-cloud/tidb-cloud-release-notes.md

add 20241217 release notes

---

wrong-index-solution.md

The wrong index solution doc only focuses on one possible reason for why a different index than expected might be chosen. This update tries to extend this and also reference other helpful resources.

wrong-index-solution: update

---

check-before-deployment.md
dm/quick-start-with-dm.md

See also:
- https://docs.pingcap.com/tidb/stable/deploy-a-dm-cluster-using-tiup
- https://docs.pingcap.com/tidb/stable/tiup-component-cluster-check#selinux

check-before-deployment: add selinux

---

hardware-and-software-requirements.md
releases/release-8.4.0.md
releases/release-8.5.0.md
temp.md
upgrade-tidb-using-tiup.md

Highlight the info that CentOS 7 is no long supported 
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19332

add warnings for CentOS 7 usage

---

.github/workflows/cron.yml
.github/workflows/ja-full-translation-google.yaml

update(ci): ja translation

---

temp.md
tiup/tiup-playground.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19357

tiup-playground: add info about TiProxy

---

sql-statements/sql-statement-import-into.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/19261

Improve usage of `IMPORT FROM SELECT`

---

README.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19371

README.md: add release-8.5

---

br/backup-and-restore-overview.md
br/br-pitr-guide.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18970

restore: update full restore speed

---

.github/pull_request_template.md
README.md
temp.md

Remove v5.3/v8.2 from the PR template because v5.3/v8.2 docs have been archived at [docs-archive.pingcap.com/zh/tidb](https://docs-archive.pingcap.com/zh/tidb) and will no longer receive new updates.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19414

chore: remove v5.3/v8.2 from PR template

---

sql-statements/sql-statement-rename-table.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/19452

sql: `RENAME TABLE` supports renaming multiple tables and across dbs

---

data-type-default-values.md

Use https://github.com/pingcap/tidb/blob/5e8d1b8ae1de446841c105d0c177320c88ff893d/pkg/ddl/add_column.go#L628-L787 to update the docs
See also:
- https://github.com/pingcap/tidb/pull/32608
- https://github.com/pingcap/tidb/pull/52786

Update docs for expression defaults

---

functions-and-operators/tidb-functions.md

- https://github.com/pingcap/tidb/pull/51678

functions: Add TIDB_MVCC_INFO, TIDB_ENCODE_INDEX_KEY and TIDB_ENCODE_RECORD_KEY

---

config-templates/simple-tiproxy.yaml
tiproxy/tiproxy-configuration.md
tiproxy/tiproxy-deployment-topology.md
tiproxy/tiproxy-overview.md
tiup/tiup-cluster-topology-reference.md

Currently, I received some confusion about deploying TiProxy. The main reason is that the documents are spread everywhere.
Some of the confusion:
- I can't find the deployment sample of TiUP
- Are the TLS configs in the sample mandatory?
- How can I customize the deploy directory?
- The description of some configs is unclear
- What's the sample of configuring VIP?
One of the complaints: https://asktug.com/t/topic/1037753 …

tiproxy: improve deployment instructions for deploying TiProxy

---

sql-plan-management.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/18534

Spm fix hint issue

---

check-before-deployment.md

Clarify confusing descriptions for disabling system swap
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/14662

Clarify swap descriptions 

---

tidb-limitations.md

fix: correct CHAR and BINARY maximum length from 256 to 255
```bash
mysql> create table t(c char(256));
ERROR 1074 (42000): Column length too big for column 'c' (max = 255); use BLOB or TEXT instead
mysql> create table t(b binary(256));
ERROR 1074 (42000): Column length too big for column 'b' (max = 255); use BLOB or TEXT instead
```
- …

fix: correct CHAR and BINARY maximum length from 256 to 255

---

scripts/generate-index-for-system-varibles.py

Add a script to update the "## Variable reference" section in ` system-variable-reference.md` automatically.

scripts: add a script to generate reference index for system variables

---

scale-tidb-using-tiup.md
temp.md
tiflash/tiflash-overview.md
tiflash/troubleshoot-tiflash.md

* The "pd buddy" has been removed from TiFlash since v6.0 https://github.com/pingcap/tidb/issues/29924
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/17017

Refine tiflash docs to remove deprecated description

---

br/backup-and-restore-overview.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/19443

br: update the compatibility information for BR between TiDB versions 6.5.0 and 8.5.0

---

character-set-and-collation.md
character-set-gbk.md
migrate-from-mariadb.md
sql-statements/sql-statement-show-collation.md

- Update output of `SHOW COLLATION`
- Add collation nameing details
- Update utf8/utf8mb3 info
Note that `Pad_attribute` is in v8.5 and newer, so don't backport to older versions. See also https://github.com/pingcap/tidb/pull/54282
Might conflict with changes from …

Character set and collation updates

---

functions-and-operators/information-functions.md

https://github.com/pingcap/tidb/issues/58201 doesn't need any changes in the docs, but I found out that the optional argument of `LAST_INSERT_ID()` wasn't documented yet.

Update docs for LAST_INSERT_ID()

---

TOC-tidb-cloud.md
tidb-cloud/connected-care-announcement.md
tidb-cloud/connected-care-detail.md
tidb-cloud/connected-care-overview.md
tidb-cloud/tidb-cloud-support.md

fix TiDB Cloud Connected Care support services

---

dumpling-overview.md

Merge the info from https://github.com/pingcap/tidb/blob/master/dumpling/docs/en/user-guide.md into pingcap/docs.
**Note**: there is also https://github.com/pingcap/tidb/blob/master/dumpling/docs/cn/user-guide.md that can help for translation
See also: https://github.com/pingcap/tidb/pull/58679
- Other …

dumpling: merge userguide into docs

---

quick-start-with-tidb.md

Update wordings, notes orders to the Quick Start for TiDB Self-Managed doc.
- ~~Uses `1` for ordered list, as it will increase automatically and can avoid the manual calculation of the numbers for the list.~~
- ~~Tries to move the **NOTE** section after the main content. Some of the notes should be after the major content as they are more like extended content.~~
- Revisited the wordings, such as the topology table. …

Quick start updates

---

pd-control.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/15605

pdctl: update the description of merging store labels

---

ticdc/ticdc-avro-protocol.md

ticdc: add note to the Avro protocol

---

enable-tls-between-components.md
temp.md
tiup/tiup-cluster-topology-reference.md

`http_port` has been deprecated since v7.1.0, remove all description about it.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/18868

tiflash: remove deprecated http_port

---

config-templates/simple-tiproxy.yaml
tiup/tiup-cluster-topology-reference.md

tiup: fix tiproxy data_dir

---

check-before-deployment.md
tiup/tiup-component-cluster-check.md
tune-operating-system.md

- The current advise doesn't always make a reboot-safe change (it only changes the running configuration).
See also:
- https://access.redhat.com/solutions/46111
- https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/8/html/managing_monitoring_and_updating_the_kernel/assembly_making-persistent-changes-to-the-grub-boot-loader_managing-monitoring-and-updating-the-kernel#proc_adding-and-removing-arguments-from-a-grub-2-menu-entry_assembly_making-persistent-changes-to-the-grub-boot-loader
-  …

tiup: Update THP docs

---

TOC-tidb-cloud.md
tidb-cloud/_index.md
tidb-cloud/key-concepts.md

cloud: update the index page according to the latest TOC

---

ddl-introduction.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/19701

ddl: refine descriptions about online DDL

---

check-before-deployment.md

- Give a warning about `vm.min_free_kbytes` as it can lead to boot failures and instability if set on systems with low(er) amounts of memory
- Change `tcp_tw_recycle` as it isn't available on (most/all) new systems. It is still available on CentOS Linux 7, but that's EOL and not expected for new installations …

tiup: update sysctl settings

---

configure-store-limit.md

pd: store limit updates

---

system-variables.md

The default value of tidb_enable_plan_replayer_capture on TiDB Cloud is `ON`

cloud: fix the default value of tidb_enable_plan_replayer_capture

---

functions-and-operators/aggregate-group-by-functions.md

Fix https://github.com/pingcap/docs/issues/19736

Add doc for `APPROX_COUNT_DISTINCT` aggregate function

---

tidb-cloud/set-up-private-endpoint-connections.md

Update the the intro sentence of creating AWS endpoints according to the tab sequence changes in https://github.com/pingcap/docs/pull/20253/files

cloud: update the intro sentence of creating AWS endpoints

---

TOC-tidb-cloud.md
tidb-cloud/import-csv-files.md
tidb-cloud/import-parquet-files.md
tidb-cloud/import-sample-data.md
tidb-cloud/tidb-cloud-import-local-files.md

Separate serverless/dedicated import

---

glossary.md
grafana-tikv-dashboard.md
tikv-in-memory-engine.md

tikv-in-memory-engine: Add link to config and extend docs

---

scale-tidb-using-tiup.md
temp.md

- Update the notes for scaling in and scaling out PD nodes
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19914

Update notes for scaling PD nodes

---

mysql-schema/mysql-schema.md

As the title says.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19944

mysql-schema: add information about several missing system tables

---

br/br-log-architecture.md

让 BR log backup 的文件结构更加友好一些。
Made the file structure paragraph in the `br_log_architecture.md` more friendly.
同时解决了 pingcap/docs-cn#19767 中提到的 `min_restored_ts` 和现行惯用词不同的问题。
Meanwhile, solved the problem that `min_resolved_ts` is inconsistent with customary usage mentioned at pingcap/docs-cn#19767.
- This PR is translated from: 19824
- …

br: add more info about the br log structure

---

system-variables.md
temp.md

This PR removes the default value descriptions for the following  last_xxx variables:
last_plan_from_binding
last_plan_from_cache
last_sql_use_alloc
Reason:  their values are determined by whether a function is used or not, so the default values are meaningless and confusing. 
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19982
- Other …

system-variables: remove the default value descriptions for  last_xxx variables 

---

benchmark/benchmark-sysbench-v6.2.0-vs-v6.1.0.md
benchmark/v6.2-performance-benchmarking-with-tpcc.md
benchmark/v6.2-performance-benchmarking-with-tpch.md

This PR adds aliases for the following stale benchmark docs removed in https://github.com/pingcap/docs/pull/20462.
- ./benchmark/benchmark-sysbench-v6.2.0-vs-v6.1.0.md
- ./benchmark/v6.2-performance-benchmarking-with-tpcc.md
- ./benchmark/v6.2-performance-benchmarking-with-tpch.md …

v6.5: add aliases for stale benchmark docs

---

TOC.md
br/br-compact-log-backup.md
temp.md

This PR adds a new document for the new feature "compact log backup". (experimental)
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19832

br: add compact log backup

---

clustered-indexes.md

Modify the limitation of `cluster index`. `PRE_SPLIT_REGION` is supported for auto random column.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/20056

Fix the desciption about cluster index and pre split region on auto random column

---

mysql-schema/mysql-schema.md

Add a description about the `cluster_id` row in the `mysql.tidb` table.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19831
- https://github.com/pingcap/tidb/pull/59511

Add docs about the `cluster_id` row in `mysql.tidb` table

---

tidb-cloud/tidb-cloud-auditing.md

Optimize the Database audit logging function.

Optimizing Database audit logging

---

partitioned-table.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19507
- Other reference link(s): https://github.com/pingcap/tidb/pull/58678

partitioned-table: global index supports non-unique index

---

temp.md
ticdc/ticdc-manage-changefeed.md

This PR adds documentation for the new TiCDC feature that prevents users from mistakenly configuring the same TiDB cluster as both the upstream and downstream.  
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19851

ticdc: add documentation for preventing TiCDC from using the same TiB cluster as both upstream and downstream

---

sql-statements/sql-statement-explain-analyze.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19942

Modify hash join explain analyze description

---

system-variables.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/19878

system-variables: add doc for `tidb_max_dist_task_nodes`

---

system-variables.md

after fix of https://github.com/pingcap/tidb/pull/60272, we add tidb_enable_point_get_cache back, so we just add the variable document back
- This PR is translated from:https://github.com/pingcap/docs-cn/pull/20137

add system variable back for tidb_enable_point_get_plan_cache.

---

stale-read.md

stale read: update the description of tidb_external_ts

---

information-schema/information-schema-statistics.md

information_schema: Update IS_VISIBLE description

---

statement-summary-tables.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19847
https://github.com/pingcap/tidb/issues/57543

statements: add network traffic related stats in statments summary table

---

temp.md
tiflash-upgrade-guide.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/20128

tiflash: upgrade guide

---

pipelined-dml.md
system-variables.md
temp.md

Added a system variable `tidb_pipelined_dml_resource_policy`
https://github.com/pingcap/tidb/pull/57352
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19994

variable: tidb_pipelined_dml_resource_policy

---

ticdc/ticdc-avro-protocol.md
ticdc/ticdc-canal-json.md
ticdc/ticdc-csv.md
ticdc/ticdc-open-protocol.md
ticdc/ticdc-simple-protocol.md

ticdc: add vector type in output protocol

---

TOC.md
_index.md
deploy-monitoring-services.md
tidb-monitoring-framework.md

close https://github.com/pingcap/docs-cn/issues/20206
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/20207

tidb-monitoring-framework: add TiDB Dashboard

---

pd-configuration-file.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/20260

pd configuration: add dashboard.disable-custom-prom-addr

---

tidb-cloud/scale-tidb-cluster.md
tidb-cloud/upgrade-tidb-cluster.md

update CM part for Azure public review

---

sql-statements/sql-statement-import-into.md

Added a new restriction to the `IMPORT INTO` documentation specifying that the target table must be entirely empty for import operations, including all partitions.

Add restriction for IMPORT INTO regarding empty

---

character-set-and-collation.md
information-schema/information-schema-collations.md
sql-statements/sql-statement-show-collation.md

https://github.com/pingcap/tidb/issues/54250

Update pad attribute where needed

---

information-schema/information-schema-tidb-index-usage.md

Add a limitation to the tidb usage limitation. The description is aligned with the "index-advisor.md":
> The data in `INFORMATION_SCHEMA.CLUSTER_TIDB_INDEX_USAGE` might be delayed by up to five minutes, and the usage data is reset whenever a TiDB node restarts. Additionally, index usage is only recorded if the table has valid statistics.
- …

Add tidb index usage limitation for valid stats

---

sql-statements/sql-statement-load-data.md
tidb-cloud/limited-sql-features.md

Updates `LOAD DATA INFILE` descriptions, as requested by @Frank945946 

tidb-cloud: update LOAD DATA INFILE description

---

tidb-cloud/serverless-export.md

cloud: add export speed and note

---

sql-statements/sql-statement-load-data.md

Update load data sql description

Update load data sql description

---

auto-random.md

Close issue: #20732
This PR updates the "Clear the auto-increment ID cache" section in `auto-random.md` to address confusion reported in the issue above. Specifically, the changes:
- Clarify that `ALTER TABLE ... AUTO_RANDOM_BASE` without the `FORCE` keyword does not actually change the value, despite the warning message.
- Emphasize that the `FORCE` keyword is mandatory to modify `AUTO_RANDOM_BASE`.
- Explicitly state that attempting to set `AUTO_RANDOM_BASE` to `0`, even with `FORCE`, will result in an error.
- Clarify that a non-zero positive integer must be used with `FORCE`.
- Improve the explanation of how explicit inserts can potentially collide with the internal auto-incrementing part of `AUTO_RANDOM` IDs, potentially leading to duplicate key errors.
- Split a longer paragraph …

docs: clarify AUTO_RANDOM_BASE usage and explicit insert behavior

---

tidb-cloud/tidb-cloud-release-notes.md

cloud: add 20250513 release notes

---

tidb-cloud/tidb-cloud-auditing.md

Updated the database audit log description for Azure deployment scenarios

Update the database audit log description for Azure deployment scenarios

---

tidb-cloud/migrate-from-mysql-using-data-migration.md

cloud: `information_schema` should be `performance_schema`

---

TOC-tidb-cloud.md
tidb-cloud/terraform-migrate-cluster-resource.md

cloud: add terraform migrate cluster resource doc

---

dynamic-config.md
temp.md
tikv-configuration-file.md

Fix the incorrect annotations on the background quota limiter.
This feature is already GAed in v6.5.x.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/20235

tikv-configuration: fix incorrect annotations for background quota limiter

---

storage-engine/titan-configuration.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/20304

tikv / titan: Add note for disabling titan

---

TOC-tidb-cloud.md
tidb-cloud/changefeed-sink-to-apache-pulsar.md

Signed-off-by: Ben Meadowcroft <ben.meadowcroft@pingcap.com>
TiDB Cloud Dedicated is adding support for Apache Pulsar as a downstream target for streaing data using a TiCDC changefeed. This PR includes documentation of that new feature.

cloud: Add Pulsar support docs

---

tidb-cloud/tidb-cloud-billing.md

Adding the pricing section for TiDB Cloud Starter and Essential for Alibaba Cloud.

Alicloud pricing

---

explain-walkthrough.md

Fix wording in the explain walkthrough, the current working seems to imply that the initial performance is good (which it is not).  The rest of the walkthrough is to improve the performance, so the changed wording seems more correct.
see diff

Fix wording to reflect poor performance of initial query before optimization

---

TOC-tidb-cloud.md
TOC.md
develop/dev-guide-sample-application-cs.md

Add C# / .NET example

---

tiflash/tiflash-compatibility.md
tiflash/use-fastscan.md

TiFlash: small fixes and added links

---

tiproxy/tiproxy-overview.md

Users may mistakenly think that upgrading tiproxy won't upgrade the cluster.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/20568

tiproxy: add notice about upgrading tiproxy

---

tidb-cloud/tidb-cloud-release-notes.md

cloud: add 20250722 release notes

---

resources/terms.md

- create terms.md for ai translation

ci: create terms.md for ai translation

---

scripts/concatMdByToc.js
scripts/filterCloudDoc.js
scripts/filterCloudInitFiles.js
scripts/filterNonCloudDoc.js
scripts/filterUpdateFiles.js
scripts/utils.js

- Other reference link(s): https://github.com/pingcap/docs/pull/21511

refactor: consolidate TOC file handling in cloud document scripts

---

tidb-cloud/monitor-datadog-integration.md

cloud: update the steps of installing TiDB Cloud integration in Datadog

---

br/br-log-architecture.md
temp.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/20455

log backup: update metafile format

---

shard-row-id-bits.md
temp.md

Add notice about setting the value of SHARD_ROW_ID_BITS
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/20702

Add more description about SHARD_ROW_ID_BITS

---

ticdc/deploy-ticdc.md

ticdc: correct the tiup cluster command

---

temp.md
ticdc/ticdc-csv.md

1. Add a new field `output-field-header`
1. Add the header description about CSV protocol
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/20478
- Other reference link(s): https://github.com/pingcap/tiflow/pull/12183

ticdc: add header line for CSV protocol

---

tiflash/tiflash-configuration.md

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/20704

Modify the introduction of `cop_pool_size`

---

tidb-cloud/architecture-concepts.md
tidb-cloud/connect-via-standard-connection-serverless.md
tidb-cloud/create-tidb-cluster-serverless.md
tidb-cloud/security-concepts.md
tidb-cloud/serverless-high-availability.md
tidb-cloud/set-up-private-endpoint-connections-on-azure.md
tidb-cloud/set-up-private-endpoint-connections-on-google-cloud.md
tidb-cloud/tidb-cloud-billing.md
tidb-cloud/tidb-cloud-connect-aws-dms.md
tidb-cloud/tidb-cloud-faq.md
tidb-cloud/tidb-cloud-intro.md
tidb-cloud/tidb-cloud-poc.md
tidb-cloud/tidb-cloud-quickstart.md
tidb-cloud/tidb-cloud-release-notes.md
tidb-cloud/upgrade-tidb-cluster.md

Introduced `<CustomContent language="ja">` blocks throughout TiDB Cloud documentation to provide Japanese-specific content and cloud provider details. This improves localization and clarity for Japanese users, especially regarding supported cloud platforms and feature availability.
Related issue: https://github.com/pingcap/website-docs/issues/631
Related FE PR: https://github.com/pingcap/website-docs/issues/630
> [!NOTE]
> This PR hasn't remove `- [Connect via Private Endpoint with Alibaba Cloud](/tidb-cloud/set-up-private-endpoint-connections-on-alibaba-cloud.md)` from TOC files yet. Either use CustomContent for TOC files, or directly remove the corresponding line from the `i18n-ja-release-8.5` branch.
By default, **CHOOSE MASTER ONLY** so …

*: add custom Japanese localization for cloud docs

---

maintain-tidb-using-tiup.md

Revert "v8.5: remove VictoriaMetrics guide"

---

ticdc/ticdc-open-api-v2.md

`curl -H "'Content-Type':'application/json'"` is an invalid command, it should just be `curl -H "Content-Type: application/json"`.

ticdc: Remove unnecessary quotation marks from curl command

---

releases/release-8.5.2.md
temp.md

…able_tso_follower_proxy` is enabled
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/20930

fix: add missing fix for TSO service availability issue when `tidb_enable_tso_follower_proxy` is enable

---

ticdc/ticdc-faq.md

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/20951

ticdc: fix the name of the changefeed config file

---

information-schema/information-schema-processlist.md
sql-statements/sql-statement-create-binding.md
sql-statements/sql-statement-show-processlist.md

statements: add privilege details
